### ISSUE TITLE
Mini-évent marchand

### ISSUE THREAD

**Issue by DoctorT1807** [DraftBot-A-Discord-Adventure/DraftBot#1001]
Retravailler le mini-évent du marchand pour que l'on ne puisse pu se faire d'argent en revendant les items achetés. (Actuellement ce n'est plus possible car les items sont vendus à 100% du prix)

**Comment by BastLast** [comment]
Quasi sûr que il y avait déjà une issue ouverte pour ce truc là je pense qu'il aurait été plus pertinent de la renommer

**Comment by DoctorT1807** [comment]
My bad je l'ai pas trouvé

**Comment by BastLast** [comment]
Np je checkerai maybe elle est fermée

**Comment by DoctorT1807** [comment]
Ah c la #661 je suis trop con
