### ISSUE TITLE
Message des missions complétées s'affiche en double

### ISSUE THREAD

**Issue by DoctorT1807** [DraftBot-A-Discord-Adventure/DraftBot#1002]
![image](https://user-images.githubusercontent.com/89483734/157327816-51ce3241-c291-45f9-8dd9-81d33b6224b3.png)
Quand l'on complète une mission avec un fight le message s'affiche en double.

**Comment by BastLast** [comment]
C'est pas a tous les coups non ?

**Comment by DoctorT1807** [comment]
Nop si tu regardes sur le serv le bug n'apparaît que dans l'arène. En tout cas je n'ai pas vue de cas autre que lors de fights.

**Comment by BastLast** [comment]
faudrait trouver dans quels conditions exactes on peut reproduire le bug à tous les coups

**Comment by symsym-1629** [comment]
Je vais essayer de voir ça sur une instance dans la semaine je vous dirais tout ca

**Comment by Feiryn** [comment]
Impossible à reproduire et peut-être déjà corrigé
