### ISSUE TITLE
Commande !da et !s pas bloquer lors du choix de la destination

### ISSUE THREAD

**Issue by DoctorT1807** [DraftBot-A-Discord-Adventure/DraftBot#1012]
Commande !da et !s pas bloquer
![image](https://user-images.githubusercontent.com/89483734/158025901-3a8e3716-3a5e-44ce-869e-caeaa5a3caab.png)
![image](https://user-images.githubusercontent.com/89483734/158025907-0738f412-9e5a-4332-8588-81e3e9aa7691.png)

**Comment by Pietagorh** [comment]
Dans la 1ère situation, c'est que ça débloque à cause de l'item gagné

Donc en gros y'a un problème de blocage (encore) quand t'es doublement bloqué : 1 seul déblocage suffit pour les 2

**Comment by romain22222** [comment]
fix dans la pr #1157
