### ISSUE TITLE
Possible de faire la 1ère mission d'autres joueurs

### ISSUE THREAD

**Issue by DoctorT1807** [DraftBot-A-Discord-Adventure/DraftBot#1022]
Si l'on fait !m suivi du rang ou en mentionnant un joueur n'ayant pas fait sa 1ère mission, il arrive que cela la lui complète : 
![unknown-2](https://user-images.githubusercontent.com/89483734/158549336-35856a65-1989-43a8-9b35-be8f2182ffd3.png)

**Comment by Pietagorh** [comment]
J'ai vérif, tu voles pas leur récompense, donc c'est déjà ça x)

**Comment by BastLast** [comment]
Still, évitez de faire mumuse

**Comment by BastLast** [comment]
faudra faire une migration aussi pour repasser à 0 tous les joueurs qui ont été victime de ce bug parce que je crois que ca les bloque das leur aventure

**Comment by romain22222** [comment]
@BastLast

**Comment by BastLast** [comment]
@romain22222 pourquoi tu m'a ping déjà ? ptdr

**Comment by romain22222** [comment]
je sais plus, je crois c'est par rapport à la migration à créer

**Comment by BastLast** [comment]
bah faut juste faire que tous les gens qui sont à la mission 1 soient passés à la mission 0 à nouveau

**Comment by BastLast** [comment]
et faut fix le bug aussi
