### ISSUE TITLE
Curseur mal placé sur la map

### ISSUE THREAD

**Issue by DoctorT1807** [DraftBot-A-Discord-Adventure/DraftBot#1023]
Le curseur entre le Mont Célestrum et le Chemin aux Loups est mal placé : 
![Screenshot_20220314-0740122](https://user-images.githubusercontent.com/89483734/158554443-c333c0ab-c0be-475d-9d4c-3267aae0d4ec.png)

**Comment by BastLast** [comment]
@Surdidi  ?

**Comment by BastLast** [comment]
bug fix par surdidi le dieu qui a oublié de tag l'issue mais c pas grave

**Comment by Surdidi** [comment]
> bug fix par surdidi le dieu qui a oublié de tag l'issue mais c pas grave

Mdr j'ai tag l'issue mais vu que c'est pas sur le même projet ça a pas marché je crois

**Comment by BastLast** [comment]
Oue c un peu tricky
