### ISSUE TITLE
La mauvaise pp apparaît lorsque l'on regarde le pet de qqn

### ISSUE THREAD

**Issue by DoctorT1807** [DraftBot-A-Discord-Adventure/DraftBot#1030]
Lorsque utilise le classement pour voir l'animal de compagnie d'une personne, ça met la mauvaise photo de profil alors que si on ping ça fonctionne normalement
![image](https://user-images.githubusercontent.com/89483734/159086236-411c361d-1eed-4670-be20-bca77f7f2fb0.png)

**Comment by BastLast** [comment]
fixé dans #1051
