### ISSUE TITLE
Faire un système propre de register / clear de slash commands

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1033]
Pour que quand le bot démarre ca prenne pas 50 ans à register des trucs qui n'ont pas changé
que ca clear les trucs qui existent plus 
et que ca register bien ce qui a été modifié

A FAIRE AVANT LA MAJ

**Comment by Feiryn** [comment]
Fixed in 7507fb3d629523345855b820f5263daca93bbadc

**Comment by BastLast** [comment]
du coup c'est fini ça non ?
