### ISSUE TITLE
Enlever node-ipc

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#1037]
Il faut se passer de cette dépendance, on ne peut plus avoir confiance en un auteur qui met un malware et qui censure les retours sur son github

**Comment by Feiryn** [comment]
Au passage faudrait ajouter une sécurité pour ne pas pouvoir installer une dépendance qui n'a pas une version fixe (préfixée par ^). Avec yarn add ça ajoute ça par défaut

**Comment by BastLast** [comment]
fixé dans #1040
