### ISSUE TITLE
Classement des guildes

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#105]
- [x] Les guildes ont un score, qui pourra être amélioré principalement grâce à la zone PVE
- [x] Les joueurs pourront accèder à l'affichage du classement des guildes

**Comment by Asemerald** [comment]
- Un système de top week/guilde avec le score au top week de tout les joueurs de la guilde additionné maybe 

 - Sinon le nombre de points normaux de chacune additionnés

 - Par level 

 - J'ai pas d'autres idées

**Comment by quenquentin** [comment]
Attribution de points de guilde avec mini évent,
PvE si effectué, fights ou encore gd ? Avec une récompense par semaine / mois avec un classement et des vraies récompenses données à chacun des membres ? Money etc.. Pas juste un badge, aussi avec le système de bornes de rareté d'item, possibilité de filer un item d'une certaine rareté ou plus, obtenable avec une commande type !reward pour récupérer la récompense et décider de la garder ou non.

**Comment by BastLast** [comment]
J'imaginais faire un truc genre des donjons qui se feraient entre guildes et qui permettrait d'obtenir de la réputation de guilde, aussi cette fameuse reput deviendrait une récompense possibles des events et mini évents

**Comment by BastLast** [comment]
du coup j'efface les anciens commentaires vu qu'ils sont obsolète, la description de l'issue est à jour
