### ISSUE TITLE
bloquage personne mauvaise personne adressée

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#1073]
faire en sorte que lorsqu'on regarde si une personne bloquée par une commande se fait influencer par une commande qui N EST PAS l'auteur de la commande, et que celle ci vérifie le bloquage de cette personne, alors c'est elle qui est affichée comme étant l'auteur de la commande

en gros faut faire un sendblockederror pour un utilisateur qui n'est pas l'auteur de la commande

**Comment by BastLast** [comment]
a faire avant de merge #1016

**Comment by Pietagorh** [comment]
Je devrais pouvoir le faire
