### ISSUE TITLE
Faire une commande admin pour forcer le changement d'un chef de guilde

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1083]

**Comment by Pietagorh** [comment]
ça kickerait l'ancien chef de guilde du coup ?
J'pense que j'vais l'faire

**Comment by BastLast** [comment]
@Pietagorh  tu le fais du coup ou pas ?

**Comment by Pietagorh** [comment]
@BastLast ouaip, j'l'ai quasi fini

**Comment by BastLast** [comment]
Tu pense pouvoir pr ce soir ?

**Comment by Pietagorh** [comment]
J'ai pas mal de trucs à faire mais j'essaierai

**Comment by Pietagorh** [comment]
Du coup j'ai pas pu parce que j'ai aidé romain plus ou moins toute la soirée :pQuack:
Mais c'est quasi tout fini

Ah et btw y'a des bugs sur les commandes admins que j'vais fix au passage (genre à cause de ça ça marche juste PAS)

**Comment by Pietagorh** [comment]
(+ le fait que TOUT LE MONDE puisse les utiliser sur la nouvelle version)

**Comment by Pietagorh** [comment]
@BastLast du coup j'ai fini, j'vais juste attendre que ma première pr soit passée avant de pr ça (vu qu'il me faut les trucs de la première x))
