### ISSUE TITLE
!q [mention] valide la première quête

### ISSUE THREAD

**Issue by symsym-1629** [DraftBot-A-Discord-Adventure/DraftBot#1097]
!q [mention] valide la première quête pour la personne mentionnée
![bruhh](https://user-images.githubusercontent.com/83075391/164729248-9e0a68bb-7f59-4935-b52d-36bb20908a41.png)

**Comment by Chevalier2** [comment]
Déjà sur cette issue : https://github.com/DraftBot-A-Discord-Adventure/DraftBot/issues/1022. Avant de créer une nouvelle issue, on vérifie.
