### ISSUE TITLE
Régénération arrêtée pour les joueurs avec leur énergie partiellement restaurée ou vidée par un !f

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1101]
Du 29 avril à 19h30 jusqu'au 30 à 14h environ (donc pendant plus de 13h), tous les joueurs ayant participé à un combat classé et n'ayant pas eu leur énergie complètement restaurée avant l'arrivée du bug ayant engendré la maintenance ont vu leur régénération **stoppée net**... Ce problème pouvait être particulièrement gênant s'il avait fallu remplir une mission secondaire nécessitant de réaliser un combat classé si celui qui l'a prise était bloqué à *0 :zap:*.

Est-ce dû à la maintenance avec la première correction qui a échoué dans son objectif de fixer les bugs concernés, ou est-ce un processus qui n'a pas été notifié de la remise en marche du bot? À moins que la cause vient d'autre part? La source du problème reste encore à localiser (et le mystère à élucider).

**Comment by romain22222** [comment]
le bug n'a pas pu être reproduit, et personne ne l'a resubit depuis ce dit jour, je close donc l'issue

**Comment by BananePlantain** [comment]
J'ai subit ce bug:
j'ai fait un combat à 19h18 il me restait 300 ⚡  puis j'ai tout perdu je sais comment comment et depuis j'ai rien récupérée.
Voir screenshots
![regen](https://user-images.githubusercontent.com/126412670/227334769-79ae4fa1-4d47-43a7-a665-d521c5b26a86.PNG)
![bug](https://user-images.githubusercontent.com/126412670/227334797-e460d699-f357-47cd-91de-6a1986122340.PNG)

**Comment by Nargacaura** [comment]
> 

Après des tests, il s'agit en fait d'un bug totalement différent. Faudra créer une nouvelle issue sur ça... (Si tu veux, je m'en occupe.)
