### ISSUE TITLE
dupli pets

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1113]
Il est possible de sacrifier un pet pour que 2 personnes aient le même

1) Lancer un petsell avec un pet (on le nommera A)
2) Annuler la vente pendant qu'une 2è personne l'accepte (passe dans la 2è phase
Maintenant, la vente est en cours alors que le joueur n'est plus bloqué
3) Lancer un pettrade avec une 3è personne disposant d'un pet qu'on nommera B
4) Accepter le pettrade
5) La 2è personne finit d'acheter le pet

Et voilà, il y a maintenant 2 personnes possédant A et B a disparu

![image](https://user-images.githubusercontent.com/60353007/167311435-0b36256e-3f3d-4fb8-b4a1-540cdced39a1.png)
![image](https://user-images.githubusercontent.com/60353007/167311427-56adb7a4-a11d-400c-877a-ca8a65501a37.png)
À la suite de cet exemple, Hitori ET romain avaient la poule, alors le crocodile avait disparu

**Comment by Pietagorh** [comment]
(C'est quasiment la même chose que le #688, on rajoute simplement l'étape 2 pour se débloquer en fait)

**Comment by BastLast** [comment]
@niqore  étant donné que la #688  est close est-ce que ce bug est déjà fix ?

**Comment by Pietagorh** [comment]
Nan justement, c'est une nouvelle méthode pour faire le bug de la #688
Et cette méthode est aussi difficile à empêcher que les doubles fights à mon avis
