### ISSUE TITLE
Overlap plusieurs gains

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1121]
Il arrive que quand il y a plusieurs gains d'une même ressource en même temps, une écrase l'autre, et donc que le joueur ne gagne qu'une d'entre elle
Ça peut arriver qu'avec {truc où tu gagnes de l'argent/exp} + mission remplie vu que de tête y'a pas d'autres moyens de gagner une même ressource 2 fois au même moment

**Comment by BastLast** [comment]
Je vois que la pr est liée mais aucun commit ? Ça allait ?
