### ISSUE TITLE
équilibrage complet du guild daily

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1131]
![image](https://user-images.githubusercontent.com/38099970/171965148-1d18c563-50bd-41e3-a1c1-1764d71a795c.png)

**Comment by BastLast** [comment]
[guilddaily.xlsx](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/files/8836130/guilddaily.xlsx)

**Comment by Pietagorh** [comment]
Il faudrait que le gd donne de l'argent au lieu de la vie si tous les membres de la guilde sont full life et que la récompense est un heal

**Comment by romain22222** [comment]
dépendance des probas : si une action est inutile, alors toute sa probabilité va sur le reward indiqué par la flèche
![image](https://user-images.githubusercontent.com/29299679/172346653-6b5b7509-9264-4a82-bc33-27a0cc59d28d.png)
