### ISSUE TITLE
Expérience conservée après une montée de niveau

### ISSUE THREAD

**Issue by Chevalier2** [DraftBot-A-Discord-Adventure/DraftBot#1140]
![image](https://user-images.githubusercontent.com/72626953/174169008-f5ec2543-e789-4ffe-909d-7a5a090ac4f8.png)
![image](https://user-images.githubusercontent.com/72626953/174169018-5682e88d-0257-4763-bd89-e2779b81a02d.png)

**Comment by BastLast** [comment]
Ct kwale soucisssss
