### ISSUE TITLE
Checkup les traductions manquantes

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#1143]
commands.fight: "actionsOf" is present in french but not in english 
commands.fight: "actions.attacksResults.succeed.8" is present in french but not in english 
commands.fight: "actions.attacksResults.succeed.9" is present in french but not in english
commands.fight: "actions.attacksResults.succeed.10" is present in french but not in english
commands.fight: "actions.attacksResults.succeed.11" is present in french but not in english
commands.fight: "actions.attacksResults.succeed.12" is present in french but not in english
commands.fight: "actions.attacksResults.succeed.13" is present in french but not in english
commands.fight: "actions.attacksResults.succeed.14" is present in french but not in english
commands.fight: "actions.attacksResults.succeed.15" is present in french but not in english
commands.fight: "actions.attacksResults.succeed.16" is present in french but not in english
commands.fight: "actions.attacksResults.notGood.8" is present in french but not in english
commands.fight: "actions.attacksResults.notGood.9" is present in french but not in english
commands.fight: "actions.attacksResults.notGood.10" is present in french but not in english
commands.fight: "actions.attacksResults.notGood.11" is present in french but not in english
commands.fight: "actions.attacksResults.failed.8" is present in french but not in english
commands.fight: "error.levelTooLow.direct" is present in english but not in french
commands.guildDaily: "alterationNoHeal" is present in french but not in english
commands.profile: "badgeDisplay" is present in french but not in english 
commands.profile: "badgeDisplay.title" is present in french but not in english
commands.profile: "badgeDisplay.numberBadge" is present in french but not in english
commands.top: "topTitle" is present in french but not in english
commands.top: "endFirstWrongPage" is present in french but not in english
commands.top: "endFirstRightPage" is present in french but not in english
commands.top: "endAnyWrongPage" is present in french but not in english
commands.top: "endAnyRightPage" is present in french but not in english
commands.top: "lowScore" is present in french but not in english
commands.top: "yourRanking" is present in french but not in english
commands.top: "playerRankLine" is present in french but not in english
commands.top: "nextReset" is present in french but not in english
smallEvents.bigBadEvent: "alteration.stories.13" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.13.sentence" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.13.alte" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.14" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.14.sentence" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.14.alte" is present in english but not in french
smallEvents.staffMember: "context.7" is present in english but not in french
classes.0: "13" is present in english but not in french
classes.1: "13" is present in french but not in english
classes.1: "14" is present in french but not in english 
classes.1: "15" is present in french but not in english
classes.2: "15" is present in english but not in french
classes.3: "26" is present in english but not in french
classes.3: "27" is present in english but not in french
classes.4: "20" is present in english but not in french
classes.5: "24" is present in english but not in french
classes.5: "25" is present in english but not in french
classes.6: "15" is present in english but not in french
classes.6: "16" is present in english but not in french
classes.8: "19" is present in french but not in english
classes.8: "20" is present in french but not in english
classes.8: "21" is present in french but not in english
classes.8: "22" is present in french but not in english
classes.8: "23" is present in french but not in english
classes.9: "24" is present in french but not in english
classes.11: "12" is present in french but not in english
classes.11: "13" is present in french but not in english
classes.11: "14" is present in french but not in english
classes.12: "14" is present in english but not in french
classes.13: "23" is present in english but not in french 
classes.13: "24" is present in english but not in french
classes.13: "25" is present in english but not in french
classes.15: "23" is present in french but not in english
classes.15: "24" is present in french but not in english
classes.15: "25" is present in french but not in english
advices: "advices.184" is present in french but not in english
advices: "advices.185" is present in french but not in english
advices: "advices.186" is present in french but not in english
advices: "advices.187" is present in french but not in english

**Comment by BastLast** [comment]
@Pietagorh  si tu as le time de me décharger de cette issue ça sera la bonne journée de ma journée de demain :)

**Comment by BastLast** [comment]
commands.guildDaily: "alterationNoHeal" is present in french but not in english
commands.profile: "badgeDisplay" is present in french but not in english
commands.profile: "badgeDisplay.title" is present in french but not in english
commands.profile: "badgeDisplay.numberBadge" is present in french but not in english
commands.top: "topTitle" is present in french but not in english
commands.top: "endFirstWrongPage" is present in french but not in english
commands.top: "endFirstRightPage" is present in french but not in english
commands.top: "endAnyWrongPage" is present in french but not in english
commands.top: "endAnyRightPage" is present in french but not in english
commands.top: "lowScore" is present in french but not in english
commands.top: "yourRanking" is present in french but not in english
commands.top: "playerRankLine" is present in french but not in english
commands.top: "nextReset" is present in french but not in english
smallEvents.bigBadEvent: "alteration.stories.13" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.13.sentence" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.13.alte" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.14" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.14.sentence" is present in english but not in french
smallEvents.bigBadEvent: "alteration.stories.14.alte" is present in english but not in french
smallEvents.staffMember: "context.7" is present in english but not in french

**Comment by BastLast** [comment]
Voilà la liste à jour
