### ISSUE TITLE
tests à effectuer à faire avec l'instance de draft

### ISSUE THREAD

**Issue by p-bzh** [DraftBot-A-Discord-Adventure/DraftBot#1158]
- [ ] vérifier que les commandes admin soient affichées uniquement sur le serveur principal

**Comment by BastLast** [comment]
Du coup pour le moment on charge les commandes uniquement sur le main serv du coup faudra transformer les commandes concernées en commandes générales quand la maj sera terminée

**Comment by BastLast** [comment]
Test passé avec succès
