### ISSUE TITLE
refactor la gestion des objets dans le bot

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#1175]
faire un système qui soit BIEN plus modulaire pour les objets, et que si l'objet est un objet de combat, alors qu'il soit sous une catégorie commune, et non split entre attaque def vit

**Comment by Pietagorh** [comment]
+ centraliser le nerf, ça peut apporter que du bien

**Comment by Feiryn** [comment]
Déjà fait

**Comment by BastLast** [comment]
> Déjà fait

ah ?

**Comment by BastLast** [comment]
quand ?
