### ISSUE TITLE
Typos pour la 3.0.0.a

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1183]
Envoyer en commentaire toutes les typos repérées sur le bot qui doivent être corrigées. CF issue #952 pour celles déjà corrigées

**Comment by symsym-1629** [comment]
sur la branche develop quand on mentionne le bot on a le droit a un joli {prefix} sur le anglais
![Capture-1_7-7-2022](https://user-images.githubusercontent.com/83075391/177829567-0f3fd2d4-f16b-4ff2-b31c-ce1412086a1a.png)

**Comment by symsym-1629** [comment]
La répétition du semble est pas très jolie, il faudrait replacer le 2eme semble par a l'air

![unknown-2.png](https://user-images.githubusercontent.com/83075391/177959995-4c5eb52d-e38a-40b3-b866-39d90bf59882.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/179220026-b3b295f1-cbf0-4f29-b24c-3c21bc24520f.png)
Enlever la répétition de "fidèle", en supprimant la première utilisation du mot ("mais qui reste fidèle dans la course [...]") ?

**Comment by Pietagorh** [comment]
"Pendant que vous oservez" -> observez
"matière que nous parvenez pas à identifiez" -> identifier
![image](https://user-images.githubusercontent.com/60353007/179266293-20279b36-d21b-402f-8ee3-c6e0b943b51d.png)

**Comment by Pietagorh** [comment]
Modifier la répétition de "fidèle"
![image](https://user-images.githubusercontent.com/60353007/179269055-40432329-47fe-4309-9bfb-8ae7f312325c.png)

**Comment by BastLast** [comment]
> Mauvais emoji ![image](https://camo.githubusercontent.com/1a7021bd549f1007b386aa184e62388d99457c8e36b3e8957909bf926ebbee8e/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3837303336333333313932323338323836382f3939373535343531313532343636333339382f53637265656e73686f745f32303232303731352d3139323432342e6a7067)
???????????????????

**Comment by Pietagorh** [comment]
Bah c'est 🏅 pas 🎖

**Comment by Pietagorh** [comment]
"des classes disponible" -> disponibles
"personnage et leur statistique" -> leurs
![image](https://user-images.githubusercontent.com/60353007/179286820-c2126e6b-1a04-4c86-b6b5-62cbfed8f3a0.png)

**Comment by Pietagorh** [comment]
"Fonctionne mieux sur adversaire lent" -> sur un adversaire lent
![image](https://user-images.githubusercontent.com/60353007/179287930-08204149-af16-43de-a455-494a0af464f3.png)

**Comment by Pietagorh** [comment]
1/ "une rumeur cours" -> court
2/ La 1ère phrase commence par "Après", la deuxième phrase aussi -> Répétition du mot "Après"
3/ "pendant quelques jours" -> Pas logique, on obtient pas d'alté de quelques jours, et l'on vient juste d'arriver 
4/ "sous-sol d'un grenier à grain" -> Par définition, un grenier est une pièce sous les combles d'une maison, peut-être préférer une cave d'affinage de fromages ou de vins, par exemple
![Capture_decran_2022-07-15_a_20.31.10.png](https://user-images.githubusercontent.com/60353007/179308064-31185204-bbf4-4303-a1c5-bac514b06f5a.png)

**Comment by Pietagorh** [comment]
J'ai pas tout fait, il reste les trucs de reformulation pour la 3.0.0.b
Ou alors je les déplace dans une nouvelle issue ?

**Comment by BastLast** [comment]
go nouvelle issue qui référence celle là
