### ISSUE TITLE
mission chooseclass tier ne fonctionne pas 

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1200]

**Comment by Pietagorh** [comment]
Ok donc je sais pas pourquoi mais selectedClass.classGroup ça donne undefined, au moins dans ClassCommand, par contre je sais pas pourquoi ça fait ça x)

**Comment by Pietagorh** [comment]
En fait c'était juste un problème de majuscule dans un nom entre model et db x)
Il y avait class**G**roup dans le model et class**g**roup dans la db, du coup classGroup pouvait prendre aucune valeur xD

Par contre du coup pour modif le nom dans la db, faut obligatoirement faire un nouveau fichier dans migrations, j'peux pas ajouter ça à fixes 3.0.0 ? J'ai essayé mais ça marchait pas x)
