### ISSUE TITLE
Extract methode les changements d'altérations dans les fightAction

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1201]
_Originally posted by @romain22222 in https://github.com/DraftBot-A-Discord-Adventure/DraftBot/pull/1174#discussion_r918219528_

**Comment by BastLast** [comment]
@Feiryn  du coup je crois que tu l'as fait ça dans ton refactor non ?

**Comment by Feiryn** [comment]
Je ne comprends pas l'issue

**Comment by BastLast** [comment]
Check le lien en haut

**Comment by BastLast** [comment]
@romain22222 si tu as des clarifications sinon

**Comment by Feiryn** [comment]
Si j'ai bien compris oui c'est fait, compliqué sur tel

**Comment by BastLast** [comment]
ok je close then

**Comment by romain22222** [comment]
> @romain22222 si tu as des clarifications sinon

je confirme que ca a été résolu (pas comme je l'imaginais  à l'époque, mais oui c'est good)

**Comment by BastLast** [comment]
Merci bg

**Comment by romain22222** [comment]
de rien bb
