### ISSUE TITLE
Ne pas avoir de commandes "only for me" si c'est pas un bug

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1202]
Par exemple le drink force s'affiche pas, mais yen a d'autres.

Je pense que c'est mieux que le jeu reste public.

**Comment by Pietagorh** [comment]
Euh ?
![image](https://user-images.githubusercontent.com/60353007/178374007-d1b20636-cd3b-4cd4-a138-d58f68f249fa.png)

**Comment by BastLast** [comment]
Uh

**Comment by BastLast** [comment]
Bah tt a lheure pr symsym ca s'affichait pas wtf

**Comment by BastLast** [comment]
Jai maybe confondu

**Comment by Pietagorh** [comment]
Y'a que les erreurs qui sont pas des annulations qui sont en ephemeral
Du coup là c'est boire une potion sans effet
Après j'trouve que c'est une bonne idée de faire que boire une potion sans effet donne pas un message d'erreur

**Comment by BastLast** [comment]
oui je trouve aussi.
