### ISSUE TITLE
Certains messages disparaissent parfois de l'historique de fight

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1214]

**Comment by BastLast** [comment]
impossible de reproduire ce bug de manière constante. ca a l'air d'arriver après une altération d'état mais pas toujours... je ne comprend pas

**Comment by BastLast** [comment]
je propose de repousser ce bug à plus tard vu qu'il est très peu génant

**Comment by Pietagorh** [comment]
J'ai une théorie
Ce serait que le await attend que le message du bot soit parti, mais pas qu'il soit reçu sur discord, et donc quand on récupère le dernier message on récupère une ancienne version à cause du lag

**Comment by BastLast** [comment]
smart

**Comment by Hatisham** [comment]
Ça m'est arrivé plusieurs fois, je te laisse un screenshot d'un de mes combats récents où le message qui montre les dégâts causés par mon attaque ultime n'apparait pas 
![image](https://user-images.githubusercontent.com/110303693/203411164-475e91e7-d7f4-4b3d-bd78-3ca0bc355ef0.png)

**Comment by BastLast** [comment]
J'annonce que j'offre un sticker DraftBot + le badge 🎰 au premier qui fix ce bug x)

**Comment by voltou91** [comment]
J'ai déjà le badge, mais sinon tu me met vip :)

**Comment by BastLast** [comment]
Vip si fix ce soir mdr
