### ISSUE TITLE
Réussir une mission qui donne de l'xp en meme temps qu'on recoit de l'xp fait que les 2 trucs d'xp s'annulent

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1216]

**Comment by BastLast** [comment]
@romain22222  le bug des missions n'est toujours pas fix

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/178706100-2841bd46-b0c6-409f-8a33-307e360e28d8.png)
et ya toujours le bug de répétition de missions

**Comment by Pietagorh** [comment]
C'est pas #1121 ça ?
