### ISSUE TITLE
mission "visiter x lieux différents" se complète à chaque nouveau lieu

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1217]
![image](https://user-images.githubusercontent.com/38099970/178695164-0e500dfb-e2eb-48ef-a5ce-455b5985df21.png)

**Comment by Feiryn** [comment]
J'ai toujours le problème sur develop

**Comment by Feiryn** [comment]
J'ai rien dit
