### ISSUE TITLE
Répétition echec de mission

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1230]
![image](https://user-images.githubusercontent.com/38099970/178706100-2841bd46-b0c6-409f-8a33-307e360e28d8.png)
et ya toujours le bug de répétition de missions

_Originally posted by @BastLast in https://github.com/DraftBot-A-Discord-Adventure/DraftBot/issues/1216#issuecomment-1183016127_

**Comment by Nargacaura** [comment]
C'est encore présent. Shin en a fait les frais il y a moins d'une heure.
![IMG_20220831_134139.jpg](https://user-images.githubusercontent.com/94372084/187670543-8872cc9f-1c58-41c7-81e7-7e53b2c93379.jpg)
