### ISSUE TITLE
Les emotes persos ne s'affichent pas bien sur certains servs

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1246]
![image](https://user-images.githubusercontent.com/60353007/179263269-025efb59-2514-4f42-bc29-fd7e015b006a.png)
![image](https://user-images.githubusercontent.com/60353007/179263458-2f510cca-b345-4e2c-8aad-a8a63f5267b2.png)

**Comment by Pietagorh** [comment]
(Le bot a les perms des emojis externes)

**Comment by BastLast** [comment]
sûr de ça ?

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/179327417-1e0391e8-d111-4bbc-be8f-5c7e7e8e255f.png)

sur mon serv ça marche niquel

**Comment by Pietagorh** [comment]
Ouaip moi aussi mais j'suis allé check et ça marche juste pas là bas
Apparemment le bot y est admin donc il est censé avoir la perm

**Comment by BastLast** [comment]
j'y crois pas perso m'enfin bon

**Comment by BastLast** [comment]
ca marche niquel
sauf sur un serveur ...

**Comment by Pietagorh** [comment]
J'suis allé vérif moi-même il est admin

**Comment by BastLast** [comment]
ptetre tu as mal vérifié

**Comment by Pietagorh** [comment]
Nan mais du coup j'suis en train de leur en reparler et d'autres bits ont un problème aux emojis externes sur leur serv
Donc en fait c'est juste un problème chelou de discord (et j'ai vérif 20 fois il est admin)

**Comment by Voisin1234** [comment]
.

**Comment by romain22222** [comment]
ouais du coup issue closable ?

**Comment by Pietagorh** [comment]
Nope, juste après avoir fermé l'issue on a eu un report de la même chose pour un autre serv
Mais cette fois-ci c'est juste 1 fois que l'emote s'est pas affichée

**Comment by Pietagorh** [comment]
Apparemment ça remarche chez ceux qui l'ont report en premier

**Comment by Pietagorh** [comment]
C'est aussi réparé chez Voisin, donc j'imagine que c'était un problème de discord x)
