### ISSUE TITLE
Tuto fonctionnalité annexes

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#125]
- [x] Bloquer les commandes liées aux guildes pour les niveaux inférieurs à 10
- [ ] Mettre des évents qui 'n'aparaissent qu'une fois pour expliquer comment fonctionne les fights et les guildes

https://trello.com/c/ci7IphRT/415-d%C3%A9bloquer-les-guildes-a-un-certain-level-genre-10-378513552270557185

**Comment by quenquentin** [comment]
Pour les évents "tuto" je doute qu'ils soient prêts pour la 2.0.3, car actuellement aucun d'eux n'est commencé.
A voir quand la 2.0.3 sortira ¯\_(ツ)_/¯

**Comment by BastLast** [comment]
> 
> 
> Pour les évents "tuto" je doute qu'ils soient prêts pour la 2.0.3, car actuellement aucun d'eux n'est commencé.
> A voir quand la 2.0.3 sortira ¯_(ツ)_/¯
je déplace cet issue pour une future mise à jour alors.

**Comment by quenquentin** [comment]
Le bloquage des commandes de guilde inférieur au niveau 10 a été fait. Ça peut donc être check.

**Comment by BastLast** [comment]
Au final avec le guide et les changemants de la 2.0.0 On passe en wontfix poru le moment
