### ISSUE TITLE
Typos pour la 3.0.0.b

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1269]

**Comment by Pietagorh** [comment]
![unknown-35.png](https://user-images.githubusercontent.com/60353007/179351997-dbf0098e-83ad-4683-a1ee-8fe64fd96db4.png)

**Comment by Pietagorh** [comment]
En anglais
![IMG_20220716_125656.jpg](https://user-images.githubusercontent.com/60353007/179352050-a042b595-8e23-4b4e-96dc-9b7d347e2754.jpg)

**Comment by Pietagorh** [comment]
![unknown-49.png](https://user-images.githubusercontent.com/60353007/179361604-8810a8d5-e518-4ee6-b309-308bcf4c4c14.png)

**Comment by Pietagorh** [comment]
+ ce qu'il reste dans #1183

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180024389-efd488d3-930b-4955-bb78-669ba0cc3603.png)
C'est une femelle donc au départ c'est bon, mais à la fin il y a "in **his** mouth". Et sinon il y a des ** mal placés.
