### ISSUE TITLE
Message help quand on mentionne répond au everyone

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1277]
(& aux réponses aussi, donc c'est chiant quand on veut montrer un truc à quelqu'un mais c'est optionnel ça)

**Comment by Nargacaura** [comment]
Le bug n'a pas été fix, malheureusement. Le bot répond toujours aux everyone et here.

**Comment by BastLast** [comment]
Wtf ça a été testé ça...

**Comment by BastLast** [comment]
@romain22222  du coup j'ai add ça dans la milestone
