### ISSUE TITLE
Un combat peut refuser de se lancer

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1278]
Dans le cas où plus de 2 personnes cliquent en même temps (dans l'exemple du screenshot, 3 personnes ont cliqué en même temps au début, puis 2 autres ont essayé ultérieurement), le bot peut hésiter sur qui sera l'adversaire du demandeur et simplement refuser de lancer un combat, même si d'autres essaient d'accepter la demande de combat ultérieurement en se demandant si ce n'était pas dû aux altérations des précédents prétendants au duel (l'erreur d'alté étant en ephemeral). En conséquence, le bot pense que personne n'a accepté la demande et clot celle-ci malgré des acceptations valides (aka provenant d'adversaires qui n'ont aucune altération d'état).

![Screenshot du cas rencontré](https://cdn.discordapp.com/attachments/998164850364661800/998236199435124826/Capture_decran_2022-07-17_133544.png)

**Comment by romain22222** [comment]
le second est un bobard
j'ai juste accepté le fight en concurence avec les autres, et j'ai double clic sur la reac, donc elle y est plus

**Comment by Nargacaura** [comment]
J'ai modifié l'issue en prenant en compte ton commentaire.

**Comment by BastLast** [comment]
est-ce que vous arrivez à reproduire le bug ou c'est arrivé juste une fois ?

**Comment by romain22222** [comment]
pour le moment je l'ai vu qu'une seule fois à l'action, donc je pense c'est des conditions particulières

**Comment by BastLast** [comment]
On arrive pas à reproduire ce truc ?

**Comment by BastLast** [comment]
bon pas de nouvelle de ce soucis depuis juillet, à réouvrir si qqun arrive à reproduire
