### ISSUE TITLE
Dockerisation

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#1279]
C'est bien d'isoler le bot au cas où 👍

Le plan actuel c'est 3 docker, 

- [x] 1 pour draftbot
- [x] #1281
- [x] #1282
- [x] Il faut changer la structure du dossier dist et mieux gérer le link-module-alias (l'enlever par exemple)
- [x] #1376

**Comment by BastLast** [comment]
Je plussoie

**Comment by BastLast** [comment]
Le plan actuel c'est 3 docker, 

1 pour draftbot
1 pour les bdd
1 pour un grafana
