### ISSUE TITLE
Typos pour la 3.0.1

### ISSUE THREAD

**Issue by Chevalier2** [DraftBot-A-Discord-Adventure/DraftBot#1284]

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180028352-22e15666-6b78-45f2-8b33-8aeb83ff9587.png)
 "Si vous en n'avez plus" -> "Si vous n'en avez plus".

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180037598-848329de-3be0-4169-bd3f-dc47b92601fa.png)
"se détache" à la place de "s'en détache" ?

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180038118-4a902d3e-6ff6-4abe-9cda-0a8ebbb42940.png)
C'est "t**h**reats" et non "treats".

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180230447-89627e90-8595-44c6-af4f-65d2f23e9089.png)
Prefix -> :x: ; badge -> badges ; shelter -> guildshelter ; guildelder_remove -> guildelderremove ; mypet -> pet.

**Comment by Pietagorh** [comment]
> ![image](https://user-images.githubusercontent.com/72626953/180230447-89627e90-8595-44c6-af4f-65d2f23e9089.png)
> Prefix -> :x: ; badge -> badges ; shelter -> guildshelter ; guildelder_remove -> guildelderremove ; mypet -> pet.

La commande prefix existe toujours, elle affiche un texte qui dit qu'on est passé aux slash

**Comment by Pietagorh** [comment]
Remolacer par ⌛ et utiliser la façon d'afficher le temps utilisée dans tout le bot (x Min)
![IMG_20220725_162150.jpg](https://user-images.githubusercontent.com/60353007/180800008-c143b7d7-7d8e-47de-8ed5-2d931a71e6f0.jpg)

**Comment by Pietagorh** [comment]
Ajouter un texte pour quand le familier fielleux est celui de l'autre ![unknown-57.png](https://user-images.githubusercontent.com/60353007/180872921-8be82c30-fc18-49cc-a92d-a7828acbd0fc.png)

**Comment by Pietagorh** [comment]
Ajouter le Journal de x
![IMG_7159.png](https://user-images.githubusercontent.com/60353007/180977108-7f8bdf63-4802-4966-a29a-a406b5022acf.png)

**Comment by Pietagorh** [comment]
![unknown-39.png](https://user-images.githubusercontent.com/60353007/181124891-f5655907-d389-4a71-a308-fe736f1d197c.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181936081-78aa8e1a-4a47-41f4-85a7-5071bbed2008.png)
"Avance le temps plus rapidement pendant x heure" -> "Avance le temps de x heure" ?

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181936138-f6bcbb2c-58cb-4c43-b7ba-6870989ec685.png)
Remplacer "un groupe" par "une harde".

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181936170-af8bf911-111c-458d-a81c-f4aac1dfb5df.png)
"dans le bas-côté" -> "sur le bas-côté".

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181936300-620d2803-4286-4408-afdd-8455c34b89fd.png)
"expansive" -> "expensive".

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181936349-ffd79334-f0f5-4337-8d8f-3c091e92b55f.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181936407-a7fbc1a7-271b-4c0b-9459-8bdb063d7666.png)
Il manque la majuscule à "Ce n'est que partie remise [...] votre route".

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181937051-9b5e7d50-e1a8-4a9e-ae77-1005260e6fc5.png)
Conseil encore valable ?

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181937194-af9fa01a-8140-4e13-a9c1-d7b059998c53.png)
Répétition à enlever : "Couverts de **de** plumes". C'est un nouvel event.

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181937373-05fa1c71-b9bd-4be4-a739-9471ddd405fa.png)
Aucune explication sur un gain d'objet, donc il faudrait le retirer.

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181937559-378ccd6d-0b35-4df7-8ca8-32f2a63df9d0.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181937588-e05ae93f-6b71-45e4-b34c-11deea2ca66e.png)
"!respawn" -> "/respawn".

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181937622-0af7dbd1-bdef-4f73-8ecf-8dcc17dd324f.png)
Les alias n'existent plus, il y a seulement "/pet" maintenant.

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/181937692-ecf7be4b-dbbb-4c95-bd09-2cdb475350c2.png)
"assénez cette dernière d'un grand coup" -> "assénez un grand coup à cette dernière".
