### ISSUE TITLE
Event qui n'apparaît pas

### ISSUE THREAD

**Issue by Chevalier2** [DraftBot-A-Discord-Adventure/DraftBot#1285]

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180411339-7358388c-fd5d-427b-b680-732c2641c733.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180411604-6bf51be7-7a30-4ab0-956d-3e2f0a79e0a2.png)
![image](https://user-images.githubusercontent.com/72626953/180411643-9b719d3b-7faf-4d0f-b49a-d4893385b4fd.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180411807-db44c55f-a408-426e-a319-a8c1538ea17f.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180411873-c6ac0dc5-36d0-4e8e-a5a4-0dee986cfda6.png)
![image](https://user-images.githubusercontent.com/72626953/180411901-2c4dc945-d37d-42bf-ba60-b2b0f2170f0c.png)

**Comment by Chevalier2** [comment]
@Pietagorh

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/180432496-a52be2cb-ab1b-4547-884a-762a0fed9f03.png)

**Comment by Pietagorh** [comment]
Pareil, Unknown Interaction
