### ISSUE TITLE
Double report

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1292]
https://discord.com/channels/429765017332613120/435100271413297152/999390038477521068 (on va éviter de donner l'explication à ceux qui l'ont pas x))

**Comment by BastLast** [comment]
vu qu'o a moyen de surveiller, ce bug n'est pas urgent, on s'en occupera later

**Comment by BastLast** [comment]
@romain22222  pr le numéro de l'issue btw :)
