### ISSUE TITLE
[BUG]: une interaction trop rapide avec le shop peut causer sa fermeture

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#1301]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

lors de l'achat d'une potion le shop s'est fermé à la place de proposer l'achat

### Reproduction du bug.

ouvrir le shop et sélectionner un article rapidement, le bug sembler arriver aléatoirement

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by BastLast** [comment]
pas un bug trop génant et j'aimerai faire la maj ce soir donc je repousse ça

**Comment by romain22222** [comment]
Le bug semble si rare qu'il semblerait ne pas avoir été reproduit depuis plus d'un mois, je ferme l'issue

**Comment by BastLast** [comment]
Ya une personne qui a encore réussi à ke refaire du coup ca a pas l'air si rare

**Comment by Jaarzz** [comment]
En testant sur le dB Alpha, j'ai fait /guildshop et acheté de l'XP
J'ai fait un 2e /guildshop et essayé d'acheter des aliments. Le bug de la fermeture du shop s'est produit
J'ai fait un 3e /guildshop et encore le même bug.
Ce n'est pas dû a l'exécution d'une réaction rapidement, d'après moi, car je ne me suis pas dépêché d'appuyer sur une de celles ci

Pour compléter cette description, auparavant, j'avais fait plusieurs /shop (cette fois ci) et le même bug s'est produit après quelques essais. 
Je fournis des screen ci contre 
![Capture d'écrans_20221003-182015](https://user-images.githubusercontent.com/106905934/193629439-0e6feba8-0049-4d35-9fa3-0e96cc29da4d.png)
![Uploading Capture d'écrans_20221003-182011.png…]()

**Comment by Jaarzz** [comment]
Hop, je rajoute mon essai sur /shop
![Capture d'écrans_20221003-182651](https://user-images.githubusercontent.com/106905934/193629801-074b867e-467c-4288-ae92-af999e130ce2.png)
