### ISSUE TITLE
Message de vente + message annulation (/sell)

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1307]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

![image](https://media.discordapp.net/attachments/870363331922382868/1002183569885642804/Screenshot_20220727_003802.jpg)

### Reproduction du bug.

Faire /sell
Vendre un item
Attendre 2 minutes

Il doit y avoir un autre paramètre par contre, je suis allé check d'autres messages de sell et ça le fait pas
C'est pas non plus qu'une autre transaction (type petsell) était faite avant, sinon il aurait pas pu ouvrir le sell + le message d'arrêt du petsell est pas le même

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by Feiryn** [comment]
J'ai regardé le code et j'ai fait des tests et je n'ai aucune idée de comment ce problème et celui de #1345 sont possibles

**Comment by BastLast** [comment]
est-ce que des @DraftBot-A-Discord-Adventure/testers  peuvent faire des tests sur alpha juste pour check que le bug existe toujours et confirmer ici si c'est le cas ? Si possible avoir un peu plus d'infos aussi, ça peut être utile

**Comment by KirIcare** [comment]
J'ai fait la démarche avec le même objet et... Rien
Il doit effectivement y avoir autre chose

**Comment by BastLast** [comment]
> J'ai fait la démarche avec le même objet et... Rien
> Il doit effectivement y avoir autre chose 

Faut essayer un max de situations, pleins de trucs jusqu'à reproduire, et si c'est pas possible on fermera l'issue

**Comment by KirIcare** [comment]
Et ben je vois pas... J'ai effectué une quinzaine de situations différentes mais toujours rien.
Soit y'a vraiment rien soit faut voir avec un autre testeur s'il trouve ou pas
