### ISSUE TITLE
[BUG]: non affichage du guilddaily

### ISSUE THREAD

**Issue by Azedixene** [DraftBot-A-Discord-Adventure/DraftBot#1308]
### Le bug n'a t-il pas déjà été signalé ?

- [x] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

![0E8B8DC9-5BD3-40E2-A42C-3E0888551236](https://user-images.githubusercontent.com/61432341/181891723-0ed37e8a-dfcc-461c-9ace-52440bdd9897.png)
![8AFBB45F-C164-430F-B663-98303F86BBA7](https://user-images.githubusercontent.com/61432341/181891740-07fb42de-17da-4954-90be-1e8cf4e5f200.png)

Le guilddaily nous a apparemment redonné des vies puisque la mission du jour « gagner 10 pv » à été réussie, mais aucun message du bot pour nous dire combien on a gagné 

### Reproduction du bug.

Aucune idée 

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by Nargacaura** [comment]
L'ossue existe déjà: #1275.

**Comment by BastLast** [comment]
Faut fusionner les 2 issues en une seule avec toutes les infos et mettre le tag duplicata sur l'autre

**Comment by Pietagorh** [comment]
C'est fix dans une pr

**Comment by Pietagorh** [comment]
Juste parfois avec le nombre de tests sur les gens ça prend plus de 3 secondes, donc j'ai mis un defer et ça marche bien

**Comment by BastLast** [comment]
Faut quand meme fusionner

**Comment by Pietagorh** [comment]
Comment tu fais ? x)

**Comment by BastLast** [comment]
Tu met duplicata en label sur l'issue la moins bien, tu tag l'autre issue et éventuellement la pr et tu close

**Comment by Pietagorh** [comment]
Bah écoute vu que j'ai tag l'autre issue dans les commits j'vais close celle-ci xD
La pr c'est #1291 du coup
