### ISSUE TITLE
Améliorer la regex de détection de voyelle

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1312]
Ça fonctionne pas avec les h actuellement x)
![IMG_20220720_204121.png](https://user-images.githubusercontent.com/60353007/181937585-68ccd879-aa95-4dd9-b145-292869d2219e.png)

**Comment by Nargacaura** [comment]
J'étais tombé sur un regex non fonctionnel avec le "É" il y a un peu plus d'une heure, du coup... Est-ce que le fix a été accidentellement revert ou ça ne fonctionnait pas avec ce caractère même avec ce fix? En tout cas, le regex ne fonctionne actuellement pas.
![IMG_20220813_151815.jpg](https://user-images.githubusercontent.com/94372084/184498789-9d8e0226-3b6e-497b-b2a0-02810a7202a6.jpg)

**Comment by BastLast** [comment]
Je reouvre.

**Comment by romain22222** [comment]
euh j'ai revérifié sur le bêta, sur la même situation, je n'ai pas le problème et il n'y a pas eu de nouveau commits sur cette zone. J'en conlus donc que c'est non reproducible

**Comment by BastLast** [comment]
Avec le meme item ? Screen ?

**Comment by romain22222** [comment]
![image](https://user-images.githubusercontent.com/29299679/184546942-0332149e-56aa-44c8-927c-2fc1b685f14b.png)

**Comment by BastLast** [comment]
Hm

**Comment by Feiryn** [comment]
C'est fix du coup ?

**Comment by Feiryn** [comment]
Le vent

**Comment by Pietagorh** [comment]
C'est finit ça nan ?

**Comment by BastLast** [comment]
Faut que @romain22222 confirme

**Comment by romain22222** [comment]
j'aimerais confirmer, mais je préfère que y'ait des tests sur l'alpha avant, je l'ai fix une 1re fois ca n'avait pas marché pour une raison inconnue

**Comment by Feiryn** [comment]
Je valide c'est corrigé

**Comment by Nargacaura** [comment]
À rouvrir: ~~sa~~ **son Â**!
![IMG_20221125_140749.jpg](https://user-images.githubusercontent.com/94372084/203992467-fe419b52-20c3-457b-b1f4-a17d7c6629c6.jpg)

**Comment by BastLast** [comment]
> À rouvrir: ~~sa~~ **son Âme**!
> ![IMG_20221125_140749.jpg](https://user-images.githubusercontent.com/94372084/203992467-fe419b52-20c3-457b-b1f4-a17d7c6629c6.jpg)

Cette issue est fermée, il faut envoyer ca sur l'issue de typo
