### ISSUE TITLE
[BUG POSSIBLEMENT DEJA REPORT]: 1 PV non justifié en combat 

### ISSUE THREAD

**Issue by AzuraLee** [DraftBot-A-Discord-Adventure/DraftBot#1313]
### Le bug n'a t-il pas déjà été signalé ?

- [x] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Lors d'un combat avec un membre de la guilde (FROG I), j'ai pris un - 222 alors que j'avais 183 hp et quelques. Hors, suite à cette attaque, j'ai été descendu à 1 HP 
Ce qui est donc illogique, car il n'existe pas (à ma connaissance du moins) de résistance à la mort dans le système de combat.
![Report2](https://user-images.githubusercontent.com/108440316/181996252-ef5e84de-e190-4ac2-b8da-871ef73389d1.PNG)
![report1](https://user-images.githubusercontent.com/108440316/181996348-54e7bbef-3bb2-44d7-98cf-91356229057c.PNG)

### Reproduction du bug.

La façon dont le bug s'est produit n'est pas certaine, mais dans un soucis de lisibilité, j'ai mis la totalité du combat en pj 
Note: je possède 969 hp de base, après calcul j'ai bien pris 39 dégâts de plus que ma vie ne le permettait
![report1](https://user-images.githubusercontent.com/108440316/181996385-92197fa8-5141-45ef-babc-bb7f5b6b439d.PNG)
![Report2](https://user-images.githubusercontent.com/108440316/181996390-fdebd5b2-560a-4699-8491-b7f0a08b711e.PNG)

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by leuhvraiminoryo** [comment]
l'attaque intense ne peut pas tuer. C'est voulu et précisé dans le bot

**Comment by Pietagorh** [comment]
Comme l'a dit mino, c'est une mécanique voulue, seulement pour l'attaque intense
C'est précisé à la fin de la description de l'attaque dans le /classinfo btw 👀
