### ISSUE TITLE
Refacto minievent gobelets

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1314]
![unknown-58.png](https://user-images.githubusercontent.com/60353007/182021560-639bac08-4616-441d-9e7b-9feb9317a952.png)

**Comment by BastLast** [comment]
division par 3,75

**Comment by romain22222** [comment]
D ailleurs question sur ce m8ni event, c est fait expres qu il y ait que des malus ?

**Comment by BastLast** [comment]
oui

**Comment by BastLast** [comment]
en gros c'est l'opposé du mini event de gaspard-jo ou ya que des bonus
