### ISSUE TITLE
[BUG]: Classement du serveur

### ISSUE THREAD

**Issue by lemaximedu66** [DraftBot-A-Discord-Adventure/DraftBot#1315]
### Le bug n'a t-il pas déjà été signalé ?

- [x] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Quand la commande de.classement du serveur est passer, le bot ne donnera jamais de réponse.

### Reproduction du bug.

Envoyer la commande /top server

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by Nargacaura** [comment]
Doublon de #1243

**Comment by lemaximedu66** [comment]
J'avais pas vu dsl
