### ISSUE TITLE
Nouveaux items pour la 3.1.0

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1318]

**Comment by Pietagorh** [comment]
Objet d'attaque : 🎭 Masque Mojaro | Epique | ~90 (équivalent à la Lune de Mojaro mais en attaque)

**Comment by BastLast** [comment]
Item donateur ?

**Comment by Pietagorh** [comment]
Oui

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/189948261-e67bcf83-ff0f-4414-bc0d-a775210488ae.png)
Demande d'armure mais peut être changer ça en item ?

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/189955360-9e6897cc-b878-4331-ac81-80c0ac06bb7b.png)
+30 atk + 100 def

**Comment by BastLast** [comment]
on fera un point sur les items juste avant la maj

**Comment by BastLast** [comment]
@quenquentin  possible de préparer la pr ? la maj est soon

**Comment by quenquentin** [comment]
Got it, envoie la date finale en dm Discord tho @BastLast

**Comment by BastLast** [comment]
Avant vendredi

**Comment by quenquentin** [comment]
![_20220930_191213.JPG](https://user-images.githubusercontent.com/56274541/193322496-9c07f71d-4617-41e1-ab62-d930886ca4c6.JPG)![_20220930_191148.JPG](https://user-images.githubusercontent.com/56274541/193322510-bc94061d-6400-43c5-9731-53fc5b6bb74a.JPG)![_20220930_191129.JPG](https://user-images.githubusercontent.com/56274541/193322519-d1765214-81ee-439a-a3aa-38f139921d76.JPG)![_20220930_191114.JPG](https://user-images.githubusercontent.com/56274541/193322528-b252fd19-7d69-44f5-9543-085360a0afe5.JPG)![_20220930_191107.JPG](https://user-images.githubusercontent.com/56274541/193322540-2cfd5c65-ada1-420b-84e8-9a9a534e1c70.JPG)

**Comment by quenquentin** [comment]
![IMG_20221005_121641.jpg](https://user-images.githubusercontent.com/56274541/194038069-bca9ac2b-9cb6-4be7-83b3-82a26e307109.jpg) Si possible avant maj ? Sinon je ferai le switch de milestone

**Comment by BastLast** [comment]
Imo reclose ici et ouvre une nouvelle

**Comment by BastLast** [comment]
Et pas pr cette maj
