### ISSUE TITLE
[PAS UN BUG]: Combat faisable pendant une altération d'état

### ISSUE THREAD

**Issue by Jaarzz** [DraftBot-A-Discord-Adventure/DraftBot#1319]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Je suis en altération pendant encore 2h mais j'ai réussi à faire un combat demandé par quelqu'un d'autre 
![image](https://user-images.githubusercontent.com/106905934/182360194-4245a88f-9999-4ebc-86ee-d1a7909ef226.png)
![image](https://user-images.githubusercontent.com/106905934/182360389-910fcadd-db2d-490c-b137-8a5e0163a956.png)
 Regardez l'heure de chacun des message

### Reproduction du bug.

Aucune étape

### Dans quelle condition le bug a-t-il été trouvé ?

Sur le serveur officiel du bot avec le bot officiel.

**Comment by Pietagorh** [comment]
Pas un bug, c'est voulu

**Comment by Pietagorh** [comment]
Les combats sont amicaux pendant cette màj, donc c'est possible (comme les ff avant)
