### ISSUE TITLE
Typos pour la 3.1.0

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1327]

**Comment by Pietagorh** [comment]
badge -> badges
mypet -> pet
shelter -> guildshelter
![IMG_20220807_204526.jpg](https://user-images.githubusercontent.com/60353007/183306383-087e708a-7ba4-4f98-903e-29e06412a997.jpg)

**Comment by Nargacaura** [comment]
Corrigé dans les détails, hm? Le titre des commandes spécifiques n'est pas à jour non plus...
![Screenshot_20220807-205348.png](https://user-images.githubusercontent.com/94372084/183306685-2d0a28a6-2f8f-4376-a617-6563d66e7833.png)

**Comment by Pietagorh** [comment]
Underscore en trop dans le titre 
![IMG_20220807_205745.jpg](https://user-images.githubusercontent.com/60353007/183306792-b6de726c-f0b2-4c50-880c-edff5bd02f18.jpg)

**Comment by BastLast** [comment]
commands.pet: "isFeistyOther" is present in french but not in english 
commands.pointsWeek: "errors.invalidNumberOfArgs" is present in english but not in french

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/183858671-b5cefe49-681d-4033-a59a-da478e5cc833.png)
Accent manquant sur le e -> R**é**ceptacle.

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/184556823-dda43d4c-62b0-4651-8272-4eb20e40d890.png)
Accent manquant au e de "**é**toile filante".

**Comment by Pietagorh** [comment]
Message de succès du guilddesc
![IMG_20220816_214012.jpg](https://user-images.githubusercontent.com/60353007/184970816-5c38500a-25dd-4c9c-a6cd-4a9a154dfa9b.jpg)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/188181722-43d7da92-f44a-4b55-9a2e-de75e75d1970.png)
"[...] la masse d'animaux qui vien**t** de vous frôler [...]", c'est vien**t** pas vien**s**.

**Comment by Nargacaura** [comment]
Il manque une partie de la phrase dans le mini-event de vote... **Aucune** partie n'est récupérée pour effectuer une liaison entre l'intro et la parole effectuée. Une suspicion serait un JSON mal formaté ou manquant.
![IMG_20220903_151052.jpg](https://user-images.githubusercontent.com/94372084/188272032-e7cdb099-9062-4d8c-859d-3adc805acee1.jpg)

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/192599591-b4ecf501-9453-4814-a33d-0ade662b6bc5.png)

**Comment by BastLast** [comment]
Merci de report les prochaines typos ici : #1428
