### ISSUE TITLE
[BUG]: guilddaily ne fonctionne plus

### ISSUE THREAD

**Issue by Bombafox** [DraftBot-A-Discord-Adventure/DraftBot#1331]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Le guilddaily tourne en boucle et ou me met un message d'erreur donc ne s'affiche pas sur la commande et ne s' envoie pas mp

![Screenshot_20220808_084020](https://user-images.githubusercontent.com/96150225/183391313-1b27d63e-a381-4799-a26a-7ddff42a165a.jpg)

### Reproduction du bug.

A pars faire la commande jsp trop c'est que la deuxième fois que ça me le fait

La dernière fois c'est quand j'ai fait le gd on a reçu de la vie ça a fini la mission secondaire de sh7no qui lui a fait lvl up niv 100
Mais on a jamais eu le mp et ça me l'a mis en message d'erreur 

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by Pietagorh** [comment]
Si c'est c'que j'pense j'suis vraiment con xD

**Comment by Pietagorh** [comment]
J'irai voir dans les logs

**Comment by BastLast** [comment]
c'est quoi ce titre d'issue est-ce que vous pouvez faire un effort svp ?

**Comment by Bombafox** [comment]
Mb c'est la première fois que je passe faire ça sur tel et c'est un peu compliqué j'ai pas fait gaffe

**Comment by BastLast** [comment]
np je disais surtout ca pr les gens qui sont passés dessus sans maj le titre :)
