### ISSUE TITLE
[BUG]: variable (et pas la valeur) pour l'item de vie "pomme"

### ISSUE THREAD

**Issue by voltou91** [DraftBot-A-Discord-Adventure/DraftBot#1332]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Bah ça affiche la variable et non la valeur de la variable, c déjà écrit dans le titre ptdr.

### Reproduction du bug.

Bah tu ouvre ton inventaire si tu l'a.

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by voltou91** [comment]
![Capture d'écrans_20220808-123140](https://user-images.githubusercontent.com/62652451/183399477-c295a42f-88fa-495f-9530-9e16dca1e2b9.png)

**Comment by BastLast** [comment]
@Pietagorh c'est quoi ces tests en carton ?
