### ISSUE TITLE
[BUG]: la map ne s'affiche pas 

### ISSUE THREAD

**Issue by Akutana** [DraftBot-A-Discord-Adventure/DraftBot#1335]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

J'ai essayé plusieurs fois de regarder la map mais elle ne s'affiche pas. Cela semble n'affecter que moi, c'est peut-être en lien avec le trajet spécifique en cours.
![Screenshot_2022-08-08-23-27-00-18_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/106627995/183558466-e45a1a1c-66df-4218-a3de-5712d99a426a.jpg)
![Screenshot_2022-08-08-23-25-35-67_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/106627995/183558471-3d62c311-3183-4c63-828f-f14bca1b77b4.jpg)

### Reproduction du bug.

Si c'est lié à ce trajet en particulier : effectuer la commande /map quand on voyage jusqu'à la Ville Forte depuis la Grande Rue. Sinon je sais pas ce qui cause le bug.
Edit : je confirme que c'est en lien avec ce trajet précis vu qu'après être arrivé à destination et être parti en direction du Berceau la map fonctionne correctement.

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by Pietagorh** [comment]
Aller au berceau depuis la ville forte ???

**Comment by Akutana** [comment]
Oui bon je me suis trompé X) je suis reparti vers le croisement des destins

**Comment by BastLast** [comment]
des fois c'est juste discord mobile qui bug est-ce que tu sais si d'autres personnes ont aussi le meme soucis avec les messages ?

**Comment by Pietagorh** [comment]
C'est déjà arrivé de temps en temps depuis la 2.0.0, que ce soit globalement ou pour juste une personne
C'est pas forcément lié au trajet, ça peut aussi être que le temps que t'arrives à destination discord a recommencé à t'aimer

**Comment by BastLast** [comment]
du ocup c'est un bug de discord ou de nous ?

**Comment by Pietagorh** [comment]
¯\_(ツ)_/¯
Faut tester

**Comment by BastLast** [comment]
Bon on est d'accord que ce bug n'est pas arrivé une fois de plus et que o' arrive pas à le refaire ?

**Comment by Pietagorh** [comment]
Ouaip, sûrement juste du lag

**Comment by BastLast** [comment]
Est-ce que un @DraftBot-A-Discord-Adventure/testers peut check si ça fonctionne sur le bot alpha sur ce trajet et poster la réponse ici ?

**Comment by symsym-1629** [comment]
> Est-ce que un @DraftBot-A-Discord-Adventure/testers peut check si ça fonctionne sur le bot alpha sur ce trajet et poster la réponse ici ?

ca a été test ou nan dcp ?

**Comment by BastLast** [comment]
> > Est-ce que un @DraftBot-A-Discord-Adventure/testers peut check si ça fonctionne sur le bot alpha sur ce trajet et poster la réponse ici ?
> 
> ca a été test ou nan dcp ?

non faut le faire

**Comment by symsym-1629** [comment]
ok je m'en occupe

**Comment by BastLast** [comment]
> Si jamais, je viens de tester la commande sur le bot Alpha et elle est fonctionnelle 

Spécifiquement dans les conditions ci-dessus ?

**Comment by symsym-1629** [comment]
non c'est ce qu'on viens de remaquer

**Comment by Jaarzz** [comment]
Désolé j'ai confondu avec le 2e /map du screen :-(

**Comment by BastLast** [comment]
Alors ça donne quoi ?

**Comment by symsym-1629** [comment]
ca marche sur le bot alpha, je close

**Comment by BastLast** [comment]
Fallait pas close comme ça

**Comment by BastLast** [comment]
Go nous laisser close les trucs c'est mieux
