### ISSUE TITLE
[BUG]: crash de guilddaily

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#1339]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

[2022/08/10 17:30:06] Error: Erreur generateRandomProperty : nombre property invalide
    at generateRandomProperty (/home/draftbot/DraftBot-A-Discord-Adventure/dist/src/commands/guild/GuildDailyCommand.js:232:11)
    at Object.<anonymous> (/home/draftbot/DraftBot-A-Discord-Adventure/dist/src/commands/guild/GuildDailyCommand.js:265:94)
    at Generator.next (<anonymous>)
    at fulfilled (/home/draftbot/DraftBot-A-Discord-Adventure/dist/src/commands/guild/GuildDailyCommand.js:5:58)
    
    Effectué lors d'un daily

### Reproduction du bug.

1- faire un guilddaily
2- boum ca crash

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by BastLast** [comment]
Fuck

**Comment by Pietagorh** [comment]
C'est pas tous les gds, j'en ai eu un à 16h11

**Comment by BastLast** [comment]
du coup j'ai pas compris dans quel cas ça crash @romain22222 ?

**Comment by romain22222** [comment]
ca crash soit sur un type de gd, mais aucune idée duquel, soit c'est avec une certaine proba, et dans ce cas c'est la gestion des probas qui va pas

**Comment by romain22222** [comment]
et si c'est un type de gd, c'est un des plus rares

**Comment by romain22222** [comment]
au niveau 100 je précise

**Comment by BastLast** [comment]
Ce bug a l'air super peu fréquent et on a pas assez dinfos pour le fixer vite alors je le decale d'une mise à jour

**Comment by Pietagorh** [comment]
Hum, on l'avait pas fix ça ?
De mémoire c'était juste qu'il manquait 50 dans la répartition des probas

**Comment by BastLast** [comment]
Hmm pourquoi l'issue a pas été tag ?

**Comment by Chevalier2** [comment]
> Hum, on l'avait pas fix ça ? De mémoire c'était juste qu'il manquait 50 dans la répartition des probas

Je confirme qu'il manque 50, je viens de vérifier.

**Comment by BastLast** [comment]
C'est toujours le cas sur develop ?

**Comment by Chevalier2** [comment]
Non, c'est fix sur develop.

**Comment by BastLast** [comment]
Ok quel commit ?

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/193153387-598f83ec-bb47-43f8-a6d0-eed04ad989a3.png)

**Comment by BastLast** [comment]
Tu as le lien ? Xd

**Comment by Chevalier2** [comment]
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/commit/a9af783ae4eeacd151df052edc6a0d7ba4831782 money passe de 350 à 400.

**Comment by BastLast** [comment]
Merci, je close du coup
