### ISSUE TITLE
Potions dans les fights

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1340]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

On a oublié de le fix la dernière fois x)

Les potions sont pas bues pendant les fights

### Reproduction du bug.

Faire un fight avec une potion de combat

### Dans quelle condition le bug a-t-il été trouvé ?

Sur le serveur officiel du bot avec le bot officiel.

**Comment by BastLast** [comment]
@Pietagorh ajoute ça à ta todo liste

**Comment by Pietagorh** [comment]
Déjà fait xD

**Comment by BastLast** [comment]
Déjà fixe ou deja sur la liste ?

**Comment by Pietagorh** [comment]
Déjà sur la liste
