### ISSUE TITLE
[BUG]: joueur bloqué sur la mission 1

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1343]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

La mission 1 est impossible à passer

![image](https://user-images.githubusercontent.com/38099970/184560901-3d917c96-2f7b-475e-af03-48240797f5b9.png)

### Reproduction du bug.

Je pense que c'est lié aux joueurs dont la mission 1 avait été réalisée à leur place

### Dans quelle condition le bug a-t-il été trouvé ?

Sur le serveur officiel du bot avec le bot officiel.

**Comment by Pietagorh** [comment]
J'pense pas que ce soit ça, dans mes souvenirs ça les faisait bien passer à la prochaine

**Comment by BastLast** [comment]
bah j'a pas d'explications alors

**Comment by BastLast** [comment]
faudrait check en bdd si ya un soucis avec aerue en particulier et si oui check si ya d'autres gens dans le meme cas

**Comment by Pietagorh** [comment]
T'es sûr que c'est pas juste le bug où la mission 1 a une chance de pas se valider qui existait précédemment ? Il a essayé la commande plusieurs fois ?

**Comment by BastLast** [comment]
> T'es sûr que c'est pas juste le bug où la mission 1 a une chance de pas se valider qui existait précédemment ? Il a essayé la commande plusieurs fois ?

oui, faudrait voir avec son id si ya un truc chelou en bdd

**Comment by BastLast** [comment]
je close en cannot reproduce, à rouvrir si le bug réapparait
