### ISSUE TITLE
[BUG]: issue d'un mini event ne s'affiche pas + skip délai de 10 min

### ISSUE THREAD

**Issue by Akutana** [DraftBot-A-Discord-Adventure/DraftBot#1344]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Au mini event de la loterie quand j'ai réagi l'issue n'est pas apparue, j'ai attendu et réessayé plusieurs fois
Ensuite je me suis aperçu que le mini event n'a pas été pris en compte car j'ai pu en faire un autre après 5 min et j'aurais même pu en faire un direct après la loterie jpense
PS : mes stats n'ont pas bougé 
C'est pas un bug majeur mais voilà 
![Uploading Screenshot_2022-08-15-17-21-50-53_572064f74bd5f9fa804b05334aa4f912.jpg…]()
![Screenshot_2022-08-15-17-21-53-07_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/106627995/184722192-1e6b5531-b6e5-4767-932c-e40487aa4688.jpg)

### Reproduction du bug.

Ben...
Ne pas avoir de bol X)

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.
Edit : le 1er screen s'affiche pas jsp pk, c'était la loterie à 17h15

**Comment by Pietagorh** [comment]
Y'a une image qui s'est pas bien mise, tu pourrais modif la description pour la remettre ? x)
Mais ça m'est arrivé, en fait après avoir le minievent qui crash suffit de le refaire pour avoir le minievent, et oué y'a un skip de 10 minutes
D'après romain, le bug est fix dans la prochaine màj
@romain22222 du coup tu confirmes ?

**Comment by Akutana** [comment]
Euh je peux pas rajouter de screen en edit 😅

**Comment by Pietagorh** [comment]
Mets en commentaire du coup x)

**Comment by Akutana** [comment]
Awé pas con

**Comment by Akutana** [comment]
![Uploading Screenshot_2022-08-15-17-21-53-07_572064f74bd5f9fa804b05334aa4f912.jpg…]()

**Comment by Akutana** [comment]
![Screenshot_2022-08-15-18-01-45-55_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/106627995/184725948-313ab679-0d01-4fcc-ade2-c387f8c35931.jpg)
