### ISSUE TITLE
Erreur sur le sell

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1345]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

![IMG_20220816_164648](https://user-images.githubusercontent.com/60353007/184909436-1ced1ab1-a524-4232-aab1-8379a6bdf31a.jpg)

### Reproduction du bug.

Faire un sell

### Dans quelle condition le bug a-t-il été trouvé ?

Sur le serveur officiel du bot avec le bot officiel.

**Comment by BastLast** [comment]
Des news de ce truc ?

**Comment by Pietagorh** [comment]
Je vois toujours l'erreur quand je check les logs
C'est à chaque sell, mais ça affecte rien en fait, c'est juste un .then() vide qui génère l'erreur

**Comment by BastLast** [comment]
Izi a fix then

**Comment by BastLast** [comment]
Suffit de le virer non ?

**Comment by Pietagorh** [comment]
De mémoire j'avais check et ça marchait plus en le virant, mais ça fait longtemps x)

**Comment by Pietagorh** [comment]
Faut que quelqu'un réessaie

**Comment by BastLast** [comment]
Je checkerai

**Comment by Feiryn** [comment]
> Je vois toujours l'erreur quand je check les logs C'est à chaque sell, mais ça affecte rien en fait, c'est juste un .then() vide qui génère l'erreur

Non on ne vire pas un problème en le cachant, de plus les then() vides sont nécessaires

**Comment by BastLast** [comment]
@Feiryn c'est fix ça du coup ?

**Comment by Feiryn** [comment]
Non y a pas de raison
