### ISSUE TITLE
[BUG]: Pas de réponse du guildshop

### ISSUE THREAD

**Issue by Nininanou16** [DraftBot-A-Discord-Adventure/DraftBot#1346]
### Le bug n'a t-il pas déjà été signalé ?

- [x] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

- Ouvert le guildshop, acheté plusieurs fois de l'xp de guilde sans soucis
- Ouvert une fois de plus, après la séléction de l'xp, le message de confirmation s'envoie
- Cliqué sur le :white_check_mark: 
- Aucune confirmation du bot

Résultat : Pas bloqué par le shop, aucun xp recu, aucun argent débité

Screens : 
![image](https://user-images.githubusercontent.com/71654580/185152532-9fd456a5-3e5b-44aa-9baa-597292e20a2f.png)
![image](https://user-images.githubusercontent.com/71654580/185152658-e6847a86-acb5-4cb7-aada-8a1e2f68b4bc.png)
![image](https://user-images.githubusercontent.com/71654580/185152753-64b3d984-8a3a-46f0-b3a0-8d36a5472c15.png)

### Reproduction du bug.

- Ouvrir le shop de guilde
- Séléctionner xp de guilde
- Valider la confirmation

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by Nininanou16** [comment]
FYI le bug a eu lieu le 17 aout 2022 à 15h51 UTC+2 (heure d'été francaise)

**Comment by Feiryn** [comment]
À mon avis c'est un problème de latence du bot et avec le reply en moins de 3 secondes ça a crash. Je serais pour passer tout le bot en deferReply, ça peut crash à tout moment si y a un peu de latence réseau ou disque

**Comment by Pietagorh** [comment]
Mais ça reply pas l'achat d'exp

**Comment by Feiryn** [comment]
Ah oui c'est pas un reply d'interaction mb

**Comment by BastLast** [comment]
du coup ça ressemble à un bug qui arrive jamais et pour lequel on a pas les logs... je passe en cannot reproduce vu qu'il arrive pas à chaque fois et si un jour on a des infos en plus, go reouvrir
