### ISSUE TITLE
[BUG]: Déplacement animal fielleux

### ISSUE THREAD

**Issue by AyameKodaru** [DraftBot-A-Discord-Adventure/DraftBot#1349]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Mon familier s'affichait encore fielleux après avoir été nourri, mais je pouvais (contrairement à avant la dernière friandise) le laisser au refuge et le vendre. 

### Reproduction du bug.

jour 1 : 
- familier sauvage au refuge

jour 2 :
- familier fielleux au refuge
- récupération du familier avec /pettransfer
- /petsell et /pettransfer impossibles
- /petfeed (friandise) x 2
- /pettransfer toujours impossible, familier fielleux
- /petfeed (friandise) x 1
- /pet toujours fielleux, mais /pettransfer et /petsell possibles
![image](https://user-images.githubusercontent.com/111611899/185709937-2627f3b5-2592-4316-addf-69c31491fb97.png)

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by Pietagorh** [comment]
J'pense qu'il faut creuser du côté de l'affichage
Peut-être qu'à 5 points pile il est affiché fielleux alors qu'il l'est pas
Faut voir
