### ISSUE TITLE
[BUG]: La map est très lourde donc très longue à s'afficher.

### ISSUE THREAD

**Issue by Fointard** [DraftBot-A-Discord-Adventure/DraftBot#1350]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Lorsque je me trouve dans une zone où le réseau n'est pas optimal, la map peut prendre jusqu'à 5 minutes pour s'afficher.
De manière générale, il est peu probable qu'il soit utile d'avoir une map en 8192*5488 qui pèse 25Mio.

### Reproduction du bug.

Lancer la commande `/map`.

### Dans quelle condition le bug a-t-il été trouvé ?

Sur le serveur officiel du bot avec le bot officiel., Sur un serveur perso avec le bot officiel.

**Comment by BastLast** [comment]
Hey ceci n'est pas vraiment un bug je me permet donc de fermer cette issue et de rediriger vers l'espace suggestions :)
