### ISSUE TITLE
description de guilde : caractères spéciaux interdits mais "!" autorisé

### ISSUE THREAD

**Issue by symsym-1629** [DraftBot-A-Discord-Adventure/DraftBot#1354]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

bahh en gros on peut mettre un ! alors que c'est écrit que c'est interdit les caractères spéciaux 

### Reproduction du bug.

jvais pas vous faire un dessin vous changer la desc de votre guilde et vous mettez un ! ca marche mais les autres caractères spéciaux ca marche pas

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by BastLast** [comment]
Je crois que tu as tout mélanger

**Comment by symsym-1629** [comment]
et mince

**Comment by BastLast** [comment]
le comportement voulu est qu'on puisse en mettre mais que ça ne puisse pas être plus d'1 caractère sur 3 ou un truc du genre (en gros que ça soit utilisable en ponctuation mais pas pr faire des trucs chelou. Aussi tout les seuls autorisés c'est :

: ! ? , - . ' ( ) [ ]

je pense pas qu'on ai besoin d'en autoriser d'autre

**Comment by Feiryn** [comment]
Ce serait pas plus simple de juste ne pas autoriser les caractères spéciaux ? Je vois mal des cas où ces caractères sont cohérents, et puis ça va être compliqué à programmer

**Comment by Pietagorh** [comment]
Bah surtout les ' parce que sinon ça restreint vachement la manière dont t'écris xD
Le reste est superflu

**Comment by BastLast** [comment]
On peut pas juste check à coup de regex ?

**Comment by BastLast** [comment]
Je sais que le regex est lent mais cette commande est exécutée genre jamais et ça sera jamais sur des grosses strings

**Comment by Feiryn** [comment]
Je veux bien que tu explicit la règle, car je ne sais pas trop ce que tu veux faire

**Comment by BastLast** [comment]
Autoriser la ponctuation normale dans une description de guilde mais éviter les descriptions avec des trucs genre
------------ bonjour----------

**Comment by Feiryn** [comment]
Plus précis stp x) Où est-ce qu'on a le droit de placer la caractères (partout, à la fin ?), combien maximum etc...

**Comment by BastLast** [comment]
> Plus précis stp x) Où est-ce qu'on a le droit de placer la caractères (partout, à la fin ?), combien maximum etc...

Euhhhhhhhh perso si je devais dev ça je chercherai un truc déjà fait sur internet

**Comment by BastLast** [comment]
Genre r"easonable punctuation regex"

**Comment by BastLast** [comment]
du coup pour clarifier, on autorise désormais la ponctuation dans le nom d'une guilde ou dans une description MAIS, pas deux signes de ponctuation d'affilée.
