### ISSUE TITLE
Bug badge guilde puissante

### ISSUE THREAD

**Issue by SomniumWed** [DraftBot-A-Discord-Adventure/DraftBot#1355]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

J'ai quitté une guilde (BeletteGelee) qui possédait le badge "Guilde Puissante" pour une autre guilde de niveau 35 (BeletteGeleeIII), mais j'ai quand même gardé le badge après plusieurs jours

### Reproduction du bug.

1. Aller dans une guilde qui possède le badge;
2. Quitter cette guilde pour une autre;
3. Faire la commande /profile...

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by SomniumWed** [comment]
![Screenshot_20220823-123802_Discord.jpg](https://user-images.githubusercontent.com/99070462/186169275-9a35d33e-09bd-4e7d-9cc9-e9b590793877.jpg)

**Comment by Pietagorh** [comment]
Alors non ce n'est pas un bug, c'est pas ceux dans la guilde qui ont la badge mais ceux qui étaient dans la guilde quand le badge est apparu qui l'ont et le gardent pour toujours
