### ISSUE TITLE
Timer affiche un temps négatif à la fin du voyage

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1358]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Quand il reste moins d'1 minute au voyage  (surement ça mais pas sûr), ça affiche ça
![Screenshot_20220825-114037](https://user-images.githubusercontent.com/60353007/186639781-cd1439ea-c36b-449e-83df-8357b55425ed.png)

### Reproduction du bug.

Faire un report juste avant d'arriver à destination 

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by BastLast** [comment]
Duplicata #1342
