### ISSUE TITLE
[BUG]: Mini-event qui ne s'affiche pas

### ISSUE THREAD

**Issue by Gabrielre14** [DraftBot-A-Discord-Adventure/DraftBot#1360]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

Le bug est très simple : le mini-event ne s'affiche pas. ( le screen : https://prnt.sc/FfYpPNMJY6B1)
Par contre il est pris en compte, les points ont augmenté (et que j'avance dans les missions malgré les bugs). Le seul problème c'est qu'on ne connait pas le thème du mini-event. Est-ce un gain de pièces ? Un gain de vie ? Rien ne se passe ? Le plus dérangeant c'est lorsque l'on peut gagner un objet, (car on ne voit pas lequel et on peut pas le garder) mais je n'ai jamais eu ce cas de figure. Je vais essayer d'être à l'affut si ça arrive, savoir si on peut garder l'objet même quand le mini-event s'affiche pas, ou s'il est automatiquement vendu
Ce n'est pas la première fois que ça m'arrive, ça a du arriver 7 ou 8 fois aujourd'hui. 
J'aimerai savoir si c'est l'affichage des mini-event qui crash ou si c'est mon appli discord/ma co qui a un problème

### Reproduction du bug.

Désolé mais je n'en sais rien. Vu que ça n'arrive que de temps en temps.

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by Gabrielre14** [comment]
J'ai des infos en plus, des précisions
Depuis que j'ai fini le trajet de 10h je n'ai plus ce drôle de bug, et ce, le soir même. 
Je pense que ce bug arrive lors de longs trajets, alors qu'on a fait plein de mini-event avant. Durant ce trajet de 10h, plus j'en faisais, plus le bug était fréquent. J'ai aussi remarqué que le mini-event s'affichait normalement quand on devait interagir et ne s'affichait pas si c'était informatif. 
Et depuis que je fais des courts trajets, je n'ai pas eu un seul bug. Il arrive donc lors des trajets de 8 à 10h (peut-être 7) lorsqu'on tryhard les mini-events... peut-être au bout d'un palier de points...

**Comment by BastLast** [comment]
ya pas déjà une issue pour ce bug ? histoire de centraliser les infos ?

**Comment by Pietagorh** [comment]
J'en ai pas vu

**Comment by Feiryn** [comment]
Faudrait passer la commande report en defer reply
