### ISSUE TITLE
Problème temps de trajet

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#1364]
Une alte de X minutes donne un trajet du temps normal + X min

**Comment by Feiryn** [comment]
Bug toujours présent

**Comment by BastLast** [comment]
c'est normal ça non ? genre c'est comme ça que fonctionne les altés non ?

**Comment by Pietagorh** [comment]
Trajet de 4h normalement 
![IMG_20220929_140031.jpg](https://user-images.githubusercontent.com/60353007/193025796-3df4d7fc-6169-42f3-a0af-ec65386fba18.jpg)

**Comment by BastLast** [comment]
Ahhhh
