### ISSUE TITLE
[BUG]: guilddaily qui ne s’affiche pas 

### ISSUE THREAD

**Issue by Azedixene** [DraftBot-A-Discord-Adventure/DraftBot#1368]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

![BED9E6C6-8740-41E0-8A4A-BC5EF8F371C9](https://user-images.githubusercontent.com/61432341/187857521-bcf6fc7e-dda0-4b29-82ea-7c78679626db.png)

### Reproduction du bug.

Aucune idée, première fois que ça m’arrive, j’ai juste fait un gd après mon report 

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by Pietagorh** [comment]
Duplicate de #1339 si j'me trompe pas x)
