### ISSUE TITLE
Les images d'illustration.

### ISSUE THREAD

**Issue by Voisin1234** [DraftBot-A-Discord-Adventure/DraftBot#1373]
Yop! Je ne sais pas où poster cette issu je vous laisse la redirigé. En cherchant quelques règles sur le site https://guide.draftbot.com je me suis aperçu que les images d'illustrations pour montrer les commandes sont encore avec le ! comme sur le screenshot poster ci-dessous.Et cela et pour toutes les images du site les commandes. À très vite🥸![image](https://user-images.githubusercontent.com/108148891/188287605-a814e89a-457d-4f51-8a0e-10a726ce6df0.png)

**Comment by Nargacaura** [comment]
Mais les images d'illustration ne sont-elles pas là pour montrer le _contenu_ de la commande et non pas son exécution?
Par contre, ce que tu aurais pu reporter, c'est le fait que /feedpet n'existe pas (c'est plutôt /petfeed), mais ça serait plutôt du côté du wiki qu'il faut le faire.

**Comment by BastLast** [comment]
Bonjour, les problèmes liés au guide sont à traiter via le serveur discord du bot. Ce repo concerne uniquement le développement du bot
