### ISSUE TITLE
Améliorer la gestion des permissions

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1374]
- [x] Ajouter un nouveau check de permission et les messages d'erreurs associés pour la perm "voir les anciens messages"
- [x] Mettre à jour les liens d'invitations avec ces nouvelles permissions dans le code du bot
- [x] Mettre à jour les liens d'invitation sur le serveur du bot

Rappel de l'erreur observée (voir commentaires)

TypeError: Cannot read properties of undefined (reading 'identifier')
    at DraftBotShopMessage.<anonymous> (/home/draftbot/DraftBot-A-Discord-Adventure/dist/src/core/messages/DraftBotReactionMessage.js:122:57)
    at Generator.next (<anonymous>)
    at fulfilled (/home/draftbot/DraftBot-A-Discord-Adventure/dist/src/core/messages/DraftBotReactionMessage.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Pietagorh** [comment]
Ah mais vous parliez de çaaaa

Pour plus de détails : en gros sur 1 serv DraftBot arrive pas à mettre de réactions, alors qu'il a les perms pour à cause de cette erreur, que ce soit pour des emojis externes ou par défaut (parce que c'est aussi sur les reports, fights, etc)

**Comment by BastLast** [comment]
quel serveur ? toujours le cas actuellement ?

**Comment by BastLast** [comment]
agree

**Comment by BastLast** [comment]
je redéplace en 4.0.0 parce que dans les tests ya trop de gens qui ont le problème, il vaut mieux fix ça maintenant

**Comment by BastLast** [comment]
oups c'est pas l'issue que je pensais

**Comment by Pietagorh** [comment]
> quel serveur ? toujours le cas actuellement ?

318298388158480386 et oui apparemment

**Comment by Pietagorh** [comment]
J'ai pas eu de retour de la personne qui avait ce problème, mais chez la 2è personne qui avait eu cet exact problème c'était parce qu'il manquait la perm "voir les anciens messages" au bot, qu'on demande pas actuellement
Donc il faudrait qu'on l'ajoute au lien d'invitation

**Comment by BastLast** [comment]
ok et faudrait qu'on affiche un message de permission manquante si le bot n'a pas la perm. Je passe l'issue dans la prochaine maj vu qu'elle est facile à faire du coup

**Comment by BastLast** [comment]
j'ai ajouté une tasklist à l'issue pour que ça soit plus clair pr le dev qui s'en occupe
