### ISSUE TITLE
Améliorer le système de langue

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#1375]
- [x] Traduire les commandes
- [x] Traduire les descriptions
- [x] Refactoring BasecommandGenerator
- [x] Traduire les options Commandes admin.
- [x] Traduire les options Commandes de guilde
- [x] Traduire les options Commande mission
- [x] Traduire les options Commande pet
- [x] Traduire les options Commande player
- [ ] Mettre à jour la commande help
- [ ] Mettre à jour les conseils
- [x] Refactorer les options user et rank pour les mettre dans le generator

Todo later : 
 #1429
 #1432

**Comment by Jo787** [comment]
Qu'entend tu par améliorer le système de langue

**Comment by Feiryn** [comment]
Ajouter les descriptions des commandes dans plusieurs langues

**Comment by Jo787** [comment]
A quel langue pense tu car je crois que c'est déjà fait en anglais

**Comment by Feiryn** [comment]
Faut mettre la description en français
