### ISSUE TITLE
[BUG]: blocage d'un joueur en combat

### ISSUE THREAD

**Issue by As-Nodt** [DraftBot-A-Discord-Adventure/DraftBot#1377]
### Le bug n'a t-il pas déjà été signalé ?

- [X] J'ai vérifié et je n'ai pas trouvé d'issue pour ce problème.

### Description du bug.

J'ai voulut réaliser la mission des 10 fights avec Bombafox, au début on jouait normal, le bot nous demandait de confirmer, on mettaient nos réactions pendant le fight sans problème mais c'est tellement long qu'on a voulut abreger donc sur les autres fights on validaient la confirmation du bot sans jouer les battles puis au bout de 30s ça se terminait auto. Mais on a pas eu le temps de finir la mission car quand on a voulut recommencer le bot nous a bien proposé de valider mais nous a pas rajouté ni le message avec les propositions de fight ni les réactions. 
![Screenshot_20220909_103636](https://user-images.githubusercontent.com/96839617/189394446-9ebce2d6-e602-447b-b4e9-55697dc14010.jpg)
![Screenshot_20220909_103636-1](https://user-images.githubusercontent.com/96839617/189394450-b4b90f31-a6bd-4709-bf4f-12b6ad577eb1.jpg)
![Screenshot_20220909_103711](https://user-images.githubusercontent.com/96839617/189394455-c7247691-823a-4de0-8db7-84ab2eefb469.jpg)

### Reproduction du bug.

Heu ... j'en sais rien c'est la première fois que ça nous arrive 

### Dans quelle condition le bug a-t-il été trouvé ?

Sur un serveur perso avec le bot officiel.

**Comment by BastLast** [comment]
Je pense qu'on doit étudier ça rapidement je vois pas mal d'occurrences du soucis.

**Comment by BastLast** [comment]
[2023/03/16 15:38:55] DiscordAPIError[10008]: Unknown Message
    at SequentialHandler.runRequest (/draftbot/node_modules/@discordjs/rest/dist/index.js:659:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/draftbot/node_modules/@discordjs/rest/dist/index.js:458:14)
    at async REST.request (/draftbot/node_modules/@discordjs/rest/dist/index.js:902:22)
    at async MessageManager.edit (/draftbot/node_modules/discord.js/src/managers/MessageManager.js:175:15

**Comment by BastLast** [comment]
étant donné la fréquence du bug ( j'ai eu des gens qui se sont bloqués en boucle sur un truc, je déplace en 4.3.0, on peut pas encourager les gens à faire des fights et avoir un aussi gros bug dans les fights

**Comment by BastLast** [comment]
@voltou91  est-ce que tu as le temps ce soir de te pencher dessus ?

**Comment by voltou91** [comment]
Je regarderai mais je promet rien :)

**Comment by BastLast** [comment]
j'ai l'impression que le bug survient si les gens parlent pendant le fight en gros ya un soucis où on doit pas arriver à fetch le bon message si ya un message en plus dans le channel enfin si les gens parlent en gros.

**Comment by BastLast** [comment]
> j'ai l'impression que le bug survient si les gens parlent pendant le fight en gros ya un soucis où on doit pas arriver à fetch le bon message si ya un message en plus dans le channel enfin si les gens parlent en gros.

après plus de test : non

**Comment by BastLast** [comment]
j'ai trouvé le problème. Ça vient du fait que l'un des message du bot est supprimé.

Je pense que dans ce cas là il s'agit d'un bot de modération qui bloque les messages qui contiennent trop de mention. Je rajoute une fonctionnalité qui permet de prévenir ce cas de figure.
