### ISSUE TITLE
Aucune réaction du bot lors d'un vote

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1378]
### Description du bug.

Le bot ne donne pas le badge 🗳️ ni n'indique qui a voté et quand sur le serveur officiel... Mais le vote est bien enregistré par top.gg!

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Voter. Et regarder le profil pour remarquer l'absence du badge de la liste.

### Captures d'écran

![IMG_20220910_072258](https://user-images.githubusercontent.com/94372084/189470494-98aaaae9-e217-49bd-a49c-de41664dbae8.jpg)
Notez qu'entre le mini-event et l'affichage du profil, le vote a été réalisé. Mais aucun badge...

Cependant, à la seconde tentative...
![IMG_20220910_072322](https://user-images.githubusercontent.com/94372084/189470511-e15f50fa-2e43-4ddc-9ae2-06355ad7dc9a.jpg)

**Comment by Nargacaura** [comment]
Vu que ça a été fix, c'est plus vraiment la peine de garder cette issue ouverte.

**Comment by Gabrielre14** [comment]
Nouveau bug du vote juste après la MAJ. J'ai voté, mais je n'ai eu ni badge ni rôle "voteur" sur le serveur officiel. 
![image](https://user-images.githubusercontent.com/97915848/194725450-1b61c818-9f45-4d3f-a858-c9d08a69d169.png)
![image](https://user-images.githubusercontent.com/97915848/194725452-acbe05b0-a8f6-4fd4-9898-74b52383e7a2.png)
![image](https://user-images.githubusercontent.com/97915848/194725453-e27a0598-ce89-4092-bf36-c1c5a054cc43.png)
Les trois screens ont été réalisés dans l'ordre de l'envoi, à quelques minutes d'intervalle.

**Comment by romain22222** [comment]
le bug n'a pas été corrigé, faudrait voir avec nysvaa, c'est lors de la traduction de la commande ts vers js que ca coince quelquepart dans startDBL

**Comment by Nargacaura** [comment]
C'est pas dû à la condition (guild && guild.shard)?

**Comment by romain22222** [comment]
nope rien à voir

**Comment by romain22222** [comment]
Erreur en question :

```TypeError: (0 , express_1.default) is not a function
    at Function.startDBLWebhook (/draftbot/dist/src/core/DBL.js:24:43)
    at /draftbot/dist/src/core/bot/index.js:66:23
    at Generator.next (<anonymous>)
    at fulfilled (/draftbot/dist/src/core/bot/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by Feiryn** [comment]
Cette erreur n'existe qu'en conteneur docker

**Comment by Feiryn** [comment]
Corrigé
