### ISSUE TITLE
Iop phrases manquantes

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1383]
Trying to use an invalid translation: :lock: in module smallEvents.interactOtherPlayers

**Comment by BastLast** [comment]
j'ai essayé de comprendre ce bug mais globalement j'ai rien compris possible de donner + d'infos ?

**Comment by Pietagorh** [comment]
En gros il manque les phrases de quand tu rencontres quelqu'un qui est emprisonné

**Comment by Pietagorh** [comment]
Donc ERR:TRANSLATION_NOT_FOUND
