### ISSUE TITLE
[BUG]: gtop pas à jour

### ISSUE THREAD

**Issue by Jaarzz** [DraftBot-A-Discord-Adventure/DraftBot#1389]
### Description du bug.

j'ai voulu check le classement de ma guilde avec /gtop
J'ai vu qu'elle était level 73 alors qu'elle est level 74

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

/gtop 
/guild : Uranium

### Captures d'écran

![image](https://user-images.githubusercontent.com/106905934/191557716-2a93eb35-e14e-4200-a4bc-1a00a750e83a.png)

**Comment by Nargacaura** [comment]
Ça serait pas plutôt du côté de DB Assistant qu'il faut faire l'issue?

**Comment by Pietagorh** [comment]
Bro c'est DraftBot ici, pas DBA
Y'a un serv support pour

**Comment by BastLast** [comment]
Wtf ptdr on fix pas les bugs des autres bot 😭

**Comment by Arkitu** [comment]
Si tu veux report le bug viens sur le serveur de Draftbot Assistant (le lien est dans sa bio)

**Comment by Jaarzz** [comment]
Je savais pas que c'était pas votre bot. Comment aurais-je pu le savoir ?

**Comment by BastLast** [comment]
On a jamais publié quoi que ce soit a propos de ce bot, on nest responsable de rien de ce qui est fait dessus et on encourage pas son utilisation

**Comment by Jaarzz** [comment]
OK.

**Comment by Pietagorh** [comment]
> Je savais pas que c'était pas votre bot. Comment aurais-je pu le savoir ?

Bah suffit de regarder le nom et la pp, c'est pas la même chose xD
Si on implémente un truc de ce genre, autant l'implémenter dans le bot direct au lieu d'en créer un autre
