### ISSUE TITLE
/guilddaily qui ne s’affiche pas

### ISSUE THREAD

**Issue by Voisin1234** [DraftBot-A-Discord-Adventure/DraftBot#1396]
### Description du bug.

Bonjour depuis quelques temps quand je fais la commande /guilddaily le bot ne m’affiche pas la réponse. Par compte la commande a bien été pris en compte

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

/guilddaily 

### Captures d'écran

![98FF722C-8557-4F90-A99F-8C6C3E59756B](https://user-images.githubusercontent.com/108148891/192139573-9bc80792-5432-4ab5-a9a8-f1025e046278.png)
![811774C5-8B00-4760-A868-0D3B70862F78](https://user-images.githubusercontent.com/108148891/192139575-8fb738a5-1cc3-4a9a-87d9-cd0198a2e2b3.jpeg)

**Comment by Pietagorh** [comment]
Quelle shard ?

**Comment by Voisin1234** [comment]
pas compris

**Comment by Nargacaura** [comment]
Il te demandait simplement quel numéro de shard (entre 0 et 3) s'affichait lorsque tu fais /ping.

**Comment by Voisin1234** [comment]
Aucune idée

**Comment by Nargacaura** [comment]
Fais /ping sur le serveur concerné. T'as "**Numéro de shard:** x/3" (avec 0&le;x&le;3). C'est ce x que Pieta veut.

**Comment by Voisin1234** [comment]
3

**Comment by Nargacaura** [comment]
C'est fort probable (voire même certain) que ça peut se relier à l'issue #1339... Du coup, je pense qu'on peut appliquer le label "duplicate".

**Comment by BastLast** [comment]
Ça le fait à tous les coups ?

**Comment by Voisin1234** [comment]
Je ne sais pas ça m'est arrivé que 2 fois je ne sais pas pour le reste de mon équipe.

**Comment by Pietagorh** [comment]
J'suis d'accord avec Narga
