### ISSUE TITLE
[BUG]: l'item acheté dans le shop n'est pas remis

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#1399]
### Description du bug.

Suite à l'achat de la potion du jour la potion qui aurait du se trouver dans mon inventaire ne s'y trouvait pas, aucune perte d'argent

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

1) shop
2) achat de la potion du jour
3) pas de remise de la potion après la validation
4) drink
5) "vous n'avez pas de potion dans votre inventaire"

### Captures d'écran

![](https://cdn.discordapp.com/attachments/817847843216818217/1023619788716642364/IMG_7810.png)

![](https://cdn.discordapp.com/attachments/817847843216818217/1023622995127828500/IMG_7808.png)

![](https://cdn.discordapp.com/attachments/817847843216818217/1023619789194797137/IMG_7809.png)

**Comment by BastLast** [comment]
@Thesmokingllama dis moi que tu as check ta réserve ?

**Comment by BastLast** [comment]
je pense que la reproduction du bug n'est pas complète, dans quel état ton joueur était avant l'achat de la potion ?

**Comment by BastLast** [comment]
je close en cannot reproduce, si qqun a un bug similaire, go expliquer toutes les étapes permettant de reproduire le bug
