### ISSUE TITLE
[BUG]: gestion des logs pour un joueur qui n'a pas commencé

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1400]
### Description du bug.

erreur des logs quand un joueur fais une commande random sans avoir commencé l'aventure

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

testé avec la commande prefix 

### Captures d'écran

![image](https://user-images.githubusercontent.com/38099970/192156180-ab069e7d-9db9-4729-b662-240850d8acd0.png)

**Comment by BastLast** [comment]
@Feiryn  celui là ya moyen qu'il soit pour toi mdr

**Comment by Feiryn** [comment]
Je n'arrive pas à le reproduire

**Comment by Feiryn** [comment]
Je déplace, on verra à la prochaine maj si on arrive à trouver, c'est pas dramatique comme bug

**Comment by Feiryn** [comment]
J'ai eu le bug pour la table des altérations aussi, en fait je crois que c'est le findOrCreate en transaction qui renvoie la 1ère fois un id null car le modèle n'est pas encore en base, ce qui est logique

**Comment by BastLast** [comment]
est-ce que ça veut dire que après le transfert des données on aura pas le soucis ? en gros dès qu'on a le modèle créé ? ou j'ai mal compris ?

**Comment by Feiryn** [comment]
C'est l'idée pour les modèles plus ou moins fixes (commandes, altérations...), mais il y en a aussi pour les joueurs et serveurs et y en a potentiellement une infinité

**Comment by BastLast** [comment]
anyway faudra fix de toute façon

**Comment by Feiryn** [comment]
Alors
J'ai une mauvaise nouvelle
C'est pas corrigé

**Comment by BastLast** [comment]
Oh no

**Comment by Feiryn** [comment]
En fait c'est bon c'est moi qui avait fait de la merde avec ma base de données

**Comment by BastLast** [comment]
Oh oui
