### ISSUE TITLE
Temps de trajet en minutes

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1404]
### Description du bug.

J'imagine que c'est le même truc que pour les popos de temps, mais quand y'a un trajet en minutes depuis qu'on est plus sous sqlite ça arrondit

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Faire le voyage du tuto

### Captures d'écran

![IMG_20220926_010457](https://user-images.githubusercontent.com/60353007/192169598-482dc2c1-5d9e-4db0-9661-917a300d4107.jpg)

**Comment by romain22222** [comment]
pour celui qui corrigera le bug : faut passer les maplink en minutes et non en heures

**Comment by romain22222** [comment]
Pour faire simple, toute donnée dans le bot en db doit être entière. Si une donnée n'est pas entière, elle sera arrondie lors de la mise en db

**Comment by romain22222** [comment]
Y compris les données des JSONS
