### ISSUE TITLE
Liste des bugs des commandes de test

### ISSUE THREAD

**Issue by symsym-1629** [DraftBot-A-Discord-Adventure/DraftBot#1411]
Pour le moment j'ai le fait que le advancetravel ne marche pas du tout (il ne le détecte pas comme un trajet relié)

**Comment by Pietagorh** [comment]
Le travel tout court tu veux dire ?

**Comment by symsym-1629** [comment]
euh ouaip j'ai confondu

**Comment by Pietagorh** [comment]
Quasi sûr que c'est parce que les requêtes avec 2 args dans le where marchent plus (j'ai testé en peu d'mon côté)

**Comment by symsym-1629** [comment]
le /test ne reconnaît même plus le nom de la commande de test

**Comment by BastLast** [comment]
> Quasi sûr que c'est parce que les requêtes avec 2 args dans le where marchent plus (j'ai testé en peu d'mon côté)

du coup ça c'est bullshit ?
