### ISSUE TITLE
Faire les 4 commandes admin restantes dont l'interface est commune

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1429]
ya quelques commandes admin qui sont pas traduites en français parce que leur truc de génération de slash command builder est mutualisé et du coup c'est un peu relou à faire.

Les commandes concernées sont genre point et pointsw

Il faut faire en sorte que les commandes et leurs argument soit traduites

**Comment by Feiryn** [comment]
Plus d'actualité vu qu'on va passer les commandes admins en web
