### ISSUE TITLE
Améliorer la gestion des constantes dans le bot

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#1432]
Refactoring des constantes du bot

- [x] Déplacer la constante d'émoji "QUICK END EMOTE" actuellement dans la catégorie REPORT vers la catégorie des menu reactions et l'utiliser ailleurs, je l'ai par exemple repérée dans un mini-évènement
- [x] botfacts ligne 23 : utiliser le json
- [x] GuildInvite ligne 144 : idem

**Comment by Pietagorh** [comment]
- [ ] botfacts ligne 23 : utiliser le json
- [ ] GuildInvite ligne 144 : idem

**Comment by BastLast** [comment]
@Pietagorh  possible de cocher dans cette issue les trucs que tu as résolu via la pr #1603

**Comment by Pietagorh** [comment]
1 chose mdr

**Comment by BastLast** [comment]
@Pietagorh  est-ce que la tasklist est à jour ?

**Comment by BastLast** [comment]
ou est-ce que les points 2 et 3 sont fixs ?

**Comment by Pietagorh** [comment]
À jour
En gros les 2 autres c'est juste qu'il y a du texte à ces lignes là

**Comment by Pietagorh** [comment]
Donc pas vraiment constantes x)@

**Comment by BastLast** [comment]
Ok possible de faire une pr ce soir ?

**Comment by BastLast** [comment]
Qu'on puisse fermer l'issue ?

**Comment by Pietagorh** [comment]
Yus
