### ISSUE TITLE
[BUG]: bug du magasin de guild

### ISSUE THREAD

**Issue by Jo787** [DraftBot-A-Discord-Adventure/DraftBot#1446]
### Description du bug.

quand on appuis sur une réponde rapidement sa fait quitter le shop
on peut avoir plus de bouf que de place par exemple 16 sur 15 salade 

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

- faire un /Guilshop
- appuyer le plus rapidement possible sur la réponse

### Captures d'écran

![image](https://user-images.githubusercontent.com/110350223/193429120-9e4b1720-5b2d-4996-b3ff-742e0cd6fb53.png)
![image](https://user-images.githubusercontent.com/110350223/193429153-2556d02d-6e9b-4605-8a9d-06188e46c991.png)

**Comment by Pietagorh** [comment]
La première partie y'a déjà une issue pour

Par contre j'veux bien des détails sur comment passer la limite de nourriture

**Comment by BastLast** [comment]
Merci de faire 1 issue par bug et de biens vérifier les doublons svp

**Comment by BastLast** [comment]
Je ferme cette issue pour doublon, merci d'en recréer une pour la bouffe

**Comment by BastLast** [comment]
duplicate de #1374 btw
