### ISSUE TITLE
BotFacts sql errors

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1447]
### Description du bug.

- Sur la moyenne de niveau des guildes
- Sur le nombre de personne dans un trajet

SequelizeDatabaseError: (conn=5817, no: 1146, SQLState: 42S02) Table 'draftbot_dev_game.Players' doesn't exist
sql: SELECT COUNT(*) as count
                       FROM draftbot_dev_game.Players
                       WHERE (mapLinkId = 12
                          OR mapLinkId = 13)
                         AND score
                           \> 100 - parameters:[]

SequelizeDatabaseError: (conn=5823, no: 1146, SQLState: 42S02) Table 'draftbot_dev_game.Guilds' doesn't exist
sql: SELECT AVG(level) as avg
                       FROM draftbot_dev_game.Guilds - parameters:[]

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Faire des botFacts

### Captures d'écran

.

**Comment by Feiryn** [comment]
C'est à cause des majuscules aux noms des tables

**Comment by BastLast** [comment]
cool izi a fix alors ça
