### ISSUE TITLE
[BUG]: achat de plus de bouffe que possible 

### ISSUE THREAD

**Issue by Jo787** [DraftBot-A-Discord-Adventure/DraftBot#1449]
### Description du bug.

On peut acheter plus de bouffe que d'emplacement d'inventaire de Guild
Par exemple on peut avoir 16/15 salade

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Faire un /guildshop
Acheter 16 salade 

### Captures d'écran

https://user-images.githubusercontent.com/110350223/193429153-2556d02d-6e9b-4605-8a9d-06188e46c991.png

**Comment by ghosts-arch** [comment]
Draftbot alpha

J'obtiens bien le message d'erreur quand j'essayes d'acheter la 16ème salade.

**Comment by Nargacaura** [comment]
La cause du bug a été identifiée: lorsqu'on nourrit un pet, au lieu de supprimer 1 nourriture, elle en supprime... -1.

La ligne fautive? Celle-ci: `guild.removeFood(item, -1, NumberChangeReason.PET_FEED);`

**Comment by Jo787** [comment]
C'est pas guildshop qui bug mais le petfeed
