### ISSUE TITLE
Test atravel ne fait plus avance les minievents

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1452]
### Description du bug.

Le test atravel affecte plus le temps des minievents à partir du moment où on a déjà fait un minievent dans le trajet

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

- Faire un minievent
- /test atravel 10
- Pas de minievent

### Captures d'écran

![IMG_20221003_000427](https://user-images.githubusercontent.com/60353007/193478319-1ef23d4c-0559-4cb7-af6c-632526bde767.jpg)

**Comment by KirIcare** [comment]
Je sais pas si c'est lié mais depuis, à chaque rapport que je fais je gagne ou perds du temps avant le prochain mini event, j'ai pu prendre +2min comme -2min

**Comment by Pietagorh** [comment]
Correction : ça affecte les minievents *parfois* d'une durée plus ou moins aléatoire
