### ISSUE TITLE
Faire passer la commande sendlogs en ephemeral

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1454]
c'est hyper relou d'avoir à jongler entre le channel et les dms et aussi ça force à avoir un serveur en commun avec un bot de test qui n'est pas le serveur principal si on a bloqué ses mp sur le serveur officiel du bot

**Comment by Feiryn** [comment]
C'est pratique de pouvoir retrouver les anciens logs, en ephemeral ils vont disparaître après

**Comment by BastLast** [comment]
On peut faire un argument ? 

Ca me fait penser que faut maj notre politique de confidentialité

**Comment by Pietagorh** [comment]
@Feiryn anyway le fichier est envoyé en mp, donc c'est juste le message "Logs envoyés" qui passe en ephemeral

**Comment by BastLast** [comment]
> @Feiryn anyway le fichier est envoyé en mp, donc c'est juste le message "Logs envoyés" qui passe en ephemeral 

Mais non ptdr je veux que le fichier soit envoyé en ephemeral si l'option est a true
