### ISSUE TITLE
[BUG]: le bot alpha crash de manière random

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1468]
### Description du bug.

le soucis vient du container du bot qui semble crash et ne pas redemarrer 

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Pas la moindre idée

### Captures d'écran

.

**Comment by BastLast** [comment]
On peut pas maj si on a pas un redemarrage auto en cas de crash

**Comment by BastLast** [comment]
faut aller voir si ya un truc dans les logs du bot alpha

**Comment by Feiryn** [comment]
C'était un problème de base de données car j'avais tout refait

**Comment by BastLast** [comment]
bon le dernier crash ct la bdd et mtn le bot semble être stable  dcp je close pour le moment
