### ISSUE TITLE
[BUG]: Unknown command in help command

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1484]
### Description du bug.

Si le nom d'une commande a changé, la commande est supprimée et recréée lors du démarrage du bot. 
Mais du coup quand il démarre il charge l'ancienne id de la commande
et du coup dans la commande help la commande est affichée en unknown command.

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Changer le nom d'une commande
démarrer le bot
faire /help

### Captures d'écran

![image](https://user-images.githubusercontent.com/38099970/194715952-7782b228-7853-4964-b0e4-ccc9b51d27f4.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by romain22222** [comment]
la personne ayant fait le système pour les commandes dans la commande help va devoir gérer, j'ai aucune idée de comment ca fonctionne précisément ni de comment marche le bug

**Comment by BastLast** [comment]
la prochaine maj va faire des changements de commande et j'aimerai bien qu'on ai pas besoin de faire 40 redemarrage du coup je déplace en 4.3.0
