### ISSUE TITLE
Certaines options de commandes marchent plus

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1485]
### Description du bug
L'option position de /pettransfer marche plus, quand tu veux récupérer un pet dans le shelter alors que t'en as pas ça te dit qu'il faut que t'en aies un

Le rank dans celles qui l'utilisent est un option user, obv ça marche pas avec un chiffre

Le nom de la guilde dans le /guild

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Utiliser l'une des options ci dessus

### Captures d'écran

![IMG_20221008_184305](https://user-images.githubusercontent.com/60353007/194718343-50313abf-6795-4776-9a5c-d8a1f7419b47.jpg)

### Sur quel shard avez vous rencontré le bug ?

Shard 1

**Comment by romain22222** [comment]
Toute la partie récupération d'utilisateur dans le bot n'est pas correcte et n'est pas générique, il faut faire un refactor de la fonction Entities.getByOptions pour rajouter le module de traduction
