### ISSUE TITLE
[BUG]: 2h d'attente en mini évent 

### ISSUE THREAD

**Issue by Jaarzz** [DraftBot-A-Discord-Adventure/DraftBot#1486]
### Description du bug.

J'ai participé à une loterie et j'ai perdu 10min. Je fais /rapport et je vois que je dois attendre 2h pour un mini évent 

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Juste un /rapport 
J'ai pas d'explication 

### Captures d'écran

![Capture d'écrans_20221008-184614](https://user-images.githubusercontent.com/106905934/194718526-6b81a174-18ec-45fb-9950-bfb587c9d25c.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

**Comment by Pietagorh** [comment]
Le problème a pas l'air de venir directement de la lotterie

**Comment by Jaarzz** [comment]
![Capture d'écrans_20221008-185704](https://user-images.githubusercontent.com/106905934/194718802-44cf76aa-2ab8-4987-a794-595a2590110d.png)

**Comment by romain22222** [comment]
@Jaarzz j'ai trois questions pour toi : 

1- avais tu une alté au début du voyage et si oui lequel (maybe d'avant la maj)
2- t'as eu une alté sur le mini event, et si oui de combien
3- le screen de ton path a été pris combien de temps après ton mini event ?

**Comment by romain22222** [comment]
Si c'est ce que je pense, c'est un duplicata de #1489

**Comment by Nargacaura** [comment]
Ce laps de temps est probablement dû à une guérison post-màj d'une alté pré-màj... L'alté retirée sans être retirée, en somme.

**Comment by Jaarzz** [comment]
@romain22222 
1. J'avais une alté de 3h avant la maj, qui a été terminée pendant la maintenance

2. J'ai eu une alté de 10min suite à la loterie 

3. Mon screen a été pris environ 30min après ma loterie
