### ISSUE TITLE
[BUG]: Le test atravel fait avancer l'alté ET le minievent 

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1487]
### Description du bug.

Si j'ai une alté de 5 minutes et que je fais /test atravel 5 , mon minievent sera dans seulement 5 minutes
Cette issue est surement liée à #1499 

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

- Avoir une alté
- Faire un atravel

### Captures d'écran

Dans cet exemple j'avais une alté de 10 minutes donc j'ai fait un atravel 10 et j'me suis retrouvé direct avec un minievent
![IMG_20221008_190316](https://user-images.githubusercontent.com/60353007/194719039-16e8175e-530d-4a27-ac18-7e86fc7b00b7.jpg)

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by Pietagorh** [comment]
Fixed nan ?

**Comment by BastLast** [comment]
Nan pas a ma connaissance
