### ISSUE TITLE
[BUG]: Impossibilité de regarder un profil en fonction de son rang

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1488]
### Description du bug.

Le rang est considéré comme un champ d'user, donc faire /profile rank:\<nombre> ne fonctionne pas car ledit nombre n'est pas un user d'après la commande...

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Faire /profile rank:<rang du'un joueur dans le classement>

### Captures d'écran

<img width="226" alt="Capture d’écran 2022-10-08 à 19 05 35" src="https://user-images.githubusercontent.com/94372084/194719234-fc366606-d57d-4244-bade-54487faac035.png">

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Pietagorh** [comment]
Je close, on va tout mettre dans celle du pettransfer

**Comment by BastLast** [comment]
ne pas oublier de mettre les labels et la redirection avec ping d'issue

**Comment by Pietagorh** [comment]
#1485
