### ISSUE TITLE
Easter eggs

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#149]

**Comment by BastLast** [comment]
enft on va faire des easter eggs mais on va pas du tout les mettre dans une issue ca serait bien trop simple de les repérer sinon eh eh :)

**Comment by niqore** [comment]
On pourrait réouvrir non?

**Comment by quenquentin** [comment]
Clairement pour, après à voir comment @BastLast veut organiser ça pour que ce soit "discret"

**Comment by BastLast** [comment]
> On pourrait réouvrir non?
> 

Naaah perso flm

**Comment by BastLast** [comment]
> > On pourrait réouvrir non?
> > 
> 
> Naaah perso flm

Vraiment je préfère pas faire ca en temps quobjectif en soit et juste glisser des ptits trucs de manière random

**Comment by niqore** [comment]
Je parle pas forcément de faire une mise à jour pour ça, mais par exemple prendre 1h pour rajouter quelques easter eggs, sans spoiler, par exemple la commande qui donnait ton poids (if you know what i mean)

**Comment by Pietagorh** [comment]
Sinon ce qui serait marrant c'est qu'on prenne des bugs qui impactent pas l'aventure du joueur et qu'on rajoute une sorte de banderole disant que c'est un easter egg
Comme ça c'est dans des trucs qui existent déjà et faut vraiment tester les limites du jeu pour les trouver

**Comment by Pietagorh** [comment]
J'pense notamment au fait de pouvoir boire des emplacements libre (après sinon peux l'fix mais j'trouve ça drôle)

**Comment by BastLast** [comment]
Vraiment pas chaud

**Comment by BastLast** [comment]
De manière générale je serai pour la suppression de cette issue, on ne la tag meme pas quand on rajoute des easter eggs

**Comment by BastLast** [comment]
je ferme pour les raisons citées ci-dessus
