### ISSUE TITLE
[BUG]: Potion consommée pendant le combat

### ISSUE THREAD

**Issue by Procion06** [DraftBot-A-Discord-Adventure/DraftBot#1490]
### Description du bug.
j'ai fait des combats et ça a consommé la potion qui était équipée

### Selon vous, quelle est l'importance de ce bug ?

Normal

### Reproduction du bug.

non

### Captures d'écran

![Screenshot_5](https://user-images.githubusercontent.com/107723160/194721472-a4fd4b86-b433-4ba9-a321-66d09981114e.png)
![Screenshot_7](https://user-images.githubusercontent.com/107723160/194721475-b21d8c3b-774c-4478-9d45-44e2d7d5d306.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Nargacaura** [comment]
Tu n'as pas fait un combat avant de lancer le mini-event de potion?

**Comment by Procion06** [comment]
le screen de 9h51 c'était pour montrer que le jus de kiwi était toujours équipé
mais effectivement j'ai fait des combats avant les mini events et je viens de vérifier il y a un écart de défense donc la popo a été consommée, bien vu !
je modifie le 1er post

**Comment by BastLast** [comment]
Bah du coup c'est pas un bug c'est normal, cf le changelog de la maj

**Comment by Nargacaura** [comment]
Du coup, ce n'est pas un bug, vu que la consommation de la potion est _un bugfix_ d'un autre bug. L'issue peut être fermée.

**Comment by BastLast** [comment]
Je close
