### ISSUE TITLE
discord api error unknown interraction

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1495]
draftbot  | DiscordAPIError[10062]: Unknown interaction
draftbot  |     at SequentialHandler.runRequest (/draftbot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:293:15)
draftbot  |     at runMicrotasks (<anonymous>)
draftbot  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
draftbot  |     at async SequentialHandler.queueRequest (/draftbot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
draftbot  |     at async REST.request (/draftbot/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
draftbot  |     at async ChatInputCommandInteraction.deferReply (/draftbot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:68:5) {
draftbot  |   rawError: { message: 'Unknown interaction', code: 10062 },
draftbot  |   code: 10062,
draftbot  |   status: 404,
draftbot  |   method: 'POST',
draftbot  |   url: censuré
draftbot  |   requestBody: { files: undefined, json: { type: 5, data: [Object] } }
draftbot  | }
draftbot  | DiscordAPIError[10062]: Unknown interaction
draftbot  |     at SequentialHandler.runRequest (/draftbot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:293:15)
draftbot  |     at runMicrotasks (<anonymous>)
draftbot  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
draftbot  |     at async SequentialHandler.queueRequest (/draftbot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
draftbot  |     at async REST.request (/draftbot/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
draftbot  |     at async ChatInputCommandInteraction.deferReply (/draftbot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:68:5)
draftbot  | ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
draftbot  |     at ConnectionManager.getConnection (/draftbot/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:204:15)
draftbot  |     at async Transaction.prepareEnvironment (/draftbot/node_modules/sequelize/lib/transaction.js:85:24)
draftbot  |     at async Sequelize.transaction (/draftbot/node_modules/sequelize/lib/sequelize.js:496:7) {
draftbot  |   parent: TimeoutError: Operation timeout
draftbot  |       at Timeout.<anonymous> (/draftbot/node_modules/sequelize-pool/lib/Deferred.js:17:25)
draftbot  |       at listOnTimeout (node:internal/timers:559:17)
draftbot  |       at processTimers (node:internal/timers:502:7),
draftbot  |   original: TimeoutError: Operation timeout
draftbot  |       at Timeout.<anonymous> (/draftbot/node_modules/sequelize-pool/lib/Deferred.js:17:25)
draftbot  |       at listOnTimeout (node:internal/timers:559:17)
draftbot  |       at processTimers (node:internal/timers:502:7)
draftbot  | }
draftbot  | Sequ

**Comment by romain22222** [comment]
pour ce qui est des discord unknown interaction, j'en ai aucune foutre idée, pour pouvoir savoir à quoi c'est relié faudrait savoir déjà quand ca proc, or y'a même pas un indice dans les paths loggés

**Comment by Feiryn** [comment]
Peut-être lié à #1496
