### ISSUE TITLE
operation timeout

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1496]
SequelizeConnectionAcquireTimeoutError: Operation timeout
draftbot  |     at ConnectionManager.getConnection (/draftbot/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:204:15)
draftbot  |     at async Transaction.prepareEnvironment (/draftbot/node_modules/sequelize/lib/transaction.js:85:24)
draftbot  |     at async Sequelize.transaction (/draftbot/node_modules/sequelize/lib/sequelize.js:496:7)
draftbot  | ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
draftbot  |     at ConnectionManager.getConnection (/draftbot/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:204:15)
draftbot  |     at async Transaction.prepareEnvironment (/draftbot/node_modules/sequelize/lib/transaction.js:85:24)
draftbot  |     at async Sequelize.transaction (/draftbot/node_modules/sequelize/lib/sequelize.js:496:7) {
draftbot  |   parent: TimeoutError: Operation timeout
draftbot  |       at Timeout.<anonymous> (/draftbot/node_modules/sequelize-pool/lib/Deferred.js:17:25)
draftbot  |       at listOnTimeout (node:internal/timers:559:17)
draftbot  |       at processTimers (node:internal/timers:502:7),
draftbot  |   original: TimeoutError: Operation timeout
draftbot  |       at Timeout.<anonymous> (/draftbot/node_modules/sequelize-pool/lib/Deferred.js:17:25)
draftbot  |       at listOnTimeout (node:internal/timers:559:17)
draftbot  |       at processTimers (node:internal/timers:502:7)
draftbot  | }

**Comment by romain22222** [comment]
les 10 milliards d'erreurs sequelize operation timeout, je suis sur à 99% que c'est les erreur de valueof null des petentities lors de leur création dans la bdd des logs

**Comment by romain22222** [comment]
cf un exemple :

```
TypeError: Cannot read properties of null (reading 'valueOf')
    at Function.<anonymous> (/draftbot/dist/src/core/database/logs/LogsDatabase.js:195:74)
    at Generator.next (<anonymous>)
    at /draftbot/dist/src/core/database/logs/LogsDatabase.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/draftbot/dist/src/core/database/logs/LogsDatabase.js:4:12)
    at Function.findOrCreatePetEntity (/draftbot/dist/src/core/database/logs/LogsDatabase.js:191:16)
    at LogsDatabase.<anonymous> (/draftbot/dist/src/core/database/logs/LogsDatabase.js:881:51)
    at Generator.next (<anonymous>)
    at /draftbot/dist/src/core/database/logs/LogsDatabase.js:8:71
    at new Promise (<anonymous>)
```

**Comment by BastLast** [comment]
Fixable facilement ?

**Comment by Feiryn** [comment]
> cf un exemple :
> 
> ```
> TypeError: Cannot read properties of null (reading 'valueOf')
>     at Function.<anonymous> (/draftbot/dist/src/core/database/logs/LogsDatabase.js:195:74)
>     at Generator.next (<anonymous>)
>     at /draftbot/dist/src/core/database/logs/LogsDatabase.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/draftbot/dist/src/core/database/logs/LogsDatabase.js:4:12)
>     at Function.findOrCreatePetEntity (/draftbot/dist/src/core/database/logs/LogsDatabase.js:191:16)
>     at LogsDatabase.<anonymous> (/draftbot/dist/src/core/database/logs/LogsDatabase.js:881:51)
>     at Generator.next (<anonymous>)
>     at /draftbot/dist/src/core/database/logs/LogsDatabase.js:8:71
>     at new Promise (<anonymous>)
> ```

C'est corrigé ça, et une tentative de fix a été faite pour le premier, à voir si ça corrige le pb

**Comment by BastLast** [comment]
go close , à réouvrir si ya encore le problème
