### ISSUE TITLE
[BUG]: La guérison (naturelle ou non) d'une altération d'état mène directement à un mini-event

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1499]
### Description du bug.

Quand on subit une altération, on a le réflexe de se soigner et de regarder si ça s'est bien effectué en observant la présence de 🧍🏻 dans la barre et la durée du trajet de retour à 10min max, n'est-ce pas? Là, en se soignant et en lançant /report, on tombe... sur un nouveau mini-event, skippant entièrement l'attente de 10 minutes. Cela peut éventuellement causer un flag automatique dans certains cas.

Notes: 
- l'issue peut être relative à #1487,
- le cas A a probablement déjà été fix avant l'envoi de cette issue (ne laissant que le cas B à prendre en compte)

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

- Subir une altération d'état (principalement par mini-event, mais un event peut aussi compter, qui sait?)
- Se soigner (par le shop ou naturellement)
- Faire /report pour vérifier que ça s'est bien guéri (mais ça donnera le mini-event à la place)

### Captures d'écran

Cas A (celui qui m'a donné un flag):
<img width="564" alt="Capture d’écran 2022-10-09 à 10 30 07" src="https://user-images.githubusercontent.com/94372084/194769912-7f56a40b-0d93-40ce-9434-a74049502e97.png">

Cas B (notez que je n'ai rien bu entre les 2 screens ci-dessous):
<img width="474" alt="Capture d’écran 2022-10-09 à 18 53 03" src="https://user-images.githubusercontent.com/94372084/194769950-cb9df406-fb97-41f7-901a-d50cb2f6d476.png">
<img width="497" alt="Capture d’écran 2022-10-09 à 18 53 10" src="https://user-images.githubusercontent.com/94372084/194769944-98a28ffa-d5f9-42cd-b131-4e9d847bce07.png">

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by BastLast** [comment]
@Thesmokingllama  si tu as des nouvelles infos go les ajouter ici stp

**Comment by Thesmokingllama** [comment]
> @Thesmokingllama si tu as des nouvelles infos go les ajouter ici stp

Oui ! Deux nouvelles infos même ! 
Primo, ce bug fonctionne quasiment tout le temps (et pour ma part même uniquement) avec la loterie, l'altération de 10min ne ralentit pas dans la durée du voyage, dès la fin de l'alté il est possible de rejouer.
Secundo, le bug ne fonctionne pas lorsqu'il n'y a pas de mini event de prévu dans les 10 minutes qui suivent l'altération (en fin de voyage donc).

**Comment by BastLast** [comment]
> > @Thesmokingllama si tu as des nouvelles infos go les ajouter ici stp
> 
> Oui ! Deux nouvelles infos même ! 
> Primo, ce bug fonctionne quasiment tout le temps (et pour ma part même uniquement) avec la loterie, l'altération de 10min ne ralentit pas dans la durée du voyage, dès la fin de l'alté il est possible de rejouer.
> Secundo, le bug ne fonctionne pas lorsqu'il n'y a pas de minievent initialement prévu dans les 10 minutes qui suivent l'altération (en fin de voyage donc).

@niqore avec ces infos ça rend le bug facilement reproductible donc a priori vu que tu maîtrises le mieux le système de temps je serai grave chaud que tu fasses une mini pr

**Comment by Pietagorh** [comment]
J'pense que j'ai un fix
Par contre les testeurs va falloir bien tester parce que j'suis pas sûr de moi x)
