### ISSUE TITLE
[BUG]: affichage de la guilde Frog II 

### ISSUE THREAD

**Issue by Jo787** [DraftBot-A-Discord-Adventure/DraftBot#1502]
### Description du bug.

depuis la maj quand on fait un /guilde Frog II ou alors qu'on choisit un membre de la guilde le bot affche qu'il ne repond pas 

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

faire un /guilde Frog II (mètre une majuscule au F )

### Captures d'écran

![image](https://user-images.githubusercontent.com/110350223/194930430-38adffa1-2d02-4085-9ea2-229c6693860b.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Pietagorh** [comment]
Sûrement lié à #1495, vu qu'un des joueurs affecté fait partie de la guilde

**Comment by Jaarzz** [comment]
Je m'incruste pour dire que moi aussi ça fait pareil avec le /guilde

**Comment by Pietagorh** [comment]
Idem, il a Kiri dans sa guilde
