### ISSUE TITLE
[BUG]: nom de pet 

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#1512]
### Description du bug.

Le nom lisible en event n'est pas celui attribué par son propriétaire

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

2 joueurs :
-J1 renomme un pet 
-J2 force le mini event pour croiser J1 en compagnie de son pet 

### Captures d'écran

![1DF20B3D-87AA-49FC-8273-5EF5D08A1AA2](https://user-images.githubusercontent.com/80409766/195274016-da8da472-acd3-4e53-b77b-3df5a29a5b2c.jpeg)
![650B011C-DCCB-4E10-8767-018FD390F6A5](https://user-images.githubusercontent.com/80409766/195274021-f113158c-f994-4b8e-8961-d1eeaea9a779.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Procion06** [comment]
Quand tu veux afficher le pet de quelqu'un il t'affiche ton propre pet

![Screenshot_7](https://user-images.githubusercontent.com/107723160/195345973-94820bf8-c340-41a6-b62c-d37c7aea4e55.png)

**Comment by quenquentin** [comment]
Hmhm @Pietagorh Si réopen possible d'apporter des précisions ou autre ?

**Comment by BastLast** [comment]
Faut rajouter un await qqpart

**Comment by BastLast** [comment]
Btw 1 issue /bug à l'avenir et si c'est moi qui ai dit de merge j'ai été stupide

**Comment by Procion06** [comment]
oui c'est toi qui m'a dit de le poster ici ^^
