### ISSUE TITLE
[BUG]: mission visiter 3 lieux différents

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#1513]
### Description du bug.

La mission est validée lorsque le joueur revient sur un lieu déjà visité (Mergagnan-Sentinelle-Mergagnan).

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Avoir la mission et faire le trajet vers la plage Sentinelle puis en revenir

### Captures d'écran

![150B49C1-7F41-47BA-89D7-7192C93952BE](https://user-images.githubusercontent.com/80409766/195274895-88eec0b5-4e8c-44d1-ab4c-fc189a102ebb.jpeg)
![9F5C6FA8-F938-4A65-88A5-387658D94B95](https://user-images.githubusercontent.com/80409766/195274899-6b537272-c517-4b82-bd97-d93725b5753d.jpeg)
![028B8C49-BFD3-4F14-A545-07B111C7A34C](https://user-images.githubusercontent.com/80409766/195274904-038b323b-c850-46c1-8bd9-ecf0ab4f3de0.jpeg)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by BastLast** [comment]
Tu as eu la. Mission quand ?

**Comment by Thesmokingllama** [comment]
> Tu as eu la. Mission quand ?

Ce matin

**Comment by Feiryn** [comment]
@Thesmokingllama Est-ce que tu peux me donner les dates et heures exactes des visites des 3 lieux stp ?
