### ISSUE TITLE
[BUG]: top10 pas top10

### ISSUE THREAD

**Issue by KirIcare** [DraftBot-A-Discord-Adventure/DraftBot#1514]
### Description du bug.

Le mini event supposé me faire croiser un joueur du top 10 me fait croiser un joueur hors de cette restriction. 

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Report pour obtenir le mini event. 

### Captures d'écran

![IMG_20221012_100206](https://user-images.githubusercontent.com/111249432/195289235-861a186e-0ab2-4622-bbce-4d92439fb3a7.jpg)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

**Comment by Feiryn** [comment]
J'ai rencontré le bug pour le top week aussi
![Uploading Screenshot_20221013-093813_Aliucord.png…]()

**Comment by BastLast** [comment]
> J'ai rencontré le bug pour le top week aussi
> ![Uploading Screenshot_20221013-093813_Aliucord.png…]()
> 

Oui c'est normal

**Comment by Feiryn** [comment]
Bon rip le screenshot

**Comment by BastLast** [comment]
Check le commit tentative, quand on récupère le player on récupère pas le rank et le weeklyrank, du coup ça vaut -1

**Comment by BastLast** [comment]
Jai try un fix qui est censé marcher mais jsp pk ca renvoi toujours -1...

**Comment by Procion06** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/107723160/195822777-29c0b1ab-38a7-40f5-82d8-8852d3dd1804.png)
