### ISSUE TITLE
[BUG]: double message level up

### ISSUE THREAD

**Issue by KirIcare** [DraftBot-A-Discord-Adventure/DraftBot#1515]
### Description du bug.

Comme le nom l'indique, 2 messages pour un qu'un seul level up

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Je sais c'est pas moi mais level up je suppose ? 

### Captures d'écran

![IMG_20221012_102330](https://user-images.githubusercontent.com/111249432/195291684-d3f7887d-0628-434d-9082-d5c011808c76.jpg)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

**Comment by Procion06** [comment]
Double message mission complétée

![Screenshot_12](https://user-images.githubusercontent.com/107723160/195559931-9ff771ca-4a7c-4b86-8ee5-8659d28ed173.png)

**Comment by BastLast** [comment]
Possible d'avoir plus d'infos ? Comment l'xp qui a fait le montage de level a été gagnée ? Quelles ressources ont été perçues, quelle est l'id discord du joueur affecté ?

**Comment by BastLast** [comment]
je rouvre suite au problème relevé par @KirIcare , si tu as plus d'infos d'ailleurs , hésite pas à envoyer tout ce que tu sais à l'occasion

**Comment by KirIcare** [comment]
Alors tout ce que je sais c'est que:
-je me suis mis lv50 manuellement
-au moment où je suis passé level 51, j'ai pris 525xp, 25 pour l'évent et 500 grâce aux deux missions de campagne (58 et 59) complété d'un coup
-j'ai également était mis en alté suite à l'évent (aucun problème de ce côté juste je précise tout ce qu'il s'est passé)

**Comment by KirIcare** [comment]
J'ai réussi à le reproduire en test et le point commun à l'air d'être le fait de compléter de mission de campagne en même temps.
Premier screen j'ai level up en complétant une mission de campagne et j'ai eu qu'un message.
Deuxième screen j'ai encore level up en complétant 2 missions de campagne cette fois et le bug s'est reproduit
On peut voir que lorsque j'ai ré ouvert l'issue, j'ai eu le double message en complétant 2 missions de campagne également
![IMG_20221028_005222](https://user-images.githubusercontent.com/111249432/198413212-c0b132ae-bbaf-4914-89dd-f0be5239a588.jpg)
![IMG_20221028_005244](https://user-images.githubusercontent.com/111249432/198413249-f9f0cdb3-dae2-4be2-ab77-a67329c04f2d.jpg)

**Comment by BastLast** [comment]
Ça ça aide énormément ! Merci !!!

**Comment by KirIcare** [comment]
Je pense que y'a plus besoin de chercher
![IMG_20221028_010515](https://user-images.githubusercontent.com/111249432/198414151-b89f8884-9d78-428c-bbd1-1b146a0da2ce.jpg)
![Screenshot_20221028-010459](https://user-images.githubusercontent.com/111249432/198414184-4e5472fa-b56b-4a7e-acd2-adf447e64622.jpg)

**Comment by KirIcare** [comment]
Le seul truc qu'il me resterais à test c'est de savoir si ça s'applique qu'aux missions de campagne ou également aux missions secondaires

**Comment by BastLast** [comment]
Pas besoin de tester ça c'est sur ça s'applique aux 2

**Comment by KirIcare** [comment]
Alors c'est bon mon rôle s'arrête ici
Je suis content pour une fois que j'arrive à trouver un truc de ma propre initiative, ça fait plaisir et ça donne envi de test encore plus mdr

**Comment by KirIcare** [comment]
Juste pour info, ça parais logique mais au cas où, le bug s'applique peut importe le nombre de missions complétés tant qu'il y en a au moins 2
![Screenshot_20221031-201504](https://user-images.githubusercontent.com/111249432/199096057-0a01719c-bf72-436c-ba3e-400de4c1c3bc.jpg)

**Comment by Nargacaura** [comment]
Pour apporter un peu plus de précisions sur ce bug, il y a autant de messages de level up que de missions complétées. Quelque chose laisse donc à penser que le message de level up est vérifié à chaque mission complétée. Par exemple, j'ai reproduit le bug avec une mission de campagne et 3 missions secondaires... 4 messages de level up. Les screens précédents le montrent aussi (4 messages de level up pour 4 missions, ou 2 pour 2 missions).
<img width="525" alt="Capture d’écran 2022-11-01 à 15 58 50" src="https://user-images.githubusercontent.com/94372084/199264553-47ac9583-0ddc-4076-9be9-2a70e6347254.png">

Si le check de level up est effectué sur la mission, il faudrait le sortir de la boucle de check de complétion.
