### ISSUE TITLE
[BUG]: Message 2 levels up

### ISSUE THREAD

**Issue by Procion06** [DraftBot-A-Discord-Adventure/DraftBot#1518]
### Description du bug.

au passage d'un nouveau niveau affiche également le passage du niveau précédent

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

aucune idée

### Captures d'écran

![Screenshot_13](https://user-images.githubusercontent.com/107723160/195823825-8de0052f-39c3-4700-afb2-50baf81060a2.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by BastLast** [comment]
Ca fait ça a chaque passage de niveau ? Il etait niveai 49 iu 50 a la base ?

**Comment by Procion06** [comment]
il était 50 c'est en passant au 51
il était déjà full life donc je ne peux pas dire si la restauration a fonctionné ou non

**Comment by Procion06** [comment]
![Screenshot_11](https://user-images.githubusercontent.com/107723160/196427571-43c0aa5f-0c2b-476c-a8fa-02e83aad4e6d.png)

**Comment by BastLast** [comment]
j'aimerai l'id discord du joueur stp

**Comment by Procion06** [comment]
Dartio : 376761072465477635
Carsebel : 691923370358472774
