### ISSUE TITLE
Mission de régénération non accomplie avec un guilddaily particulier

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1521]
### Description du bug.

Lorsqu'on a toute notre vie et aucune alté, et qu'on obtient ce guilddaily, ça laisse à penser que la mission ne s'est pas accomplie malgré le fait qu'il affiche un gain de PV si le gain est supérieur à l'objectif.

Si c'est devenu du gain d'argent (donc pas un bug à proprement parler), c'est assez fourbe de ne pas afficher "Vous avez obtenu x 💰" à la place, rendant cette issue caduque... sauf que je n'ai rien gagné en termes d'argent, donc cette possibilité est à écarter.

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Faire un /guilddailybonus en espérant tomber sur celui dans la capture tout en étant sans alté et possiblement full-vie, avec la mission de régen en cours.

### Captures d'écran

![IMG_20221017_062734](https://user-images.githubusercontent.com/94372084/196155962-a39e0f14-3a56-4bce-95a4-5fa99a1928ee.jpg)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Feiryn** [comment]
Pour moi ce n'est pas un bug, la récompense marche de la façon suivante :
- Si au moins un joueur a une altération alors :
  - Les joueurs avec alte sont soignés
  - Les joueurs sans alté et non full vie gagnent de la vie et avancent la mission
  - Les joueurs sans alté et full vie ne gagnent rien
- Si aucune alte et tout le monde full vie :
  - Gain d'argent

**Comment by Feiryn** [comment]
Après on peut faire en sorte que la vie excédentaire compte dans la mission
