### ISSUE TITLE
Erreur sur le drink

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1522]
### Description du bug.

TypeError: Cannot read properties of null (reading 'getItem')
    at Object.<anonymous> (/draftbot/dist/src/commands/player/DrinkCommand.js:85:98)
    at Generator.next (<anonymous>)
    at fulfilled (/draftbot/dist/src/commands/player/DrinkCommand.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections 

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

Aucune idée

### Captures d'écran

Nope

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
possible de donner + de contexte ? comment est apparu le log ? quel bot ? possible  que les testeurs fassent des tests sur le bot alpha ?

**Comment by BastLast** [comment]
bon le seul moyen d'avoir ce truc c'est d'avoir null dans le main potion slot, faudrait voir dans la bdd combiende joueurs sont concernés et comment ils sont arrivés là

**Comment by BastLast** [comment]
bon j'ai fait un check sur toute la base de donnée et j'ai trouvé aucun inventory slot avec un itemId qui n'était pas un nombre...
Je n'ai pas non plus réussi à reproduire le bug sur mon instance. Je close , à réouvrir si qqun arrive à refaire le truc ou obtient plus d'infos
