### ISSUE TITLE
[BUG]: Guilddaily qui régénère quand tous les membres sont full vie

### ISSUE THREAD

**Issue by ZRunner** [DraftBot-A-Discord-Adventure/DraftBot#1523]
### Description du bug.

Il m'est arrivé plusieurs fois (même consécutivement) d'avoir un /guilddailybonus qui donne des pv aux membres de la guilde alors même qu'on a déjà tous nos points de vie. Pourtant les vérifications faites lors d'un guilddaily devraient empêcher ce cas de figure et utiliser une autre récompense à la place.

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

- se trouver une guilde
- s'assurer que tous ses membres soient full pv
- faire un guilddailybonus
- avec un peu de chance vous verrez le bug (bah oui ça reste du random hein)

### Captures d'écran

<img width="596" alt="Le guildbonus, mon profil, et ma guilde" src="https://user-images.githubusercontent.com/30912430/196464398-366e272b-7552-466f-ab84-fb4cae26adc1.png">
<img width="438" alt="Le profil des deux autres membres de ma guilde" src="https://user-images.githubusercontent.com/30912430/196464422-2c55a591-8a18-45e9-8b24-b315ac2541b3.png">

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by BastLast** [comment]
Est-ce vraiment un bug ? Ou juste une suggestion ?

**Comment by ZRunner** [comment]
t'as lu ma belle description bien écrite ?
on vient de m'assurer dans #général que ça ne devrait pas arriver, c'est pas une suggestion, c'est un constat que ton code est foireux :kappa:

**Comment by BastLast** [comment]
Je viens de lire le général et je confirme que c'est un bug dcp

**Comment by BastLast** [comment]
pour moi ce truc est normal, l'un de vos membres était sous alté et du coup c'est ce check qui prend le dessus, le heal est un cadeau secondaire et du coup ya pas de check dessus, après révision, ceci n'est pas un bug.
