### ISSUE TITLE
Haut faits & missions

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#153]
- [x] Implémenter les variantes (je le ferais)
- [x] Faire les json de quetes et les appels dans le code (peut-être attendre les variantes ou alors faire que des quetes sans variantes)
- [x] Design la campagne et le gros json avec les 100 missions (pour une 1ère maj on va jusqu'à 40 ou 50)
- [x] Faire la campagne coté code
- [ ] Fix les mission daily des joueurs qui ne se reset pas
- [ ] Changer le style de la progress bar
- [x] Implémenter le message qui dit qu'une quete a expiré
- [x] Améliorer l'embed qui annonce les missions finies
- [x] Ajouter le fait qu'un joueur puisse trouver une mission liée à son niveau
- [x] Implémenter le changement du nombre de slot de missions maximal pour un joueur
- [x] Changer les noms et les prix du shop
- [x] Faire quelque chose pour les missions de campagne qui se valident toutes seules car le joueur l'a déjà fait (exemple : équiper un objet rare minimum, atteindre le lvl 25)
- [x] Equilibrer la nouvelle monnaie (gemmes)
- [ ] Implémenter plein de petites quêtes temporaires et daily
- [x] Corriger le bug qui fait que la dernière mission de campagne e tla mission quotidienne sont complétées en boucle
- [x] Ne pas mettre Missions actuelles dans l'embed s'il n'y en a pas (ou mettre une erreur)

**Comment by eagles666** [comment]
je me retire de cette issue

**Comment by romain22222** [comment]
A faire : 

- [ ] Créer la structure des missions hauts faits
- [ ] Créer la commande pour afficher les hauts faits
- [ ] Créer la commande pour afficher les missions
- [ ] Donner tous les hauts faits niveau 0 aux joueurs
- [ ] Gérer le cas des hauts faits maximaux
- [ ] Remplir les slots de missions finies au bout de X temps
- [ ] Ajouter la fonction qui update les missions et hauts faits aux endroits nécessaires

**Comment by BastLast** [comment]
J'aurai vraiment voulu discuter plus de ce truc avant de se lancer tête baisse dedans

**Comment by niqore** [comment]
b2ef6e4

**Comment by niqore** [comment]
- [ ] Implémenter les variantes (je le ferais)
- [ ] Faire les json de quetes et les appels dans le code (peut-être attendre les variantes ou alors faire que des quetes sans variantes)
- [ ] Design la campagne et le gros json avec les 100 missions
- [ ] Faire la campagne coté code
- [ ] Fix les mission daily des joueurs qui ne se reset pas
- [ ] Changer le style de la progress bar car à chaque fois y a un testeur qui me fait chier avec
- [ ] Implémenter le message qui dit qu'une quete a expiré
- [ ] Améliorer l'embed qui annonce les missions finies
- [ ] Ajouter le fait qu'un joueur puisse trouver une mission liée à son niveau
- [ ] Implémenter le changement du nombre de slot de missions maximal pour un joueur
- [ ] Changer les noms et les prix du shop

**Comment by BastLast** [comment]
possible de mettre tout ce qui est checkliste dans le commentaire en haut de l'issue ? comme ca on est sur que les checklist sont à jour

**Comment by niqore** [comment]
Les campagnes 29, 30 et 33 ne sont pas faites encore

**Comment by romain22222** [comment]
Todo : réfléchir aux flags pour event 33 / 36 (autres possibles, à voir)

**Comment by BastLast** [comment]
je pense que cette issue mérite d'être fermée. Merci à tous pour le taf effectué, les tâches liées seront désormais suivies dans des issues dédiées.
