### ISSUE TITLE
Nouveau mini event du bateau

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1545]
- [x] Mini-évent du bateau
- [x] Ajouter une commande qui permet aux joueurs de la guilde de rejoindre un joueur sur un bateau
- [x] Sélectionner une île globale aléatoire chaque semaine (faire un roulement)

**Comment by Feiryn** [comment]
> ça coûterait des gemmes de la même façon pour rejoindre le bateau ?

Oui, comme le mini évent, ça dépendra du nombre de fois où tu y es allé dans la semaine avec le même coût
