### ISSUE TITLE
Créer les miniévènements spécifiques à l'ile

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1549]
- [x] #1617
- [x] Rien ne se passe
- [x] #1878
- [x] #1879
- [x] Gain fight points
- [x] Conseils trajet bateau

**Comment by romain22222** [comment]
Idée de mini event pour l'ile : pouvoir poser un caillou sur sa route avec un petit mot dessus (genre taille d'un tweet) et chaque personne passant par cette route pourrait tomber dessus X fois avant que le message disparaisse (autre mini event). Les joueurs pourraient se partager des tips, faire une pub cachée pour leur guilde (coucou les messages sauvages de draft irl), ou encore parler du temps qui passe, qui sait ?

**Comment by BastLast** [comment]
wow la modération d'un truc comme ça...
