### ISSUE TITLE
Gérer la perte de l'énergie sur l'île (et le fait que si tu te fait buter, tu doit partir immédiatement)

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1551]
- [x] si tu meurs (plus d'energie) tu pars de l'ile (tu te fais tp sur l'ile principale et tu prend une alté de 40 min)
- [x] bloquer la regen d'energie
- [x] bloquer le drink, daily, bonus et toutes les commandes qui donnent des trucs (y compris les shops)

**Comment by Feiryn** [comment]
Bug quand on perd on se fait pas kick
