### ISSUE TITLE
Mission 51

### ISSUE THREAD

**Issue by Voisin1234** [DraftBot-A-Discord-Adventure/DraftBot#1553]
### Description du bug.

Bonjour j’ai voulu faire la mission 51 j’ai acheté l’argent du roi sauf que la mission n’a pas été validé.

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

/mission - /magasinmisson - acheter trésor du roi - validé -argent reçu -Mission non validé.

### Captures d'écran

![C93C3FD2-F74C-4DD4-B119-B3EB42D2AB2C](https://user-images.githubusercontent.com/108148891/198719226-9c6aa07d-fdc5-45a3-bce9-1cf6b4e99da5.png)
![906A5C3C-729B-45FF-A9CE-FE63033BE039](https://user-images.githubusercontent.com/108148891/198719230-fe47148c-0d0e-488e-a188-5553699854d4.png)
![F0126891-909B-42C2-BD5C-E40B75F4D671](https://user-images.githubusercontent.com/108148891/198719233-43ad14e8-48da-4669-8ba0-a15ea7387af2.png)
![7A3CC01F-3CCB-4C3E-95C6-B3EE53C50BB0](https://user-images.githubusercontent.com/108148891/198719238-66a590db-8e47-49d3-b1b5-ffbe778ec954.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

**Comment by KirIcare** [comment]
Tu l'as pas complété

**Comment by KirIcare** [comment]
Faut gagner moins de 6500 et la t'as eu 7360

**Comment by Voisin1234** [comment]
Pardon effectivement je n'ai pas vu j'ai le démon désolé
