### ISSUE TITLE
Ajouter un menu d'aide

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#1555]
- [x] Ajouter une section dans la commande help
- [ ] Ajouter une page au guide et mettre à jour les autres pages
- [x] Ajouter un max de conseils pour boatAdvice

**Comment by BastLast** [comment]
@Feiryn on avais noté des truccs à faire pr ça plus détaillé ?
j'ai ajouté quelques idées en todolist mais j'ai surement oublié des trucs

**Comment by Feiryn** [comment]
Pour la 4ème tâche y a déjà le mini-évent sur le bateau

**Comment by BastLast** [comment]
> Pour la 4ème tâche y a déjà le mini-évent sur le bateau

Tu pense que ça suffit ?

**Comment by Feiryn** [comment]
Oui ça fait exactement ça

**Comment by Feiryn** [comment]
Y a qu'un mini-évent possible et c'est un conseil pour l'ile

**Comment by BastLast** [comment]
Ok go le supprimer alors

**Comment by Feiryn** [comment]
Je sais pas si ça vaut le coup de mettre les conseils PVE dans les conseils des /report : c'est une feature complètement à part de l'aventure principale et c'est déjà le rôle de boatAdvice de donner des conseils. Car finalement si one le fait ça va être un exact copié collé du mini-évent du bateau.
Ou alors on en mets juste un genre : au lvl 20 vous débloquez le pve

**Comment by BastLast** [comment]
je close cette issue, on ne traque pas vraiment le guide sur github. je m'occuperai de check que ça a bien été fait avant la release
