### ISSUE TITLE
[BUG]: Rencontre de pets non aléatoire

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1556]
### Description du bug.

Les pets rencontrés dans un mini-event sont toujours les mêmes que ceux qu'on possède.

Cause: `randomAnimal: randomAnimal ? ${randomAnimal.getPetEmote(petModel)} ${randomAnimal.getPetTypeName(petModel, language)} : ""`
avec petModel... notre pet.

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Avoir le mini-event où on rencontre un autre pet.

### Captures d'écran

![Screenshot_20221030-083254_Discord](https://user-images.githubusercontent.com/94372084/198869688-126d8ab0-401b-4aeb-abe4-de167fde11d4.jpg)
![IMG_20221024_052657](https://user-images.githubusercontent.com/94372084/198869690-6b781c1d-b100-4191-b527-854506743da3.jpg)
![Screenshot_20221030-082148_Discord](https://user-images.githubusercontent.com/94372084/198869697-5ca9d54d-5c76-4597-8722-639a4862a1f0.jpg)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
j'ai check le code je sais pas exactement ce qu'il se passe mais le coup du petModel = pet ça n'a aucun sens...
