### ISSUE TITLE
[BUG]: La mission havePotions ne se valide pas quand il le faut

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1560]
### Description du bug.

Visiblement, la mission havePotions ne veut pas valider, même si on a 2 potions sur soi... mais il se peut aussi qu'elle se valide alors qu'on a bu la seconde potion avant de faire la mission précédente!

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Se mettre sur la mission 30 de la campagne sans l'avoir automatiquement complétée dans le bot de tests. Récupérer 2 potions.
OU
Boire une potion de vie ou de temps avec une autre potion dans l'inventaire. Faire la mission précédente. Voir sa mission validée avec une seule potion.

### Captures d'écran
Cas de test (mission non validée avec 2 potions):
<img width="398" alt="Capture d’écran 2022-11-01 à 19 04 00" src="https://user-images.githubusercontent.com/94372084/199306107-6da2f61b-b224-4dc1-b053-e1b4c6438ecb.png">
<img width="365" alt="Capture d’écran 2022-11-01 à 19 04 09" src="https://user-images.githubusercontent.com/94372084/199306127-2768d4ca-9cc7-41df-a5de-e1adc1941604.png">

Cas de réalisation de la mission précédente (boire une potion de vie/temps, puis faire les 10 fights tout en laissant l'autre potion dans sa réserve):
<img width="365" alt="Capture d’écran 2022-11-01 à 19 23 14" src="https://user-images.githubusercontent.com/94372084/199309633-3658e8fd-3493-434a-af08-fc8d9532831f.png">
<img width="374" alt="Capture d’écran 2022-11-01 à 19 23 21" src="https://user-images.githubusercontent.com/94372084/199309659-07cef9f8-69f1-4ded-a886-3c69d3b9e650.png">
NOTE: j'ai bu une potion de vie avant de faire la mission des 10 combats.

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by romain22222** [comment]
alors étonnamment, j'ai aucune idée la comme ca

**Comment by Nargacaura** [comment]
> Ce serait pas parce qu'il compte que les items de l'inventaire ? Donc pour lui y a qu'une potion. 
> Et de ce que je voit quand le mec boit une potion, on compte le nombre de potions dans son inventaire, mais c'est la potion du profil qui est bu.

Sauf que la potiona été bue avant même de faire les 10 combats, du coup, j'ai plus l'impression qu'il ne fait que checker s'il y a une deuxième potion dans l'inventaire, mais juste quand il ne faut pas x)

**Comment by romain22222** [comment]
@Nargacaura 
1 - Comment as tu obtenu ta 2nde potion ?
2 - On est d'accord que t'as validé la mission en faisant un fight en ayant 2 potions sur toi ?

**Comment by Nargacaura** [comment]
> @Nargacaura 
> 1 - Comment as tu obtenu ta 2nde potion ?
> 2 - On est d'accord que t'as validé la mission en faisant un fight en ayant 2 potions sur toi ?

1. Via le shop (les 2, d'ailleurs.)
2. Même pas, j'ai bu la première potion avant même de démarrer le premier des 10 combats.

**Comment by BastLast** [comment]
@voltou91  je déplace en 4.1.0 du coup ?

**Comment by voltou91** [comment]
> @voltou91 je déplace en 4.1.0 du coup ?

Comme tu veux, je vais push dans quelques minutes.

**Comment by BastLast** [comment]
bah je vois pas l'interet d'attendre alors go, je te laisse faire la pr

**Comment by voltou91** [comment]
A l'évidence elle est tjr pété T-T

**Comment by quenquentin** [comment]
Shop + Fight apparemment (à étudier tho)

**Comment by voltou91** [comment]
Ok j'ai compris le problème X)
En gros on check les potions de ton inventaire avant de te la give. Du coup il compte une potion puis te give ta 2e potion.
