### ISSUE TITLE
[BUG]: Une personne KO peut encore interagir avec des autres utilisateurs

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1561]
### Description du bug.

Dans un souci de logique, une personne KO ne peut que faire /respawn, non? Bah... pas s'il peut interagir avec des commandes lancées par d'autres personnes.

Commandes affectées: /guildinvite, /petsell... en gros, toutes celles qui peuvent offrir à la personne KO une interaction.

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Avoir une personne KO avec laquelle intéragir. Exécuter une commande telle que /guildinvite ou /petsell.

### Captures d'écran

/guildinvite:
<img width="394" alt="Capture d’écran 2022-11-01 à 20 01 57" src="https://user-images.githubusercontent.com/94372084/199317256-5e24fd2e-2b96-4234-ac27-27ae1ba61d2f.png">

/petsell: (note: KirIcare était encore KO à cet instant là)
<img width="406" alt="Capture d’écran 2022-11-01 à 20 02 08" src="https://user-images.githubusercontent.com/94372084/199317281-dc279fd1-4a7c-4848-b3d5-0292380be534.png">

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
à part ces deux commandes, il y a d'autres commandes qui sont concernées ?

**Comment by KirIcare** [comment]
On a pas test plus en profondeur puisque Pagos a exposé mort + commande lancé par autre joueur = osef de la mort
Comme si y'avais pas de check de l'état de la personne (alors qui si puisque on peut pas interagir quand on est en alté)

**Comment by BastLast** [comment]
> On a pas test plus en profondeur puisque Pagos a exposé mort + commande lancé par autre joueur = osef de la mort Comme si y'avais pas de check de l'état de la personne (alors qui si puisque on peut pas interagir quand on est en alté)

je vais fix les cas ci dessus mais go tester en profondeur asap
