### ISSUE TITLE
[BUG]: affichage du badge voteur sur le profil des joueurs médaillés

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#1565]
### Description du bug.

Le badge obtenu grâce au vote peut parfois, sur un profil donné, apparaître comme deuxième badge malgré la possession de la médaille et non à l'intérieur de la médaille supposée contenir l'ensemble des badges du joueur.

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

- Sur le bot test ajouter 10 badges de manière à obtenir la médaille
- Voter pour obtenir le badge vote
- Vérifier son emplacement sur le profil ou dans la médaille
- Recommencer en inversant la première et la 2e étape

### Captures d'écran

![09E5E2D0-A4BC-444D-9E58-12CA31AFE862](https://user-images.githubusercontent.com/80409766/199581604-a7315f8c-dbeb-4512-8de6-bee0e2c7ba45.jpeg)
![7DFF23C5-B873-4866-8329-44BA0B49544B](https://user-images.githubusercontent.com/80409766/199581608-4ed1a1cb-110d-466b-8c9d-783ea3be6aab.jpeg)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by BastLast** [comment]
est-ce que ça a un impact sur le fait que le badge soit retiré une fois que la personne n'est plus voteur ?

**Comment by Pietagorh** [comment]
En fait c'est juste romain qui a ça parce que pour une raison inconnu il a le badge voteur en permanent mdr

**Comment by BastLast** [comment]
faudrait que romain vote pour check si ça lui enlève

**Comment by BastLast** [comment]
avant
pr être sûr

**Comment by quenquentin** [comment]
A voir de ce qu'on fait de ça pour le coup @BastLast

**Comment by BastLast** [comment]
toujours pas la réponse de ce qu'il se passe avec romain

**Comment by BastLast** [comment]
je veux l'infos ici avec des screens

**Comment by romain22222** [comment]
> faudrait que romain vote pour check si ça lui enlève

je sais pourquoi je l'ai en perma, et ca n'a surement rien à voir avec le bug en question

**Comment by BastLast** [comment]
> > faudrait que romain vote pour check si ça lui enlève
> 
> je sais pourquoi je l'ai en perma, et ca n'a surement rien à voir avec le bug en question

tu peux balancer les infos ?

**Comment by romain22222** [comment]
> > > faudrait que romain vote pour check si ça lui enlève
> > 
> > 
> > je sais pourquoi je l'ai en perma, et ca n'a surement rien à voir avec le bug en question
> 
> tu peux balancer les infos ?

alors pour mon cas, quasi sur que le badge a été rajouté pas un gérant des badges par mégarde lorsqu'il s'est chié dans les badges

pour ce qui est du bug en soi, je dirais que le badge de voteur est juste pas ajouté au bon endroit, genre mauvais message ou autre

**Comment by BastLast** [comment]
est-ce que tu peux voter pour check si le badge t'es enlevé stp ? ça éviterait à un gérant des badges de te reset tes badges pour les remettre si c'est le cas

**Comment by romain22222** [comment]
je confirme qu'il ne peut s'enlever, les badges ne "s'enlèvent" pas, ils sont juste donnés temporairement

de mon côté c est en hard et en plus c est au milieu des badges

**Comment by BastLast** [comment]
est-ce que tu peux voter stp ? j'aimerai check :)
