### ISSUE TITLE
[BUG]: le bonus de guilde ne valide pas la mission quotidienne 

### ISSUE THREAD

**Issue by 85inconu** [DraftBot-A-Discord-Adventure/DraftBot#1573]
### Description du bug.

le bonus journalier soigne les membres de la guilde mais ne valide pas la mission quotidienne pour le chef de guilde

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

- Avoir la mission quotidienne qui demande de gagner 10PV
/Bonusjournalierguilde

### Captures d'écran

![Capture d'écrans_20221106-094652](https://user-images.githubusercontent.com/117566400/200162311-5c0ff794-3b82-4815-a5cb-4eb5a7a84cf6.png)
![Uploading Capture d'écrans_20221106-094659.png…]()

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Nargacaura** [comment]
Est-ce que le chef de guilde a subi une altération au moment de ce guilddaily?

**Comment by 85inconu** [comment]
Je sais bien que si une altération d'état est présente elle sera supprimée et je ne gagnerais pas de PV

**Comment by BastLast** [comment]
Temps perdu = occupé = altération

**Comment by romain22222** [comment]
je confirme aussi que d'après les screens, il était bien sous altération (temps perdu) lors du gd. Autre précision, il est en effet possible de faire un gd en étant sous altération. Les seules exceptions sont baby (mais ca doit jamais arriver), dead (si t'es mort tu respawn c'est tout) et lock (en prison tu peux pas communiquer avec les agents du royaume afin de collecter la dime journalière)

**Comment by romain22222** [comment]
je close donc l'issue car not a bug

**Comment by BastLast** [comment]
Le label quand c'est pas un bug c'est invalid, wontfix c'est quand on décide de pas fix le bug car il n'apparaît quasi jamaos ou qu'il est du à une migration  ou ce genre de trucs

**Comment by romain22222** [comment]
pour moi invalid c'était juste un label quand tu penses que c'est pas correct, mais tu sais pas si c'est juste pas voulu, si c'est un bug, si c'est une typo, si c'est rien et je suis con, etc. c'était pas pour une mauvaise issue

à rename / à changer de description

**Comment by romain22222** [comment]
poke @BastLast faut absolument le faire

**Comment by BastLast** [comment]
Ok je ferai un passage sur les labels asap pas hesiter a me ping sur discord dnas 1 semaine si j'ai oublie
