### ISSUE TITLE
Des NULL_OR_UNDEFINED_VALUE de partout

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1580]
### Description du bug.

Où sont passé les valeurs entre temps? Qu'est-ce qui a pu donner les NULL_OR_UNDEFINED_VALUE de partout?

Commandes affectées: report, profile, top, shop (et ses homologues), ping, guilddailybonus (et son homologue individuel), rarity... Bref, tout ce qui contient une valeur.

### Selon vous, quelle est l'importance de ce bug ?

😱 Extrêmement grave

### Reproduction du bug.

Faire une commande contenant une valeur.

### Captures d'écran

![IMG_20221107_043813](https://user-images.githubusercontent.com/94372084/200221841-b2971c0a-a8bc-4566-a0c4-6a21b114d072.jpg)
![IMG_20221107_043825](https://user-images.githubusercontent.com/94372084/200221846-b5d74295-2a35-4eb1-9fb9-8bda5223dc92.jpg)
![IMG_20221107_043835](https://user-images.githubusercontent.com/94372084/200221856-f95654a8-f7cc-4708-85a5-c5fe36b88a3e.jpg)

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by KirIcare** [comment]
![IMG_20221107_052958](https://user-images.githubusercontent.com/111249432/200226993-4a4f2ed9-5eac-4677-947f-8f83e535efd1.jpg)
