### ISSUE TITLE
Confusion sur la perte de temps

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1581]
### Description du bug.

Les infos sur la perte de temps diffèrent entre le report et le profil d'une minute.

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Subir une alté de perte de temps (préférablement de quelques minutes). Faire à nouveau /report, et puis /profile.

### Captures d'écran
(Note: j'ai bien lancé le /report)
![IMG_20221107_052703](https://user-images.githubusercontent.com/94372084/200226719-3c711f0c-94be-4891-b7bb-2991f2f28154.jpg)

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
Peut-être que l'arrondi utilisé n'est pas le même ? Possible de vérifier cela ?

**Comment by BastLast** [comment]
je dois aller au taf du coup je peut pas investiguer plus pr le moment mais je viens d'essayer de reproduire le bug sans succés, faut check plus en détail

**Comment by Pietagorh** [comment]
Dans profile :
 askedPlayer.effectEndDate.valueOf()  -  interaction.createdAt.valueOf()

Dans report
this.effectEndDate.valueOf()  -  Date.now();

Par contre la fonction que report utilise est une fonction globale de player, donc go l'utiliser anyway nan ?

**Comment by BastLast** [comment]
> Dans profile :
>  askedPlayer.effectEndDate.valueOf()  -  interaction.createdAt.valueOf()
> 
> Dans report
> this.effectEndDate.valueOf()  -  Date.now();
> 
> Par contre la fonction que report utilise est une fonction globale de player, donc go l'utiliser anyway nan ?

C kwa le nom de la fonction ?

**Comment by Pietagorh** [comment]
Player.effectRemainingTime()

**Comment by BastLast** [comment]
Ok go utiliser ça, je déplace dans la milestone 4.0.2.b vu que c'est super izi à fix

**Comment by BastLast** [comment]
Gg pour l'avoir vu @Nargacaura le timing devait être super précis tho

**Comment by Nargacaura** [comment]
> Gg pour l'avoir vu @Nargacaura le timing devait être super précis tho

De rien x)
Pas tant que ça, j'ai fait les 2 commandes à quelques secondes d'écart sur l'alpha à 3 moments (celui qui a été screen, celui où le report affichait 1 minute et dès la guérison de l'alté), et c'était pareil: c'était une minute de moins que ce que disait le profil.
