### ISSUE TITLE
[BUG]: Problèmes de temps

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1589]
### Description du bug.

- Le trajet entre 2 mini-events dure ~~9 minutes au lieu de 10~~ **8min45 environ** au lieu de **9min45** sur la version stable et l'alpha depuis la tentative de fix, et le tuto ne dure que 2 minutes au lieu de 3. [Corrigé pour le tuto]
- Les altérations d'état durent une minute de plus. [Merging depuis #1607]

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

- Faire /report afin d'avoir un mini-event, et un autre afin d'avoir l'état du voyage.
- Subir une altération d'état (peu importe sa durée) et regarder son profil via /profile ou faire /report.

### Captures d'écran

Cas du tuto: [Corrigé]
<img width="512" alt="Capture d’écran 2022-11-09 à 19 14 31" src="https://user-images.githubusercontent.com/94372084/200922248-7dcf3a5f-e66e-4121-8b7b-add62f60db3c.png">

Cas des altérations d'état: voir l'issue mentionnée dans la description du bug.

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Pietagorh** [comment]
Screen pour le temps entre 2 minis ?

**Comment by Nargacaura** [comment]
Les deux reports ont été fait immédiatement l'un après l'autre.
<img width="512" alt="Capture d’écran 2022-11-09 à 19 14 31" src="https://user-images.githubusercontent.com/94372084/200922653-7753b0a6-f379-4698-9c43-0519b894caff.png">

**Comment by Pietagorh** [comment]
Par rapport au tuto, j'suis quasi sûr que c'est ça
`await Maps.startTravel(player, newLink, interaction.createdAt.valueOf(), NumberChangeReason.BIG_EVENT, interaction.createdAt);` où faudrait mettre des Date.now(), parce qu'il a pu se passer 2 minutes entre les deux en soit

Par contre pour le minievent aucune idée

**Comment by BastLast** [comment]
le bug n'existe pas sur les bot bêta mais touche le bot alpha et le bot en prod @niqore  j'ai besoin de toi, je ne comprend pas pourquoi la gestion des dates serait différente dans un environnement dockerisé, on a probablement un truc qui donne une valeur avec 1 minute d'écart j'ai essayer de comprendre mais j'ai pas réussi.

**Comment by BastLast** [comment]
je pense que cela vient des changements que @romain22222  a fait sur l'utilisation de la date now au lieu de la date du message ou je sais plus quoi

**Comment by BastLast** [comment]
@Pietagorh  tu  peux t'occuper de ça ce soir ?

**Comment by Pietagorh** [comment]
J'vais voir
