### ISSUE TITLE
[BUG]: Déconnexion du Shard 0 sans raison apparente

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#1590]
### Description du bug.

[2022/11/10 14:54:54] Shard 0 disconnected from draftbot IPC

Aucune information sur le pourquoi de la déconnexion, les personnes sur la machine auront peut être plus d'information

Aucun autre shard ne s'est déocnnecté.

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

🤷 

### Captures d'écran

j'ai pas vraiment de captures à faire :doge:

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Feiryn** [comment]
Pas que le shard 0, ça vient de le faire pour le shard 2. Il faudrait faire en sorte que le shard détecte qu'il n'est plus connecté et s'auto redémarre (un process.exit et ensuite le shard manager fera le redémarrage)

**Comment by BastLast** [comment]
on est d'accord que ce bug arrive quasiment jamais ?

**Comment by BastLast** [comment]
bon j'ai pas entendu parlé de ce bug depuis des mois donc je le close en cannot reproduce
