### ISSUE TITLE
[BUG]: faim après dressage 

### ISSUE THREAD

**Issue by KirIcare** [DraftBot-A-Discord-Adventure/DraftBot#1602]
### Description du bug.

Le vétérinaire continu de donner "affamé" ou "dans x temps" même après le dressage du pet.
Il est également possible de continuer à nourrir un pet après qu'il soit dressé alors qu'un conseil spécifie que ce n'est plus nécessaire. 

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

- avoir un pet dressé (100lp/100)
- acheter le vétérinaire de la cour royale
- le nourrir (facultatif) 

### Captures d'écran

![IMG_20221111_232729](https://user-images.githubusercontent.com/111249432/201440523-4fc52de0-29a6-4663-b6c3-dc5f235350fa.jpg)

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
ceci n'est pas un bug, c'est volontaire
