### ISSUE TITLE
[BUG]: Bug envoi mp quand messages privés bloqués

### ISSUE THREAD

**Issue by ghosts-arch** [DraftBot-A-Discord-Adventure/DraftBot#1606]
### Description du bug.

```
Cannot send messages to this user
```

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

1. bloquer les dm sur le serveur draftbot
2. faire une action qui envoie un message à l'utilisateur en mp (testé avec mort, à voir avec les autres actions)
3. faire un thé

### Captures d'écran

https://cdn.discordapp.com/attachments/771370060848824350/1041142749283500083/image.png

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
dafuk ?

**Comment by BastLast** [comment]
jspr que t'es pas en train de report un message d'erreur d'une commande test mdr
