### ISSUE TITLE
[BUG]: une minute supplémentaire sur les altés 

### ISSUE THREAD

**Issue by KirIcare** [DraftBot-A-Discord-Adventure/DraftBot#1607]
### Description du bug.

Toutes les altés ont gagnés une minute supplémentaire 

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

- avoir une alté
- faire /profil ou /report

### Captures d'écran

![Screenshot_20221113-173504](https://user-images.githubusercontent.com/111249432/201533070-a5f2e683-cfcd-4ab1-acd5-9b7075d21fba.jpg)
![Screenshot_20221113-173520](https://user-images.githubusercontent.com/111249432/201533095-d6e6fd93-725e-4dfa-9906-9ac52f509c1e.jpg)
![Screenshot_20221113-173538](https://user-images.githubusercontent.com/111249432/201533105-a77fe1ec-c1d9-4e99-b19c-fa57205871cc.jpg)
![Screenshot_20221113-173544](https://user-images.githubusercontent.com/111249432/201533116-eb6a9bef-6fa7-4131-9660-2f8ced9d1af6.jpg)

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by KirIcare** [comment]
Faudrait peut être que je détermine s'il y a une vrai minute en plus ou si c'est seulement l'affichage

**Comment by Pietagorh** [comment]
99% c'est la même chose que le -1 minute sur le temps entre 2 minieventq

**Comment by BastLast** [comment]
> 99% c'est la même chose que le -1 minute sur le temps entre 2 minievents

ne pas hésiter à ping les issues dans ce genre de cas, ça faciline bcp la navigation, #1589 

Je ferme cette issue puisqu'il s'agit du même problème
