### ISSUE TITLE
Gros refactoring DraftBot 5.0

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1609]
Tâches de préparation : 

- [x] #1612
- [ ] #1492
- [x] #1432 
- [ ] #1508 
- [ ] #1507
- [ ] #1165
- [ ] #1035
- [ ] #1028
- [ ] #653
- [ ] #1504
- [x] #1621
- [ ] #1627

Tâches principales :

- [x] #1501
- [ ] #1491
- [ ] #1610
- [ ] #1059
- [ ] #1175
- [ ] #1611
- [ ] #1634

**Comment by BastLast** [comment]
@DraftBot-A-Discord-Adventure/contributors  cette issue a pour objectif de décrire toutes les étapes de refactoring nous permettant de faire évoluer Draftbot vers un model un peu moins dépendant de discord et discordjs :) 

J'ai séparé les tâches en 2 groupes : Les tâches de préparation, qui peuvent êtres faites dans un premier temps en parrallèle de l'ajout de fonctionnalités

et les tâches principales qui consistent à réaliser l'évolution en elle même et qui prendront plus de temps

**Comment by BastLast** [comment]
au final, personne a envie de faire 2 ans de refactoring avant de faire du refactoring donc on se lance direct dans draftbot 5.0 et on garde les sous taches pour les faire à l'occasion ? yolo

**Comment by Aikoo-Sama** [comment]
> au final, personne a envie de faire 2 ans de refactoring avant de faire du refactoring donc on se lance direct dans draftbot 5.0 et on garde les sous taches pour les faire à l'occasion ? yolo

J'adore bosser sur la qualité d'un code, je veux bien m'y coller

**Comment by BastLast** [comment]
> > au final, personne a envie de faire 2 ans de refactoring avant de faire du refactoring donc on se lance direct dans draftbot 5.0 et on garde les sous taches pour les faire à l'occasion ? yolo
> 
> J'adore bosser sur la qualité d'un code, je veux bien m'y coller

well, les issue dans la liste ci-dessus sont toujours ouvertes mdr fais toi plaiz on avance juste sur d'autres priorités pr le moment si tu veux être dans les contibuteurs actifs j'y suis pas fermé btw

**Comment by Aikoo-Sama** [comment]
> > > au final, personne a envie de faire 2 ans de refactoring avant de faire du refactoring donc on se lance direct dans draftbot 5.0 et on garde les sous taches pour les faire à l'occasion ? yolo
> > 
> > 
> > J'adore bosser sur la qualité d'un code, je veux bien m'y coller
> 
> well, les issue dans la liste ci-dessus sont toujours ouvertes mdr fais toi plaiz on avance juste sur d'autres priorités pr le moment si tu veux être dans les contibuteurs actifs j'y suis pas fermé btw

Vu que j'ai peur de faire nawak je bosse pas sur les trucs trop complexes, mais là dessus je peux avancer tranquillement. C'est donc toi qui cochera l'avancée quand je ferais des tâches ?

**Comment by BastLast** [comment]
cette issue n'est plus d'actualité, pas besoin de faire quoi que ce soit, après comme j'ai dit tous les trucs de cette liste ne sont pas prioritaires vu qiu'on est en train de refaire tout le code de draftbot de 0 pr la v5 ça sert pas à grand chose de l'améliorer, pr ça que je te propose de faire partie des meetings pr savoir comment aider à la v5

**Comment by Aikoo-Sama** [comment]
> cette issue n'est plus d'actualité, pas besoin de faire quoi que ce soit, après comme j'ai dit tous les trucs de cette liste ne sont pas prioritaires vu qiu'on est en train de refaire tout le code de draftbot de 0 pr la v5 ça sert pas à grand chose de l'améliorer, pr ça que je te propose de faire partie des meetings pr savoir comment aider à la v5

Okay je veux bien ^^

**Comment by BastLast** [comment]
@romain22222  possible de check si yen a d'autres ici que l'on peut close ?
