### ISSUE TITLE
Ajouter des types pour les arguments qui dépendent de constantes

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1621]
- [x] Langage
- [x] Effets
- [x] Blocking reason

**Comment by Pietagorh** [comment]
Si quelqu'un a des idées, comme ça j'le fais au passage

**Comment by BastLast** [comment]
ya aucune info dans cette issue , possible d'avoir plus d'explications ?

**Comment by BastLast** [comment]
aussi si c'est fini pourquoi il n'y a pas de pull request ?

**Comment by romain22222** [comment]
j'ai pas l'impression que c'est fini, faut voir avec pieta, mais je pense que c'est pas le cas

**Comment by BastLast** [comment]
@Pietagorh  je retrouve pas les réponses aux questions sur discord, est-ce que tu peux répondre ici ?

Est-ce que c'est fini ? et si oui, pourquoi il n'y a pas encore de pull request ?

**Comment by Pietagorh** [comment]
J'ai fini tout ce à quoi j'ai pensé, mais j'attends le merge du witch pour pouvoir faire les modifs dessus proprement

**Comment by BastLast** [comment]
Ok !
