### ISSUE TITLE
[BUG]: On ne peut pas avoir le mini-event winPersonalXP (bot de test)

### ISSUE THREAD

**Issue by Gabrielre14** [DraftBot-A-Discord-Adventure/DraftBot#1624]
### Description du bug.

Pendant une phase de tests sur le bot Alpha, j'ai essayé de recevoir le mini-event winPersonalXP avec la commande /rapport habituelle. Mais malgré un très grand nombre de mini-events, je n'ai reçu aucun mini-event de ce type...

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Faîtes /rapport...

### Captures d'écran

Inutile, sauf si vous voulez plus de 100 captures

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
Quel est la proba de ce mini event ?

**Comment by Pietagorh** [comment]
3

**Comment by Pietagorh** [comment]
Sachant que là y'a pile 100 tous minievents confondus, ça fait 3%

**Comment by BastLast** [comment]
Possible de faire un dashboard mini event sur grafana et de check quel est la répartition des différents mini events ?

**Comment by Pietagorh** [comment]
Après Gab en a fait 28 sur la dernières semaines, c'est vachement probable que ça arrive quand même 97%^28 = 42%

**Comment by BastLast** [comment]
après vérification sur grafana, il n'y a pas de bug , le mini event apparait bien. Je crois qu'il y avais un soucis où il était 33% moins probable que ce que nous indiquiont dans la documentation mais je suis quasi sûr que cela a été résolu Je laisse @niqore me reprendre si c'est faux
