### ISSUE TITLE
Améliorer le code du small event gobelet

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1627]
Ce mini event mériterait un refacto, voilà une liste non exaustive de trucs repérés : 

- [x] boucle for + break qui devraient etre remplacés par des while ou un truc récursif
- [x] ligne 84 ) 85 ????? 
![image](https://user-images.githubusercontent.com/38099970/202925000-a0088ce2-9502-4180-8ecb-50ca7808a268.png)
- [x] des extract method seraient cool das la fonction principale

**Comment by Feiryn** [comment]
Fait
