### ISSUE TITLE
add contributing guidelines and issue template

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#163]

**Comment by niqore** [comment]
Je pense qu'il faudra bien préciser les normes et les configs IDE (lf (et pas crlf je crois), tabulations, linter...)

**Comment by BastLast** [comment]
> Je pense qu'il faudra bien préciser les normes et les configs IDE (lf (et pas crlf je crois), tabulations, linter...)

je ferai la v1 et je te laisserai compléter ca te va ?

**Comment by niqore** [comment]
Ok
