### ISSUE TITLE
[BUG]: bug mission 49, mission pas lancée depuis mergagnan

### ISSUE THREAD

**Issue by ghosts-arch** [DraftBot-A-Discord-Adventure/DraftBot#1630]
### Description du bug.

cépété ! 

J'était à 1h de réussir la mission, hein merci les choix auto de destination  | X_X |, je suis arrivé à mergagnan et je me disais "chouette, youpi, j'ai hate de refaire tout le chemin en sens inverse" , je part de mergagnan et la au milieu du trajet je vois que la mission à pas été comptée et que je doit soit retourner à mergagnan soit aller à clair-de-ville puis retourner à mergagnan ... dans les deux cas, cépacool ... 

### Selon vous, quelle est l'importance de ce bug ?

Normal 

### Reproduction du bug.

1. arriver à mergagnan après expiration de la mission
2. partir de mergagnan

### Captures d'écran

[à suivre]

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by ghosts-arch** [comment]
bug bonus : la mission à expirée 1 minute avant la date annoncée dans l'embed

**Comment by ghosts-arch** [comment]
cette fois la mission à été lancée en partant de mergagnan

**Comment by BastLast** [comment]
j'aimerai des infos plus précises obtenues avec draftbot alpha

**Comment by Aikoo-Sama** [comment]
Du nouveau ? Si ce n'en est pas un, go fermer l'issue
