### ISSUE TITLE
Staff event

### ISSUE THREAD

**Issue by quenquentin** [DraftBot-A-Discord-Adventure/DraftBot#1643]
Add new members + Fix name

**Comment by BastLast** [comment]
j'ai pas compris cette issue possible d'expliquer mieux? le but c'est pas juste de se faire un reminder mais d'avoir un truc qui peut être lu par tous, aussi si tu as une idée du temps qu'il te faudrait pour le faire et de quand tu pourrais le faire ça serait super top !

**Comment by BastLast** [comment]
@quenquentin  up

**Comment by quenquentin** [comment]
Oops, well je vois ça dès que je peux (je pense ce soir si j'ai pas de problème pour réinstaller Docker qui du jour au lendemain m'a mis un gros NOPE)

**Comment by BastLast** [comment]
> Oops, well je vois ça dès que je peux (je pense ce soir si j'ai pas de problème pour réinstaller Docker qui du jour au lendemain m'a mis un gros NOPE)

Lis mon message mdr je te demande pas de le faire en urgence je veux juste savoir ce qu'il se passe

**Comment by quenquentin** [comment]
Je sais pas hein on sait jamais les up ça veut tout et rien dire mais uh pour le moment rien du coup :x

**Comment by BastLast** [comment]
> Je sais pas hein on sait jamais les up ça veut tout et rien dire mais uh pour le moment rien du coup :x

Lis le message au dessus du up ptdr

**Comment by quenquentin** [comment]
Ah oui effectivement, l'appli sur tel de GitHub qui load que le premier et dernier message, j'avais pas vu le "load 15 more items" 🤦
Bref sinon faut pas hésiter à me tag instant sur GitHub j'ai la notif, sinon pour l'issue c'est juste ajouter les nouveaux textes des TT !

**Comment by BastLast** [comment]
Ok ok pr info tu peux profiter de cette pr pr maj la description de pourfi qui en a fait la demande par contre la règle a l'avenir c'est pas plus d'une modif / personne / 3 ans, pas envie que ca devienne le zouk
