### ISSUE TITLE
[BUG]: switch avec pas de potion

### ISSUE THREAD

**Issue by KirIcare** [DraftBot-A-Discord-Adventure/DraftBot#1652]
### Description du bug.

Si on a pas de potion sur nous et que l'on switch avec une potion de notre inventaire, le bot affiche "potion x et pas de potion on était échangé" alors qu'il serait plus juste de juste écrire "potion x a été équipée". 

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

- ne pas avoir de potion sur soi
- avoir une potion dans l'inventaire
- faire /switch avec une potion 

### Captures d'écran

![IMG_20221201_115600](https://user-images.githubusercontent.com/111249432/205036025-e5599989-7bd1-4bf5-bb14-04f711f8bc19.jpg)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
j'ai l'impression que ce truc est un duplicate de #1657
