### ISSUE TITLE
[BUG]: crash report

### ISSUE THREAD

**Issue by KirIcare** [DraftBot-A-Discord-Adventure/DraftBot#1662]
### Description du bug.

J'ai effectué la commande /report ce qui a résulté en un "l'application ne répond plus"
Après ça, plus moyen de /report jusqu'au déblocage de 5min
Date: 07/12/2022
Heure: 13h37
Shard: 0 (serv officiel)
Id serveur: 429765017332613120 (toujours le serv officiel mdr) 

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Aucune idée 

### Captures d'écran

![IMG_20221207_133759](https://user-images.githubusercontent.com/111249432/206183679-ac5019c2-33a2-4c15-a522-c3dc74107216.jpg)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Pietagorh** [comment]
C'est pas lié au /report particulièrement de c'que j'ai pu voir dans d'anciens tests

**Comment by Pietagorh** [comment]
C'est au moins quand un defer crash parce que trop de trucs lag voire quand quelque chose crash parce que trop de lag tout court

**Comment by BastLast** [comment]
est-ce que c'est arrivé à d'autres gens ?parce que si c'est arrivé une seule fois il y a un mois ça part en cannot reproduce jusqu'a ce qu'on arrive à le reproduire

**Comment by Pietagorh** [comment]
C'est clairement arrivé très peu, vu qu'il faut que le bot prenne plus de 3 secondes à répondre sur un defer x)

**Comment by BastLast** [comment]
bon je close en cannot reproduce et si qqun entend à nouveau parler d'un soucis comme ça faudra rouvrir
