### ISSUE TITLE
[BUG]: Alté de l'event witch pas prise en compte

### ISSUE THREAD

**Issue by Gabrielre14** [DraftBot-A-Discord-Adventure/DraftBot#1663]
### Description du bug.

Ce n'est pas moi qui l'ai eu, mais je le signale car celui qui a découvert ce bug n'a jamais signalé de bug, donc il m'a prévenu. 
C'est très simple, il a choisi de "distiller la potion" dans le mini-event de la sorcière, a reçu une altération de 55min et une potion, mais l'alté n'a pas été prise en compte, il a pu continuer à jouer comme si elle n'existait pas. 

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Faire des /rapport pour avoir (ou forcer) le mini-event witch, et espérer avoir l'issue "distiller la potion". La choisir. Je ne sais pas si c'est valable pour d'autres actions.

### Captures d'écran

![image](https://user-images.githubusercontent.com/97915848/206194215-b341d35b-5dc9-4d6f-909e-53b2ad888742.png)
![image](https://user-images.githubusercontent.com/97915848/206194231-29941446-5123-4550-accd-7751bed11fc5.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 2

**Comment by Pietagorh** [comment]
Y'avait des gens qui avaient fait des recherches plus en détail sur ça nan ?

**Comment by Nargacaura** [comment]
Y'avait eu des tests sur ce bug, mais au vu de sa nature aléatoire (vu que des fois, l'alté est donnée, des fois non), c'était assez difficile de pointer sa source correctement. Quelque chose m'avait dit que ça pointait des fois sur la fonction giveEffect de la classe mère au lieu de celle concernée, mais ça doit certainement être une mauvaise piste...

**Comment by BastLast** [comment]
c'est pas une mauvais piste imo
