### ISSUE TITLE
[BUG]: pas de notification à la fin du trajet

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#1673]
### Description du bug.

Je venais de report un mini-event skiptime de 40min enchaîné à un second report pour vérifier le temps qu'il me restait à parcourir mais suis tombée sur mon event, or je n'avais pas reçu de notification confirmant mon arrivée alors même que je venais de paramétrer le DM notification

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

- Arriver à la fin d'un trajet de manière classique
- Arriver après la consommation d'une potion
- Arriver après un mini event skiptime

### Captures d'écran

![0C56FE65-222F-4B3C-AA52-84E64D4D0615](https://user-images.githubusercontent.com/80409766/209410969-e42d4109-653a-4dd2-8cf4-c058a65f6564.jpeg)
On constate l'absence de 1 de notification en haut à gauche

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
trajet débuté avant la maj ?

**Comment by Thesmokingllama** [comment]
> trajet débuté avant la maj ?

Ah oui y a probablement ça qui peut jouer

**Comment by Thesmokingllama** [comment]
De nouveau pas de notif post màj et après un time skip

**Comment by voltou91** [comment]
C normal étant donné qu'on vérifie chaque minute si t'es arrivé dans la dernière minute donc si tu dépasse le temps grâce à ta popo, t'as pas de notif, cependant je pense ce serait bien de verif si t'es arrivé après avoir bu une potion de temps.
