### ISSUE TITLE
[BUG]: je reçoit tous les dm en double

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1683]
### Description du bug.

tous les messages du bot me sont envoyés en double

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

envoyer un mp au bot

### Captures d'écran

![Uploading image.png…]()

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by romain22222** [comment]
nice image :doge:

**Comment by BastLast** [comment]
Pg on comprend qd mm

**Comment by quenquentin** [comment]
Y'a pas un bug lié aux notifs qui fait ça de base déjà ? A voir si c'est pas lié poke @voltou91
