### ISSUE TITLE
[BUG]: Duplication des notifications

### ISSUE THREAD

**Issue by voltou91** [DraftBot-A-Discord-Adventure/DraftBot#1690]
### Description du bug.

Quelques fois on reçoit plusieurs notifications.
(Dû aux shards)

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Avoir les notifications d'activées
Recevoir une notification

### Captures d'écran

![image](https://user-images.githubusercontent.com/62652451/209869192-558b89d6-d90b-4bd1-93da-2c5264e8b961.png)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
du coup c'est terminé ?

**Comment by BastLast** [comment]
on peut close cette issue ?

**Comment by voltou91** [comment]
Nop on peut pas, j'ai vrmt pas eu le temps de trouver une solution à ce problème. Après le 8 janvier je serais dispo.

**Comment by BastLast** [comment]
Te stress pas, je décale d'une milestone ya rien de gravissime
