### ISSUE TITLE
[BUG]: la stat de vitesse du vétéran chevronné est mal calculée

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#1703]
### Description du bug.

...

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

se mrettre niveau 111
prendre vétéran chevro

### Captures d'écran

...

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
après étude, c'est juste que le poing et l'item "pas de bouclier" ont 1 point de stat de base
