### ISSUE TITLE
[BUG]: Mission 10 Remise d'altération d'état

### ISSUE THREAD

**Issue by Jeremy-Bussy** [DraftBot-A-Discord-Adventure/DraftBot#1706]
### Description du bug.

La mission de remise d'altération d'état ne s'effectue pas si l'altération d'état à été obtenue avant la mission.

### Selon vous, quelle est l'importance de ce bug ?

Mineur

### Reproduction du bug.

1. Être à la mission 9 (boire une potion)
2. Subir une alteration d'état, dans mon cas un 'Gravement blessé' (maladroit avec l'ouvrier)
3. Boire un potion, dans mon cas 'Soupe à l'oignon' achetée au shop pendant l'altération d'état
4. Mission 9 complétée, Mission 10 lancée (Se remettre d'une altération d'état)
5. Attendre la remise d'altération d'état (12h c'est long quand même)
6. Mission non complétée

### Captures d'écran
Etat actuel : 
![image](https://user-images.githubusercontent.com/94181818/210757260-f9abd712-7d96-47c5-a7ae-3cca73f51bae.png)
![image](https://user-images.githubusercontent.com/94181818/210755756-56d3a60f-3278-4ef7-8c5e-7af3089d09d6.png)
Déroulé du bug :
![image](https://user-images.githubusercontent.com/94181818/210755987-2a13e07a-60f0-4380-aaf0-eb865b4fbfac.png)
![image](https://user-images.githubusercontent.com/94181818/210756194-f3736d14-e926-47d9-8848-9241e6a99c34.png)
![image](https://user-images.githubusercontent.com/94181818/210755825-be0c7e56-26ed-4a62-9b9d-fdd246fa91c3.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 2

**Comment by BastLast** [comment]
Je me permet de reajuster la gravité du bug en mineur.

**Comment by Jeremy-Bussy** [comment]
Je savais pas dans quelle catégorie le mettre et comme c'est sur l'avancement de la mission principale ¯\_(ツ)_/¯

**Comment by BastLast** [comment]
Pas de soucis tkt

**Comment by romain22222** [comment]
@Jeremy-Bussy Je me permet de te poser une question cruciale : est ce que t'as fait un rapport entre le moment où ton altération s'est soignée et le gros rapport SANS tomber sur un mini event (en gros, t'as fait /report et t'as eu un résumé d'ou t'en étais dans l'aventure) ?

**Comment by romain22222** [comment]
Mon hypothèse : 

en gros, le check de se remettre d'une altération n'est fait QU APRES avoir fait le check de si on a un mini event et le check du big event
donc si on avait une alté et qu'on a pas fait de report blanc entre la fin de l'alté et un mini event / gros event, la mission se valide pas

**Comment by Jeremy-Bussy** [comment]
Ouais j'avais fait un report pour resumer l'avancement
![image](https://user-images.githubusercontent.com/94181818/211328961-7e30b222-2dbe-41b5-ba04-e876e6b213e6.png)
(et d'autres reports qui mènent à des mini-events)

Mon hypothèse est que j'ai eu l'altération d'état avant d'obtenir la mission, et que draftBot, pour cette mission, check la remise d'une altération obtenue lors de la mission.

**Comment by BastLast** [comment]
Nope jai check le code et la théorie de romain est valide, dans ton rapport vide tu as heal ton alte et la mission a jamais été check

Et quand tu as eu le big event ca a été check mais tu etais heal depuis le /rapport d'avant.

Bref izi fix je m'en occupe ce soir

**Comment by Pietagorh** [comment]
Je vous dit que c'est pas si simple
Le check de l'alté passe mais ça update pas la mission j'sais pas pourquoi
