### ISSUE TITLE
[BUG]: La protection, une fois finie et la def au plus bas via une mutation, remet la défense à sa valeur de base

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1715]
### Description du bug.

Dans un combat fantassin contre mage, utiliser une mutation lors d'une attaque chargée en pleine protection réduit met la défense à sa stat la plus faible. Mais, une fois la protection terminée et l'attaque chargée finie, la défense revient à sa valeur initiale...

### Selon vous, quelle est l'importance de ce bug ?

mineur

### Reproduction du bug.

Lancer un combat fantassin vs. mage. Faire une protection, et une attaque chargée juste après. Le mage doit faire une mutation *à ce moment-là*. Observer le boost de défense inattendu.

### Captures d'écran

<img width="779" alt="Capture d’écran 2023-01-06 à 23 23 44" src="https://user-images.githubusercontent.com/94372084/211110186-b0854429-04a3-4321-96e8-e5e8e8f72f8f.png">

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
je ferme l'issue car fix via la suppression de l'attaque mutation dans le commit ci-dessus
