### ISSUE TITLE
[BUG]: Valeur d'expérience non réinitialisée après un gain de niveau.

### ISSUE THREAD

**Issue by Syandre** [DraftBot-A-Discord-Adventure/DraftBot#1721]
### Description du bug.

Après une prise de niveau (105 vers 106), la valeur d'expérience n'est pas retombée à zéro et semble être restée à la valeur maximum requise du niveau précédent (ou bien à vérifier).

Date et heure du rapport / gain de niveau : 8 janvier 2023 à 05h48.
Lieu / event : Lac mirage, livraison du colis.

Détails supplémentaires :
- Une mission quotidienne et une mission secondaire validées en même temps.
- Le montant d'expérience n'a pas été vérifié sur le moment mais remarqué un peu plus tard après un autre rapport vers 12h30.

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

1 - Aucune idée.
2 - Essayer de passer de 105 à 106 (ou tout autre niveau ?) en terminant des missions en même temps ?

### Captures d'écran

![rapport_gain_de_niveau](https://user-images.githubusercontent.com/100872404/211206342-e6225b9b-33ef-41a1-ad8e-759e51556e80.jpg)
![montant_experience_apres_niveau](https://user-images.githubusercontent.com/100872404/211206454-ab90c167-f73b-4d99-82fa-476710c29bec.jpg)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Nargacaura** [comment]
J'ai pu reproduire le bug avec d'autres missions sur l'alpha:
![Capture d’écran 2023-01-08 à 19 04 01](https://user-images.githubusercontent.com/94372084/211211718-4b3671f9-9875-465c-8e14-7a6b0044d9ff.png)

Quelque chose me dit qu'il y a un conflit entre les 2 embeds des missions au niveau de l'XP: l'un ayant déjà fait monter de niveau, l'autre checkerait avec les mêmes données qu'avant le level up, et donc rajoute non seulement le bonus, mais aussi le montant initial d'avant la complétion des missions.

**Comment by BastLast** [comment]
passé 1h + dessus avec pagos, je ne comprend pas ce truc j'ai clairmenet pas envie de bosser dessus.

c'est un peu le bazar la manière dont c'est fait, ya des players. save dans tous les sens on comprend pas pourquoi ils sont là... idem pr les get or register, ya rien de défini...

globalement ça mériterait un gros cleanup tout ça, mais perso  I AM OUT.

@romain22222  si tu as le temps de te pencher dessus je pense que tu auras plus le courage que moi.

**Comment by BastLast** [comment]
vu que le bug est quasiment impossible à reproduire ingame, je repousse de milestone.

**Comment by Nargacaura** [comment]
Pour reproduire le bug, une méthode serait de:
- se donner la mission earnMoney, quelque soit sa difficulté;
- se donner une autre mission (l'exemple qui va suivre utilisera la mission travelHours au niveau difficile);
- se donner de l'expérience (environ max-5, minimum max-50 :star:) après avoir vérifié son profil;
- dans l'exemple du travelHours, voyager de la Dune à la vallée des Rois et avancer son voyage de 10h;
- se donner max-1 💰; 
- faire /profile et /missions pour vérifier que tout est bon;
- exécuter la commande /report et faire l'event;
- refaire /profile.

**Comment by voltou91** [comment]
Ok j'apporte plus de précision sur le bug, je pense que c'est n'importe quelle mission "earnMoney" qui fait bug le truc (du moins j'ai l'impression). Je pense que c'est dû à l'espèce de boucle que fait les missions. updatePlayerStats -> player.addMoney -> MissionsController.update -> MissionsController.checkCompletedMissions -> updatePlayerStats -> player.add... etc, etc, etc
Et je pense que le bug se cache ici.

**Comment by BastLast** [comment]
> Ok j'apporte plus de précision sur le bug, je pense que c'est n'importe quelle mission "earnMoney" qui fait bug le truc (du moins j'ai l'impression). Je pense que c'est dû à l'espèce de boucle que fait les missions. updatePlayerStats -> player.addMoney -> MissionsController.update -> MissionsController.checkCompletedMissions -> updatePlayerStats -> player.add... etc, etc, etc
> Et je pense que le bug se cache ici.

Cependant ya la meme dans le add xp et la ya pas de soucis

**Comment by BastLast** [comment]
@Nargacaura à priori @voltou91  a fix le truc mais si tu as le temps de faire un passage dessus sur draftbot alpha avant de fermer l'issue ça serait top !

**Comment by Nargacaura** [comment]
C'est testé et approuvé :thumbsup:

**Comment by Nargacaura** [comment]
Je retire ce que j'ai dit en fait, ça a influé sur l'XP sur d'autres missions en faisant monter 2 fois de niveau x)
![Screenshot_20230113-071017.png](https://user-images.githubusercontent.com/94372084/212249931-d727cda9-ad06-4626-be36-2ab71322006f.png)

**Comment by voltou91** [comment]
Ça a juste dupliqué le message de lvl up, t'es pas monté deux fois.

**Comment by Nargacaura** [comment]
Fais le calcul: il me restait 6 points avant la montée de niveau. J'ai gagné 150 avec l'issue de l'event + 50 de la mission travelHours + 75 de la mission earnXP. Je devrais avoir 269 XP (150+75+50-6). Sauf que je n'ai que 194 après avoir fait l'event x)

**Comment by voltou91** [comment]
C'est comme si la mission a 75 d'exp n'avait pas compté, si tu enlève 75 on a bien ton nombre d'exp, et ça expliquerai pourquoi y a eu une double notif de lvl up, car il a pas save les +75 d'exp et le lvl up.

**Comment by BastLast** [comment]
ok c'est mergé sur develop @Nargacaura  si tu as le temps de refaire une session de test ça serait tooooop :)

**Comment by Nargacaura** [comment]
Ça m'a l'air bon, par contre à une occasion, y'a eu duplication de missions earnMoney validées (et enregistrées!) alors que j'en n'avais qu'une...
![Screenshot_20230115-051646.png](https://user-images.githubusercontent.com/94372084/212522844-39c97248-b197-459f-a5d9-54031f726e2d.png)

Peut-être que c'est un différent bug, dunno. (J'ai pas testé ce bug-là en détail vu que je testais le bugfix à la base, tho) ┐⁠(⁠‘⁠～⁠`⁠;⁠)⁠┌

**Comment by BastLast** [comment]
Je pense que c'est un bug causé par le fix donc je laisse l'issue ouverte le temps que ça soit corrigé

**Comment by voltou91** [comment]
Moi je pense que c'est parce que j'ai fix la partie player en enlevant le GetOrRegister mais on fait la même chose sur le mission controler (on get les missions) et du coup faudrait retourner le mission controler comme avec le Player, quasi sûr que c ça le bug.

**Comment by BastLast** [comment]
semble fix (enfin) , à réouvrir si on trouve un truc mdr
