### ISSUE TITLE
[BUG]: Non formatage de la commande respawn dans les mp

### ISSUE THREAD

**Issue by voltou91** [DraftBot-A-Discord-Adventure/DraftBot#1738]
### Description du bug.

Si on envoie un mp au bot et qu'on clique sur une réac, il nous envoie un embed avec la commande respawn dedans, seulement elle n'est pas formatée.

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Envoyer un mp au bot
cliquer sur une des réacs

### Captures d'écran

<img width="420" alt="image" src="https://user-images.githubusercontent.com/62652451/212070987-e9b2ac17-3a1e-4efc-828b-ab60ba28243c.png">

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
@Pietagorh même pr les typos c'est censé être testé les trucs avant d'être push sur github...

**Comment by Pietagorh** [comment]
Ah p'tain j'ai oublié sur le help mp
J'ai check que pour quand tu meurs direct
