### ISSUE TITLE
[BUG]: Gain d'xp (toujours) incorrect avec un gain d'item

### ISSUE THREAD

**Issue by Gabrielre14** [DraftBot-A-Discord-Adventure/DraftBot#1742]
### Description du bug.

C'est le même bug que l'issue #1674 (qui est sensée être corrigée) mais on m'a dit d'ouvrir une nouvelle issue^^
Lorsque l'on gagne un objet lors d'un event, on ne gagne pas les 300 d'xp qui sont sensés venir avec. On ne gagne que 150 au lieu de 450. Ce bug n'a donc pas été fix par la maj. 
Cependant, les points d'xp sont maintenant correctement distribués lors d'une simple perte de temps (+25). 
Ce bug a été réparé, mais pas celui du gain d'item. 

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Faites un évent puis un choix où vous pouvez gagner un objet. Vérifiez le gain d'xp associé au gain d'item, il est de 150 au lieu de 450. 
Par exemple : le "ne pas répondre" de l'évènement du suicidaire (44)

### Captures d'écran

Voici le gain incorrect d'xp après un gain d'item : 
![image](https://user-images.githubusercontent.com/97915848/212357656-b6b8a75d-248b-4cf5-be3d-bb8819532979.png)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Pietagorh** [comment]
Ça vient du fait qu'on check outcome.randomItem === true, alors que maintenant c'est un objet qui contient différents paramètres
