### ISSUE TITLE
[BUG]: Mauvaise pp sur la notif du gd

### ISSUE THREAD

**Issue by voltou91** [DraftBot-A-Discord-Adventure/DraftBot#1754]
### Description du bug.

Ca affiche la pp de la première personne qui reçoit la notif.

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Avoir une guilde de plusieurs joueurs
Avoir les notifs d'activées (en mp ?)
Faire un gd

### Captures d'écran

![image](https://user-images.githubusercontent.com/62652451/212915598-f39734c1-b900-4098-9cbc-5a366c2ed656.png)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Bombafox** [comment]
![Screenshot_20230324_120303](https://user-images.githubusercontent.com/96150225/227748428-5d738c9f-6d98-4e2f-9dab-10e10cb7e180.jpg)

J'ai encore eu le bug (1 fois) de mon côté le 24/03/23 a 3h18

**Comment by BastLast** [comment]
@voltou91  on a pas mal de rapport comme quoi ya bcp de bugs avec les notifs, mais je crois que tu es pas trop dispo en ce moment. On prévoit de sortir la 4.3.3 en début de semaine pro (voir avant peut etre) donc je repousse dans une future milestone ? ou tu as le temps de regarder ce qu'il se passe ?

@Feiryn  tu as peut etre le temps également ?

**Comment by voltou91** [comment]
Bah vrmt lundi, mardi et mercredi prochain c'est mes 3 plus grand contrôle de fin d'année. Faut pas que je foire, mais après oui. Donc après le 5 avril je regarderai.

**Comment by BastLast** [comment]
> Bah vrmt lundi, mardi et mercredi prochain c'est mes 3 plus grand contrôle de fin d'année. Faut pas que je foire, mais après oui. Donc après le 5 avril je regarderai.

Ok !

**Comment by BastLast** [comment]
je déplace ceci en 4.4.1, c'est un peu génant comme bug mais le pve est la prio là

**Comment by voltou91** [comment]
C'est cool cette issue mais depuis que tu l'a réouverte, c'est que des bugs de notifs d'arrivée et non du gd. Quelqu'un sait si le bug du gd est encore présent ? Si c'est pas le cas normalement le bug devrait être réglé grâce à #2180

**Comment by BastLast** [comment]
ok je referme alors

**Comment by BastLast** [comment]
en créer une autre si ça revient
