### ISSUE TITLE
Translate everything in english

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#176]
Some admin texts are in french (e.g. DMs)

**Comment by BastLast** [comment]
pas urgent imo

**Comment by quenquentin** [comment]
--> Resetbadge traduction à faire sinon crash du bot lors de l'exécution de la commande

**Comment by BastLast** [comment]
Je suppose que tu bosses sur ton fork ? Tu as le lien de la branche ?

**Comment by BastLast** [comment]
Apparament c'est fini x)
