### ISSUE TITLE
Items pour la 4.2.2

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1761]
Kiri :
Arme :feather: Aile gauche d'Icare | :star: Épique
Bouclier :feather: Aile droite d'Icare | :star: Épique
(Petit bonus de vitesse sur les deux)

**Comment by BastLast** [comment]
items ajoutés, j'ai également fait un peu d'équilibrage : 

Tournevis sonique : Vitesse augmentée
Sceptre à 100 sorts : Attaque augmentée
Jurisprudence : Défense augmentée
