### ISSUE TITLE
[BUG]: Commandes /report et /missions mal formatées dans le tuto

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1772]
### Description du bug.

Tout est dans le titre. Dans le tuto, la commande /report est affichée en tant que {command:report}. Pareil pour /missions, formaté comme {command:missions}.

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Commencer le tuto. Choisir une réaction (ou pas, au choix).

### Captures d'écran

<img width="1173" alt="Capture d’écran 2023-02-04 à 19 09 41" src="https://user-images.githubusercontent.com/94372084/216782889-70b48fb9-1841-4600-99be-f3d5fe09a1a5.png">
<img width="1013" alt="Capture d’écran 2023-02-04 à 19 17 14" src="https://user-images.githubusercontent.com/94372084/216783123-290e9aa2-0365-4160-86d9-896b52fe1184.png">

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
ce bug a été corrigé #1729 j'ai plus le commit exact
