### ISSUE TITLE
Améliorer les logs pour les fights

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1780]
Améliorer les logs des combats

- [x] ajouter dans les fightaction launched, la classe du joueur qui a lancé l'attaque
- [x] prendre en compte la glory dans les logs

**Comment by Feiryn** [comment]
J'avais fait le 2ème points dans la table fights_results mais le problème c'est que ça ne permet pas de suivre la valeur dans le temps facilement et ça fait de la duplication de code pour le calcul de l'élo, donc je propose plutôt de créer une nouvelle table avec le suivi de la valeur totale (comme l'argent, les scores...) avec comme colonnes playerId, value, raison, fightId (référence au fight qui a changé la valeur si besoin, car une commande test ou un reset de la semaine ça change la valeur aussi), date

Pour le 1er point je préfererai trouver une requete viable plutôt car sinon va falloir faire une migration de fou et il y aura de la duplication de valeur

**Comment by BastLast** [comment]
Ok pour le 2

Pour le 1 je vois pas d'autre solution la roquette j'ai vraiment passé une ou deux journées dessus enfin j'ai vraiment passé beaucoup de temps dessus et en fait c'est probablement possible d'en faire une mais ce sera impossible d'avoir des perf correctes sur grafana

Après je pense pas qu'on ait besoin de faire une migration je pense que on peut juste dire qu'on s'en fout des données précédentes et les enregistrer à partir de maintenant
