### ISSUE TITLE
[BUG]: NaN% sur le botFacts

### ISSUE THREAD

**Issue by TomEvans66** [DraftBot-A-Discord-Adventure/DraftBot#1784]
### Description du bug.

Voir image...

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

message envoyé via le bot

### Captures d'écran

![image](https://user-images.githubusercontent.com/122872130/216832657-65091aac-9c71-4233-9c75-be8730639887.png)

### Sur quel shard avez vous rencontré le bug ?

Instance perso

**Comment by BastLast** [comment]
yo c'est sur une instance du bot ? ou sur le bot officiel ?

**Comment by BastLast** [comment]
du coup je pense que c'est juste parce qu'il manque des données dans ta base de données, je me permet de déplacer cette issue à un très lointain futur vu que ça ne nous touchera jamais.

**Comment by BastLast** [comment]
(si qqun a le courage de se pencher là desus, (déjà go check si ya pas un truc plus urgent) ne pas hésiter à balancer plus d'infos :)

**Comment by BastLast** [comment]
Etant donné l'impact de ce bug, je pense que nous n'allons pas dépenser de budget de dévelopment dessus, je ferme donc cette issue
