### ISSUE TITLE
Améliorer la migration vers la gloire

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1785]
utiliser le lvl du joueur pour calculer sa gloire :

Si un joueur a un lvl < 8 alors : 0

Sinon : 800 / (120 - 8) * (lvl - 8)

**Comment by romain22222** [comment]
on est bien d'accord que la gloire c'est le système d'élo que tu veux ajouter ?

**Comment by BastLast** [comment]
Oui
