### ISSUE TITLE
[BUG]: temps entre rapports pas respecté 

### ISSUE THREAD

**Issue by KirIcare** [DraftBot-A-Discord-Adventure/DraftBot#1792]
### Description du bug.

Il semblerait que si on est assez rapide (rien d'extraordinaire) on tombe sur ce bug.
Après avoir guéri une altération (via le shop) après un évent, le temps affiché sur le prochain rapport excède les 9min45. 

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

- avoir un évent
- prendre une alté en sorti
- la supprimer à l'aide du shop
- faire /report
- (exécuter le tout relativement vite) 

### Captures d'écran

![IMG_0513](https://user-images.githubusercontent.com/111249432/219495549-12a8c31b-00e6-464d-823a-5459d4bdb5fb.png)
![IMG_20230216_224832](https://user-images.githubusercontent.com/111249432/219495606-f75dcdde-b81e-4725-abce-8150e136cc60.jpg)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Pietagorh** [comment]
De mémoire, le fait que t'aies un truc pas pile le temps normal en guérissant d'une alté c'était intended

**Comment by KirIcare** [comment]
Ah ? Jamais entendu parler xD

**Comment by BastLast** [comment]
est-ce que quelqu'un peut faire un peu d'analyse là dessus ?

**Comment by BastLast** [comment]
bon, pas plus d'infos, je ferme cette issue, à rouvrir quand yaura plus d'infos
