### ISSUE TITLE
[BUG]: niveau des guildes de la commande gtop du bot Dratbot Assisstant

### ISSUE THREAD

**Issue by Mura667** [DraftBot-A-Discord-Adventure/DraftBot#1793]
### Description du bug.

j’ai voulu regardé le classement des guildes en utilisant la commande gtop du bot Draftbot Assisstant et j’ai remarqué que certains niveaux de guilde sont au-dessus de 100.

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

- faire la commande gtop du bot Draftbot assisstant

### Captures d'écran

![0E6DA713-944C-42D5-A818-D80ADCCBD543](https://user-images.githubusercontent.com/80298797/219502857-1a3c6a98-f7d0-49b1-9f2f-982a252b81e7.jpeg)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

**Comment by BastLast** [comment]
Bonjour, DraftBot assistant n'est pas une fonctionnalité de DraftBot, il n'est pas développé par nous ni supporté ni encouragé. Nous n'offrons pas de support pour ce bot et nous ne sommes pas en capacité de résoudre les bugs de ce bot.
