### ISSUE TITLE
[BUG]: Récompenses de missions

### ISSUE THREAD

**Issue by Procion06** [DraftBot-A-Discord-Adventure/DraftBot#1805]
### Description du bug.

cela fait plusieurs fois que je constate que les points des récompenses de missions (quotidienne + secondaire) ne sont pas comptabilisés

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

je valide des missions mais mon classement en points ne bouge pas

### Captures d'écran

soirée du 2 mars : mission quotidienne + secondaire
![Screenshot_3](https://user-images.githubusercontent.com/107723160/222897519-c38aa4f4-3404-49dd-99f7-2ba94f64cedb.png)
![Screenshot_5](https://user-images.githubusercontent.com/107723160/222897538-dc4acf15-9524-4439-bd0f-8b9465da5a2d.png)
![Screenshot_6](https://user-images.githubusercontent.com/107723160/222897547-bb0c225e-8108-4198-8408-b51f38b991d8.png)

ce midi : mission quotidienne
![Screenshot_7](https://user-images.githubusercontent.com/107723160/222897591-ffcb6a3f-adc8-4e99-afd3-a737b28052a3.png)
![Screenshot_8](https://user-images.githubusercontent.com/107723160/222897602-e1f81cc4-1b14-46dc-ae18-fce228492ec5.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

**Comment by Nargacaura** [comment]
Ton problème est probablement lié à #1790.

**Comment by BastLast** [comment]
Hello possible de fusionner les deux issues en une seule ( mentionner moi pour fermer celle qui est abandonnée) et go essayer de récolter un max d'informations sur draftbot alpha @DraftBot-A-Discord-Adventure/testers

**Comment by Procion06** [comment]
de nouveau la mission des 15 rapports qui me passe sous le nez
si je dois commencer à vérifier le compteur avant et après chaque mission et prendre des screens à chaque fois ça va vite devenir compliqué
...

![Screenshot_8](https://user-images.githubusercontent.com/107723160/223283156-03310f26-2d77-4612-8a40-45ec46e31618.png)
![Screenshot_3](https://user-images.githubusercontent.com/107723160/223283161-0c3f1bad-7b38-4b44-becb-dcfe04655c18.png)
![Screenshot_9](https://user-images.githubusercontent.com/107723160/223283165-74d7b8ed-407c-40b0-820b-b70c61a453bf.png)
![Screenshot_10](https://user-images.githubusercontent.com/107723160/223283169-e7c947c4-f073-4dff-8e4c-ffb5b8232876.png)
![Screenshot_7](https://user-images.githubusercontent.com/107723160/223283170-b0f2d39e-ce74-4bd9-a236-560743fd4a91.png)

**Comment by Procion06** [comment]
encore une mission qui ne me donne pas de points 
c'est la 3ème aujourd'hui...


![Screenshot_11](https://user-images.githubusercontent.com/107723160/223524677-842bde76-cb67-4e16-9845-95b78cf69576.png)
![Screenshot_3](https://user-images.githubusercontent.com/107723160/223524688-da0d869d-f1e5-461c-a968-7656a133ac80.png)

**Comment by Procion06** [comment]
Mission "faire 30 rapports" > aucun point comptabilisé

**Comment by BastLast** [comment]
commen mentionné plus haut, cette issue est aussi un doublon
