### ISSUE TITLE
Système de maintenance

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#1807]
Pour éviter de couper le bot pour mettre en maintenance et potentiellement couper des commandes en cours

- [x] Mettre une commande /maintenance pour mettre en maintenance, avec un argument pour save la config
- [x] Faire un script permettant de remplacer watchtower
- [x] Faire un point d'entrée retournant le nombre de joueurs bloqués (pour savoir si on peut restart le bot ou non)
- [x] Mettre à jour status.draftbot.com automatiquement pendant ces maintenances
- [x] Autoriser le bypass de la maintenance pour la commande /maintenance

**Comment by BastLast** [comment]
dans l'objectif de surfer sur la hype des fights asap, je me demande si ca serait pas pertinent de repousser cette issue dans la petite update suivante ?

**Comment by BastLast** [comment]
ça nous permettrai de sortir la 4.3.1 dès ce soir
