### ISSUE TITLE
[BUG]: Mission secondaire "Faire 15 rapports"

### ISSUE THREAD

**Issue by Procion06** [DraftBot-A-Discord-Adventure/DraftBot#1808]
### Description du bug.

J'ouvre un post spécifique concernant ce bug car c'est la 3ème fois que je le rencontre en seulement quelques jours dont 2 fois aujourd'hui ! (cf issue #1805 mise à jour cette nuit)

la quête se valide bien mais je ne reçois pas les points correspondants

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

obtenir la mission secondaire mentionnée
faire 15 rapports...

### Captures d'écran

![Screenshot_5](https://user-images.githubusercontent.com/107723160/223419615-e0196223-a777-4c96-bccb-bb7e84be1a78.png)
![Screenshot_6](https://user-images.githubusercontent.com/107723160/223419643-5f241bb9-3c12-4817-86d6-87947cad9523.png)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
Si c'est le même bug que l'autre, ça sert a rien d'ouvrir 2 issues...
