### ISSUE TITLE
[BUG]:  error when creating a player through admin command

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1813]
### Description du bug.

après avoir fait la commande donbadge le joueur est créé mais n'a pas de destination

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

faire donbadge à un mec qui a jamais intéragis avec draftbot
faire profile de cette personne
le profil s'affiche normalement mais  il y a une erreur dans la console

### Captures d'écran

![image](https://user-images.githubusercontent.com/38099970/224122702-51eba6d2-4ed4-4367-9a89-ea985e6cfb06.png)

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by voltou91** [comment]
la même erreur que le skiptuto  ?

**Comment by BastLast** [comment]
> la même erreur que le skiptuto  ?

Oui
