### ISSUE TITLE
[BUG]bot crash when a player in tutorial use dailybonus

### ISSUE THREAD

**Issue by Kyusakick** [DraftBot-A-Discord-Adventure/DraftBot#1814]

**Comment by Kyusakick** [comment]
Update: le même souci a l'air de se produire avec un joueur ayant commencé l'aventure mais ayant son inventaire vide

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/225111616-4b0776b3-af03-47c0-b4e0-44afd0d40c54.png)
impossible de reproduire le bug avec un inventaire vide, je creuse.

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/225111811-ab83c524-51a3-48a3-94a6-c27168b2b893.png)
idem avant la création du joueur...

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/225112031-bd386df1-6dd3-46b9-8620-795053b6da86.png)
aha j'ai bien le soucis après avoir fait le premier rapport
