### ISSUE TITLE
gérer l'équilibrage des missions de combat vis à vis de la maj

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1817]
- [x] Supprimer toutes les missions secondaire et missions du jour "faire X combat" sauf : Faire 3 / 5 combat amicaux
- [x] Ajouter une mission de campagneavoir une certaine ligue
- [x] Étudier la campagne pour voir les missions de combat qu'il y a déjà et les ajuster si besoin

**Comment by BastLast** [comment]
@voltou91  chaud pour faire le 3 ème point ?

**Comment by voltou91** [comment]
Yup
