### ISSUE TITLE
Remplacer le passe mission par un remplace mission

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1819]
Le passe mission devient un "remplace-mission", le prix est le même mais il suprime une mission secondaire du joueur (sans donner les récompenses) et donne une nouvelle mission secondaire aléatoire à la place. 

_Originally posted by @KirIcare in https://github.com/DraftBot-A-Discord-Adventure/DraftBot/discussions/1816_

**Comment by BastLast** [comment]
étant donné que cette issue est petite et que @voltou91  n'a pas grand chose à faire et est disponible, je la met dans la milestone de la 4.3.0, @voltou91  tu sais si tu peux faire ça ce soir ?

**Comment by voltou91** [comment]
Je fait ça ce soir

**Comment by KirIcare** [comment]
Juste detail mais le remplacement est entièrement random ou la difficulté de la nouvelle mission sera identique à la mission remplacée ?

**Comment by BastLast** [comment]
La difficulté est basé sur le level du joueur donc je pense que l'idée c juqte de regenerer une mission toute neuve
