### ISSUE TITLE
[BUG]: PV "infinis" fight

### ISSUE THREAD

**Issue by Akutana** [DraftBot-A-Discord-Adventure/DraftBot#1820]
### Description du bug.

On était en combat, en face il ne lui restait qu'un pv donc j'aurais dû le battre sauf qu'il ne se prenait plus aucun dégât (alors que d'après le bot je lui mettais dans les 300). Les screens montrent chacun l'état du jeu après une attaque que je lui ai portée à 3 moments différents. J'ai fait plusieurs fois le test et ça semble pouvoir durer indéfiniment.

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Je connais pas les conditions précises, en tout cas je spammais l'attaque intense en canonnier.

### Captures d'écran

![infinitepv1](https://user-images.githubusercontent.com/106627995/225414264-3fb69207-d6d2-4382-84cf-283acfd41c01.png)
![infinitepv2](https://user-images.githubusercontent.com/106627995/225414288-dc42d5b8-ef83-4266-ab31-cd2417cd807d.png)
![infinitepv3](https://user-images.githubusercontent.com/106627995/225414303-6d4a1be7-fb8e-4735-8996-c44ad3a4ba1c.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 1

**Comment by Nargacaura** [comment]
Pas un bug: **l'intense n'achève pas l'adversaire**.
