### ISSUE TITLE
Proposer des moyens d'accèlérer la régénération de l'énergie de combat.

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1845]
Suite à la mise à jour des combats classés, beaucoup de gens veulent combattre mais la régénération de l'énergie est un peu trop lente. Je pense que cela représente une opportunité pour rajouter des petites mécaniques sympa et mettre en lumière des fonctionnalités alternatives du bot #go forcer la divesité du gameplay :) 
Voilà une liste d'actions que je propose.

- [x] Ajouter des potions d'énergie (qui se consomment comme des potions de vie)
- [x] Ajouter des items daily de gain d'énergie.
- [x] Ajouter le fait que l'énergie soit loggée afin de garder des traces des utilisations de mécaniques la régénérant.
- [x] Ajouter des gains d'énergie comme récompense supplémentaire dans certains mini-évènements (comme le pet)
- [x] Ajouter un mini-évent qui ne peut apparaître que sur un trajet entre deux lieux qui regen complètement l'énergie de celui qui tombe dessus.
- [x] Ajouter un nouveau truc à acheter dans le shop qui permet de regen complètement son énergie jusqu'à 3 fois par semaine. Le prix est progressif : 151 pièces, 1550 pièces et 5550 pièces

**Comment by BastLast** [comment]
@Feiryn  pour le 3 ème point est-ce que c'est déjà merge le code qui permet de faire ça ou c'est que sur la branche du pve ?

**Comment by Feiryn** [comment]
> @Feiryn pour le dernier point est-ce que c'est déjà merge le code qui permet de faire ça ou c'est que sur la branche du pve ?

Ca fait pas ça le mini-évent, ça regen qu'un petit peu
