### ISSUE TITLE
Equilibrages combats.

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1847]
Vu qu'on vient de faire une mise à jour sur les combats, je pense qu'il est important de rester au point sur les équilibrages. Cette issue a pour objectif de recueillir un max d'infos sur ce qui est trop puissant et ce qui ne l'est pas assez :)

Je vous laisse mettre vos commentaire ci-dessous :)

**Comment by Pietagorh** [comment]
La lourde c'est cheaté af je trouve, si t'as un type qui est équilibré/porté sur la défense en face ça lui casse la gueule et il perd son avantage, si t'as un type qui a pas beaucoup de défense ça peut l'étourdir et de toute façon tu vas lui faire beaucoup de dégâts avec les autres attaques

**Comment by Chevalier2** [comment]
En fait, un chevalier contre un adversaire avec beaucoup de défense, ça lui permet de spam l'attaque. Sinon elle est nulle, elle ne fait pas de dégâts si l'adversaire dispose de moins d'un tiers de la défense de l'attaquant. Et à part la bénédiction une fois, il n'a aucune attaque vraiment intéressante.

**Comment by Pietagorh** [comment]
Sauf que le truc c'est que quasi personne a très peu de défense parce que c'est pas pratique
T'es bien un des seuls qui puissent faire full attaque
Depuis que je suis chevalier j'ai perdu que contre toi x)

**Comment by OrionYp** [comment]
La lourde son problème c’est qu’elle coche toutes les cases, elle fait beaucoup de dégâts, ne coûte pas trop de souffle, nerf l’adversaire (-25% de def à coup sûr) et à une chance d’etourdir l’adversaire.
Tout ça avec une bonne précision 
Je propose de diminuer le nerf de défense ou donner une limite d’utilisation (comme l’ultime ou les actions des dieux) 2 par combat et par joueur ça ne ferai "que -43,57% de la défense.

**Comment by OrionYp** [comment]
Mon avis sur le mage : 
Classe cool mais trop d’alte sur l’adversaire, avec la brûlure et l’alte maudit je ne trouve aucun moment pour jouer l’attaque poison qui fait beaucoup moins de dégâts, je propose donc de la remplacer par une attaque qui donne un boost au lanceur à la place comme Concentration ou protection.

**Comment by PirmezBenoit** [comment]
Hello !
Perso je trouve la regen ultra lente, peut être la lié aux gains de vie dans l'aventure ? Ou un nouvel item rendant de l'énergie ? Un nouveau produit dans un shop ?
Deuxième point, je pense qu'il serait intéressant de revoir certaines conditions sur le fait qu'un adversaire puisse accepter le combat.. par exemple une différence max de 5 level au dessus contre 25 en bas.. je pense que cela fera en sorte que plus de joueurs osent poster des demandes de combats.. je trouve moins dérangeant l'idée de devoir poster plusieurs demandes que d'avoir un mastodonte en face à chaque fois :)  
En dehors de ça, la maj est vraiment une réussite, classes intéressantes et équilibrées ! Le chevalier est anti classe du tank et a aussi déjà des anti classes, donc pas intérêt de nerf selon moi..

**Comment by BastLast** [comment]
> Hello !
> Perso je trouve la regen ultra lente, peut être la lié aux gains de vie dans l'aventure ? Ou un nouvel item rendant de l'énergie ? Un nouveau produit dans un shop ?
> Deuxième point, je pense qu'il serait intéressant de revoir certaines conditions sur le fait qu'un adversaire puisse accepter le combat.. par exemple une différence max de 5 level au dessus contre 25 en bas.. je pense que cela fera en sorte que plus de joueurs osent poster des demandes de combats.. je trouve moins dérangeant l'idée de devoir poster plusieurs demandes que d'avoir un mastodonte en face à chaque fois :)  
> En dehors de ça, la maj est vraiment une réussite, classes intéressantes et équilibrées ! Le chevalier est anti classe du tank et a aussi déjà des anti classes, donc pas intérêt de nerf selon moi..
> 
> 

#1845 et cette issue est faite pr parler d'équilibrage des attaques pas pour faire des suggestions 😅
Il y a deja une limite d'écart de points de gloire, il faut juste attendre que les gens haut level en gagnent ca va prendre quelques semaines jpense

**Comment by romain22222** [comment]
quelle est la liste des équilibrages actuels ?

**Comment by BastLast** [comment]
> quelle est la liste des équilibrages actuels ?

Bah justement ca sera fait en fonction des problèmes que les gens décrivent ici

**Comment by romain22222** [comment]
par rapport à la lourde, je suis complètement pour : le paladin nécessite un nerf assez sévère la dessus : les autres classes ont aucun moyen de diminuer l'armure efficacement, pendant que cette dite classe en possède beaucoup. Ca fait que le match parfait contre un paladin est un paladin...

**Comment by BastLast** [comment]
> par rapport à la lourde, je suis complètement pour : le paladin nécessite un nerf assez sévère la dessus : les autres classes ont aucun moyen de diminuer l'armure efficacement, pendant que cette dite classe en possède beaucoup. Ca fait que le match parfait contre un paladin est un paladin...

Le paladin n'a pas la lourde

**Comment by BastLast** [comment]
ok afin d'avoir le temps de faire les choses propres mais de pas retarder la maj, je repousse cela à la prochaine

**Comment by KirIcare** [comment]
Retirer la limite de 3 utilisations de l'attaque puissante (après 3 utilisation l'attaque fait -70% de dégâts). Avec le souffle mis en place, on est déjà assez limité comme ça

**Comment by PirmezBenoit** [comment]
Hello ;)

Je lisais le code pour voir si la classe mage avait de l'intérêt, je vois aussi que la classe est très peu jouée..

Je me demandais ce qu'il se passe si je place une malédiction, suivi directement d'un empoisonnement.. la malédiction est-elle encore prise en compte ? Idem avec l'attaque de feu ? J'ai l'impression que la classe n'est pas très compétitive à partir du moment où l'on ne peut pas stacker les attaques.. surtout que le mage débute avec très peu de souffle.. la pipe Haha ?

Belle journée,

**Comment by BastLast** [comment]
> Hello ;)
> 
> Je lisais le code pour voir si la classe mage avait de l'intérêt, je vois aussi que la classe est très peu jouée..
> 
> Je me demandais ce qu'il se passe si je place une malédiction, suivi directement d'un empoisonnement.. la malédiction est-elle encore prise en compte ? Idem avec l'attaque de feu ? J'ai l'impression que la classe n'est pas très compétitive à partir du moment où l'on ne peut pas stacker les attaques.. surtout que le mage débute avec très peu de souffle.. la pipe Haha ?
> 
> L'effet de l'empoisonnement me semble aussi très limité dans le temps..
> 
> Belle journée,

La classe a été conçu avec cela en tête, la classe est très puissante mais les effets se marchent un peu dessus 😏#tradeof

**Comment by Pietagorh** [comment]
"Quand tu réussi une attaque sans avoir assez de souffle ça devrait mettre ton souffle à 0
Ca serait trop punitif de le faire si elle échoue
Mais si elle réussi ca me semble legit" - Drapht

**Comment by BastLast** [comment]
> "Quand tu réussi une attaque sans avoir assez de souffle ça devrait mettre ton souffle à 0
> Ca serait trop punitif de le faire si elle échoue
> Mais si elle réussi ca me semble legit" - Drapht

Un bg l'auteur
