### ISSUE TITLE
[BUG]: Aucun message quittant la commande /classes pour inactivité envoyé

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1856]
### Description du bug.

On pourrait croire qu'on est encore dans la commande /classes pendant une éternité sans réagir, mais pourtant, ça le quitte bien automatiquement... Un message d'annulation pour cause d'inactivité serait préférable.

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Faire /classes. Attendre 2 minutes ou plus sans réagir. Lancer une autre commande.

### Captures d'écran

<img width="499" alt="Capture d’écran 2023-03-23 à 20 31 23" src="https://user-images.githubusercontent.com/94372084/227329873-d3f92840-d8cf-4e33-ad03-563ed8f3c642.png">

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
c'est pas vraiment un bug puisque ça a été conçu comme cela volontairement

**Comment by romain22222** [comment]
1. cite moi ces différents endroits, je vois pas d'exemples
2. même si c'est le cas, c'est pas probre au niveau ergonomie

**Comment by BastLast** [comment]
bah si, si le mec répond pas c'est qu'il est plus là.

infosclasse, les badges du profil n'envoient pas de message quand ils se terminent.
le switch non plus la commande inventaire non plus pourtant ils ont aussi un menu ou l'utilisateur peut cliquer.

Je crois que les shop en ont un par contre

Après en soit pour la commande classe ça peut se débattre parce que je crois que jusquà présent on annoncait quand c'était une action qui bloquait le joueur genre les shops et pas quand ct pas bloquant (genre l'inventaiçre)

**Comment by romain22222** [comment]
en l'occurence, class bloque le joueur, pas classinfo, ni les badges joueurs, ni inventory

je suis allé voir pour switch et en effet y'a pas de message, je suis pour en rajouter un aussi, si le joueur est bloqué à cause de cette commande, il veut savoir quand elle se termine s'il a une co de merde

**Comment by BastLast** [comment]
je propose que la logique soit : quand on bloque le joueur on doit envoyer un message en cas de déblocage

**Comment by romain22222** [comment]
draft si j'ai rajouté le label c'est parce que sinon je peux pas la link avec l'issue de mass fix

**Comment by romain22222** [comment]
laisse mon label tranquille

**Comment by BastLast** [comment]
Le label empeche pas de lier a la PR

**Comment by romain22222** [comment]
en l'occurence, j'avais pas possibilité de link sans le label taleur
