### ISSUE TITLE
[BUG]: Mauvais retrait des points d'énergie à la fin des fights

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#1857]
### Description du bug.

C'est normal qu'on retire des points aux combattants, ok. Mais quand on retire tous les points *au gagnant **sans possibilité de régen pendant 1h environ, sauf via le shop*** et qu'on en laisse 50 *au perdant*, y'a un souci...

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Faire un combat, et gagner. Faire /profil.

### Captures d'écran

<img width="499" alt="Capture d’écran 2023-03-23 à 20 55 49" src="https://user-images.githubusercontent.com/94372084/227336804-cb93e080-a72d-4461-b299-f52aae15e7e6.png">
<img width="499" alt="Capture d’écran 2023-03-23 à 20 55 58" src="https://user-images.githubusercontent.com/94372084/227336815-a3a33bb7-5655-4d45-9d79-0cb5764142a4.png">

Screens provenant de #1101:
![227335897-6e8ee341-cf66-44e8-a6b1-e31e085a3b35](https://user-images.githubusercontent.com/94372084/227336995-3f766a9e-841c-4e87-a5a0-bfd30df62488.png)
![227334769-79ae4fa1-4d47-43a7-a665-d521c5b26a86](https://user-images.githubusercontent.com/94372084/227337038-083a466c-d801-4b14-900e-b764e1ebb429.png)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Bombafox** [comment]
Bug fight 

![Screenshot_20230323_205952](https://user-images.githubusercontent.com/96150225/227339627-978873f4-9260-42a4-893c-14e08d658dd6.jpg)
![Screenshot_20230323_210005](https://user-images.githubusercontent.com/96150225/227339666-149f73b9-38ee-417d-a2b1-878bfe8b015d.jpg)

**Comment by Bombafox** [comment]
Bug en buvant une popo d'⚡

![Screenshot_20230323-205708_Discord](https://user-images.githubusercontent.com/96150225/227339820-6092a440-8dcd-4d1e-8268-b314f027b103.jpg)
![Screenshot_20230323-205654_Discord](https://user-images.githubusercontent.com/96150225/227339845-34648a7f-520c-4aa1-801b-c572a381ffc4.jpg)
![Screenshot_20230323-205756_Discord](https://user-images.githubusercontent.com/96150225/227339866-169863c1-d1c7-4e5e-81bb-62eaebed7108.jpg)

**Comment by symsym-1629** [comment]
La regen temporelle ne fonctionne pas non plus

**Comment by symsym-1629** [comment]
update : ce se regenerais après un tps approximatif d'une heure

**Comment by Bombafox** [comment]
> update non 

![Screenshot_20230323_210005](https://user-images.githubusercontent.com/96150225/227366284-36ca7dcd-0bc0-4630-a085-82b37aa7790a.jpg)
![Screenshot_20230323_222346](https://user-images.githubusercontent.com/96150225/227366334-db97b0f5-2fb3-4664-ad59-bbd77a9b470d.jpg)
