### ISSUE TITLE
[BUG]: Perte d'énergie totale à la fin d'un fight gagné

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#1858]
### Description du bug.

Le titre en est exmplicite, je sais pas quoi rajouter d'autre

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

1 - Faire un combat classé résultant en une victoire parfaite pour le joueur X sur Y
2 - Faire /profil : le joueur X a 0 énergie

### Captures d'écran

![image](https://user-images.githubusercontent.com/29299679/227337395-7d853ab2-6a83-452c-8e2f-ea756171bbf1.png)
![image](https://user-images.githubusercontent.com/29299679/227337453-76be7369-c47d-4a4e-b88b-f554625474a0.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by symsym-1629** [comment]
doublon de #1857
