### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by As-Nodt** [DraftBot-A-Discord-Adventure/DraftBot#1864]
### Description du bug.

J'ai une altération d'état d'une heure après l'event de la rivière vacarme, choix 2, je prends popo glaçon fondue de 3h dans le shop, après l'avoir bu, j'ai toujours mon altération d'une heure alors que je suis censé avancer de 3h 

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Pas besoin de + de renseignement

### Captures d'écran

![Screenshot_20230324-132758_Discord](https://user-images.githubusercontent.com/96839617/227524408-40c3d0b8-4afb-4193-a908-93c11e01d80e.jpg)
![Screenshot_20230324-132806_Discord](https://user-images.githubusercontent.com/96839617/227524438-254f7390-2319-4400-b266-31882b693522.jpg)

### Sur quel shard avez vous rencontré le bug ?

Shard 2

**Comment by BastLast** [comment]
Du coup jai pas compris, la potion n'a rien fait ?

**Comment by Nargacaura** [comment]
Elle n'a pas été bue, juste trouvée x)

**Comment by As-Nodt** [comment]
Oh mince ! Oui, après vérification je l'ai acheté mais pas bu, toutes mes excuses 😔

**Comment by BastLast** [comment]
Ah oui du coup c'est pas un bug, suffit de boire la potion avec /drink
