### ISSUE TITLE
Le skiptime ne recharge pas l'énergie

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#1872]
### Description du bug.

En utilisant une potion/objet de skiptime, le temps avance mais ça regen pas l'énergie

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

- Avoir des fpl
- Boire une potion de skiptime
- Check son profil

### Captures d'écran

![IMG_20230326_164920](https://user-images.githubusercontent.com/60353007/227783983-7fb1d82a-5fbf-4863-9d45-0b54d854fb5c.jpg)
![IMG_20230326_164935](https://user-images.githubusercontent.com/60353007/227783992-6fb36e9a-d282-4df3-b9d5-c744823cff78.jpg)
![IMG_20230326_164945](https://user-images.githubusercontent.com/60353007/227783997-2cdce390-2c36-497d-b09e-a5c58b5ea38c.jpg)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Nargacaura** [comment]
C'était pas déjà comme ça lorsqu'il y avait encore l'ancien système de combats classés?

**Comment by Pietagorh** [comment]
Si
C'est pas un bug au sens propre du terme, parce que c'est pas un truc qui marche "pas comme prévu", mais c'est un bug dans le sens "on y a pas pensé" quoi x)

**Comment by KirIcare** [comment]
Dans ce cas, le atravel des testeurs devrais recharger l'énergie également ?

**Comment by BastLast** [comment]
> Si C'est pas un bug au sens propre du terme, parce que c'est pas un truc qui marche "pas comme prévu", mais c'est un bug dans le sens "on y a pas pensé" quoi x)

si j'y ai pensé j'ai conscienment décidé de pas le faire

**Comment by Pietagorh** [comment]
Hmm

**Comment by Feiryn** [comment]
On fait quoi de ça du coup ?

**Comment by BastLast** [comment]
> On fait quoi de ça du coup ?

Faut décider

**Comment by BastLast** [comment]
> > On fait quoi de ça du coup ?
> 
> Faut décider 

D'un côté je comprend pk des gens trouveraient ça pas logique

D'un autre jai peur que ça soit un peu pété deja que les objets daily de temps de haut level sont assez fort et que ca rende les objet d'énergie bcp moins intéressants

**Comment by KirIcare** [comment]
Perso je trouve pas ça nécessaire, on a ajouté assez de méthode de recharge d'énergie pour que tout le monde y trouve son compte, et puis si on le fait, plus besoin de drop une potion épique ou légendaire d'énergie puisque une simple potion de skiptime spécial fera le taff (je dis ça sans avoir check si c'est vrai mdr)

**Comment by Feiryn** [comment]
Je suis d'accord ça me paraît pas nécessaire avec les méthodes de régénérations qui existent maintenant

**Comment by BastLast** [comment]
> Je suis d'accord ça me paraît pas nécessaire avec les méthodes de régénérations qui existent maintenant

Après la question est, niveau gameplay est qu'il y a besoin de le justifier ? Peut etre ajouter un conseil qui explique que c normal que ca ne le fasse pas

**Comment by Feiryn** [comment]
Ça m'a jamais choqué, on n'accélère pas non plus les daily et tout, donc pourquoi ça ?

**Comment by BastLast** [comment]
> Ça m'a jamais choqué, on n'accélère pas non plus les daily et tout, donc pourquoi ça ?

On peut aussi ajouter un conseil qui dit que ca accélère pas les daily

**Comment by BastLast** [comment]
Juste pr que ca soit clair pr tout le monde que c intentionnel

**Comment by BastLast** [comment]
du coup j'ai ajouté les conseils, ça devient officiellement un comportement officiel
