### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Carsebel** [DraftBot-A-Discord-Adventure/DraftBot#1875]
### Description du bug.

Quand je fais 2 rapports à la suite pour connaître le temps restant avant d'arriver à destination, sur 2 fois c'était noté qu'il me restait 9 minutes avant le prochain rapport.

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

Faire 2 /rapport à la suite si pas d'altération d'état 

### Captures d'écran

![Screenshot_2023-03-27-00-14-43-78](https://user-images.githubusercontent.com/120785212/227809445-70321638-e4fb-49ee-aef8-e63518b13e60.jpg)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by romain22222** [comment]
ce n'est pas un bug : le temps affiché dans le dit rapport est dynamique : il s'actualise en direct. Donc les deux rapports auront le même temps affiché quelquesoit le temps élapsé entre les deux rapports.

**Comment by Carsebel** [comment]
Donc c'est toujours 9 minutes 45?

**Comment by Pietagorh** [comment]
@Carsebel si t'es sous android, c'est normal qu'il s'actualise pas, c'est un bug de l'app discord
Si tu la redémarres ça te réaffichera le bon temps
Malheureusement on peut faire qu'attendre qu'ils fix leur truc

**Comment by Carsebel** [comment]
Ok merci. 
J'ai posé la question sur le serveur et Drapht m'a dit de faire un ticket si ça recommençais donc j'ai fait
