### ISSUE TITLE
mini event bonus de guilde (si ya d'autres joueurs de la guilde sur l'île)

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1878]
En gros c'est un mini event ou un danger soudain fait face au joueur (pas un monstre car pas un combat)  mais ca peut etre genre un rocher qui tombe ou un feu ou pleins de trucs randoms et dangereux ou combattre n'est pas la solution.

En fonction du nombre de joueurs de la guilde du joueur qui sont également sur l'ile pve, il y a 3 options : le danger est écarté (points de guilde gagnés), le danger fait fuire le joueur (rien ne se passe), le danger le touche (malus d'énergie, perte d'argent...)

- [x] en gros le mini event génère un nombre random entre 2 et 4  (2 et 3 sont plus probable, 4 est rare) et en fonction du nombre de joueur de la guilde du joueur qui sont aussi sur l'ile, il se passe des trucs.

- [x] Si il y a autant ou plus de joueur que ce qui est demandé, alors 100% de chanced'avoir l'issue positive

- [x] si ya pas assez de joueur alors 10% de chance de réussite, 30 % de chance de fuite et 60 % de chance de malus

**Comment by Feiryn** [comment]
Évent de GabrielRe

Le ciel est gris, la température est moyenne. C’est un temps idéal pour marcher et avancer dans votre aventure. Cependant, au bout de quelques pas, le sol frêle se dérobe sous vos pieds et vous chutez dans un trou (avec vos compagnons de guilde). 

Réussite : 
-    Avec guilde : Grâce à l’aide de vos camarades de guilde, vous parvenez à vous hisser hors de cette crevasse et à les sauver à leur tour. Cette épreuve surmontée a renforcé vos liens, votre guilde reçoit ... ⭐
-    Solo (mais avec guilde) : Ne perdant pas votre sang-froid, vous appliquez immédiatement les enseignements de votre guilde et parvenez aisément à escalader la paroi. Votre guilde reçoit ... ⭐
- Solo (mais sans guilde) : Ne perdant pas votre sang-froid, vous appliquez ce que vous avez appris durant vos aventures et parvenez aisément à escalader la paroi. 

Fuite : 
-    Avec guilde : Ne perdant pas de temps, vous et vos compagnons se pressent d’examiner cette crevasse, qui s’avère être une grotte. Un peu de marche à l’aveugle plus tard, vous parvenez à ressortir de ce trou plus loin. 
-    Solo : Désespéré, seul au fond de cette crevasse, vous ne remarquez l’étroit conduit à votre gauche qu’au bout de quelques minutes. Après vous être démené contre cette terre qui avait décidé de vous enfermer, vous ressortez à l’air libre.

Perte : 
-    Avec guilde : Grâce à l’aide de vos camarades de guilde, vous parvenez à vous hisser hors de cette crevasse et à les sauver à leur tour. Cependant, celui qui avait votre bourse est remonté en dernier, et a malencontreusement laissé tomber l’argent durant l’escalade. Vous perdez ... pièces. 
-    Solo : Alors que vous tentez d’escalader la paroi, la terre s’effrite sous vos doigts et vos pieds et provoque un éboulement. Grâce à lui, vous parvenez à sortir de cette crevasse mais vous êtes bien amoché. Vous perdez ... vies.

**Comment by Nargacaura** [comment]
Vous décidez de vous reposer un peu après une traversée intense sur l'île. Mais, au moment où vous vous allongez sur le sol, la terre se mit à trembler...

**Réussite**
- *Avec guilde*: Cependant, vous vous agrippez les uns des autres, afin d'éviter qu'une potentielle crevasse fasse tomber l'un d'entre vous. La secousse se termine, et vous êtes tous sains et saufs. Vous gagnez x points de guilde.
- *Sans guilde*: Vous essayez de tenir malgré la secousse. Heureusement, elle n'a causé aucun dégât autour, vous continuez à vous reposer un peu en admirant le ciel et les environs.

**Fuite**
- *Avec guilde*: Pris de panique, votre guilde tente de trouver un endroit plus sûr afin d'éviter tout dégât sur l'un d'entre vous. Après plusieurs minutes à tourner en rond car au moins l'un des membres pense que tel lieu n'est pas sûr, vous ne ressentez plus la secousse. Néanmoins, vous essayez de vous regagner de la confiance pour ce qui va suivre dans votre parcours de l'île...
- *Sans guilde*: Paniqué, vous essayez d'esquiver les dégâts potentiels du seisme. Après quelques instants, la secousse ne se ressent plus. Au retour à l'endroit où vous vouliez vous reposer, vous constatez les dégâts du séisme. Heureusement que vous n'y étiez pas resté...

**Échec**
- *Avec guilde*: Vous vous dites que ce séisme sera court, et demandez au reste de la guilde de braver celui-ci. Quelle erreur! Un rocher s'écrase sur vous et vous assomme. Vous perdez x points d'énergie.
- *Sans guilde*: Vous disant qu'il n'y aura que peu de dégâts, vous continuez à vous reposer. Cependant, une crevasse se forme sous votre corps. Par peur de tomber dedans, vous essayez de courir le plus loin possible, mais vous trébuchez et vous entaillez le bras. Vous perdez x PV.

**Comment by Gabrielre14** [comment]
Vous avanciez tranquillement dans votre aventure (avec vos compagnons de guilde), lorsque votre instinct vous signale un danger. Petit à petit, une brume blanchâtre presque opaque s’élève du sol accidenté et tombe du ciel pour vous encercler. Vous ne voyez rapidement plus rien autour de vous. 

**Réussite :** 
-    _Avec guilde :_ Plusieurs paires d'yeux valent mieux que deux ! Grâce à la coopération de vos visions, vos compagnons et vous parvenez à avancer entre les rochers et les crevasses sans qu’un seul ne soit blessé ou perdu. Votre guilde reçoit X ⭐
-    _Solo (avec guilde) :_ Dans cette situation urgente, vous gardez votre sang-froid et utilisez les techniques de pistage apprises grâce à votre guilde afin de vous sortir de ce pétrin sans encombre. Votre guilde reçoit X ⭐
-    _Solo (sans guilde) :_ Dans cette situation urgente, vous gardez votre sang-froid et utilisez des techniques de pistage apprises un peu plus tôt afin de vous sortir de ce pétrin sans encombre. 

**Fuite :** 
-    _Avec guilde :_ Complètement perdus dans ce brouillard dense et menaçant, vos compagnons et vous décidèrent de se regrouper pour parer la fraicheur, en attendant que le vent disperse la brume. 
-    _Solo :_ Complètement tétanisé par l’angoisse de ce phénomène presque surnaturel, vous paniquez, votre pouls s’emballe et malgré la fraicheur vous sentez les moiteurs de votre front blême couler une à une, jusqu’à ce que la brume soit dispersée par le vent.

**Perte :** 
-    _Avec guilde :_ Votre groupe n’étant pas au complet, vos compagnons de guilde et vous paniquez face à cette épreuve. Chacun fuit de son côté et vous ne demandez pas votre reste pour courir à votre tour. Mais dans la précipitation, vous laissez tomber X pièces. 
-    _Solo :_ Complètement paniqué devant cette brume presque menaçante, vous prenez vos jambes à votre cou et courrez droit devant vous. Une grave erreur, car vous choyez bien vite au sol à cause du brouillard. Vous perdez X vies.

**Comment by voltou91** [comment]
> Vous décidez de vous reposer un peu après une traversée intense sur l'île. Mais, au moment où vous vous allongez sur le sol, la terre se mit à trembler...
> 
> **Réussite**
> 
> * _Avec guilde_: Cependant, vous vous agrippez les uns les autres, afin d'éviter qu'une potentielle crevasse fasse tomber l'un d'entre vous. La secousse se termine, et vous êtes tous sains et saufs. Vous gagnez x points de guilde.
> * _Sans guilde_: Vous essayez de tenir malgré la secousse. Heureusement, elle n'a causé aucun dégât autour, vous continuez à vous reposer un peu en admirant le ciel et les environs.
> 
> **Fuite**
> 
> * _Avec guilde_: Pris de panique, votre guilde tente de trouver un endroit plus sûr afin d'éviter tout dégât sur l'un d'entre vous. Après plusieurs minutes à tourner en rond car au moins l'un des membres pense que tel lieu n'est pas sûr, vous ne ressentez plus la secousse. Néanmoins, vous essayez de vous regagner de la confiance pour ce qui va suivre dans votre parcours de l'île...
> * _Sans guilde_: Paniqué, vous essayez d'esquiver les dégâts potentiels du seisme. Après quelques instants, la secousse ne se ressent plus. Au retour à l'endroit où vous vouliez vous reposer, vous constatez les dégâts du séisme. Heureusement que vous n'y étiez pas resté...
> 
> **Échec**
> 
> * _Avec guilde_: Vous vous dites que ce séisme sera court, et demandez au reste de la guilde de braver celui-ci. Quelle erreur! Un rocher s'écrase sur vous et vous assomme. Vous perdez x points d'énergie.
> * _Sans guilde_: Vous disant qu'il n'y aura que peu de dégâts, vous continuez à vous reposer. Cependant, une crevasse se forme sous votre corps. Par peur de tomber dedans, vous essayez de courir le plus loin possible, mais vous trébuchez et vous entaillez le bras. Vous perdez x PV.

Yo, me faudrait une phrase pour solo mais avec guilde ^^

**Comment by Nargacaura** [comment]
Une phrase pour le solo sans guilde pourrait être du genre:
> Vous suivez les instructions qui vous ont été données en cas de seisme par votre guilde, et décidez de vous abriter sous une structure qui, heureusement, ne s'est pas écroulée sur vous. Sain et sauf, vous vous promettez de remercier votre guilde dès votre retour de votre expédition.

Si ça peut t'aider, @voltou91 (et s'il y a des modifs à faire, tu peux toujours les faire ;))

**Comment by Gabrielre14** [comment]
Voici quelques petits scénarios supplémentaires. Je les envoie dans des messages séparés. 
PS : il y a peut-être des fautes... et je les ait déjà envoyé sur le salon de discussion de l'équipe technique

Vous avanciez tranquillement pour de nouvelles aventures lorsqu’un petit caillou sournois, insolent et pointu décida de faire de vous sa victime et vous entaille cruellement la cheville…

**Réussite :** 
-	Avec guilde : Heureusement pour vous, vos compagnons de guilde sont experts en soin et vous êtes rapidement sur pied. Votre guilde reçoit X :star:
-	Solo (avec guilde) : Malgré la douleur, vous parvenez à vous souvenir des enseignements de votre guilde et parvenez grâce à ces connaissances à vous soigner rapidement. Votre guilde reçoit X :star:
-	Solo (sans guilde) : Malgré la douleur, vous parvenez à désinfecter et à bander la plaie afin de reprendre votre route au plus vite. 

**« Fuite » :** 
-	Avec guilde : Voulant éviter d’être retardés, vos compagnons de guilde décidèrent de vous porter afin de vous soigner plus tard, une fois arrivés à destination.  
-	Solo : Malgré la douleur, vous parvenez à continuer à marcher en clopinant. Vous vous soignerez une fois arrivé à destination. 

**Perte :** 
-	Avec guilde : Complètement impuissants face à cette blessure, vos compagnons vous soignent comme ils le peuvent mais la plaie s’infecte et la douleur devient insoutenable. Vous perdez X vies
-	Solo : Seul, vous tordant de douleur au milieu du chemin, maudissez cette pierre fière de son coup et endurez l’effroyable douleur afin de continuer votre aventure. Vous perdez X vies.

**Comment by Gabrielre14** [comment]
Le 2e... 

Vous marchez tranquillement en direction de votre destination lorsqu’une nuit soudaine s’installe brutalement sur la région. L’obscurité est totale… 

Réussite : 
-	Avec guilde : Vos compagnons de guilde sont cependant prévoyants et l’un d’eux sort une torche de son inventaire afin d’éclairer votre route. Votre guilde reçoit X :star:
-	Solo (avec guilde) : Heureusement que vous aviez une torche dans votre inventaire, qu’un de vos compagnons de guilde vous a donné à votre départ ! Vous pouvez ainsi aisément voir votre chemin et continuer votre route. Votre guilde reçoit X :star:
-	Solo (sans guilde) : Heureusement que vous aviez une torche dans votre inventaire, préparée avant votre départ ! Vous pouvez ainsi aisément voir votre chemin et continuer votre route.

« Fuite » : 
-	Avec guilde : Complètement aveuglés, vous et vos compagnons avancez à tâtons dans le noir complet, en vous entraidant pour éviter les obstacles, jusqu’à ce que cette étrange nuit reparte aussi vite qu’elle était venue.
-	Solo : Complètement aveuglé, vous avancez à tâtons dans le noir complet jusqu’à ce que cette étrange nuit reparte aussi vite qu’elle était venue.

Perte : 
-	Avec guilde : Complètement perdus face à cette cécité soudaine, vous et vos compagnons paniquez et courez droit devant vous jusqu’à ce que cette étrange nuit reparte aussi vite qu’elle était venue. Mais dans la précipitation, vous avez perdu X pièces. 
-	Solo : Seul et complétement perdu face à cette cécité soudaine, vous commencez à paniquer et à avancer droit devant vous sans remarquer le petit caillou sournois qui vous guettait à ce moment-là. Vous ramassant par terre, vous perdez X vies.

**Comment by Gabrielre14** [comment]
Et le dernier 

Vous marchiez déjà depuis un certain temps sur un chemin qui vous paraît ne jamais finir lorsque soudain les forces vous manquent et vous vous écroulez de fatigue. 

Réussite : 
-	Avec guilde : Voyant votre malaise, vos compagnons accourent pour vous soutenir et vous offrent à manger l’énergie nécessaire pour vous relever et continuer à avancer dans votre quête. Votre guilde reçoit X :star:
-	Solo (avec guilde) : Malgré ce malaise, vous utilisez le peu d’énergie qui vous reste pour sortir de votre inventaire un peu de nourriture offerte par votre guilde afin de reprendre des forces et continuer votre quête. Votre guilde reçoit X :star:
-	Solo (sans guilde) : Malgré ce malaise, vous utilisez le peu d’énergie qui vous reste pour sortir de votre inventaire un peu de nourriture préparée à l’avance afin de reprendre des forces et continuer votre quête.

« Fuite » : 
-	Avec guilde : Heureusement, ce n’était qu’un malaise passager, et, encouragé par vos compagnons de guilde, vous reprenez votre route avec eux au bout de quelques minutes de repos. 
-	Solo : Heureusement pour vous car vous étiez seul, ce n’était qu’un malaise passager, et vous parvenez à reprendre votre route après quelques minutes de repos. 

Perte : 
-	Avec guilde : Face à ce soudain malaise, vos compagnons de guilde, ne sachant comment vous aider, décident de vous porter jusqu’à la prochaine étape, mais l’épuisement vous harcèle et vous vous évanouissez. Vous perdez X vies. 
-	Solo : Complètement épuisé, le ciel se met à tourner autour de vous. Vous tentez de vous relever, mais les forces vous manquant et ayant l’impression d’être sur une mer déchaînée, vous vous évanouissez au beau milieu du chemin. Vous perdez X vies.
