### ISSUE TITLE
Lancement d'un petit combat (combat passif) -> point de guilde réduction de la puissance du boss, perte fight points

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1879]
Les combats sont contre des pets, le joueur rencontre des version agressives des pets de l'ile principale et les affronte.

- [x] Le nombre d'option dépend du nombre de gens de la guilde sur l'ile
- [x] La nature et la puissance des options dépendent du niveau de la guilde du joueur, de son pet, de ses équipements...
- [x] #2010
- [x] Faire passer codacy/ codescene etc
- [x] Traduire certains textes en anglais

**Comment by Feiryn** [comment]
Utiliser les pets comme ennemis

**Comment by BastLast** [comment]
top tes changements

**Comment by BastLast** [comment]
j'ai mis à jour l'issue avec ce qu'il reste à faire sur cette issue je pense que je vais pas pouvoir toucher au code pendant quelques jours :/

**Comment by BastLast** [comment]
j'ai déplacer un truc dans  #2019 parce que c pas dans le MVP de la maj
