### ISSUE TITLE
Récompenses alternatives à l'xp de guilde pour les guildes level 100

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1882]
### Discussed in https://github.com/DraftBot-A-Discord-Adventure/DraftBot/discussions/778

<div type='discussions-op-text'>

<sup>Originally posted by **Thesmokingllama** December 12, 2021</sup>
Permettre aux membres des guildes level 100 une récompense alternative (en argent ou en xp) à l'xp de guilde dans les mini-event et dans les transactions de pets.</div>

du coup ça donnera un tout petit peu de points de guilde

EN GROS : 

- [ ] Pour faire simple, quand une guilde est lvl 100 et qu'elle obtient de l'xp, elle recoit un tout petit peu de points de guilde (xp qu'elle aurait du recevoir / 69 arrondi au supérieur) (nice)

- [ ] Ajouter une récompense dans le daily de guilde qui donne un tout petit peu de points de guilde (un nombre random entre 15 et lvl de guilde +15 (cette récompense sera assez rare)

**Comment by Feiryn** [comment]
On voit ça dans la prochaine maj

**Comment by BastLast** [comment]
Euh.... Pas trop chaud de faire ca en 2 fois perso

**Comment by Feiryn** [comment]
Pas le choix

**Comment by BastLast** [comment]
+ Go pas tout melanger dans la milestone 4.4.1 parce que ya deja bcp de choses dedans

**Comment by BastLast** [comment]
Je ferme cette story pour le moment en wont do puisque les guildes peuvent monter lvl 150 et qu'il va falloire passer du temps avant de voir des guildes lvl max
