### ISSUE TITLE
Rendre le switch gratuit (plus de malus 30 min sur le daily)

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1888]
### Discussed in https://github.com/DraftBot-A-Discord-Adventure/DraftBot/discussions/1887

<div type='discussions-op-text'>

<sup>Originally posted by **Chevalier2** March 28, 2023</sup>
</div>

### Discussed in https://github.com/DraftBot-A-Discord-Adventure/DraftBot/discussions/1852

<div type='discussions-op-text'>

<sup>Originally posted by **Pietagorh** March 22, 2023</sup>
</div>

**Comment by BastLast** [comment]
j'ai peur qu'un bonus de 30 % soit un peu violent et creuse trop l'écart avec des gens qui utiliseraient un item de daily du coup je pensais à un malus de 30% serait plus juste
ça permettrait d'avoir le choix entre les 3 modes de jeu:

- que combat,
- que daily
- hybride

Et que les gens puissent choisir entre les 3 de manière équilibrée.

**Comment by BastLast** [comment]
Bon nouveau plan, le switch devient juste gratuit, pas de buff, pas de nerf de rien du tout

**Comment by BastLast** [comment]
issue renamed

**Comment by Pietagorh** [comment]
D'ailleurs le code qui faisait ça été mal foutu, si j'me trompe pas un switch moins de 30 minutes après un daily influençait pas le cooldown
