### ISSUE TITLE
Ajouter un mini évent, le marchand épique.

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1889]
- [x] Mini event de rareté minimale.
- [x] Le marchand propose l'achat d'un équipement épique ou légendaire (pas de mythique, pas de spéciales).
- [x] L'item acheté est random mais connu à l'avance (comme l'autre marchand des mini events).
- [x] Le prix de l'item est de 7 fois sa valeur (oui,c'est cher) (1 chance sur 10 que ça soit 3 fois sa valeur seulement).
- [x] Le mini event n'apparait que sur la moitié est de la carte.

**Comment by Pietagorh** [comment]
ça va comme délimitations des zones géographiques ? 
![image](https://user-images.githubusercontent.com/60353007/229485110-d1bda2f8-8d7f-46d0-9a87-254dd8935138.png)

**Comment by BastLast** [comment]
> ça va comme délimitations des zones géographiques ? 
> ![image](https://user-images.githubusercontent.com/60353007/229485110-d1bda2f8-8d7f-46d0-9a87-254dd8935138.png)
> 

Est-ce que tu as vu la milestone ?

**Comment by Pietagorh** [comment]
Oui mais j'fais c'que j'veux :p 
Plus sérieusement j'avais dit que je ferais des trucs rapides, et ça l'est + je rajoute des trucs sur la map qui pourront être utiles sur le pve niveau maps (c'qui est d'ailleurs la raison pour laquelle j'ai pas fini en le temps d'1 cours de français et c'est lié à ma question juste au dessus)

**Comment by BastLast** [comment]
> Oui mais j'fais c'que j'veux :p 
> Plus sérieusement j'avais dit que je ferais des trucs rapides, et ça l'est + je rajoute des trucs sur la map qui pourront être utiles sur le pve niveau maps (c'qui est d'ailleurs la raison pour laquelle j'ai pas fini en le temps d'1 cours de français et c'est lié à ma question juste au dessus)

Sauf qu'on a une branche pr le pve et que merge tes changements risque de ne pas être au programme

**Comment by Pietagorh** [comment]
Yes bon bah ok monsieur le psychorigide, j'vais juste ne pas dév quoi que ce soit parce que c'est trop long 😠

**Comment by BastLast** [comment]
> Yes bon bah ok monsieur le psychorigide, j'vais juste ne pas dév quoi que ce soit parce que les autres trucs c'est trop long 😠 

C'est pas de la psychorigidité c'est juste qu'on doit travailler en équipe :/

**Comment by Pietagorh** [comment]
> > > Yes bon bah ok monsieur le psychorigide, j'vais juste ne pas dév quoi que ce soit parce que les autres trucs c'est trop long 😠
> > 
> > 
> > C'est pas de la psychorigidité c'est juste qu'on doit travailler en équipe :/
> 
> Check discord stp

Peux pas, le proxy du lycée veut pas xD

**Comment by BastLast** [comment]
au final j'ai pas dfait un event qui apparait que sur la moitié de la map il apparait partoutmais les items sont moins cher à coté de la route des merveilles
