### ISSUE TITLE
[BUG]: Bo3 qui marche pas. 

### ISSUE THREAD

**Issue by Anamoya-1123581321** [DraftBot-A-Discord-Adventure/DraftBot#1921]
### Description du bug.

Je fais un combat classé contre quelqu'un. Je perds. 
Plus tard, nous en refaisons un. Je gagne. 
Nous en sommes donc à un partout, il nous reste techniquement un combat encore à faire. Ni la condition de 3 combats ou de 2 victoires n'a été remplie. 
Pour autant, je reçois l'erreur me disant que j'ai fait trop de combats contre cette personne (la même hein). 

J'ai tous mes :zap:, je n'ai pas d'alté, je suis sur et certain de n'avoir fait que deux combats contre lui, je suis sur et certains que c'était bien une victoire et une défaite. 
![Screen erreur bug bo3](https://user-images.githubusercontent.com/96310054/230626650-66960846-668e-4d18-97c8-a6ac8cae6b1f.png)

NB : 
Mon ID : 420628217649692676
ID de l'adversaire en question : 219560393499082756
Les combats ont tous été faits après 14h ce jour même. 

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Comment on ne sait pas trop comment le faire, je pense qu'il suffit de tenter de faire une victoire puis une défaite classée. À noter que ce n'est pas la première fois que mon adversaire précité subit ce genre de limitation étrange. 

### Captures d'écran

Déjà postée au-dessus. S'il en faut d'autres auxquelles je n'ai pas penser, me DM sur Discord ou me ping sur l'offi'. 

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Anamoya-1123581321** [comment]
<img width="551" alt="Capture d’écran 2023-04-07 à 16 42 52" src="https://user-images.githubusercontent.com/96310054/230627905-a52b11f0-2963-463d-9e6c-43f2b94ea665.png">
Je suis dans la même situation avec Pourfi' : nous avons une victoire et une défaite l'un contre l'autre, seulement ça. Pour autant, en témoigne le screen que je dépose, j'obtiens la même erreur qu'avec mon adversaire antérieur. 

<img width="550" alt="Capture d’écran 2023-04-07 à 16 44 04" src="https://user-images.githubusercontent.com/96310054/230628078-2de328df-f799-4462-b142-8f7f92695ff7.png">
Autre adversaire, autre exemple, ici avec Cécilia. Toujours le même schéma de la victoire et de la défaite, et toujours aussi peu possible de faire le 3e et dernier combat.

**Comment by Feiryn** [comment]
Bug lié à #1942
