### ISSUE TITLE
[BUG]: Le second joueur gagne trop souffle avant sa première action

### ISSUE THREAD

**Issue by MelvinCou** [DraftBot-A-Discord-Adventure/DraftBot#1927]
### Description du bug.

La release 4.3.0 précise :
`Le joueur qui ne commence pas un combat gagne *un petit peu* de souffle lors du premier tour du combat.`

Cependant, dans le code source [FightController.ts (l181)](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/src/core/fights/FightController.ts#L181) :

```ts
if (endTurn) { // turn = 1
	this.turn++; // turn = 2
	this.invertFighters();
	this.getPlayingFighter().regenerateBreath(this.turn < 2); // false => le second joueur récupère l'équivalent d'un tour et non la moitié
	await this.prepareNextTurn();
}
```

Sachant que le constructeur initialise le tour à 1 [(l33)](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/src/core/fights/FightController.ts#L33) :

```ts
public constructor(fighter1: Fighter, fighter2: Fighter, friendly: boolean, channel: TextBasedChannel, language: string) {
	this.fighters = [fighter1, fighter2];
	this.fightInitiator = fighter1;
	this.state = FightState.NOT_STARTED;
	this.turn = 1; // ligne en question
	this.friendly = friendly;
	this._fightView = new FightView(channel, language, this);
	}
```

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Faire un combat.

### Captures d'écran

Pas besoin

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
Je comprend pas, cette mécanique a été testée...?

**Comment by Nargacaura** [comment]
> Je comprend pas, cette mécanique a été testée...?

Ça avait été testé par Muzan et Bomba, et ça ne fonctionnait déjà pas lors des tests. Aucun fix n'avait été réalisé avant le push.
