### ISSUE TITLE
Pas de délai de voyage.

### ISSUE THREAD

**Issue by Nininanou16** [DraftBot-A-Discord-Adventure/DraftBot#1940]
### Description du bug.

Après avoir fait un premier /report, quelques secondes plus tard je reçois par MP un message m'indiquant que je suis arrivé à destination. J'essaye donc a nouveau /report, et le bot me propose un nouvel évent.

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Sans aucune garantie de fonctionnement systématique :
- faire un premier /report
- a la réception du mp, en faire un second

### Captures d'écran

![Screenshot_20230427-070658~2](https://user-images.githubusercontent.com/71654580/234765197-62ee57d8-9294-49b1-9e37-ad5009cb9662.png)
![Screenshot_20230427-070642~2](https://user-images.githubusercontent.com/71654580/234765206-09724e82-10a3-43ce-88f9-799f6c989095.png)

### Sur quel shard avez vous rencontré le bug ?

Shard 1

**Comment by Nargacaura** [comment]
Y'a pas une faille quelque part? Ça me semble comme un bug majeur, ça...

**Comment by Nininanou16** [comment]
> Y'a pas une faille quelque part? Ça me semble comme un bug majeur, ça...

Je ne l'ai pas mis en majeur car ca ne s'est, pour ma part, produit qu'une seule fois (le bug n'a pour le moment pas continué), et que ça n'impacte pas plus que ça le gameplay. Bien que j'estime qu'il soit important d'y apporter de l'attention ;)

**Comment by Pietagorh** [comment]
De c'que j'vois, le bot a log les bons trucs aux bons moments, donc aucune idée

**Comment by KirIcare** [comment]
On est d'accord que ça peut pas être le bug où tu pouvais skip le temps de trajet si tu /report très vite après avoir réagi, on l'avait bien fix celui là non ?

**Comment by Nininanou16** [comment]
> On est d'accord que ça peut pas être le bug où tu pouvais skip le temps de trajet si tu /report très vite après avoir réagi, on l'avait bien fix celui là non ? 

Ça ne peut pas être ça, j'ai fait le 2e /report plusieurs dizaines de secondes plus tard, seulement après avoir reçu le mp du bot.

**Comment by Nargacaura** [comment]
Vu comme on n'a pas eu d'autres cas similaires à celui-ci, en plus d'être quasi-impossible à avoir dans le bot de tests, autant le classifier comme non reproductible jusqu'à apparition d'un nouveau cas.
