### ISSUE TITLE
[BUG]: Mauvais winner dans les logs des fights

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#1942]
### Description du bug.

Le winner dans les logs des fights est le mauvais. Depuis le invertFighters de
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/commit/d8da64cc0d5901a4c55783c24cf1b3a1af8c2f0f
les logs ne sont plus bons pour le winner car on voit à cette ligne
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/0c64a18295ea61b753de07710d27d0cce80d3b4a/src/core/database/logs/LogsDatabase.ts#L985
que c'est l'initiateur et pas le fighter 0 qui est récupéré.

Il faudra aussi faire une migration en utilisant le nombre de tours pour inverser la bonne valeur de winner afin d'avoir la bonne valeur pour toutes les valeurs insérées depuis le déploiement de la 4.3.2

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

-

### Captures d'écran

-

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
💀💀💀

**Comment by BastLast** [comment]
> j'en connais un qui va se faire taper sur les doigts avec une règle alu de 15cm. après les avoir trempés dans de l'azote liquide pendant 2 minutes

Naah c'est le genre de chose qui arrivent

**Comment by BastLast** [comment]
> > j'en connais un qui va se faire taper sur les doigts avec une règle alu de 15cm. après les avoir trempés dans de l'azote liquide pendant 2 minutes
> 
> Naah c'est le genre de chose qui arrivent 

Juste, pas de chance

**Comment by Feiryn** [comment]
En fait ça dépend de celui qui joue en premier mais on ne peut  avoir cette info que dans les combats avec des tours impairs (en regardant celui qui a fait 1 attaque de plus) donc la migration est impossible
