### ISSUE TITLE
[BUG]: missions

### ISSUE THREAD

**Issue by Cirpacha** [DraftBot-A-Discord-Adventure/DraftBot#1949]
### Description du bug.

j'ai eu pour mission d'explorer 20 lieux, mais ensuite j'ai trouvé celle d'explorer 10 lieux et depuis celle des 20 est bug et n'avance plus depuis quelques jours, seuls les 10 lieux ont pu être réalisés.

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

- avoir pour mission d'explorer un nombre de lieux
- avoir une deuxième mission d'explorer un nombre de lieux, même différent de la première
- faire des reports pour passer des lieux

### Captures d'écran

![cvcv](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/100078346/5e7b1de6-71b6-4925-b6e7-b0a1e5619f62)
![grfs](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/100078346/dc3fd665-be36-4146-b5ba-ca2d86f18d7d)

### Sur quel shard avez vous rencontré le bug ?

Shard 0

**Comment by Bombafox** [comment]
C'est pas un bug vu que c'est 20 lieu **differents**
Donc si tu repasses à un endroit où t'es déjà passé ça le compte pas.

**Comment by Cirpacha** [comment]
> C'est pas un bug vu que c'est 20 lieu **differents** Donc si tu repasses à un endroit où t'es déjà passé ça le compte pas.

c'est sûrement ça merci

**Comment by BastLast** [comment]
Hello, jme permet juste un message pr demander à ne pas fermer les issues même si c'est une erreur :)
