### ISSUE TITLE
Bug réaction combat

### ISSUE THREAD

**Issue by Voisin1234** [DraftBot-A-Discord-Adventure/DraftBot#1975]
### Description du bug.

Bonjour, j’étais en plein combat le bot je ne sais pas pour quelle raison n’a pas voulu me donner les réactions pour pouvoir continuer celui-ci! De se fête, je n’ai pas pu continuer le combat et de plus ma fait perdre le match

### Selon vous, quelle est l'importance de ce bug ?

😱 Extrêmement grave

### Reproduction du bug.

Nous étions en plein combat, et les réactions ne se sont pas affichés

### Captures d'écran

![IMG_4344](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/10bee099-9518-460b-9a6f-06cfc30a3df0)
![IMG_4345](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/0eba298c-110c-4f53-ab1c-d0b8d147d0cb)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Nargacaura** [comment]
Y'a-t-il pas eu un rate limit du bot?

**Comment by BastLast** [comment]
ça ressemble fort à un rate limit ou à un soucis de discord... est-ce qu'un @DraftBot-A-Discord-Adventure/contributors  peut check si ya qqch dans les logs ?

**Comment by BastLast** [comment]
j'ai pas de nouvelles, sans plus de détails sur ce bug je ferme en cannot reproduce, à rouvrir si ça revient et qu'on a plus d'infos parce que en l'état c'est pas possible de le fix (à priori c'est un soucis de discord)
