### ISSUE TITLE
[BUG]: Le mini-event winGuildXP crash

### ISSUE THREAD

**Issue by Gabrielre14** [DraftBot-A-Discord-Adventure/DraftBot#1988]
### Description du bug.

Sur le bot de test, mercredi soir. 
Je teste d'obtenir le mini-event witch normalement, le bot tourne en boucle lors d'un rapport.
Le /rapport suivant, je vois que ce mini-event était un event à XP, et j'étais sans guilde : 
Le mini-event qui donne de l'XP personnelle a crash, et je n'ai reçu aucun point d'XP (après vérification sur le profil)

PS : en forçant le mini-event fonctionne

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Faire des /rapport jusqu'à obtenir un mini-event qui crash (sans être dans une guilde)
Vérifier ensuite qu'il s'agissait bien d'un mini-event à XP

### Captures d'écran

Ce qu'il s'est passé en test : 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/ec547ed9-5d80-4d29-a26a-d98c1eb76472)
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/c8c90845-0dd5-422a-a5c3-a58713977da7)

Capture d'écran donnée par Drapht : 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/ff4bb06f-245e-495c-a9d0-6d50c8ab4a84)

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
@Nargacaura c'est pas le même small event qui crash sur la #2028 ya moyen que ça soit pas le même bug.

**Comment by Nargacaura** [comment]
Probable, même si j'émets des doûtes. D'ailleurs, ce n'est pas le winPersonalXP qui est cassé ici, mais wi n*Guild*XP, à en voir le message d'erreur.

**Comment by BastLast** [comment]
Je check ça ce soir
