### ISSUE TITLE
Equilibrage du pve

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#1993]
Le but de cette story est d'équilibrer au maximum le pve

**Comment by BastLast** [comment]
penser à ajouter des poids de probabilité sur les attaques des monstres

**Comment by BastLast** [comment]
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/38099970/03be7008-3db2-42fa-ab1a-632978b9db7d)

**Comment by Feiryn** [comment]
Bon je considère ceci fini du coup
