### ISSUE TITLE
Bug affichage du temps

### ISSUE THREAD

**Issue by Voisin1234** [DraftBot-A-Discord-Adventure/DraftBot#1994]
### Description du bug.

Salut, j’ai remarqué depuis quelques temps que j’ai un problème d’affichage du temps entre chaque /rapport celui-ci ne change pas Alors qu'il y a quelques minutes de passer
- Prochain arrêt prévu dans…. Minutes.-

### Selon vous, quelle est l'importance de ce bug ?
Jai également des fois : arrêts prévus dans un jour alors qu'il y a aucune altération et que je peux jouer dans les minutes qui suivent
🙂 Faible

### Reproduction du bug.

22h46 /report prochain arrêt prévu dans 27 minutes.
22h50 /report prochain arrêt prévu dans 27 minutes.

### Captures d'écran
![22h46 22h50](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/5993c058-48f0-45c2-9134-868312d35b78)
![s](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/1296e85a-af35-4c3e-a202-0d7ce2ad93bc)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by ZRunner** [comment]
Salut !
Ce bug est un bug venant de la version mobile de Discord. Un ticket a été ouvert il y a quelques semaines pour qu'ils le corrigent, mais en attendant le seul moyen de "mettre à jour" le temps d'attente semble être de relancer l'application.

**Comment by Voisin1234** [comment]
Ok merci
