### ISSUE TITLE
[BUG]: Magasin Récupération d'énergie

### ISSUE THREAD

**Issue by Procion06** [DraftBot-A-Discord-Adventure/DraftBot#2011]
### Description du bug.

ça fait 3 jours que la récupération d'énergie reste bloquée à 1550 dans le magasin alors que je n'en achète pas
elle devrait normalement être en vente à 151 pour la 1ère utilisation

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

achat dans la magasin d'une récupération à 151

### Captures d'écran

![Screenshot_12](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/107723160/b5ebffd0-5166-4e21-9573-304a5636ce11)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

**Comment by BastLast** [comment]
C'est par semaine que ça se reset hein

**Comment by Procion06** [comment]
my bad, je me coucherai moins con merci :)
