### ISSUE TITLE
après être sorti de l'île les trajets font tous 10 min alors qu'on est sur l'île normale

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2013]
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/38099970/1d7fb093-7f41-4206-a88f-10d2b7a14063)

**Comment by Feiryn** [comment]
C'est normal je vois pas le pb

**Comment by Nargacaura** [comment]
Tu ne vas quand même pas *d'une destination à une autre* en 10 minutes?

**Comment by Feiryn** [comment]
Oui c'est sur un bateau donc je trouve ça normal
De plus, il faut que ce soit plus rentable que prendre une alté de 40 min si tu t'évanouis

**Comment by BastLast** [comment]
Je je ferme jai relu et j'étais fatigué
