### ISSUE TITLE
[BUG]: /class répond séparément de l'interaction (embed + did not respond) quand on ne peut pas changer de class

### ISSUE THREAD

**Issue by symsym-1629** [DraftBot-A-Discord-Adventure/DraftBot#2014]
### Description du bug.

Quand on ne peut pas changer de classe, le bot nous revoie l'embed d'erreur en message normal et la réponse a l'interaction finit en "This application did not respond".

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

- Changer de classe
- faire /class

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/83075391/52ab6bf1-6082-4471-974b-27bb1d389aee)

### Sur quel shard avez vous rencontré le bug ?

tous

**Comment by Voisin1234** [comment]
Salut, j'ai exactement le même problème j'allais le poster également ce matin😊

**Comment by BastLast** [comment]
> Salut, j'ai exactement le même problème j'allais le poster également ce matin😊

Bien ouej la vérif pr pas dupli

**Comment by BastLast** [comment]
izi to fix alors je fix en 4.4.0
