### ISSUE TITLE
[BUG]: Possibilité d'accéder à l'île en ayant aucun point d'énergie

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2025]
### Description du bug.

Il n'aurait pas été mieux de check l'énergie *avant* de monter sur le bateau? Parce que là, y'a moyen qu'il puisse cheese un peu la mort en se restaurant un peu d'énergie via les mini-events de l'île... Bon, après, ça rend le voyage plus fun en mourant direct au mini-boss, si c'était l'effet voulu x)

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

Ne plus avoir de points d'énergie. Accepter l'offre de voyage en bateau.

### Captures d'écran

<img width="453" alt="Capture d’écran 2023-07-10 à 20 18 46" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/9a255804-6386-4ebe-b383-5ba39ad5db4b">

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
Le fix a pas marché

**Comment by BastLast** [comment]
my bad le bug restant est #2031
