### ISSUE TITLE
[BUG]: Régénération naturelle sur l'île

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2026]
### Description du bug.

Visiblement, il est tout à fait possible de se régénérer naturellement sur l'île, comme l'a constaté Ibbo dans sa run.

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

Être sur l'île, sans être full-énergie. Faire /profil. Patienter plus d'1/4 d'heure. Refaire /profil.

### Captures d'écran

Avant:
<img width="349" alt="Capture d’écran 2023-07-10 à 20 39 30" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/594973f1-96de-42e7-946b-70fe2e4b544b">

Après:
<img width="349" alt="Capture d’écran 2023-07-10 à 20 39 36" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/670ebb8a-412b-4365-a3c0-5a53cc36411d">

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by BastLast** [comment]
est-ce que c'est tout le temps cassé ou seulement de temps en temps ?

**Comment by Nargacaura** [comment]
Je crains que la régèn se fasse tout le temps sur l'île, y'a pas de conditions spécifiques.

**Comment by BastLast** [comment]
réponse reçu sur discord, ça vient de là https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/7e817616b8d6383c9901a0ee1e7e8af024ba0628/src/core/bot/DraftBot.ts#L297
