### ISSUE TITLE
[BUG]: Mini-event witch cassé

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2028]
### Description du bug.

Lors de mes tests pour vérifier l'apparition du mini-event du bateau, je tombe sur une boucle infinie du bot. Me disant qu'il y a un problème sur la latence, j'ai checké si /report était bloqué... pour constater qu'il me renvoie sur le voyage actuel, m'affichant que le dernier mini-event reçu est le witch.

J'ignore ce qui a causé ce bug, cependant. Notez cependant que ça ne s'applique que sur le bot bêta, la pre-release et la version stable ne sont pas affectées.

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Faire des /report jusqu'à tomber sur le mini-event witch. Refaire /report si ça tourne en boucle pour constater que le witch est cassé.

### Captures d'écran

<img width="490" alt="Capture d’écran 2023-07-10 à 22 35 00" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/5294cb67-52c8-4541-a66e-7100f2f6748c">

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by Nargacaura** [comment]
Il crash à chaque apparition, que ce soit via /report ou via un forcing.

**Comment by BastLast** [comment]
Ok donc c bien 2 bugs différents
