### ISSUE TITLE
[BUG]: Pve - Le titan se prend les dégâts de la météo

### ISSUE THREAD

**Issue by Bombafox** [DraftBot-A-Discord-Adventure/DraftBot#2046]
### Description du bug.

Le titant subit les dégâts de la météo (soleil)
A voir si il subit aussi avec la pluie 

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Se battre contre le titan et attendre que la météo tombe

### Captures d'écran

![Screenshot_20230715_172432_edit_550171995033718](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/96150225/a2c61fc7-3160-4114-98e1-c931085a997b)

### Sur quel shard avez vous rencontré le bug ?

Bot bêta

**Comment by BastLast** [comment]
@romain22222  tu as une idée de ce qu'il se passe ?

**Comment by romain22222** [comment]
Je sens que quelqu un a edit la météo sans faire gaffe au fait que sunny = rien

**Comment by BastLast** [comment]
@romain22222  je viens de lire le code et je pense que c'est ici le soucis 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/38099970/90993a2b-278e-4ef4-870b-f14b05146579)
 tu peux fix ce bug stp ?

**Comment by BastLast** [comment]
@romain22222  ya aussi ça comme soucis 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/38099970/e685a902-4256-4c3c-a34c-6ef6312a8cf3)
