### ISSUE TITLE
[BUG]: Joueur ne s'affichant pas sur le top glory

### ISSUE THREAD

**Issue by Jaarzz** [DraftBot-A-Discord-Adventure/DraftBot#2052]
### Description du bug.

Contexte : Je fais un fight avec Shin. Ensuite, je vais voir le classement de gloire et Shib n'apparaît pas dans le classement 

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

1. Faire un fight 
2. /topglory
PS : Je ne vois pas trop quelles étapes pour decrire le le bug. Shin n'a pas fight la saison dernière, je pense que le problème vient de là 

### Captures d'écran

![Screenshot_20230717_213704_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/106905934/74dde8df-00e3-412a-88ce-962f4b61b888)
![Screenshot_20230717_213721_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/106905934/4b135b5b-a523-48b0-9fa7-6a439d0a8e1d)
![Screenshot_20230717_213728_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/106905934/c23eecf9-a8f8-4df0-a248-b4f207a2aeec)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Nargacaura** [comment]
S'il n'a pas combattu durant la saison précédente, ça rajoute 1 au nombre de combats à réaliser tant que c'est inférieur à 7. Si c'est le cas, il devrait faire 2 combats au total avant de se voir à nouveau dans le classement.

**Comment by BastLast** [comment]
si shin fait la commande ça lui dit combien de combat il doit faire. étant donné que les étapes pour reproduire ce bug ne sont pas claire, je ferme cette issue, à rouvrir si plus d'infos
