### ISSUE TITLE
Mieux gérer les attaques de guilde

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2060]
Actuellement elles sont calculés en fonction de combien ya de membre de la guilde sur l'ile et je pense qu'on devrait faire un système plus tolérant parce que sinon si un groupe de joueur fait l'ile ensemble, le dernier qui fight le boss il a pas le bonus

**Comment by Feiryn** [comment]
Ça a bien été testé ça ?

**Comment by BastLast** [comment]
j'ai pas de news de bomba et noza mais je pense que je vais recruter d'autres @DraftBot-A-Discord-Adventure/testers  parce que je crois qu'ils étaient pas dispo. A ma connaissance ils ont bien testé mais pas parfaitement.

**Comment by BastLast** [comment]
ça mérite une petit check de plus parce que si ya un bug là dedans ça va être tendu à repérer
