### ISSUE TITLE
[BUG]: Moyenne hebdomadaire des points mal calculée

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2069]
### Description du bug.

En reçevant un mini-event sur le botFacts, le bot indique que les joueurs ont récolté tel nombre de points en moyenne dans la semaine. Or le classement hebdomadaire, si on regarde surtout les derniers, dépasse ce chiffre...

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

Avoir le mini-event botFacts parlant de la moyenne hebdomadaire de points récoltés. Constater que le top week dépasse (des fois *largement*) la moyenne, même sur les derniers.

### Captures d'écran

<img width="466" alt="Capture d’écran 2023-07-26 à 12 40 20" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/da075fac-9ac2-4319-9637-834646d55e30">
<img width="466" alt="Capture d’écran 2023-07-26 à 12 43 13" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/304d7b0e-95b4-4c8d-8318-92a5e91859ed">

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
Ça compte aussi ceux qui jouent pas

**Comment by Nargacaura** [comment]
C'est ce que je m'étais dit après cette issue, mais ça ne serait pas mieux de ne calculer que ceux qui sont dans le classement hebdo?

**Comment by BastLast** [comment]
> C'est ce que je m'étais dit après cette issue, mais ça ne serait pas mieux de ne calculer que ceux qui sont dans le classement hebdo?

Du coup c'est une suggestion pas un bug
