### ISSUE TITLE
Typos, bugs et suggestions finales pour le PVE

### ISSUE THREAD

**Issue by symsym-1629** [DraftBot-A-Discord-Adventure/DraftBot#2070]
2 typos : 
le cd est de 20s et non 60
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/83075391/c41e985a-46cb-40c1-9d55-a2a76a973657)

espèce inconnue https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/7eaec8ca491fe450d498412e5dc1db9438d839e1/resources/text/monsters/spider.json#L7C61-L7C70

**Comment by symsym-1629** [comment]
Peut etre ajouter un gain d'xp de guilde à la fin des fights

**Comment by BastLast** [comment]
Augmenter le lvl max des guildes a 150

**Comment by BastLast** [comment]
je laisse ça ouvert au cas ou il y ai d'autres typos

**Comment by BastLast** [comment]
je pense fermer cette isssue parce que elle cible rien de précis et que les typos ont été faites
