### ISSUE TITLE
[BUG]: rage à 0 de dégâts sur l'île

### ISSUE THREAD

**Issue by 0eddo** [DraftBot-A-Discord-Adventure/DraftBot#2071]
### Description du bug.

Je testais la classe écuyer avec le level 13 et je retournais sur l'île en payant mes 25 gemmes et en étant avec 175 d'énergie. Il était 9h14. J'ai fait les commandes test pour avancer le temps...puis je suis parti vers la Forêt de la pénombre. Je fais un mini event et je dois combattre un animal avec comme propositions 
⚡ Concentrer son énergie et attaquer
🏃 Fuir
Je choisis la première et j'obtiens une rage ++. peu de temps après je tombe face à un troll des forêts. Je test d'abord avec : attendre avant de combattre, 🔚 et ne rien faire. Puis je décide en fin de le fight et je déferle ma rage au premier tour. Le problème 0 de dégâts. 

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

1. aller sur l'île
2. prendre la direction de La foret de la pénombre
3. avoir un mini-event avec un pet en colère (dans ce cas là un mammouth furax) à combattre et choisir ⚡ Concentrer son énergie et attaquer parmi ces deux là : ⚡ Concentrer son énergie et attaquer 
4. Si il y a obtention de la rage ++, aller combattre le troll
5. Faire d'abord : ⏳ , puis 🔚, le no reaction et enfin décider de combattre le troll
6. attendre de voir la rage se déferler pour regarder les dégâts

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/140090736/11e5c953-9bed-4d6d-a5e6-94f4d028edea)
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/140090736/c0320eca-9750-450b-b3a5-a0eec7429b33)
fin du fight après la seconde capture

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by 0eddo** [comment]
ok je le fais

**Comment by BastLast** [comment]
Est-ce que la rage fonctionne des fois avec l'option sablier ? Ou c'est des que on a le sablier rip la rage ?

**Comment by Nargacaura** [comment]
La rage fonctionnait quelque soit l'option dans mes tests sur n'importe quel boss... sauf le squelette, de mon côté.

**Comment by 0eddo** [comment]
je viens de re-test contre le squelette avec rage ++ en faisant avant le sablier. cette fois ci ça a marché, 250 dégats

**Comment by BastLast** [comment]
Faut trouver le point commun a tous les trucs lu ça a fail

**Comment by Nargacaura** [comment]
Difficile de trouver un point commun à tout ça, vu que depuis mes derniers tests, j'en ai fait 9 autres contre le squelette (cette fois, au niveau 40 au lieu de 30, en archer), et:
- des 3 nouveaux fights sans se cacher, aucun n'a eu le 0 dégât
- des 3 autres avec le sablier, seul 1 rage sur 3 a causé des dégâts
- pareil pour les 3 tests du 🔚 que le sablier

**Comment by BastLast** [comment]
Bon clairement c'est pas lié à ça alors

**Comment by BastLast** [comment]
je ferme mais à rouvrir si le soucis est observé à nouveau @Nargacaura  si tu as le temps de tester demain ça serait super top

**Comment by Nargacaura** [comment]
> je ferme mais à rouvrir si le soucis est observé à nouveau @Nargacaura si tu as le temps de tester demain ça serait super top

J'ai pu faire 6 tentatives contre le squelette (celui avec lequel c'était le plus simple pour reproduire le bug), et ça m'a l'air fix d'après les résultats. À voir avec plusieurs autres tests d'autres testeurs, tho.

**Comment by BastLast** [comment]
Excellent
