### ISSUE TITLE
[BUG]: Mauvais nombre de personnes affichées sur l’île 

### ISSUE THREAD

**Issue by OrionYp** [DraftBot-A-Discord-Adventure/DraftBot#2092]
### Description du bug.

La ligne « nombre de membres sur l’île » du /guilde affiche 5 alors qu’on est 4 dans la guilde dont 3 sur l’île

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

/guilde 

### Captures d'écran

![00352EB8-3B14-477D-97E0-EB659B12FF00](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/128425910/d6595492-d099-4cdf-9ba5-644783f86935)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
Go essayer de recup un max d'informations là dessus svp
