### ISSUE TITLE
[BUG]: Affichage gloire

### ISSUE THREAD

**Issue by As-Nodt** [DraftBot-A-Discord-Adventure/DraftBot#2102]
### Description du bug.

La gloire n'apparaît plus sur les combats 

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Lancer un combat 

### Captures d'écran

![Screenshot_20230731-231423_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/96839617/530ce113-faae-46a7-a6a6-a081293a3b0b)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Voisin1234** [comment]
Waouh, quel combattant:)

**Comment by Bombafox** [comment]
Y a plus la classe aussi

**Comment by Bombafox** [comment]
Le top ne donne plus les places correctement


![Screenshot_20230802-1340202.png](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/96150225/a5bd23ac-d865-4fc1-8b70-b7ebcaca143a)

**Comment by Nargacaura** [comment]
> Le top ne donne plus les places correctement
> 
> ![Screenshot_20230802-1340202.png](https://user-images.githubusercontent.com/96150225/257817126-a5bd23ac-d865-4fc1-8b70-b7ebcaca143a.png)

En plus, ce n'est probablement pas montré ici, mais quand on n'est pas sur la bonne page du top, il met automatiquement "Vous êtes sur la page 1/x" au lieu de la bonne page.
