### ISSUE TITLE
Ajouter un système d'astuce

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2103]
Envoyer un conseil aléatoire dans le salon dédié (ajouté au fichier de config) chaque jour

**Comment by BastLast** [comment]
@ZRunner je pensais faire ça via draftbot mais en ft je pense que ça serait plus simple de le gérer via un bot à part genre zbot ou autre qui aille chercher une string random là dedans  https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/resources/text/advices.json et qui balance un message dans le salon défini avec une mention du rôle associé

**Comment by BastLast** [comment]
j'ai grave la flemme de le dev sur draftbot enft pr être honnete

**Comment by ZRunner** [comment]
> @ZRunner je pensais faire ça via draftbot mais en ft je pense que ça serait plus simple de le gérer via un bot à part genre zbot ou autre qui aille chercher une string random là dedans https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/resources/text/advices.json et qui balance un message dans le salon défini avec une mention du rôle associé

Je ne pourrais pas ajouter un tel système à Axobot, le but d'Axobot est d'être un bot public modulaire donc difficile de caser ce genre de fonctionnalité pour juste un seul serveur (même en supposant que je le rende configurable par serveur, personne ne l'utiliserait). Il faudrait donc créer un bot custom ayant pour seul but d'envoyer un message de temps en temps... pas hyper rentable mdr.

Je pense donc qu'utiliser Draftbot pour ça reste notre meilleure option. Ou, à la rigueur, une tâche CRON qui envoie le tip à un webhook.

**Comment by BastLast** [comment]
Yep jme suis mal exprimé jme demandais si ct viable de faire un bot custom qui ferait que ça ?

**Comment by ZRunner** [comment]
Bah, je pense que tu sais aussi bien que moi ce qui est possible de faire avec un bot Discord ptdr. Oui c'est totalement faisable. Même si, encore une fois, une tâche CRON serait plus indiquée (moins de ressources, moins de maintenance, etc.)

**Comment by BastLast** [comment]
on peut passer par github actions du coup ? genre 

```yaml
name: Daily Advice  
  
on:  
  schedule:  
    - cron: '0 0 * * *' # Runs every day at 00:00  
  
jobs:  
  send_advice:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v2  
  
    - name: Send daily advice  
      env:  
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  
      run: |  
        # Read JSON data  
        advices_json=$(cat path/to/your/advices.json)  
  
        # Extract advice strings  
        advices_list=$(echo "$advices_json" | jq -r '.translations.fr.advices[]')  
  
        # Get a random advice  
        random_advice=$(echo "$advices_list" | shuf -n 1)  
  
        # Send advice to Discord webhook  
        content=":bulb: **Astuce du jour** :\n\n$random_advice"  
        payload="{\"content\": \"$content\"}"  
        curl -s -X POST -H "Content-Type: application/json" -d "$payload" $DISCORD_WEBHOOK_URL ```

**Comment by BastLast** [comment]
<@&1136367073317113917>

**Comment by BastLast** [comment]
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/38099970/977381de-733b-45d5-a4e4-0fac65b344df)
