### ISSUE TITLE
[BUG]: la popo du jour différente selon le shard

### ISSUE THREAD

**Issue by Mura667** [DraftBot-A-Discord-Adventure/DraftBot#2105]
### Description du bug.

sur les shards 4 et 2 la potion du jour c'est le bizous'koup (depuis 3 jours) et sur le shard 0 c'est le miel.

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

- faire la commande /magasin sur le shard 0, 4 et 2 afin de constater que la potion du jour est différente

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/80298797/8ab29d81-66a7-4589-87cc-24473646d666)
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/80298797/bcf3908a-1c8d-4fe9-a31c-a4841259b999)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Feiryn** [comment]
J'ai pas le temps de corriger ça maintenant mais c'est à cause du cache des Settings, c'est le shard principal qui ordonnance le refresh de la potion
