### ISSUE TITLE
[BUG]: Bot qui se bloque en mini-event sur l'île

### ISSUE THREAD

**Issue by Flammenkuche** [DraftBot-A-Discord-Adventure/DraftBot#2106]
### Description du bug.

Ce jeudi 3 août vers 14h05, alors que j'étais en trajet sur l'île avec un autre membre de ma guilde, nous tentions de faire un mini-event avec la commande /report quand le bot s'est bloqué, stipulant que nous avions "Une action en attente". Cet autre membre de ma guilde et moi-même étions dans la même situation. On a retenté plusieurs fois de lancer la commande mais le même message d'erreur était affiché (voir screen)

On a donc attendu d'être arrivé à destination pour voir si le bot allait se débloquer mais le bot ne répondait toujours pas une fois arrivé.

Le problème s'est néanmoins résolu de lui-même au bout de 5 bonnes minutes.

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Je ne saurai dire comment faire, le but est arrivé soudainement, sans raison apparente et à disparu de la même manière 

### Captures d'écran

![Screenshot_20230803-140559_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/110783281/4039bb0e-646a-4297-a132-c597b24554ae)
![Screenshot_20230803-140956_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/110783281/b0443fbe-b296-424b-83d5-557b7e6e45b3)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

**Comment by BastLast** [comment]
hello, j'ai pas l'impression qu'on ai beaucoup d'infos sur ce bug est-ce que quelqu'un sait ce qu'il se passe @Feiryn  je crois que tu avais check les logs ? 

Si un testeur arrive a reproduire sur pre release

**Comment by Feiryn** [comment]
> hello, j'ai pas l'impression qu'on ai beaucoup d'infos sur ce bug est-ce que quelqu'un sait ce qu'il se passe @Feiryn je crois que tu avais check les logs ?
> 
> Si un testeur arrive a reproduire sur pre release

C'est un peu la mort les stacks async d.js, faudrait tout refactor en faisant des .catch() car c'est impossible de comprendre ce qu'il se passe

**Comment by BastLast** [comment]
Ok en attendant si un testeur arrive à reproduire on pourra bosser dessus en attendant je deplace en "cannot reproduce"

**Comment by Aikoo-Sama** [comment]
Cette issue me fait penser à #2139, n'est-elle pas une duplication ?

**Comment by BastLast** [comment]
Possible en effet, difficile à dire sans les logs

**Comment by BastLast** [comment]
bug aussi lié à #2175

**Comment by BastLast** [comment]
je ferme cette issue car la  #2175 est plus détaillée et présente mieux le problème
