### ISSUE TITLE
[BUG]: Les guildes de niveau 100 à 109 ne peuvent pas obtenir le badge 🪩

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2112]
### Description du bug.

Dû à un oubli (sûrement), les chances d'obtenir le badge 🪩 sont à 0% pour les guildes de niveau 100 à 109:

https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/646eab6bb500cfc8529b096782d0c426ae524ab3/src/core/constants/GuildDailyConstants.ts#L165-L176

Or un des critères d'obtention de ce badge est que la guilde devrait être au niveau *100* ou plus...

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

Mettre sa guilde à un niveau entre 100 ou 109. Faire énormément de /guilddaily... ou juste étudier le fichier GuildDailyConstants.ts.

### Captures d'écran

Pas de capture, mais voir le snippet dans la description.

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by R-remi** [comment]
je vais la faire
