### ISSUE TITLE
Ajouter des missions liées au pve

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2118]
Voilà une petite liste à laquelle j'ai pensé

- [x] Aller sur l'île pve 
- [x] Battre X boss (dispo en secondaire)
- [x] Rejoindre un équipier sur le bateau 
- [x] Battre X familiers sauvages (ou gagner x point de rage) (dispo en secondaire)
- [x] Être dans une guilde qui a plus de X points de guilde (campagne only)
- [x] Payer des gemmes pour rejoindre l'île (campagne only)

voir le framapad des missions pour voir les emplacements dans la campagne

**Comment by BastLast** [comment]
j'ai ajouté une liste d'idée à la description de l'issue, si des gens ont d'autres idées allez-y

**Comment by BastLast** [comment]
@romain22222  ya une pr du coup pour la dernière de la liste ?

**Comment by romain22222** [comment]
ouep mb j'ai zappé de la link

**Comment by BananePlantain** [comment]
je pense que mettre des missions de pve en journalière n'est pas du tout une bonne idée sachant que si le joueur à déjà fait ses 3 passages de l'ile de la semaine (ou ne veut pas payer de gemmes puisque les récompenses seront probablement inférieurs à 15 gems) cela la rend impossible or une mission journalière doit être possible pour tous (en plus les niveaux 0-19 n'y ont pas accès).
Puis parfois un passage ne suffit pas à vaincre X animaux ou boss
