### ISSUE TITLE
Rework campagne + ajout mission PVE

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2119]

**Comment by BastLast** [comment]
à faire après #2118

**Comment by Feiryn** [comment]
Pour la campagne je pense que ce serait bien d'ajouter une sauvegarde des missions déjà faites ou non car :
- Rajouter des missions qu'à la fin c'est pas fou car c'est pas équilibré et les joueurs de début du jeu n'auront pas de missions liées à certaines features
- Si on les ajoute au milieu les gens à la fin n'auront jamais la mission

Je propose d'enregistrer un blob binaire avec chaque bit qui correspond à une mission de campagne faite, par exemple :
Un joueur qui a en sauvegarde 0b1110111111111101, on sait qu'il lui manque la mission 4 et 15, on peut donc les lui faire faire

**Comment by BastLast** [comment]
J'aime bien go convertir ce commentaire en issue

**Comment by Feiryn** [comment]
Cette issue sert à ça en soit

**Comment by Feiryn** [comment]
Ah ouais non en fait ça marche pas car si on ajoute une mission au milieu faut tout décaler. Faut trouver un truc mieux

**Comment by Feiryn** [comment]
C'est chiant à faire et c'est le meilleur moyen de se planter

**Comment by BastLast** [comment]
On fait une fonction dans utils qu'on test avec des test unitaires et qu'on a juste à appeler avec des tests unitaire dans les migrations

**Comment by BastLast** [comment]
L'autre option c'est une table externe et une tablende jointure

**Comment by romain22222** [comment]
proposition : on donne un id aux missions (id string, pas int) qui serait unique à chaque mission de campagne, comme ca suffit de stocker dans le joueur à chaque nouvelle maj les nouvelles missions. La position de mission resterait, donnant la dernière mission à effectuer

**Comment by BastLast** [comment]
Nanpas dans le joeur pitié ca va faire une string gigantesque et indéchiffrable.

Tu fais une table missions campagne

Et une table "mission campagne done"
Qui contient une colonne "id player" et une "mission id"

Et tu peux faire un select qui te donne toutes les id de missions réussies

**Comment by Feiryn** [comment]
La table va grandir super vite ça va être lourd

**Comment by BastLast** [comment]
> La table va grandir super vite ça va être lourd

La table en question c'est 2 integer par ligne ca va pas prendre plus de place que ton blob

**Comment by Feiryn** [comment]
1 int = 8 octets

Pour un joueur ayant fait 50 missions :
50 * 2 * 8 = 800 octets

Si on ajoute une colonne dans la table MissionInfo :
50 / 8 = 9 octets pour stocker

Donc pour cet exemple on est sur un ratio de 8888%

Pour 100 missions ça fait un ratio de 12307%

**Comment by Feiryn** [comment]
Ah et j'ai pas compté le temps CPU pour faire la jointure

**Comment by Feiryn** [comment]
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/98115666/d25b8cb8-4244-4cda-8b93-a07acbf51fba)

**Comment by BastLast** [comment]
Alors go faire mon idée avec la fonction testé unitairement

**Comment by romain22222** [comment]
SALE POLUEUR

**Comment by BastLast** [comment]
> SALE POLUEUR

So tu as mieux go proposer

**Comment by BastLast** [comment]
cette story a été faire à travers la pr #2202
