### ISSUE TITLE
Traduction des maps en anglais

### ISSUE THREAD

**Issue by symsym-1629** [DraftBot-A-Discord-Adventure/DraftBot#2128]
### Description du bug.

La map du /map est pas traduite en anglais

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Mettre le bot en anglais
faire /map
constater

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/83075391/8afae8ab-743c-4c01-8428-f8eaed4b9ddb)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by symsym-1629** [comment]
J'ai fait la map de base dcp, je vais faire la map du pve de suite
![map draftbot v3 english version (1)](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/83075391/5619e894-5c8d-473f-8494-bef4de185e26)

**Comment by symsym-1629** [comment]
https://github.com/DraftBot-A-Discord-Adventure/Tools/commit/123c4bb93ecc0ef9cf268df596d75a4b9af7264c
Le générateur permet maintenant de créer les maps anglaises

**Comment by BastLast** [comment]
du coup la map pve ça donne quoi ?

**Comment by BastLast** [comment]
@symsym-1629 plop est-ce que tu vas avoir le temps de bosser là dessus ? sinon je décale d'une milestone

**Comment by symsym-1629** [comment]
plop c'est déjà fait, le problème c'est que ca requiert une maj du site pour upload les maps et ca casse les autres versions dcp

**Comment by symsym-1629** [comment]
car changement de structure

**Comment by BastLast** [comment]
> car changement de structure

Tu veux faire quoi comme changement de structure ?

**Comment by symsym-1629** [comment]
devant les ids des map j'ai mis fr_ ou en_, si tu veux voir le générateur de maps a été modifié en conséquence

**Comment by BastLast** [comment]
je te propose un truc, 
1: tu fais une pr sur website qui casse pas les trucs pr les maps en francais sur le bot actuel mais qui permet aux version anglaise de fonctionner (en gros on duplique les maps francaise pr le moment)
2: une pr sur le bot qui fais fonctionner le truc
3: on ouvre une issue pour pas oublier de cleanup les maps francaise plus tard
4: on fait la maj du bot comme ça
5: on fais le cleanup

**Comment by BastLast** [comment]
@symsym-1629 ça te va ?

**Comment by symsym-1629** [comment]
okay, faut juste gérer pour que l'update du site soit pas lourde au point de faire crash la task de build

**Comment by BastLast** [comment]
ça a déjà fail ?
