### ISSUE TITLE
Map à curseur manquante entre la rivière Vacarme et la Dune

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2129]
### Description du bug.

Toutes les maps à curseur fonctionnent... sauf sur ce trajet. En réalité, c'est pas dû à un mauvais format ou à un timeout de chargement, mais... c'est juste le fichier qui est manquant.

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Se rendre entre la rivière Vacarme et la Dune. Faire /map.

### Captures d'écran

![Screenshot_20230812-165855~2](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/01683672-1525-4f3b-b49a-dc86af4e7811)
![Screenshot_20230812-170239~2](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/3d8fe161-0b5f-400b-90fa-28d01b928f32)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by symsym-1629** [comment]
https://github.com/DraftBot-A-Discord-Adventure/Tools/commit/123c4bb93ecc0ef9cf268df596d75a4b9af7264c
J'ai ajouté la map manquante dans le générateur avec l'id 18_19

**Comment by Nargacaura** [comment]
Reste plus qu'à la générer et on pourra close cette issue dès que c'est mis dans le répo Website ;)

**Comment by symsym-1629** [comment]
je fais ca de suite, ca s'affiche direct sur le bot après ?

**Comment by Nargacaura** [comment]
Normalement, yep (pour ce cas-là, en tout cas).
