### ISSUE TITLE
[BUG]: A investiguer : double rapport invisible ???

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#2139]
### Description du bug.

1 : je lance un report : je recois le message "Vous lancez des commandes trop vite", bizarre j'ai fait qu'une commande depuis + de 6h

2 : je lance une autre commande (ici gd) : abanon tu peux pas t'es dans la commande report...

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

.

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/29299679/500918fe-fe72-46be-999b-8d4eb892ed66)
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/29299679/af4bd288-b62c-4e6b-8d07-d1f35798fe10)

### Sur quel shard avez vous rencontré le bug ?

Shard 3

**Comment by BastLast** [comment]
Possible de joindre les logs qui te concernent ?

**Comment by BastLast** [comment]
> J étais dans le rush ce matin, si un collab peut le faire (today à 6h)

Fais le quand tu peux jpense personne est dispo today

**Comment by romain22222** [comment]
Si : didi

**Comment by symsym-1629** [comment]
Pareil chez moi, shard 3 aussi

**Comment by BastLast** [comment]
quasi sûr que ceci est la meme chose que #2175 , est-ce qu'on a encore les logs de ce jour pour check ?
maybe qqun peut check la console voir si le bot avait restart un peu avant le report de cette issue ?

**Comment by BastLast** [comment]
du coup @voltou91  on a des news sur cette issue ?

**Comment by BastLast** [comment]
@voltou91  j'ai besoin de ton feedback stp

**Comment by BastLast** [comment]
Je ferme cette issue car très similaire à #2106
