### ISSUE TITLE
[BUG]: Commande pas affichée par moment

### ISSUE THREAD

**Issue by symsym-1629** [DraftBot-A-Discord-Adventure/DraftBot#2145]
### Description du bug.

Ca arrive par moment randoms : pas après une maj ou un reload du bot : la commande disparait comme ca sur un serv pour une personne, la commande peut être n'importe laquelle, le redémarrage discord y fait rien, je SUPPOSE que y'a pas d'override de commande dans le serv MAIS la commande est dans la liste. Les autres dans le serv peuvent faire la commande.

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

Taper /[votre commande]
espérer qu'elle disparaisse

### Captures d'écran

elles arriveront quand qlqun les enverra

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Nargacaura** [comment]
Apparemment, ce problème n'intervient que quand on écrit la commande en français, vu que l'écrire en anglais affiche bien la commande voulue. À voir si c'est pas un problème du côté de comment Discord traite les traductions des noms de commandes, tho.

**Comment by BastLast** [comment]
Du couo c un bug de discord je l'ai eu aussi
