### ISSUE TITLE
Equilibrage Monstres

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#2146]
Issue pour les suggestions de balancing concernant les monstres de l'ile PVE, que ca soit en positif ou négatif.

Je commence : Nerf la vague de lave du titan de magma : en vétéran, même avec une luck insane, t'as déjà du mal, alors quand il te sort la vague de lave, c'est genre tu passes de "j'espère que je vais win, wtf la luck que j'ai eu" à "bon bah... c'est le daron qui joue contre le feotus, il jouait un peu avec lui, puis à un moment le foetus a bavé, c'est à ce moment que le daron l'a retourné comme une crèpe party"

**Comment by BastLast** [comment]
j'ai nerf un peu la vague de lave et buff l'attaque du skeleton
