### ISSUE TITLE
Mise à jour des conseils

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2147]
Mettez dans les commentaires de cette issue les conseils nécessitant une mise à jour ou à ajouter dans le fichier `advices.json`.

Je commence avec ce conseil, à mettre à jour:
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/dd6f8e70414fe52a5bef21c2848ea52f06d687a5/resources/text/advices.json#L199
Ce ne sont pas que les joueurs les plus puissants du classement glorieux, mais **tous les joueurs ayant plus de 500 points de gloire** qui ont une compression de fin de saison, *qu'ils aient combattu ou non durant la saison*.

**Comment by Nargacaura** [comment]
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/dd6f8e70414fe52a5bef21c2848ea52f06d687a5/resources/text/advices.json#L30
... C'est encore prévu qu'on fasse d'autres tournois? Si on n'en fait plus, ce conseil ne sert plus à grand chose et peut être omis ou remplacé.

**Comment by Nargacaura** [comment]
Deux conseils à mettre à jour:
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/dd6f8e70414fe52a5bef21c2848ea52f06d687a5/resources/text/advices.json#L15
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/dd6f8e70414fe52a5bef21c2848ea52f06d687a5/resources/text/advices.json#L92
Ils parlent encore d'*achats* de classes, alors que les classes sont dorénavant gratuites. Dans le cas du second conseil, il serait possible de préciser qu'il y a un cooldown dépendant du tier de classe choisi.

**Comment by Nargacaura** [comment]
2 conseils sont vraiment similaires:
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/dd6f8e70414fe52a5bef21c2848ea52f06d687a5/resources/text/advices.json#L99
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/dd6f8e70414fe52a5bef21c2848ea52f06d687a5/resources/text/advices.json#L136
Peut-être en omettre/remplacer un?

**Comment by BananePlantain** [comment]
supprimer/modifier le conseil:

**Comment by BastLast** [comment]
> 2 conseils sont vraiment similaires:
> 
> https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/dd6f8e70414fe52a5bef21c2848ea52f06d687a5/resources/text/advices.json#L99
> 
> https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/dd6f8e70414fe52a5bef21c2848ea52f06d687a5/resources/text/advices.json#L136
> 
> Peut-être en omettre/remplacer un?

imo pas grave c'est un conseil important
