### ISSUE TITLE
Mini-event FightPet:appel au familier

### ISSUE THREAD

**Issue by BananePlantain** [DraftBot-A-Discord-Adventure/DraftBot#2149]
Salut,
Sur l'ile PVE,lorsque le joueur fait appel à son familier,même si il est meilleur que celui en face,il n'obtient pas de rage
![fam1](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/126412670/081d4000-c1a4-4bf5-9fe8-928530e70a12)
![fam2](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/126412670/f541f707-f38d-4ff3-8987-3ea14c89c340)
Ici nous avons affaires à des pets tous 2* tandis que les joueurs dans la capture d'écran ont tous un familier (mammouth) 4* dressée.
BananePlantain

**Comment by BananePlantain** [comment]
et que un 5* qui perd contre un 1* ça a 28% de chances d'arriver c'est absolutement pas réaliste

**Comment by BastLast** [comment]
C'est toi qui est pas réaliste

**Comment by BastLast** [comment]
En vrai je suis d'accord, ca sera buff
