### ISSUE TITLE
typos 4.4.4

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2151]
suite de la #2001

**Comment by 0eddo** [comment]
draft a demandé des nouveaux conseils voici mes propositions: 
"Vous pouvez libérer un familier uniquement toutes les heures"
"Etant un aventurier proche du roi vous avez accès à des fonds qui peuvent bien vous aider. Mais attention pour cela vous devez réaliser des missions particulières afin de payer l'accès à ses fonds !"
"Les autres aventuriers sont vos rivaux dans la quête pour la princesse ! Pensez à bien vous entourez grâce à vos partenaires de guilde"
"acheter des emplacements d'inventaire est un gros investissement qui peut se révéler utile dans le futur"

ptite joke:
"On raconte qu'au mont celestrum une créature rôde inlassablement dans les cavernes. Les rares l'ayant vu le décrivent comme ayant une allure de pingouin géant"

on peut faire des conseils pour le pve? comme ce seront des conseils du bot et pas des rapports classique ?

**Comment by leuhvraiminoryo** [comment]
je pose ça là même si c'est pas exactement une *typo* per se,

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/50586611/79168608-23aa-4ee9-b3cc-135eca3d3e2b)

sur la commande guild dans la version anglaise du jeu, il manque les ":" fermants aux emotes "de grade" des membres

**Comment by BastLast** [comment]
> draft a demandé des nouveaux conseils voici mes propositions (celui pour les équipements est de banane plantain ): "Vous pouvez libérer un familier uniquement toutes les heures" "Etant un aventurier proche du roi vous avez accès à des fonds qui peuvent bien vous aider. Mais attention pour cela vous devez réaliser des missions particulières afin de payer l'accès à ses fonds !" "Les autres aventuriers sont vos rivaux dans la quête pour la princesse ! Pensez à bien vous entourez grâce à vos partenaires de guilde" "acheter des emplacements d'inventaire est un gros investissement qui peut se révéler utile dans le futur"
> 
> ptite joke: "On raconte qu'au mont celestrum une créature rôde inlassablement dans les cavernes. Les rares l'ayant vu le décrivent comme ayant une allure de pingouin géant"
> 
> on peut faire des conseils pour le pve? comme ce seront des conseils du bot et pas des rapports classique ?

j'en ai ajouté certains en 4.4.3

**Comment by voltou91** [comment]
Dans le json il manque pour deux catégorie le "sunny" 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/62652451/eb931bde-d9dc-423b-8eda-eb3da1ffb3dc)

**Comment by Nargacaura** [comment]
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/db7053ed6adefd0986fef8e00a41961843a3dcc4/resources/text/advices.json#L132

Faudrait préciser que c'est *sur le continent princial uniquement* qu'un trajet dure entre 1 et 10h, à l'exception du trajet du tutoriel entre les portes du château et la salle de réception. Sur l'île, c'est des trajets principalement de 4-5min et entre 10 et 30 sur le bateau.

**Comment by Nininanou16** [comment]
Hello, je crois qu'il y a un soucis dans le nom de l'attaque riposte, qui dans les logs des combat apparait comme "attaque bouclier", tandis que l'attaque bouclier apparait bien comme attaque bouclier. L'emoji pour sa part est bon !
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/71654580/606d5b64-45b7-4ede-9de4-1574d494839d)

**Comment by BastLast** [comment]
j'ai fix les typos au dessus de ce commentaire si quelqu'un a le temps de check que yen a pas des nouvelles qui ont été report sur le discord du bot mais quis ont pas ici ça serait super  @DraftBot-A-Discord-Adventure/testers

**Comment by Nargacaura** [comment]
Alors voilà la plupart des typos reportées sur Discord et qui ne sont pas sur GitHub:
<img width="332" alt="Capture_decran_2023-08-01_a_18 04 42" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/a00fd5d7-5c39-4bed-82fe-90a2ffa43f70">
"sur la plage noir**e**"

![Donia](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/39f61542-4e73-4e06-b83d-e2651a7c912f)
"et ~~se~~ annonce se prénommer"

![Donia2](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/85b0ed18-6f1c-424b-a42a-8f95d02cf8ea)
"elle conna**î**t"

![etourdi](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/773f28bd-adf5-4d33-bb3a-d7b04ca67e98)
"Étourdi~~e~~" (sinon on aurait eu "arrivé*e*" au début de l'issue)

![frele_aventurier](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/1361e610-a77c-4bd4-944f-0f9a5fed32d6)
"quel**le** classe", "pour être vendu**s**"

![gouffre](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/4197eab1-3a6b-44e3-9023-000ff5bf3508)
"le gouffre rempli~~s~~"

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/ac52028e-43b0-480d-8865-5de0acd23b4b)
"n'est que renforcé**e**"

![image2](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/87b06a9b-73d2-4120-8e8b-db7344933c86)
"à vous entoure**r**"

![Screenshot_7](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/5d61f77c-bbec-4cf7-ae24-4b68f5034c92)
"lance un~~e~~ lancer de rocher" (ou "lance un ~lancer de~~ rocher")

![Screenshot_9](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/2a2ba6c2-3626-4a9d-bf64-47ebfdf9361a)
"d'un assau~~l~~t"

S'il y en a d'autres qui sont sur le thread des typos et qui vous semblent important à mettre dedans, vous pouvez le rajouter, mais voilà ceux les plus flagrants.

**Comment by BastLast** [comment]
merci, j'ai tout fix

**Comment by BastLast** [comment]
je ferme cette issue merci d'utiliser l'issue ci-dessus pour les prochaines typos
