### ISSUE TITLE
Gd completes mission 

### ISSUE THREAD

**Issue by quenquentin** [DraftBot-A-Discord-Adventure/DraftBot#2157]
![Screenshot_2023-09-01-07-09-23-805_com.discord-edit.jpg](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/56274541/fcc8770b-c9e8-43f1-91e6-ecefe0f3a82d)

**Comment by BastLast** [comment]
je crois que c'est un duplicata d'une discussion ou issue , possible de check ?

**Comment by Nargacaura** [comment]
Me semble pas qu'il y ait eu d'issue ou de discussion qui parlait déjà de ça auparavant.

**Comment by BastLast** [comment]
du coup je ferme cette issue pour plusieurs raisons:

- C'est pas un bug puisque ça a été conçu comme ça c'est donc une suggestion qui ne devrait pas être une issue
- Coder une notification pour cela serait un peu couteux par rapport aux bénéfices pour les joueurs donc je pense pas que ça soit sur notre radar à court terme. 

Idéalement go reposter ceci sous forme de discussion pour qu'on puisse le traiter quand on aura assez de dev
