### ISSUE TITLE
Rework seed PVE

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#2167]
Passer en ms et virer l'xp

**Comment by BastLast** [comment]
Je crois que jai fait la conversion parce que ca finissais par 000

**Comment by BastLast** [comment]
À vérifier

**Comment by Feiryn** [comment]
Dans ce on prendra d'autres paramètres moins variables que l'xp

**Comment by BastLast** [comment]
je confirme que ça finis par 000

**Comment by BastLast** [comment]
dis moi si ça te convient nysvaa
