### ISSUE TITLE
[BUG]: Double mise d'une altération

### ISSUE THREAD

**Issue by voltou91** [DraftBot-A-Discord-Adventure/DraftBot#2168]
### Description du bug.

Lors d'un event, il met deux fois une altération sur le personnage, cela fausse à la fois nos logs et impacte le bot en raison des calculs des dates qui est dupliqué.

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

Juste se tapper une alté dans un event.

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/62652451/3d0f59c9-7956-462a-b4af-b9c7fcdd40e9)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by voltou91** [comment]
Copie collé de ce que j'ai mit sur discord :

 c'est à cause de ça https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/db7053ed6adefd0986fef8e00a41961843a3dcc4/src/commands/player/ReportCommand.ts#L370
et de ça https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/db7053ed6adefd0986fef8e00a41961843a3dcc4/src/commands/player/ReportCommand.ts#L424
dans le premier lien, en démarrant un trajet il applique l'effet
et dans le deuxième lien dans la fonction en appliquant l'outcomeEffect à la ligne 216, il setLastReportWithEffect qui applique lui aussi un effet

**Comment by BastLast** [comment]
@voltou91  vu que tu as fait l'analyse est-ce que tu aurais le time de fix ça ?

**Comment by voltou91** [comment]
oui
