### ISSUE TITLE
Bug commende

### ISSUE THREAD

**Issue by Voisin1234** [DraftBot-A-Discord-Adventure/DraftBot#2178]
### Description du bug.

Depuis hier la quasi totalité des commendes  que je fais est refusé par le Bot. Soit ça m’écrit que j’envoie les comme des trop vite alors que je laisse un temps entre chaque commande et parfois j’ai que je ne peux effectuer de commande parce que j’ai un /report en attente. Sur le discord officiel c’est mieux mais pas ouf non plus . A l’aide 

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

Toutes les commandes 
 

### Captures d'écran

![IMG_5546](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/c07757df-2ba5-4358-8c06-69b369f9c75f)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by BastLast** [comment]
je ferme cette issue car duplicata de #2139
