### ISSUE TITLE
[BUG]: Bypass possible des commandes interdites ou bloquantes avec /joinboat

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2182]
### Description du bug.

On peut littéralement faire des commandes interdites et/ou bloquantes sur le bateau en faisant /joinboat, vu qu'il manque la condition suivante dans le code:
```ts
if (await sendBlockedError(interaction, language)) {
    return;
}
```

Ce qui veut dire que quelqu'un peut régèn son énergie, combattre ou avancer son temps de trajet sur le bateau juste avec cette commande si exécutée *pendant* la commande bloquante!

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Faire une commande demandant une interaction (en gros, une bloquante). Ne pas encore toucher aux réactions, puis faire /joinboat. Accepter de rejoindre les autres membres. Accepter la demande de la commande bloquante ou réagir à un event.

### Captures d'écran

<img width="928" alt="Capture d’écran 2023-09-22 à 19 12 16" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/c0552da9-72b2-4b0a-9202-de020248b63d">
<img width="928" alt="Capture d’écran 2023-09-22 à 19 12 24" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/174c9e32-5a5b-4a3f-90c0-5ee524229728">
<img width="1172" alt="Capture d’écran 2023-09-22 à 19 13 04" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/f7c71286-d453-42ab-b700-7e3d1a4a5a74">

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by voltou91** [comment]
Effectivement j'ai oublié de mettre ça quand je l'ai créé (à vrai dire je savais même pas que fallait mettre ça), je vais fix ça mtn
