### ISSUE TITLE
typos 4.4.5

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2195]
suite de la #2151

**Comment by Noelle-Ai** [comment]
Je sais pas trop où le mettre donc je le met ici, le "pronom" de l'objet parapluie de grand mère n'est pas correct. Ce n'est pas "sa" mais "son" 😉 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/268fafa0-153f-416a-9a2c-47cd8111de13)

**Comment by BastLast** [comment]
> Je sais pas trop où le mettre donc je le met ici, le "pronom" de l'objet parapluie de grand mère n'est pas correct. Ce n'est pas "sa" mais "son" 😉 
> ![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/268fafa0-153f-416a-9a2c-47cd8111de13)
> 

C'est le bon endroit pr le mettre

**Comment by Noelle-Ai** [comment]
> > Je sais pas trop où le mettre donc je le met ici, le "pronom" de l'objet parapluie de grand mère n'est pas correct. Ce n'est pas "sa" mais "son" 😉
> > ![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/268fafa0-153f-416a-9a2c-47cd8111de13)
> 
> C'est le bon endroit pr le mettre

Où dois-je le mettre ?

**Comment by BastLast** [comment]
> > > Je sais pas trop où le mettre donc je le met ici, le "pronom" de l'objet parapluie de grand mère n'est pas correct. Ce n'est pas "sa" mais "son" 😉
> > > ![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/268fafa0-153f-416a-9a2c-47cd8111de13)
> > 
> > C'est le bon endroit pr le mettre
> 
> Où dois-je le mettre ?

Bah ici c'est très bien merci :)

**Comment by Noelle-Ai** [comment]
> > > > Je sais pas trop où le mettre donc je le met ici, le "pronom" de l'objet parapluie de grand mère n'est pas correct. Ce n'est pas "sa" mais "son" 😉
> > > > ![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/268fafa0-153f-416a-9a2c-47cd8111de13)
> > > 
> > > 
> > > C'est le bon endroit pr le mettre
> > 
> > 
> > Où dois-je le mettre ?
> 
> Bah ici c'est très bien merci :)

Ah sorry j'ai lu "pas le bon endroit" my bad, de rien !

**Comment by raf972** [comment]
Salut, j'ai remarqué que la commande pour nourrir un familier contient une faute d'orthographe, en effet : /nourrirfami**ll**Ier
