### ISSUE TITLE
vérifier que les changements de l'issue 2119 fonctionnent bien

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2204]
- [x] merge #2203 
- [x] préparer des testeurs sur pre release en les mettant à divers endroits de la campagne pour check la migration
- [x] ajouter une nouvelle mission de #2118 dans la campagne
- [x] check si la migration s'est faite correctement en pre-release
- [x] fix les éventuels bugs de migration avant que ça soit sur master

**Comment by BastLast** [comment]
@romain22222  ce dont on a discuté en #2203 voilà l'issue pour suivre

**Comment by romain22222** [comment]
ok bah du coup je te laisse review :doge:
