### ISSUE TITLE
Ajouter l'alté "perdu" là où c'est cohérent

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2207]

**Comment by BananePlantain** [comment]
évènement 55 l'issue 3 peut nous faire se perdre
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/resources/text/events/55.json

**Comment by 0eddo** [comment]
event 22 le choix 1 te fait te perdre ainsi que le choix 3 de l'issue 1 

https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/resources/text/events/11.json

**Comment by Gabrielre14** [comment]
Désolé du retard, mais personne ne signale de nouveaux events. Alors je balance le dernier auquel je pense qui peut avoir ce changement... 
L'event de la grotte de la Forêt Célestrum, le choix 1 (explorer la grotte) peut te faire te perdre dans un labyrinthe de galeries... (1/3)
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/resources/text/events/6.json
