### ISSUE TITLE
Les boosts de dégats des prolongations appliqués aussi à l'attaque sombre

### ISSUE THREAD

**Issue by Gabrielre14** [DraftBot-A-Discord-Adventure/DraftBot#2214]
### Description du bug.

Bon… ce bug peut être aussi lié au post (#2173 : https://github.com/DraftBot-A-Discord-Adventure/DraftBot/issues/2173) montrant que la discrétion de l'Araignée (boss de l'île PvE) pouvait aussi doubler les dégâts de l'attaque boomerang (uniquement apparemment) du canonnier. Ou pas. A ce moment-là on m'avait dit que 600 de dégâts par cette attaque était un coup de chance…

Après avoir vu le screen vous ne pourrez pas dire que c'est un coup de chance. Une autre attaque est un peu buggée sur l'île PvE concernant les boosts de dégâts, et notamment le boost de dégât des prolongations. 

J'étais en plein combat contre le golem, le 3e boss (oui en mage j'ai réussit à aller jusque là x) ), et vu que ce lâche se surprotège on était aux prolongations. Comme prévu, mes attaques personnelles font autant de dégâts qu'auparavant jusqu'à ce que je puisse envoyer une attaque sombre qui lui a mis du 1,5K DE DEGATS. J'avais jamais vu ça depuis la màj des fights il y a des mois de cela. 

J'en conclus donc (mais ça reste à tester) que les boosts de la prolongations des boss sont aussi appliqués à l'attaque sombre uniquement (car les dégâts des autres attaques n'ont pas changé…)

Et si vous me dites encore que c'est un coup de chance que j'ai eu je ne peux plus rien faire pour vous… XD

### Selon vous, quelle est l'importance de ce bug ?

😨 Grave

### Reproduction du bug.

Aller sur l'île PvE avec la classe mage
Combattre le golem (ou un autre boss, à tester) jusqu'aux prolongations
Attendre quelques tours pour augmenter le boost de dégats et lancer une attaque sombre.
Rester sidéré quelques minutes faces aux dégats monstrueux de cette attaque...

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/3b6aa4fe-4051-4275-88bc-5bf9cdbf0a04)
(c'était au moins le 34e tour)

### Sur quel shard avez vous rencontré le bug ?

Shard 4

**Comment by Gabrielre14** [comment]
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/3e981caa-a63d-4527-b915-54d66d4cf37b)
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/5d1cbcc5-743d-4b90-a7f8-db3d5646be0a)


j'ai montré ici les stats des deux adversaires (j'étais au niveau 200) et les dégats faits avec l'attaque sombre (tour 34)...

Pour info, voici les dégats habituels de l'attaque sombre contre ce boss : 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/b8b08611-8d41-41de-b598-4a20c9962632)

**Comment by romain22222** [comment]
d'après le code, c'est un comportement normal : l'attaque sombre a une probabilité de 65% de faire en plus 15% de l'attaque de la victime en dégâts supplémentaires, à voir si faut rework le comportement de l'attaque mais ce n'est pas un bug

**Comment by BastLast** [comment]
Fixé dans #2154
