### ISSUE TITLE
[BUG]: Les missions 16 à 60 sont visiblement décalées

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2216]
### Description du bug.

En ayant fait /profile, j'ai remarqué que j'ai complété 100% de la campagne sans avoir terminé la mission des points de gloire. En faisant /missions, je m'aperçois qu'elle a été placée dans le slot *61/60*. Du coup, je présume que les missions 16 (dépenser des gemmes) à 60 (avoir 1200 points de gloire) ont *toutes* été décalées.

### Selon vous, quelle est l'importance de ce bug ?

😱 Très grave

### Reproduction du bug.

Faire /missions si on est sur une des missions entre 16 et 60.

### Captures d'écran

Exemple avec la mission 60:
<img width="471" alt="Capture d’écran 2023-10-18 à 19 32 28" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/0faebc92-6474-488d-8ef0-897dc4399947">

### Sur quel shard avez vous rencontré le bug ?

Tous les shards de la version stable

**Comment by romain22222** [comment]
alors précision : les missions SONT décalés, c'est normal, cependant le truc pas normal, c'est que le n° de campagne max est pas bon

**Comment by romain22222** [comment]
anti précision : c'est sur l'offi donc c'est pas ca

**Comment by Nargacaura** [comment]
Petite précision: ce souci n'impacte cependant que les personnes touchant à la campagne sur le bot de pre-release et qui n'ont pas terminé leur campagne sur la version stable.

**Comment by romain22222** [comment]
wait wha

**Comment by Nargacaura** [comment]
Contre-précision: ça n'a pas décalé que chez ceux qui ont touché le bot de pre-release, après revérification. En gros, c'est comme si la mission 16 était là mais n'existe pas, décalant le tout depuis la mission de la dépense des gemmes d'iune case.

**Comment by romain22222** [comment]
problème de sécurité entre le bot de pre release et celui de l'officiel : le bot de pre release a la possibilité de modifier les données côté officiel, c'est pas bon DU TOUT

**Comment by BastLast** [comment]
bug corrigé, certains joueurs ont sauté une mission mais tant pis
