### ISSUE TITLE
Problème dans le passage de level 

### ISSUE THREAD

**Issue by Thefox60** [DraftBot-A-Discord-Adventure/DraftBot#2228]
### Description du bug.

Sur le Bot prerealeas quand on passe le level 5 et 6en même temps avec un rapport on a deux messages de passage du level 6sans le message du passage du level 5

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

On doit être level 4est passer level 6avec un seul /rapport 

### Captures d'écran

![Screenshot_2023-10-20-15-08-54-869_com discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/139173842/352edfaf-1122-47e0-beeb-2442eb69bb68)
![Screenshot_2023-10-20-15-06-00-057_com discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/139173842/5d0aadcb-fb31-4519-8d3e-930169a77e65)

### Sur quel shard avez vous rencontré le bug ?

Bot de test

**Comment by BastLast** [comment]
ce bug va imo necessiter plus de temps que ce que j'ai aujourd'hui donc je décale en 4.4.6
