### ISSUE TITLE
TYPOS 4.4.7

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2231]
suite de #2195 

Merci de signaler les typos ici :)

**Comment by Nargacaura** [comment]
![image.png](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/8fa2f1e1-5131-46f0-a5ef-48ba791f870c)

Y'a un 's' en trop dans la mission de gagner 1 point de rage (dû au fait qu'il n'y a pas `{objective > 1?s:}` dans le JSON de la mission)

**Comment by Aikoo-Sama** [comment]
J'ai un gros doute sur le genre de Exagide, je pense que ça vient du Pokémon mais vu que ce dernier (et l'emote de l'objet) symbolise une épée, on dirait plutôt "une" Exagide non ?

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/f7736f05-1b6d-444b-b60c-e1120035c417)

**Comment by BananePlantain** [comment]
"Les marchands ambulants ne vendent jamais d'équipement légendaire ou épique." conseil plus à jour/à modifier ne vendent jamais de mythique
