### ISSUE TITLE
Bugs sur les commandes tests

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#2235]
Cette issue est la pour recenser les bugs sur les commandes tests.

Tous les bugs devront être accompagnés du contexte dans lequel ils ont été trouvés ainsi qu'un screen de l'erreur (console ou chat)

Si c'est un bug de fonctionnement, dire ce qui va pas.

**Comment by Nargacaura** [comment]
Faire `/test skiptuto` place le joueur directement sur le bateau pour quitter l'île au lieu d'un endroit aléatoire du continent principal.
(ex. sans avoir utilisé de /test travel — à la base, c'était juste pour tester la mission drinkEnergyPotion)
<img width="247" alt="Capture d’écran 2023-10-21 à 11 23 28" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/92437e52-1f78-4f21-b5ee-0531587e3b94">

**Comment by Nargacaura** [comment]
Lié à #1665 — exécuter `/test finditem <catégorie> <id>` n'émet aucune réponse, il n'affiche que l'objet trouvé.
<img width="322" alt="Capture d’écran 2023-10-21 à 11 26 00" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/68ea372e-9f3c-49e3-8267-df84a1eb849b">

**Comment by Nargacaura** [comment]
On ne peut plus changer le blob des missions avec `/test setCampaignBlob`, il n'enregistre plus le blob donné en base, laissant la progression actuelle du joueur.
<img width="466" alt="Capture d’écran 2023-10-21 à 12 05 12" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/78b82056-c989-4a2f-9382-576e76fd46da">

**Comment by Nargacaura** [comment]
`/test setCampaignBlob` n'a aucun effet si le joueur n'a pas encore interagi avec la campagne — aucun blob n'est créé avant de toucher une mission de campagne.
<img width="466" alt="Capture d’écran 2023-10-21 à 12 05 12" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/c3cb843e-1ede-45d0-9d66-2d88d2268951">

**Comment by romain22222** [comment]
> Faire `/test skiptuto` place le joueur directement sur le bateau pour quitter l'île au lieu d'un endroit aléatoire du continent principal. (ex. sans avoir utilisé de /test travel — à la base, c'était juste pour tester la mission drinkEnergyPotion) <img alt="Capture d’écran 2023-10-21 à 11 23 28" width="247" src="https://user-images.githubusercontent.com/94372084/277099622-92437e52-1f78-4f21-b5ee-0531587e3b94.png">

précision : skiptuto mets sur un chemin random sur la map. Tu as donc une proba de pas tomber sur le continent

**Comment by romain22222** [comment]
> > Faire `/test skiptuto` place le joueur directement sur le bateau pour quitter l'île au lieu d'un endroit aléatoire du continent principal. (ex. sans avoir utilisé de /test travel — à la base, c'était juste pour tester la mission drinkEnergyPotion) <img alt="Capture d’écran 2023-10-21 à 11 23 28" width="247" src="https://user-images.githubusercontent.com/94372084/277099622-92437e52-1f78-4f21-b5ee-0531587e3b94.png">
> 
> précision : skiptuto mets sur un chemin random sur la map. Tu as donc une proba de pas tomber sur le continent

autre chose : la fonction appelée (getRandomLink) est aussi appelée si le maplink du joueur est à null, ce qui correspond à 1527 joueurs

**Comment by romain22222** [comment]
> Faire `/test skiptuto` place le joueur directement sur le bateau pour quitter l'île au lieu d'un endroit aléatoire du continent principal. (ex. sans avoir utilisé de /test travel — à la base, c'était juste pour tester la mission drinkEnergyPotion) <img alt="Capture d’écran 2023-10-21 à 11 23 28" width="247" src="https://user-images.githubusercontent.com/94372084/277099622-92437e52-1f78-4f21-b5ee-0531587e3b94.png">

fixed (cf #2243)

**Comment by BastLast** [comment]
est-ce que tous les bugs au dessus sont fix ? pr savoir si on peut close cette issue après le merge de la PR

**Comment by romain22222** [comment]
techniquement oui ils le sont tous

**Comment by BastLast** [comment]
ok go close cette issue et en rouvrir une si besoin alors
