### ISSUE TITLE
[BUG]: L'event du fermier a une réaction cassée

### ISSUE THREAD

**Issue by Nargacaura** [DraftBot-A-Discord-Adventure/DraftBot#2238]
### Description du bug.

Visiblement, une de ces issues-là (liées à la réaction 👥) fait que le bot ne répond plus:
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/80ab01e3b2f97599b610462605c5072a53897279/resources/text/events/22.json#L51-L95

Le joueur est bloqué dans ce report qui est cassé. La source de ceci m'échappe encore, malgré que j'ai comparé ce JSON avec certains autres events et d'autres issues de celui-ci.

### Selon vous, quelle est l'importance de ce bug ?

🤔 Je ne sais pas

### Reproduction du bug.

Forcer l'event 22 (le fermier). Choisir 👥. Constater qu'il ne répond pas, et vous êtes bloqués dans cet event.

### Captures d'écran

<img width="837" alt="Capture d’écran 2023-10-21 à 12 43 22" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/94372084/86f36ef1-0acd-4f0e-b653-0558760a64f6">

### Sur quel shard avez vous rencontré le bug ?

🤖 bot de test 'officiel' (alpha ou bêta)

**Comment by romain22222** [comment]
je vais me tirer une balle, remember quand vous m'avez supplié de rajouter le fait de dépenser de l'argent dans les events, bah c'est lié

**Comment by Nargacaura** [comment]
Ok, j'ai reproduit avec l'event 11 ce bug. Je pense qu'il crash quand `money` est négatif mais qu'il n'y a pas ceci:
```json
"tags": [
	"moneyUsage"
]
```

**Comment by Nargacaura** [comment]
Plus précisément, on ne vérifie pas s'il y a `outcome.tags` sur cette ligne (en gros, ça doit donner quelque chose du style `Cannot read proprties of 'null'`):
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/80ab01e3b2f97599b610462605c5072a53897279/src/core/events/PossibilityOutcome.ts#L91

**Comment by romain22222** [comment]
> Plus précisément, on ne vérifie pas s'il y a `outcome.tags` dans l'issue sur cette ligne (en gros, ça doit donner quelque chose du style `Cannot read properties of 'undefined'`):
> 
> https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/80ab01e3b2f97599b610462605c5072a53897279/src/core/events/PossibilityOutcome.ts#L91
> 
> Une idée pour corriger ça serait de mettre ceci à la place:
> 
> ```ts
> if (!isMoneyChangePositive && outcome.tags && outcome.tags.includes("moneyUsage")) {
> ```

c'est quasi sur que c'est ca, marque juste plutot :

```ts
if (!isMoneyChangePositive && outcome.tags?.includes("moneyUsage")) {
```

**Comment by BastLast** [comment]
si tous les bugs report pouvaient être aussi beaux

**Comment by BastLast** [comment]
le monde ressemblerait à ça 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/38099970/d929fc14-c6c9-4f82-a392-bcda134754ef)
