### ISSUE TITLE
[BUG]: log un pet peut causer une erreur sql

### ISSUE THREAD

**Issue by voltou91** [DraftBot-A-Discord-Adventure/DraftBot#2239]
### Description du bug.

J'ai juste regarder les logs, aucune idée de comment il est arrivé

### Selon vous, quelle est l'importance de ce bug ?

😐 Normale

### Reproduction du bug.

Aucune idée de comment le reproduire

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/62652451/9b0d3373-d831-45d9-8cc5-73f5db4927d5)

### Sur quel shard avez vous rencontré le bug ?

Shard 4

**Comment by Nargacaura** [comment]
Y'a pas un problème dans le typage ou la rangée de la colonne dans la base de données? Cette erreur arrive généralement quand une valeur numérique est trop grande pour être stockée en base.

**Comment by BastLast** [comment]
en conclusion on sait pas ce qu'il se passe ?

**Comment by voltou91** [comment]
Non on sait pas ce qu'il se passe. Je me souviens plus si c'était au moment où on avait update le package puis enfaite ça cassait tout donc on est revenu à une version stable. Mais du coup si c'était ça bah c fixé vu qu'on est revenu à un package stable.

**Comment by BastLast** [comment]
Bon je close et si ce va pas on recouvrira
