### ISSUE TITLE
[BUG]: Il nous manque une perm qu'on ne vérifie pas lors du lancement des commandes

### ISSUE THREAD

**Issue by voltou91** [DraftBot-A-Discord-Adventure/DraftBot#2241]
### Description du bug.

tout est dans le titre

### Selon vous, quelle est l'importance de ce bug ?

🙂 Faible

### Reproduction du bug.

A tester quelle perm il nous manque

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/62652451/f3fa6b2c-8acd-4ba3-af9f-8db2212a0c2b)

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Nargacaura** [comment]
Visiblement, ça a lancé l'erreur à cet endroit:
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/d1a40139493b70f0747ffa3aa3273cb2b5cb7ca1/src/commands/player/ReportCommand.ts#L424-L432

Donc une théorie serait que quelqu'un ait coupé l'autorisation au bot d'envoyer des messages sur un serveur alors qu'un autre joueur sur ce même serveur était en plein event.

**Comment by BastLast** [comment]
ou c'est juste que qqun a fait rapport
alors que le bot a pas les perms pr les réactions

**Comment by Nargacaura** [comment]
> ou c'est juste que qqun a fait rapport alors que le bot a pas les perms pr les réactions

Pas sûr, vu que cette ligne (qui a lancé l'erreur) est appelée quand il choisi une issue via une réaction.

**Comment by romain22222** [comment]
Si c'est bien le cas (modification restrictive des permissions pendant utilisation), je propose que ca soit fix par le middleware lors de la v5 : faire en sorte que si la requête marche pas ca tente d'envoyer d'une manière ou d'une autre une erreur de secours au joueur (d'abord un message public, puis un ephemeral, puis un dm, dans tous les cas faire remonter l'erreur dans un channel dédié chez nous)

**Comment by BastLast** [comment]
je pense pas que ça soit pendant utilisation...
