### ISSUE TITLE
[BUG]: mission rejoindre un membre sur l'île se validant sans aller sur le bateau

### ISSUE THREAD

**Issue by DoctorT1807** [DraftBot-A-Discord-Adventure/DraftBot#2251]
### Description du bug.

La mission rejoindre un membre sur l'île se valide même si je ne possède pas les 💎 nécessaire pour un deuxième voyage.

### Reproduction du bug.

Faire un premier voyage sur l'île
Avoir moins de 15 💎
Avoir un membre de sa guilde sur le bateau
Rejoindre ce membre de la guilde avec la commande et validé
La mission est validé mais vous n'avez pas rejoin le bateau par manque de 💎 

### Captures d'écran

![Screenshot_20231024_113302_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/89483734/b8ffd2a7-35f8-4c7c-ad0a-bf12ff05d8e7)

### Sur quel shard avez vous rencontré le bug ?

![Screenshot_20231024_121325_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/89483734/1992be8d-2f03-4367-9f32-50d7894f2365)

**Comment by Nargacaura** [comment]
En vrai, c'est aussi le fait que cette mission s'est validée alors que tu n'as même pas fait /joinboat qui pose problème. Mais y'avait-il une autre personne de ta guilde qui était sur le bateau à ce moment-là?
