### ISSUE TITLE
Temps de récupération des fights bloque les joueurs actifs à cause de la limite

### ISSUE THREAD

**Issue by Aikoo-Sama** [DraftBot-A-Discord-Adventure/DraftBot#2254]
Je voulais signaler un problème avec la 4.4.5 : La réduction du temps de récupération est selon moi trop élevée. En effet, le nombre de joueurs faisant du pvp régulièrement n'est pas très grand, ce qui fait qu'en enchaînant les combats contre eux bah on est mardi et j'ai fait le max de combat avec les 2/3 des combattants de ma ligue. Et il n'y a pas que moi d'autres combattants comme Zozotte qui font beaucoup de combat finissent par être de plus en plus bloqué, ce qui va nous paralyser pour le reste de la semaine.
C'est pourquoi je pense que réduire cette augmentation ou augmenter le nombre de fight max par combattant peut être pertinent

**Comment by BastLast** [comment]
Le nombre de fight max par combattant est là pour limiter le feed fight, c'est plutot sain si les joueurs atteingent cette limite plutot que d'être limité par la regen :)

idéalement ce changement va encourager plus de gens à fight et donc à vous rejoindre dans les ligues les plus élevées.

Je ne veux pas remonter la limite des fights avec un adversaire.

Pour ce qui est de re réduire la regen, je redirige vers une suggestion :)
