### ISSUE TITLE
Ameliorer commande class

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#227]
- [x] Permettre un prix différent par classe
- [x] Ajout de 2 nouvelles classes
- [x] Ajuster les pvs aux pvs max

**Comment by niqore** [comment]
Pour ajuster les pv il faut penser aux 2 sens, si on a + de vie que la nouvelle classe on finit avec de la vie en trop (ex: 265/150)
