### ISSUE TITLE
Pas de tour 24 en combat

### ISSUE THREAD

**Issue by OrionYp** [DraftBot-A-Discord-Adventure/DraftBot#2279]
### Description du bug.

Pas de tour 24 en combat

### Reproduction du bug.

Faire un combat

### Captures d'écran

Non

### Sur quel shard avez vous rencontré le bug ?

Tous

**Comment by Nargacaura** [comment]
Quasi sûr que ça vient de là:
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/338a28a9ec20195d40cc01187464e42debb29e8a/src/core/fights/FightController.ts#L246

Si c'est le cas, c'est qu'il était présent depuis 3 mois environ, mais personne ne l'avait remarqué.
