### ISSUE TITLE
[BUG]: L'attaque sombre enlève 30% de l'attaque d'un vétéran après une concentration...

### ISSUE THREAD

**Issue by Gabrielre14** [DraftBot-A-Discord-Adventure/DraftBot#2284]
### Description du bug.

Ce n'est pas vraiment un bug, mais plutôt un problème avec la concentration, notamment pour la désactiver. 
Je n'ai pas le détail dans le code mais je peux théoriser que le bot prends ton attaque et ta vitesse, la rajoute pour avoir +100% d'attaque et de vitesse. Puis, à la fin de la concentration, le bot enlève à nouveau ces valeurs de tes stats pour redevenir normal. Cela fonctionne, mais il y a une faille : en cas de modifications de ces stats pendant la concentration sont doublés, car l'ajout / perte de stats lors de la concentration n'est pas proportionnel.

Je m'explique. 
Prenons un combat mage contre vétéran (j'ai testé pour vous). Le vétéran utilise sa concentration, j'attaque avec un vol de souffle puis le vétéran acquiert ses boosts de +100% de vitesse et d'attaque. Il lance une attaque quelconque, puis j'attaque avec l'attaque sombre : il perd 15% d'attaque, puis la concentration s'arrête. Le problème et qu'il a perdu 30% d'attaque au lieu de 15%. 
Pourquoi ? Tout simplement parce que si ce vétéran a 500 d'attaque, le bot fait +100% donc +500 d'attaque pour arriver à 1000. Or, si je baisse de 15% ça donne 850. Le problème est durant le retour à la normal. Contrairement à l'attaque chargée ou c'est +50% et puis -33%, la concentration ne fait qu'enlever le gain d'auparavent. Donc au lieu de faire /2 elle fait -500. Et on se retrouve avec 350 d'attaque (-30% par rapport à 500) au lieu de 425 (-15% par rapport à 500%). L'attaque sombre a un impact 2 fois plus grand. 

Il faut donc au lieu de faire +100% puis enlever ce gain, faire x2 au début de la concentration puis /2 afin d'adapter un changement des stats. Car chaque changement d'attaque ou de vitesse lors de la concentration a un impact deux fois plus grand actuellement.

### Reproduction du bug.

Faire un combat mage contre vétéran
Faire une attaque sombre qui baisse l'attaque ou (à tester) une attaque vol de souffle qui baisse la vitesse.
Comparer les stats finales après que la concentration soit finie. 
On remarque qu'elles ont subit un nerf 2 fois plus important que ce qui est marqué sur l'attaque. 

### Captures d'écran

Voici nos statistiques de base : 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/539a2e36-1c67-4650-8c99-ca16266513ae)
Puis voici nos stats après l'activation de la concentration : 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/70ed1cce-4875-46f2-b587-5102a311b824)
+100% de vitesse et d'attaque

Mais voici ce qu'il se passe après une attaque sombre + fin de la concentration : 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/57812274-5d5a-480f-acc4-4851db95a8d8)
Une perte de 30% d'attaque au lieu de 15% par rapport au premier screen

### Sur quel shard avez vous rencontré le bug ?

Sur le shard 0

**Comment by BastLast** [comment]
fixé par l'équilibrage de la 4.5.0
