### ISSUE TITLE
[BUG]: La campagne une fois terminée affiche 1% au lieu de 100% sur le profil du joueur

### ISSUE THREAD

**Issue by Procion06** [DraftBot-A-Discord-Adventure/DraftBot#2290]
### Description du bug.

Tout est dit dans le titre

### Reproduction du bug.

Terminer la campagne

### Captures d'écran

![campagne](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/107723160/145e34b8-0279-459f-979d-5048650f6b72)

### Sur quel shard avez vous rencontré le bug ?

2

**Comment by Aikoo-Sama** [comment]
J'ai du mal à comprendre pourquoi avoir faire retourner la campaignProgression à 0 une fois que la campagne est à 100, y'a une raison particulière ?

**Comment by romain22222** [comment]
> J'ai du mal à comprendre pourquoi avoir faire retourner la campaignProgression à 0 une fois que la campagne est à 100, y'a une raison particulière ?

la raison est simple : la mission 0 n'existera jamais. Si on laissait ce curseur à n+1, ca fait que lorsqu'on rajoute des missions faut faire des cas spéciaux pour les n+1 qui sont bien plus relous à gérer que les 0 (genre check l'avant après, les redéplacer à la bonne quete si jamais etc.) la si le mec a 0 dans sa mission et qu'il tente d'en piocher une, ca va faire automatiquement le check de si une nouvelle est apparue, nous évitant des tournis sur la requete bdd

**Comment by Aikoo-Sama** [comment]
> > J'ai du mal à comprendre pourquoi avoir faire retourner la campaignProgression à 0 une fois que la campagne est à 100, y'a une raison particulière ?
> 
> la raison est simple : la mission 0 n'existera jamais. Si on laissait ce curseur à n+1, ca fait que lorsqu'on rajoute des missions faut faire des cas spéciaux pour les n+1 qui sont bien plus relous à gérer que les 0 (genre check l'avant après, les redéplacer à la bonne quete si jamais etc.) la si le mec a 0 dans sa mission et qu'il tente d'en piocher une, ca va faire automatiquement le check de si une nouvelle est apparue, nous évitant des tournis sur la requete bdd

Dans ce cas quel était le but de cette condition originale ? Celle qui vérifie si la campagne est à 0 alors renvoyer 1.

**Comment by Aikoo-Sama** [comment]
Peut-être qu'il faudrait remplacer 1 par 100, si je suis correcte.
