### ISSUE TITLE
[BUG]: annulation de combat

### ISSUE THREAD

**Issue by unmec6876** [DraftBot-A-Discord-Adventure/DraftBot#2291]
### Description du bug.

quelqu'un a essayé d'annuler mon combat et il y a eu écrit :
"unmec6876, hmmm... Cela n'a pas fonctionné !
@Pepito, seul l'initiateur d'un combat peut l'annuler !"

### Reproduction du bug.

lancer un combat, prendre un deuxième compte discord et essayer d'annuler le combat

### Captures d'écran

aucune capture ne me semblerait pertinente

### Sur quel shard avez vous rencontré le bug ?

/ping non disponible dans le salon ou a été produit le bug

**Comment by Nargacaura** [comment]
Duplicata du #1639
