### ISSUE TITLE
[BUG]: Message d'arrivée à destination après un K.O

### ISSUE THREAD

**Issue by XoFel1** [DraftBot-A-Discord-Adventure/DraftBot#2294]
### Description du bug.

J'ai étais mis K.O donc j'ai fais la commande pour respawn et j'ai reçu un message me disant que j'étais arrivée à ma destination cependant c'était seulement le message car mon trajet lui n'était pas terminé.

### Reproduction du bug.

Finir K.O et faire /respawn.

### Captures d'écran

![Screenshot_20231118-205014](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/150509388/803b5259-29be-4004-b5a0-700f46260e94)

### Sur quel shard avez vous rencontré le bug ?

Sur le bot pre-release.

**Comment by Nargacaura** [comment]
C'est la même chose que l'issue précédente (la #2293)...
