### ISSUE TITLE
[BUG]: L'event de tp a un taux d'arnaque trop eleve

### ISSUE THREAD

**Issue by Muzaraigne** [DraftBot-A-Discord-Adventure/DraftBot#2302]
### Description du bug.

Sur un dizaine de test du mini évent, plus de la moitie voire plus sont des arnaques alors que le pourcentages est a 15%.

### Reproduction du bug.

avoir le mini event 

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/113132027/94e5ac5f-102a-4f2f-bce2-a2d2cacf2637)

### Sur quel shard avez vous rencontré le bug ?

tous

**Comment by Nargacaura** [comment]
C'est juste que le pourcentage de scam dans ce mini-event est actuellement de *80*% au lieu de 15%, si j'ai bien compris.

**Comment by Muzaraigne** [comment]
oui

**Comment by Aikoo-Sama** [comment]
Peut-être voir avec @BastLast pour un potentiel équilibrage, dans ce cas.

**Comment by BastLast** [comment]
> Peut-être voir avec @BastLast pour un potentiel équilibrage, dans ce cas.

C'est pas un équilibrage c'est un bug à fix, je m'en occupe

**Comment by BastLast** [comment]
> > > Peut-être voir avec @BastLast pour un potentiel équilibrage, dans ce cas.
> > 
> > C'est pas un équilibrage c'est un bug à fix, je m'en occupe
> 
> My bad alors, si tu veux je regarde ça dans une heure.

J'ai déjà check donc tkt j'en ai pr 10 sec de fix
