### ISSUE TITLE
More balancing in fight

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2327]
Mettez tous vos retours ici !

**Comment by 0eddo** [comment]
1. les nouveaux items c'est cool ! 
2.le buff de l'attaque de guilde pas encore test mais j'approuve totalement c'est une super idée
3.ensuite, l'attaque bouclier est vrmt trop op et l'attaque canon trop nulle (j'ai un peu l'impression que les dégâts de ces 2 attaques ont été inversés 🤔 
4.le nerf canon casse totalement la dynamique de jeu des canonniers car le ralentissement du canon servait pour bcp.
5.l'égide puissante moi ça me choque pas   

je reviendrais peut être après avoir test les fights plus amplement :)

**Comment by BastLast** [comment]
> 1. les nouveaux items c'est cool ! 
> 2.le buff de l'attaque de guilde pas encore test mais j'approuve totalement c'est une super idée
> 3.ensuite, l'attaque bouclier est vrmt trop op et l'attaque canon trop nulle (j'ai un peu l'impression que les dégâts de ces 2 attaques ont été inversés 🤔 
> 4.le nerf canon casse totalement la dynamique de jeu des canonniers car le ralentissement du canon servait pour bcp.
> 5.l'égide puissante moi ça me choque pas   
> 
> je reviendrais peut être après avoir test les fights plus amplement :)

Cette issue est la uniquement pr l'équilibrage des combats, de préférence après au moins 20/30 fight pr éliminer un peu le facteur chance

**Comment by Thefox60** [comment]
Moi je dit que l'attaque bouclier rend le cannonier nul
Sa veut dire que le canonier est faible au chevalier au paladin  soit plus de 60%des joueur donc bon on peut plus trop gagner et puis on a en plus une vie faible  par rapport à ces deux classes donc autant ne plus combattre donc plus trop de raison d'être canon

**Comment by Aikoo-Sama** [comment]
Nerf la shield car ce genre de spam, déjà que je fais plus beaucoup de fight, ça donne juste envie de vomir.

<img width="1093" alt="image" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/81baadb7-bbc2-49ed-8982-e267fe1fd74b">

**Comment by Ravenclaw-l** [comment]
Je partage mon point de vue en tant que mage.
Je ne suis pas d'avis de réduire la puissance du bouclier, ça donne au chevalier une vraie force d'attaque. 
Cependant, il faudrait doubler la consommation de souffle nécessaire. Ça permettra de réduire son utilisation excessive.

**Comment by BastLast** [comment]
> Je partage mon point de vue en tant que mage.
> Je ne suis pas d'avis de réduire la puissance du bouclier, ça donne au chevalier une vraie force d'attaque. 
> Cependant, il faudrait doubler la consommation de souffle nécessaire. Ça permettra de réduire son utilisation excessive.

Ca risque de reduire grandement la puissance des tanks tho

**Comment by Sousoulman** [comment]
Pour moi il faudrait baisser la puissance de l'attaque bouclier et la probabilité de l'affaiblissement et il faudrait baisser la puissance de l'attaque ultime (au alentour de 275 ce serait bien).
Et il faudrait faire démarrer le paladin avec moins de souffle.
