### ISSUE TITLE
[BUG]: Les votes sur top.gg ne remontent pas

### ISSUE THREAD

**Issue by Ravenclaw-l** [DraftBot-A-Discord-Adventure/DraftBot#2332]
### Description du bug.

Hello,

Tout est dans le titre. Les votes effectués sur top.gg ne remontent pas sur le profil des joueurs.

### Reproduction du bug.

Aller sur top.gg -> voter -> revenir sur discord....

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/149114595/5996e3b5-fa1f-411c-9b58-e1054eff005f)

![Screenshot_20231202-105337](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/149114595/37d6b593-09fe-4467-a0bc-d880d8b7203d)

### Sur quel shard avez vous rencontré le bug ?

![shard](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/149114595/ae422822-73af-4c80-a8cf-39794d05f1e7)

**Comment by BastLast** [comment]
fixé par un restart du bot

**Comment by Aikoo-Sama** [comment]
Bug de nouveau présent, y aurait-il un problème avec l'API de top.gg ?

**Comment by BastLast** [comment]
vu que ce soucis est aléatoire et que j'en ai pas entendu parlé depuis 1 mois on va dire que c'est fixé
