### ISSUE TITLE
[BUG]: Les notifs de destination ne fonctionnent plus

### ISSUE THREAD

**Issue by thef0rgoten** [DraftBot-A-Discord-Adventure/DraftBot#2333]
### Description du bug.

Les notifications en dm du bot ne marchent plus mais seulement pour les notifications de destinations (la notif du bonus de guilde à très bien marché). Nous avons ce problème depuis aujourd'hui. J'ai essayé faire la commande /notification mais ca n'a rien changé. 

### Reproduction du bug.

Il faut juste jouer normalment.

### Captures d'écran

Les notifs du jour : 
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/152720640/4ebb503d-7114-4fd6-99a7-b751f5a44e5e)

### Sur quel shard avez vous rencontré le bug ?

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/152720640/c426b1ed-6315-4db2-9b11-b4fe2b9b6409)

**Comment by BastLast** [comment]
fixé par un restart du bot, probablement lié à #2332
