### ISSUE TITLE
[BUG]: fin du combat au tour 23/24

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#2338]
### Description du bug.

il est possible qu'un combat se termine au 23e tour au lieu du 24e sans raison apparente. Le bug s'est déroulé dans un combat classé chevalier contre mage. l'interface affiche 24/24 tours sans qu'il n'y ait eu le dernier (je vous laisse le loisir de compter sur les screens vu que l'interface de combat a disparu après l'annonce de fin de match).

### Reproduction du bug.

faire un fight classé

### Captures d'écran

<img width="679" alt="image" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/80409766/02945fea-f1a3-446f-8c47-64bef190d853">
<img width="702" alt="image" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/80409766/0693cea8-d39d-43af-b1c4-40130a1fee51">
<img width="694" alt="image" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/80409766/81ee304b-31fc-446a-b345-4be537238eb4">

### Sur quel shard avez vous rencontré le bug ?

shard 0, sur le serveur officiel

**Comment by BananePlantain** [comment]
duplicata du #2279 qui a pourtant recu un fix

**Comment by Nargacaura** [comment]
Je viens de voir que l'alté compte pour un tour à lui-même, dû à l'utilisation de la fonction pouvant potentiellement terminer le tour:
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/src%2Fcore%2Ffights%2FFightController.ts#L258-L260

*Pourquoi n'ai-je pas vu ce détail lors de ma tentative de fix?*
