### ISSUE TITLE
[BUG]: On peut avoir l'event d'invitation au chateau

### ISSUE THREAD

**Issue by Gabrielre14** [DraftBot-A-Discord-Adventure/DraftBot#2347]
### Description du bug.

Mecredi matin, 6h45. Après avoir fait mon /bonusjournalier regardé la mission, je fais mon petit /rapport matinal et je vois l'evènement d'invitation au chateau. 

Après avoir choisi le 1er choix, le bot me redirige sur le chemin que j'empruntais (en l'ocurrance entre la voie champêtre et le berceau)
L'évent du chateau a donc remplacé celui de la voie champêtre mais il n'y a rien eu à la suite du choix d'accepter l'invitation

### Reproduction du bug.

Pas de reproduction possible à part faire /rapport sur un lieu et espérer l'avoir...
Ce n'est pas que à la voie champêtre, Evatco le signale aussi à l'Etendue. 
Je pense que c'est le début de l'event de Noël prématuré, mais sans la suite

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/afd2b87b-1ea0-4cd3-b3c7-0c876c7717db)
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/97915848/81001c1d-8cc5-4202-85ec-31f6b927bb36)

### Sur quel shard avez vous rencontré le bug ?

Sur le shard 4.

**Comment by Nargacaura** [comment]
C'est plus que ça ne redirige pas vers la salle de réception, le bug.
