### ISSUE TITLE
Évènement du château

### ISSUE THREAD

**Issue by Voisin1234** [DraftBot-A-Discord-Adventure/DraftBot#2350]
### Description du bug.

Alors ce matin à 00:55h j'ai décidé de partir a route marécageuse. Arrivée à destination à 4h56 en faisant le /rapport je suis tombé sur l'évènement du roi avec le sapin de Noël qui donne les cadeaux comme sur la photo.
Ce n'est pas forcément comme le bug de Gabriel qu'il a rapporté juste avant car lui a reçu l'évènement pour pouvoir s'y rendre. 

### Captures d'écran
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/8e3bfbfa-e180-4674-b063-b31c641605df)
![IMG_6658](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/b190fde9-9547-462e-bea2-a2c73f36e100)
![IMG_6659](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/7fcfd4eb-deaa-4cc8-a56c-34c38b93c3ff)
![IMG_6660](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/8370c336-0bab-4de4-ba56-15da1c06b3c3)

### Sur quel shard avez vous rencontré le bug ?

![IMG_6661](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/707960f5-142b-433f-9b94-f07ecb3b0e98)

**Comment by Nargacaura** [comment]
C'est lié à #2347 (voire même un duplicata de celui-ci).

**Comment by Voisin1234** [comment]
Du coup désolé c'est le matin, j'avais vraiment pas bien lu

**Comment by BastLast** [comment]
Merci de ne pas fermer les issues :)

**Comment by Voisin1234** [comment]
Bah en fait c'est moi qui me suis trompé je n'avais pas vu dans mon choix de destination que c'était pour aller sur le château. Du coup quand je suis arrivé à route, j'ai cru que l'évènement s'était trompé mais apparemment pas du tout c'est pour ça que je l'avais fermé. Mais désolé si j'ai toujours rien compris.😉

**Comment by BastLast** [comment]
> Bah en fait c'est moi qui me suis trompé je n'avais pas vu dans mon choix de destination que c'était pour aller sur le château. Du coup quand je suis arrivé à route marécageuse, j'ai cru que l'évènement des cadeaux, s'était trompé mais apparemment pas du tout c'est pour ça que je l'avais fermé. Mais désolé si j'ai toujours rien compris.😉

Yep tkt c'est pas un drame c'est juste que quand on ferme les issue je les classes

**Comment by BastLast** [comment]
Si qqun d'autre les ferme elles sont pas toujours classées comme il faut
