### ISSUE TITLE
Prix libération pet fielleux 

### ISSUE THREAD

**Issue by Voisin1234** [DraftBot-A-Discord-Adventure/DraftBot#2356]
### Description du bug.

Ce matin, j’ai voulu me libérer d’un coq fielleux mais il m’a proposé de payer 1000💰 or depuis la dernière mise à jour, celle-ci avait été baissé à 500 💰. Du coup je n’ai pas accepté. Je ne peux pas vous dire si j’aurais bien payé les 1000 pièces ou si c’est juste le texte qui n’a pas été changé lors de la dernière mise à jour.

### Reproduction du bug.

/petfree

### Captures d'écran

![IMG_6709](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/d02d1c0b-bddf-4e7d-ae15-ab28226a0caf)
![IMG_6710](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/dab33de5-ecbf-4fd2-af76-8c4e2fa7fcab)

### Sur quel shard avez vous rencontré le bug ?

![IMG_6711](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/e49727bf-3870-45f8-ad64-f21123fae4bb)

**Comment by Nargacaura** [comment]
C'est plus une typo qu'un bug, vu que le prix est marqué en dur dans le texte.

**Comment by QQtin3** [comment]
Depuis quand on hardcode des values comme ça dans le texte ? Y'a une constante qui doit être associée

**Comment by BastLast** [comment]
> Depuis quand on hardcode des values comme ça dans le texte ? Y'a une constante qui doit être associée

Oui c pas bien

**Comment by romain22222** [comment]
j'allais faire la blague du blame, mais c'est ase, c'est moins drole du coup

**Comment by BastLast** [comment]
> j'allais faire la blague du blame, mais c'est ase, c'est moins drole du coup

Pas bien d'être allé voir le blame

**Comment by Voisin1234** [comment]
J'ai rien capté ce que vous avez dit

**Comment by Voisin1234** [comment]
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/108148891/16912c29-b612-4126-a93a-5f826fa1b0e2)

**Comment by Voisin1234** [comment]
Du coup j'ai bien payé 500💰 c'est juste le texte qui n'est plus bon
