### ISSUE TITLE
[Probleme]: Alors pas sur que ce soit un Bug mais la description des attaques sur le doc a disparu

### ISSUE THREAD

**Issue by Trolleur17200** [DraftBot-A-Discord-Adventure/DraftBot#2358]
### Description du bug.

Pas de description des attaques

### Reproduction du bug.

.

### Captures d'écran

![IMG_8161](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/152334425/add94e65-c327-4331-8264-51343c6a479d)

### Sur quel shard avez vous rencontré le bug ?

Doc

**Comment by Trolleur17200** [comment]
Désolé si ct volontaire

**Comment by BastLast** [comment]
Hello, ceci est un soucis sur le guide et non sur le jeu. Merci d'utiliser discord
