### ISSUE TITLE
[BUG]: les notifications sont cassées

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#2369]
### Description du bug.

depuis le 08/01 le bot ne m'envoie plus de notification à la fin des trajets et ce bug semble concerner beaucoup de personnes si ce n'est tout le monde.

### Reproduction du bug.

arriver à la fin d'un trajet avec les notifications activées

### Captures d'écran

impossible d'envoyer une capture d'écran de rien

### Sur quel shard avez vous rencontré le bug ?

tous

**Comment by Aikoo-Sama** [comment]
Je n'ai pas observer d'erreurs liées aux notifications dans les logs, faudra fouiller un peu plus

**Comment by BastLast** [comment]
je crois que ce soucis est fixé pour le moment vu qu'on a pas eu de rapport de bug depuis un moment
