### ISSUE TITLE
Review des évents

### ISSUE THREAD

**Issue by QQtin3** [DraftBot-A-Discord-Adventure/DraftBot#238]
Suite à la récente mise à jour Discord avec des émojis.
Certains devraient être modifiés comme dans les évents.

- [x] Changer les émojis
- [x] Revoir les phrases dans les évents, surtout celles de one-shot

Il faut vérifier aussi l'équilibrage de chacun des évents :
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [x] 13
- [x] 14
- [x] 15
- [x] 16
- [x] 17
- [x] 18
- [x] 19
- [x] 20
- [ ] 21
- [ ] 22
- [ ] 23
- [ ] 24
- [ ] 25
- [ ] 26
- [ ] 27
- [ ] 28
- [ ] 29
- [ ] 30
- [ ] 31
- [ ] 32
- [ ] 33
- [ ] 34
- [ ] 35
- [ ] 36
- [ ] 37
- [ ] 38
- [ ] 39
- [ ] 40
- [ ] 41
- [ ] 42
- [ ] 43
- [ ] 44
- [ ] 45
- [ ] 46

**Comment by quenquentin** [comment]
- [ ] Changer les émojis

- [ ] Revoir les phrases dans les évents, surtout celles de one-shot

**Comment by BastLast** [comment]
ca avance ca @quenquentin  ?

**Comment by BastLast** [comment]
les éventes restants seront review pour la prochaine update

**Comment by BastLast** [comment]
rework de l'xp de certains évents effectués sur #347

**Comment by Thero1st** [comment]
Event 24 :

Version courte : J'aimerais que vous augmentiez le gain de l'issue 🍢 

Explications : J'ai créé cet event avant l'ajout des classes, quand les pv max étaient 150. En conséquence, les gains et pertes de vie de l'event ne sont plus d'actualité. Si la perte de 100 pvs est désormais iconique, et, je trouve, convient encore grâce aux classes à peu de vie, ce n'est pas le cas du gain de 75. C'est trop faible pour les classes à haut pv, et les classes à peu s'en fichent vu que de toute façon ils meurent régulièrement. En plus de ça, j'ai basé cet event sur une idée de jeux/paris. Parier de l'argent pour possiblement en gagner plus. Parier beaucoup de notre temps pour possiblement avoir un item. Parier notre vie pour possiblement se soigner, mais cette dernière partie ne marche plus actuellement.

**Comment by Coronana** [comment]
**Évent #51 Escalier Tortueux :**

-🔎[1] : ajouter un gain de 💰 plus important dû à un possible OS.

-🔎[3] : Laisser OS ou lourde perte de PV.

**Comment by quenquentin** [comment]
Honnêtement je sais pas trop quoi penser de cette issue, elle traîne, repoussée à chaque mise à jour et ça prend du temps de le faire en groupe.
Là où d'autres features peuvent en avoir besoin

**Comment by BastLast** [comment]
je déplace ça a la prochaine update, j'ai envie d'en faire :)

**Comment by BastLast** [comment]
finalement je close cette issue car obsolète.
