### ISSUE TITLE
[BUG]: erreur sur une mission de campagne

### ISSUE THREAD

**Issue by unmec6876** [DraftBot-A-Discord-Adventure/DraftBot#2384]
### Description du bug.

J'ai eu le bug à 11h48. L'écran des missions m'indique que j'ai 524 points de gloire alors que mon profil m'en indique 523. https://discord.com/channels/429765017332613120/429765574923649025/1201116601899032607 https://discord.com/channels/429765017332613120/429765574923649025/1201116647046516827

### Reproduction du bug.

Écrire /profil puis /missions dans le tchat

### Captures d'écran

![Capture d’écran 2024-01-28 à 11 57 35](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/139997056/596b6c33-928c-406b-9363-f5b50adadf47)
![Capture d’écran 2024-01-28 à 11 57 15](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/139997056/dd8e5581-ee18-4461-8f17-e46289687d3c)

### Sur quel shard avez vous rencontré le bug ?

0

**Comment by BastLast** [comment]
Auasi sur que pas un bug et que tu as justz perdu un point en compression de fin de saison de combat

**Comment by BastLast** [comment]
Je ferme l'issue, rouvrir si je me trompe

**Comment by BastLast** [comment]
( en gros la mission montre ton record de gloire et le profil ta gloire actuelle)

**Comment by unmec6876** [comment]
aaaaaaaaah
