### ISSUE TITLE
[BUG]: Message d'arriver lors du respawn suite à une mort

### ISSUE THREAD

**Issue by EdvansSPT** [DraftBot-A-Discord-Adventure/DraftBot#2385]
### Description du bug.

Bonjour,

En faisant un /rapport, je suis mort. J'ai reçu en message privé par le bot le message de respawn. J'ai donc effectuer la commande /respawn. Lorsque je l'ai faite j'ai reçu un message d'arrivé à destination, ce qui n'est pas le cas lors du /rapport une fois revenue en vie

### Reproduction du bug.

Mourir pendant un /rapport
faire un /revive sans regarder les mp
faire un /rapport
regarder les messages privé et voir le message de mort et d'arrivé à destination

### Captures d'écran

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/50589768/da46c8bc-5697-4dd4-9d36-8dbadd594617)
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/50589768/3bdceb12-61ce-443e-b98b-5e031cac98f1)

### Sur quel shard avez vous rencontré le bug ?

![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/50589768/0dfe1096-b246-4e6c-81a9-221e69e3d7e8)

**Comment by Nargacaura** [comment]
Une issue parlant de ça existe déjà (la #2293).
