### ISSUE TITLE
[BUG]: refus  du bot de réaliser un nouveau rapport alors que les 10 minutes sont passés

### ISSUE THREAD

**Issue by aureochocob0n** [DraftBot-A-Discord-Adventure/DraftBot#2410]
### Description du bug.

Cela fais plusieurs fois que je remarque que quand je réalise un premier rapport (il me met admettons 2min avant le prochain mini event) et que je refais un rapport 2min après le bot peut rester bloqué 1 ou 2min avec à chaque fois en description: 2min avant prochain événement. Alors que ça fait plus de 2min

### Reproduction du bug.

-Faire un rapport 1 ou 2min avant le prochain mini event
-Faire un 2e rapport au moment oû les 1 ou 2 min sont passés

### Captures d'écran

![Screenshot_20240216_075802_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/153011168/bb372493-ba7b-4a92-9bcf-61745d4c542e)

![Screenshot_20240216_075757_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/153011168/856203cc-91de-414a-9239-e49bbff83226)

### Sur quel shard avez vous rencontré le bug ?

![Screenshot_20240216_113105_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/153011168/97ce8582-abd3-4280-8224-35d4b01139a4)

**Comment by Ravenclaw-l** [comment]
Les joies de l'affichage sur mobile.
Les 9m45 ne devaient pas être totalement écoulées pour que tu n'aies pas eu ton mini-événement ; tu as dû y arriver quelques secondes après. Sur mobile, même à une seconde de la fin, il peut encore t'afficher 2 minutes sans raison.

**Comment by aureochocob0n** [comment]
Ok merci

**Comment by BastLast** [comment]
Je ferme car cest pas un bug draftbot mais un bug discord
