### ISSUE TITLE
[BUG]: multiple notification

### ISSUE THREAD

**Issue by b00mzer** [DraftBot-A-Discord-Adventure/DraftBot#2437]
### Description du bug.

Le bug arrive quand je suis arrivé à mon étapes.
Une fois que je suis arrivé DraftBot me le signal par message privé, j'ai eu 5 notifications à la suite. 
Mon téléphone à donc vibré très fort :')

### Reproduction du bug.

Attendre d'atteindre une étape

### Captures d'écran

![Screenshot_1](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/43384776/91145880-db7a-41f8-9bd8-adb2cabc9edc)

### Sur quel shard avez vous rencontré le bug ?

En message privé sur discord.

**Comment by Nargacaura** [comment]
C'était dû à un incident chez Discord, qui a causé des déco-reco du bot, dupliquant les shards (sauf le 4) plusieurs fois:
- 3 instances sur le shard 3,
- 4 instances sur le 1,
- 5 instances sur le 0,
- et... **10** instances sur le 2!

Ceci a été fix par le redémarrage du matin sur la version stable.

**Comment by b00mzer** [comment]
Bonjour,

Niquel!

Merci pour la réponse rapide,
Cordialement,
b00mzer ^^
________________________________
De : Pagos ***@***.***>
Envoyé : samedi 2 mars 2024 10:28
À : DraftBot-A-Discord-Adventure/DraftBot ***@***.***>
Cc : b00mzer ***@***.***>; Author ***@***.***>
Objet : Re: [DraftBot-A-Discord-Adventure/DraftBot] [BUG]: multiple notification (Issue #2437)


C'était dû à un incident chez Discord, qui a causé des déco-reco du bot, dupliquant les shards (sauf le 4) plusieurs fois:

  *   3 instances sur le shard 3,
  *   4 instances sur le 1,
  *   5 instances sur le 0,
  *   et... 10 instances sur le 2!

Ceci a été fix par le redémarrage du matin sur la version stable.

**Comment by BastLast** [comment]
à priori un rework du système de notif fait que ce bug sera résolu en v5

**Comment by BastLast** [comment]
#2480

**Comment by BastLast** [comment]
@Feiryn  quasi sur qu'on a pas de moyen fiable de reproduire ce bug, je ferme cette issue vu que #2480 existe ça te va ?

**Comment by BastLast** [comment]
si ya un soucis on pourra ré ouvrir

**Comment by Feiryn** [comment]
> @Feiryn quasi sur qu'on a pas de moyen fiable de reproduire ce bug, je ferme cette issue vu que #2480 existe ça te va ?

Avec le MQTT on peut se mettre en QOS 2 est assurer que la notif est envoyée qu'une seule fois

**Comment by BastLast** [comment]
> > @Feiryn quasi sur qu'on a pas de moyen fiable de reproduire ce bug, je ferme cette issue vu que #2480 existe ça te va ?
> 
> Avec le MQTT on peut se mettre en QOS 2 et assurer que la notif est envoyée qu'une seule fois

On verra si on a des soucis
