### ISSUE TITLE
Déblocage automatique

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#244]
Débloquer automatiquement les joueurs s'ils sont bloqués, pour ne pas avoir besoin de reboot. Par exemple si le blocage date de plus de 2 min et que c'est un !r, !shop... alors le débloquer. Pour les fights voir si le dernier message date de plus de 30 secondes et que le combat n'est pas terminé.
Eventuellement try catch autour des commandes mais faut voir si ça permet pas d'avoir des messages sans être bloqué. Ou alors débloquer que si le message n'est pas envoyé ou que les réactions n'arrivent pas à se faire, et dans ce cas là supprimer le message déjà envoyé et envoyer une erreur.

**Comment by BastLast** [comment]
ou éventuellement débloquer tous les joueurs bloqués depuis plus de 30 min
comme ca on est futur proof

**Comment by BastLast** [comment]
ou faire une commande admin qui débloque

**Comment by niqore** [comment]
Je mets cette issue pour la 2.1.2, en soit ça peut se faire rapidement. Je vais ajouter un argument à la méthode pour bloquer avec le temps limite (ex: 2 min pour le report, shop) et ensuite ça débloquera s'il est dépassé mais toujours actif
