### ISSUE TITLE
recoder le systeme de notification

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2480]
- [x] Commande /notifications pour paramétrer les notifs
- [x] Faire en sorte que le back (ou discord) envoie les notifs aux fronts
- [x] Gérer l'envoi de notif report côté back
- [x] Gérer l'envoi de notif guild daily côté back
- [x] Front report notif
- [x] Front guild daily notif (juste finir le todo)

**Comment by Feiryn** [comment]
Peut-être utiliser ce projet : https://kafka.apache.org/

**Comment by Feiryn** [comment]
Je pensais aussi le rendre un peu plus configurable quitte à le refaire de 0, en ayant la possibilité de choisir le type de notif

**Comment by BastLast** [comment]
@Feiryn  est-ce que tu peux update la descriptiuon de cette issue ? et potentiellement te l'assigner si tu as pas fini ?
