### ISSUE TITLE
[BUG]: Perte de vie non enregistrée

### ISSUE THREAD

**Issue by Ntalcme** [DraftBot-A-Discord-Adventure/DraftBot#2485]
### Description du bug.

Sur l'île je me suis aperçu que je ne perdais pas mes points de vies lors des reports et que je devais en perdre.

### Reproduction du bug.

Simplement faire un /report et être censé perdre des cœurs.

### Captures d'écran

Avant : 
![Capture d'écran 2024-04-25 030435](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/57364571/9035faa0-7e1a-430d-8fda-48223001f10b)
Après : 
![Capture d'écran 2024-04-25 030503](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/57364571/2d2ef34f-cb01-440b-92cc-a857b2b18d3e)

### Sur quel shard avez vous rencontré le bug ?

0

**Comment by symsym-1629** [comment]
tu as perdu 23 d'énergie, à voir si c'est donc un problème d'émoji ou de stat

**Comment by Ntalcme** [comment]
Ah oui j'avais pas vu pour l'énergie c'est vrai mais dans ces cas-là sûrement juste l'émoji oui j'essaierai de faire plus attention pour voir.

**Comment by KirIcare** [comment]
Possible parceque ça me paraît bcp 23 de vie sur l'île, nan ?

**Comment by Ntalcme** [comment]
En fait plusieurs fois j'étais censé perdre de la vie et je suis resté à 92 tout du long mais j'ai pas fait gaffe à l'énergie.

**Comment by BastLast** [comment]
du coup confirmé que c'est juste un soucis d'émoji ?

**Comment by Feiryn** [comment]
Oui c'est bien un soucis d'emoji. En français c'est bon
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/c55c7e0c55198c5aeeff59482ff4fafd8d25d322/resources/text/smallEvents/bonusGuildPVEIsland.json#L97

**Comment by BastLast** [comment]
ok du coup je close ça, si ya un soucis de trad faut s'en occuper sur crowdin
