### ISSUE TITLE
[BUG]: Aldéric vend un item 10K en dessous de son prix

### ISSUE THREAD

**Issue by Procion06** [DraftBot-A-Discord-Adventure/DraftBot#2486]
### Description du bug.

Les légendaires sont normalement vendus autour de 27500 

### Reproduction du bug.

faire un mini event, tomber sur le marchand en direction de Voie champêtre

### Captures d'écran

![Bug](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/107723160/bcb75467-8242-431d-bc63-762bf4e20c0f)

### Sur quel shard avez vous rencontré le bug ?

Serveur DB (shard 0)

**Comment by Gabrielre14** [comment]
Ce n'est absolument pas un bug. Il s'agit d'une réduction proposé par Aldéric. Normalement le prix d'un objet vendu au super mini-event est multiplié par 5,5. Sauf dans 10% des cas où celui-ci n'est que multiplié par 3,5. 
(En excluant la route des merveilles où ce prix n'est que multiplié par 1,5). 

![image](https://github.com/user-attachments/assets/f3d61be1-92a3-4382-afaf-adf6b84859c6)

On le voit sur cette image avec le "GREAT_DEAL_PROBABILITY: 0.1" et le "GREAT_DEAL_MULTIPLAYER: 3.5"

Et voici les lignes de code montrant que si on est sûr la route des Merveilles, on a un prix très faible (x1,5), et avec 10% de chance un prix réduit (x3,5) sur le reste de la map

![image](https://github.com/user-attachments/assets/b6a1dc88-e317-4e7f-91e8-5bd7f495a80b)

Ainsi, avec un objet légendaire qui vaut 5K à la base, son prix réduit sera de 17 500 🪙
