### ISSUE TITLE
[BUG]: Problème de statistiques d'attaque 

### ISSUE THREAD

**Issue by aureochocob0n** [DraftBot-A-Discord-Adventure/DraftBot#2493]
### Description du bug.

Ce bug se réalise quand j'effectue un combat. Quand j'équipe mon diamant kéraunique, mon attaque augmente en statistiques mais lors des combats, ça ne change rien que j'ai mon diamant équipé ou non. 
Sans diamant:
![Screenshot_20240512_105336_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/153011168/ea304a20-8c6d-49bc-9fac-c93539f61653)
Avec diamant:
![Screenshot_20240512_105302_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/153011168/c7af054e-a6b7-4d5c-9041-dd79c90e607d)

### Reproduction du bug.

Faire des combats

### Captures d'écran

Sans diamant:
![Screenshot_20240512_105336_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/153011168/ea304a20-8c6d-49bc-9fac-c93539f61653)
Avec diamant:
![Screenshot_20240512_105302_Discord](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/153011168/c7af054e-a6b7-4d5c-9041-dd79c90e607d)

### Sur quel shard avez vous rencontré le bug ?

Sur le serveur officiel

**Comment by BastLast** [comment]
si qqun peut investiguer ceci  ça serait cool

**Comment by Gabrielre14** [comment]
Quel est ton attaque avec et sans ton diamant ?

**Comment by aureochocob0n** [comment]
C'est vrai qu'on ne voit pas bien, mais sur les photos tu peux voir la divine qui ne change presque pas et les simples faisaient également les mêmes dégâts

**Comment by Gabrielre14** [comment]
Alors il y a plusieurs raison à cela : 
1) avoir une statistique d'attaque qui passe de 500 à 600 de dégats ne change quasiment pas les dégats en raison de la formule de transformation des statistiques)
2) la variation de 5% des dégats fait que les dégats peuvent être les mêmes malgré une attaque différente. Peut-être que tu as eu +4,5% sans le diamant et -4,5% avec celui-ci, ce qui fait que tu te retrouves avec les mêmes dégats.

**Comment by Gabrielre14** [comment]
La troisième raison est que la divine a un calcul des dégats incohérent avec la classe 🤡

En effet, la différence de vitesse entre l'attaquant et le défenseur compte pour 30% dans le calcul des dégats alors que le paladin est réputé pour ne pas avoir de vitesse. 

Ainsi, le poids de l'attaque/défense est réduit ce qui explique un peu le fait que la différence n'est pas visible (même si ce qui joue le plus sont les 2 premières raisons).

**Comment by BastLast** [comment]
du coup d'après les investigations de gabriel, pas un bug, je clsoe
