### ISSUE TITLE
[BUG]: bug du timer jusqu'au prochain arrêt

### ISSUE THREAD

**Issue by unmec6876** [DraftBot-A-Discord-Adventure/DraftBot#2494]
### Description du bug.

Le timer commence vers 1-3 secondes

### Reproduction du bug.

faire /rapport sur l'île

### Captures d'écran

https://drive.google.com/file/d/16cIYg6hFLssv0UhT0P5kj4a7isJVFO7D/view?usp=drive_link

### Sur quel shard avez vous rencontré le bug ?

![Capture d’écran 2024-05-19 183317](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/139997056/8d517264-739b-42de-8637-42e89ff8297e)

**Comment by Ravenclaw-l** [comment]
C'est un bug d'affichage sur discord, ça arrive assez régulièrement. Une autre personne ne verra pas le même compte à rebours que toi sur un PC différent.
