### ISSUE TITLE
[BUG]: Guild daily non récupéré

### ISSUE THREAD

**Issue by Ntalcme** [DraftBot-A-Discord-Adventure/DraftBot#2548]
### Description du bug.

J'ai simplement récupéré mon guild daily et seul moi m'a pas eu la récompense de celui-ci dans ma guilde.
(Voir les screens)

### Reproduction du bug.

Aucune idée vu que j'ai juste fait une commande.

### Captures d'écran

![Screenshot_2024-08-07-13-23-12-158_com discord-edit](https://github.com/user-attachments/assets/840d9187-58fc-4e6d-88aa-0741c03c64ef)
![Screenshot_2024-08-07-13-23-20-470_com discord-edit](https://github.com/user-attachments/assets/955a14e7-c55a-4557-9cc8-d9e27a48dca8)
![Screenshot_2024-08-07-13-22-57-053_com discord-edit](https://github.com/user-attachments/assets/ecbaaa54-d7b7-4763-af61-0b85a0efa672)

### Sur quel shard avez vous rencontré le bug ?

1

**Comment by Nargacaura** [comment]
T'étais en alté, ce n'est pas un bug.
