### ISSUE TITLE
[BUG]: Synchronisation

### ISSUE THREAD

**Issue by CyrilleGMF** [DraftBot-A-Discord-Adventure/DraftBot#2595]
### Description du bug.

Je fais tous les jours en même temps le /bonusjournalier et le /bonusjournalierguilde
La synchronisation entre les deux ne sont plus bon, depuis le début de la semaine le bonus de guilde n'est plus récupéré correctement.

### Reproduction du bug.

 /bonusjournalier, /bonusjournalierguilde à la même heure et observer que le délais n'est plus correcte.

### Captures d'écran

![Capture d'écran 2024-10-18 101239](https://github.com/user-attachments/assets/ff402e08-2796-408f-aeaf-da681d4ca136)
![Capture d'écran 2024-10-18 101258](https://github.com/user-attachments/assets/d5f36eb2-91a1-4b14-beb1-a355f9e95e4e)

### Sur quel shard avez vous rencontré le bug ?

DraftBot
APP
 — Aujourd’hui à 10:14
:ping_pong: Pong

Latence: 183 ms
Latence API: 104 ms
Numéro du shard: 1
Nombre de shards: 4 (+main shard)

**Comment by Ravenclaw-l** [comment]
Ce n''est pas un bug, le temps d'attente pour le GD se réinitialise quand un joueur rejoint la guilde.
