### ISSUE TITLE
Améliorer l'intégration i18next

### ISSUE THREAD

**Issue by Feiryn** [DraftBot-A-Discord-Adventure/DraftBot#2624]
- [x] Voir si on peut mettre des replacements globaux pour le remplacement des slash commands dans les textes
- [x] Voir si on peut rendre lng obligatoire

**Comment by romain22222** [comment]
working on it (super facile à faire mdr)

**Comment by BastLast** [comment]
pr info sur la branche de nta j'ai update la version de i18n de quelques mineurs en esperant fix un buig de leur part mais c toujours pas fix, j'ai bump anywy

**Comment by romain22222** [comment]
(je confirme les deux possibles, je push dès que je suis assuré que ca fonctionne correctement)

**Comment by BastLast** [comment]
Pr info je comprend pas pk mais DES FOIS quand tu rajoute un context, i18n te force a mettre une string par default, jai mis l'erreur par default sur la branche de nta mais grosse incompréhension

**Comment by Feiryn** [comment]
> (je confirme les deux possibles, je push dès que je suis assuré que ca fonctionne correctement)

Le goat

**Comment by romain22222** [comment]
btw je suis en train de repasser partout dans le code pour check les endroits où il manque lng, mais ALED y'a plein d'endroits où on assigne à une variable language "interaction.userLanguage", et aucune modif on la met telle quelle dans les options, je veux pleurer quand je vois qu'une simple modification du nom de la variable permet de pas s'embêter à faire une clé
