### ISSUE TITLE
Gérer les roles / badges votes post v5

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#2625]
Vu que la possibilité de vote disparaît à la v5, il faut gérer les récompenses obtenues lors d'un vote juste avant la sortie de la v5

**Comment by Feiryn** [comment]
Le seul problème pour moi c'est le rôle voteur. Est-ce que la solution la plus simple ce n'est pas de supprimer le rôle sur discord ?

**Comment by BastLast** [comment]
Ya littéralement une issue qui gère ça deja, oui le role va disparaitre, cf lissue du mini event que je voulais faire

**Comment by BastLast** [comment]
Mais l'idée de cette issue c'est de gérer ce qu'il se passe pr les gens qui ont le role au moment de la maj

**Comment by BastLast** [comment]
Et le badge

**Comment by Feiryn** [comment]
Le rôle c'est une rôle discord, donc si on le supprime du serveur après la release de la v5, plus personne ne l'aura.
Pour le badge c'est calculé à la volée pendant la commande /profile, y a rien en bdd

**Comment by BastLast** [comment]
> Le rôle c'est un rôle discord, donc si on le supprime du serveur après la release de la v5, plus personne ne l'aura.
> Pour le badge c'est calculé à la volée pendant la commande /profile, y a rien en bdd

C'est calculé en fonction du rôle ?

**Comment by BastLast** [comment]
Well go utiliser cette issue pr supprimer tout le code qui a un rapport avec top.gg et on verra comment on fait la suite plus tard du coup

**Comment by Feiryn** [comment]
> > Le rôle c'est un rôle discord, donc si on le supprime du serveur après la release de la v5, plus personne ne l'aura.
> > Pour le badge c'est calculé à la volée pendant la commande /profile, y a rien en bdd
> 
> C'est calculé en fonction du rôle ?

Non, y a une colonne topggvoteat en bdd, et si ça date de moins de 12h on ajoute le rôle voteur au profil. Donc si on vire la colonne et le bout de code qui ajoute le badge, bah y aura plus rien

**Comment by BastLast** [comment]
Niquel, cette issue vient de devenir une quick win
