### ISSUE TITLE
[BUG]: Campagne renvoyée en arrière en terminant une mission.

### ISSUE THREAD

**Issue by DBAzura** [DraftBot-A-Discord-Adventure/DraftBot#2631]
### Description du bug.

J'avais la mission 67 (1200 points de gloire) à faire. Après avoir accompli cette dernière, je regarde les missions afin de voir la suivante, et me rends compte que je suis maintenant à la mission 26 (aller sur l'île mystérieuse) au lieu de 68. 
La mission traînait dans mes cartons depuis un bon moment (probablement l'ajout des ligues même), donc c'est peut-être pour ça que c'est revenu en arrière, sur une mission changée après, et que je n'ai techniquement pas faite... 

### Reproduction du bug.

Avoir la mission 67 à faire 
Atteindre 1200 points de gloire avec un combat et l'accomplir 
Faire /missions

### Captures d'écran

![IMG_20241029_200339](https://github.com/user-attachments/assets/63cb4eb4-1631-4499-8ba5-33d7ea3f617e)
![IMG_20241029_202259](https://github.com/user-attachments/assets/3de6e640-cca1-42ce-b3bc-0147ec60663d)
![IMG_20241029_223643](https://github.com/user-attachments/assets/d2a21d07-4684-40b7-ba6d-6a65e5265141)
![IMG_20241029_202247](https://github.com/user-attachments/assets/d4fabae8-b9c5-4df7-92d8-80d42cb02548)

### Sur quel shard avez vous rencontré le bug ?

Les shards 0 et 4 (probablement partout du coup).

**Comment by BastLast** [comment]
Hello c'est pas un bug,
Depuis une mise à jour de Db je sais plus quand si tu réussis une mission et que tu n'avais pas réussi, une mission qu'on a rajouté dans la mise à jour qui est avant celle que tu viens de réussir. Ça te téléporte en arrière. Ça te fait faire la mission qu'on a rajouté et une fois que tu l'as réussi ça te ramène là où tu étais

**Comment by BastLast** [comment]
Hello c'est pas un bug,
Depuis une mise à jour de Db je sais plus quand si tu réussis une mission et que tu n'avais pas réussi, une mission qu'on a rajouté dans la mise à jour qui est avant celle que tu viens de réussir. Ça te téléporte en arrière. Ça te fait faire la mission qu'on a rajouté et une fois que tu l'as réussi ça te ramène là où tu étais

**Comment by DBAzura** [comment]
Aïe, au temps pour moi alors 😅 Au moins je saurai à l'avenir, et merci pour la réponse rapide !
