### ISSUE TITLE
Remake des missions en draftbot v5

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2651]
- [ ] Vérifier qu'on n'a pas oublié le trigger de certaines missions

**Comment by Feiryn** [comment]
Il reste des choses à faire sur cette issue ?

**Comment by romain22222** [comment]
je dirais techniquement non, mais je dirais on laisse ouvert tant qu'on en a pas fini avec la v5 car j'ai peur qu'on oublie des triggers de missions à certains endroits (en gros faudra recheck à la fin si y'en a pas qui ont été zappé)

**Comment by Feiryn** [comment]
J'ai édité le message de base et je déplace en end of v5 alors

**Comment by BastLast** [comment]
> je dirais techniquement non, mais je dirais on laisse ouvert tant qu'on en a pas fini avec la v5 car j'ai peur qu'on oublie des triggers de missions à certains endroits (en gros faudra recheck à la fin si y'en a pas qui ont été zappé)

Go close l'issue ya des testeurs qui feront des test de la campagne en detail avant de release

**Comment by BastLast** [comment]
Si besoin on rouvrira une issue
