### ISSUE TITLE
Les annonces de top en queue devrait être limitées à 1

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2655]
![image](https://github.com/user-attachments/assets/a6bc150b-81cd-4b96-bde6-75bda7abe3ce)

Meme si ca fait 2 semaines que le bot a pas été run, pas normal d'avoir 2 annonces de suite

**Comment by BastLast** [comment]
@Feiryn 
je met en V5 pr qu'on en discute avant si c'est un izi fix go faire si c'est relou go bouger mais j'aimerai juste savoir pourquoi ya 2 annonces de suite ici

**Comment by Feiryn** [comment]
Pas un bug du coup :
- 1 message pour la fin de saison de combat en français (car le channel configuré en français est celui du screen)
- 1 message pour la fin du top week en français (car le channel configuré en français est celui du screen)
- 1 message pour la fin de saison de combat en anglais (car le channel configuré en anglais est celui du screen)
- 1 message pour la fin du top week en anglais  (car le channel configuré en anglais est celui du screen)
