### ISSUE TITLE
A INVESTIGUER

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2661]
il semble que la commande report des fois ne réponde pas ? j'ai rien dans les logs 
![image](https://github.com/user-attachments/assets/7a227d46-db97-4d68-8df3-2c2b5c3dd7ce)

**Comment by romain22222** [comment]
c'est un truc que je vais rajouter aussi ici, mais deux choses : 
- 1 le titre de l'issue n'est pas clair, il indique rien sur l'erreur en question
- 2 vu que c'est avec un bot de dev (alpha en plus), please mettez l'erreur console quand y'en a une, et quand y'en a pas, mettez le. Ca permet déjà de vérifier rapidement que l'issue a été fix ou non, et ca aide à trouver l'erreur le cas échéant

**Comment by BastLast** [comment]
tu sais quoi go close au pire on rouvrira un truc plus clair
