### ISSUE TITLE
commands requirements liés aux effets bug

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#2697]
![image](https://github.com/user-attachments/assets/6b4e0f3b-bfd0-4d7c-b9fc-970965b0668c)

**Comment by BastLast** [comment]
+ je recois un crash sur 
![image](https://github.com/user-attachments/assets/d04bf6f3-5088-4cda-88eb-acb611de4db3)
quand j'essai de faire la commande alors que je suis pas sous effet
et dans le debugger j'ai pleins de trucs en lien avec un effet qui doit être soigné

**Comment by romain22222** [comment]
alors draft j'aurais adoré un ptit message console que je puisse au moins rapidement dire ce qui va pas, après de ce que je comprends à la lecture c'est littéralement ce que j'avais dit à nta hier mais qu'on a pas fix car pas le temps : check si l'effet du joueur est null, si c'est le cas, c'est qu'il est en no effect. je check ca later

**Comment by BastLast** [comment]
> alors draft j'aurais adoré un ptit message console que je puisse au moins rapidement dire ce qui va pas, après de ce que je comprends à la lecture c'est littéralement ce que j'avais dit à nta hier mais qu'on a pas fix car pas le temps : check si l'effet du joueur est null, si c'est le cas, c'est qu'il est en no effect. je check ca later

Oui c'est le soucis jpense
