### ISSUE TITLE
Daily timeout 6x

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#271]

**Comment by BastLast** [comment]
Comportement voulu : Chaque jour, tous les pets perdent de maniere random entre 0 et 2 points d'amour sauf si ils sont dressés.

**Comment by eagles666** [comment]
il est ou le bug ? D'après mes tests, les pets perdent bien 1 point d'amour aléatoirement, sauf les pets dressés... il faudrait pas passer cette issue en enhancement par rapport au commentaire précédent ?

**Comment by BastLast** [comment]
semble résolu ? à surveiller.
