### ISSUE TITLE
Généralisation dans l'affichage des reports

### ISSUE THREAD

**Issue by pavlekowalski** [DraftBot-A-Discord-Adventure/DraftBot#277]
Modifier :
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/4a4f1079eada01694e2b21c4469fdac8c5ff9d9f/resources/text/commands/report.json#L4 
en : 
```js
"doEvent": ":newspaper: ** Journal de {pseudo} :** {event}",
```
et retirer par la même occasion dans tous les ressources/text/events quelques caractères qui n'ont rien à faire dans ce fichier.  
La même chose peut être faite avec :
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/4a4f1079eada01694e2b21c4469fdac8c5ff9d9f/resources/text/commands/report.json#L5

**Comment by BastLast** [comment]
Merci pour cette issue, la commande report va être retravaillé en décembre, nous tiendrons compte de cette remarque.

**Comment by pavlekowalski** [comment]
Le `/n/n*- Utilisez les réactions pour effectuer une action :warning: Ne pas répondre est considéré comme un choix à part !*` peut aussi être généralisé
