### ISSUE TITLE
Identifier le joueurs tout au long de son report

### ISSUE THREAD

**Issue by pavlekowalski** [DraftBot-A-Discord-Adventure/DraftBot#283]
Remplacer `pseudo: message.author.username` par  `pseudo: message.author` dans :
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/90397a2da4155a6bf68267c8e3c89fd65563dc07/src/commands/player/ReportCommand.js#L38
et
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/90397a2da4155a6bf68267c8e3c89fd65563dc07/src/commands/player/ReportCommand.js#L83
(je l'ai fait mais j'ai pas les droits pour push)

**Comment by BastLast** [comment]
Normalement tu as le droit de faire une pull request, cela nous arrangerai :+1:

**Comment by pavlekowalski** [comment]
J'ai un permission denied quand je veux push ma branche ...

**Comment by pavlekowalski** [comment]
J'ai un permission denied quand je veux push ma branche ...
