### ISSUE TITLE
Classe utilitaire pour les messages

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#289]
* Créer une classe à part avec des fonctions pour les messages
* Créer des messages de confirmation avec callback
* Déplacer le message d'erreur ici
* Créer des embeds déjà préformatés
* Ajouter différentes fonctions comme par exemple les tooltips ( https://cdn.discordapp.com/attachments/435100271413297152/791679043191439360/Screenshot_20201224-154928_Reddit.png )

**Comment by BastLast** [comment]
@niqore  tu penses le faire ca ou on abandonne ?

**Comment by niqore** [comment]
C'est terminé j'ai oublié de close
