### ISSUE TITLE
Commande admin pour donner les récompenses de tournois

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#296]

**Comment by quenquentin** [comment]
Des commandes sont déjà présentes pour donner des points et des objets ainsi que badges, pour cette issue il faut une commande admin pour set les sous d'un joueur ?

**Comment by BastLast** [comment]
Flemme et pas urgent, repoussé à X.X.X

**Comment by quenquentin** [comment]
- [ ] Afficher un message d'erreur quand pas d'argument ou arguments dans le mauvais ordre.

- [ ] Give à plusieurs en même temps

- [ ] Changer l'ordre des arguments "points (points) @mention(s)"

**Comment by BastLast** [comment]
@quenquentin  vu que tu t'es désasigné je prend la liberté de repousser la commande d'une milestone

**Comment by BastLast** [comment]
- [ ] Refaire commande pointsw
- [ ] Refaire commande point
- [ ] Faire une commande simple à utiliser avec gestion des erreurs pour gérer les points et l'argent des utilisateurs
- [ ] pouvoir give un item de manière simple et avec gestion des erreurs
- [ ] envoyer une notif en dm à l'utilisateur (si elles sont activées) l'informant de ce qui lui est arrivé. 
- [ ] pouvoir give ou retirer de l'argent à plusieurs joueurs d'un coup
- [ ] idem pr des points / points de la semaine
- [ ] gestion des erreurs et system d'aide dédié. (comme pour les commandes test)
- [ ] seulement le botowner peut faire ces commandes

**Comment by quenquentin** [comment]
@romain22222 il reste quoi concrètement à faire ?

**Comment by niqore** [comment]
Il reste à indiquer l'ordre des arguments

**Comment by romain22222** [comment]
> @romain22222 il reste quoi concrètement à faire ?

tu vois la commande give de nysvaa, faut faire en sorte de mp la personne qui a recu l'obj et gérer les erreurs.

**Comment by niqore** [comment]
J'ai un peu la flemme de le faire, je donne volontiers cette tâche à quelqu'un d'autre

**Comment by niqore** [comment]
J'avais la flemme mais je l'ai quand même fait finalement
