### ISSUE TITLE
Manque recap de fin pour certains combats 

### ISSUE THREAD

**Issue by Royal-91** [DraftBot-A-Discord-Adventure/DraftBot#309]
Certains combats se termine brusquement et ne mais aucun messages.
Les joueurs ne sont pas bloqués 

Lorsqu'il y a une égalité, le récap du combat ne s'affiche pas après le 25ème tour.
Le joueur peut continuer à jouer et n'est pas bloqué. (vu en ff et en f)

**Comment by BastLast** [comment]
Merci de maj cette issue avec le plus d'infos possible en commentaire

**Comment by BastLast** [comment]
c'est l'issue #294 je close donc celle là
