### ISSUE TITLE
l'elder est devenue chef sans raison

### ISSUE THREAD

**Issue by Royal-91** [DraftBot-A-Discord-Adventure/DraftBot#310]
Cas d'eagles, l'elder est devenue chef sans quitter la guilde :/

**Comment by BastLast** [comment]
Est-ce que c'est arrivé plus d'une fois ?

**Comment by BastLast** [comment]
c'est testé etc ? on peut close  ?

**Comment by BastLast** [comment]
excellente innitiative ca
