### ISSUE TITLE
Réactions manquantes sur commande report

### ISSUE THREAD

**Issue by Aramaya** [DraftBot-A-Discord-Adventure/DraftBot#318]
Hi!

While playing this afternoon I had a strange bug:
![bug1](https://user-images.githubusercontent.com/26212090/106904872-fc42e900-66fb-11eb-86d4-8cec95815e10.png)
A bit later, the bot finaly reactly as such: 
![bug2](https://user-images.githubusercontent.com/26212090/106904869-fbaa5280-66fb-11eb-8d98-ed03d3d006b5.png)

I believe this due to a double command (I ask for my report while someone else, from my guild by the way, was also typing.

Kindest regards,

**Comment by BastLast** [comment]
Hi thx for your report. we are going to take a look at it.

**Comment by quenquentin** [comment]
We are sorry but it's a Discord problem so we can't do anything.

**Comment by Aramaya** [comment]
Ouch!

Sorry for you guys... Thank you for telling me.

**Comment by BastLast** [comment]
Just to be sure, can you reload discord and check if the reaction appears now under the report that appear on your screen ?

**Comment by Aramaya** [comment]
No change at all.
The bot reactions do not apppear.

**Comment by BastLast** [comment]
Ok so I do not think it is a discord bug so we will definitely take a look

**Comment by Aramaya** [comment]
Thanks. 
BTW, this is not the first it happens. Last time it was to one of my friends.

**Comment by quenquentin** [comment]
May can you share a screen please ?

**Comment by Aramaya** [comment]
Well, that'd be difficult. He just told me. 😅
I finally had proof a few hours ago whenit  happen to me.

**Comment by BastLast** [comment]
Pas de nouvelles depuis longtemps
