### ISSUE TITLE
Un animal fielleux ne peux pas etre transféré.

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#321]
un animal fielleux ne peux pas être vendu, échangé ou déposé dans le stockage de guilde. (il peut être récupéré)

Ce qui force les gens à s'en occuper pour les vendre. (mouahah)

**Comment by BastLast** [comment]
et commande freepet deviens payante (1000 d'argent)

**Comment by BastLast** [comment]
ne pas faire avant d'avoir ajouté des bonus liés aux pets (cf #322)

**Comment by BastLast** [comment]
Ajouter clarification paiement libération pet fielleux

**Comment by quenquentin** [comment]
Issue à close je présume ?

**Comment by BastLast** [comment]
A tester avant ! 

Dim 28 mars 2021, à 14:15, QuenQuentin a écrit :

**Comment by BastLast** [comment]
La personne qui a codé ca a oublié d'autoriser le retrait de familier fielleux de l'abris de guilde (sinon on s'en débarasse comment ???)
