### ISSUE TITLE
problèmes dans l'affichage de l'achat d'items dans les logs

### ISSUE THREAD

**Issue by eagles666** [DraftBot-A-Discord-Adventure/DraftBot#324]
undefined pour le nom de l'item et le prix

**Comment by eagles666** [comment]
après vérification, il semble qu'il n'y est pas de bug ...

**Comment by BastLast** [comment]
well then

**Comment by eagles666** [comment]
bah du coup si ...

**Comment by romain22222** [comment]
il y a un double message dans les logs pour l'optention d'un truc au shop
j'ai réglé ca

**Comment by romain22222** [comment]
sinon plus de problème sur les "undefined" censés apparaître, je close
