### ISSUE TITLE
petit équilibrage des fights et des classes

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#326]

**Comment by quenquentin** [comment]
#246

**Comment by BastLast** [comment]
si qqun est chaud pr lancer une instance et faire masse de test : autorisation de ping les testuers plus j'ai de retours là dessus avant la release mieux c'est. zoubi

**Comment by BastLast** [comment]
(à défaut, je close ca dans une semaine)

**Comment by BastLast** [comment]
Je pense que c'est un bon début pour cette maj, merci à tous ceux qui ont participé aux tests
