### ISSUE TITLE
Passer le daily sur un schéma qui dure 22h au lieu d'un système journalier 

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#329]
Pour éviter cet abus :

'ai 2 items : un item d'argent quotidien et un item de boost pour les combats
J'avais l'habitude tous les jours de faire : switch + daily + switch 
afin d'avoir l'argent quotidien et être sûr ensuite de garder mon item de combat actif
Maintenant donc, la modif fait que le switch m'empêche de gagner l'argent quotidien
Sauf que cette bride peut être contournée de la manière suivante :
- Au début de journée, mon objet actif est l'argent
- Je fais donc un daily et ça marche
- Je fais ensuite un switch immédiatement après pour avoir mon item de combat actif
- A la fin de la journée, je refais un switch, pour avoir l'item d'argent actif pour le lendemain matin

**Comment by BastLast** [comment]
je propose du coup pour balancer un peu le truc : 

Chaque fois qu'on fait la commande daily, on se bloque pdt 22H le daily
Chaque fois qu'on fait la commande switch on augmente de 6h le temps avant le prochain daily (sauf si la somme résultante dépasse 22h auquel cas on plafonne)

**Comment by BastLast** [comment]
On peut aussi imaginer que le temps de blocage lorsqu'on fait un switch diffère en fonction de la rareté de l'item ? à discuter, si ya du feedback hésitez pas à le mettre ici!

**Comment by quenquentin** [comment]
Perso je suis pas fan de l'idée d'augmenter en fonction de la rareté, sinon c'est une bonne idée dans ton optique de nerf ça effectivement.

**Comment by eagles666** [comment]
non mais 30 minutes c'est bien aussi ... genre le principe de base d'un daily c'est d'avoir une récompense tous les jours. 
- "On peut aussi imaginer que le temps de blocage lorsqu'on fait un switch diffère en fonction de la rareté de l'item ? à discuter, si y'as du feedback hésitez pas à le mettre ici!" -> à part perdre tous les joueurs avec un autre système totalement incompréhensible, y'as un autre intérêt ?
Personnellement, je reste sur mon idée que genre si tu fait switch, ca te rajoute genre 30 min de cooldown en plus, parce que c'est raisonnable, ca nerf un peu le système, mais ca reste plus fun d'attendre 30 min de plus que de pas avoir de daily pendant 1 semaine...

**Comment by BastLast** [comment]
30 minutes pour moi c'est pas assez  sincérement, ca pousse pas les gens à revenir une autre fois dans la journée.

**Comment by eagles666** [comment]
bah la, les gens doivent attendre un jour de plus donc bon

**Comment by BastLast** [comment]
6h != un jour

**Comment by BastLast** [comment]
c'est fini du coup ?
