### ISSUE TITLE
slash commands

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#331]
En cours : 

- [x] fight et dérivées

A faire :

`facile à traduire`

`moins facile à traduire`

`à rediscuter avec l'équipe principale`

`finies`
- [x] top et dérivées
- [x] pettrade
- [x] petsell
- [x] petfree
- [x] guildelderremove
- [x] guildkick
- [x] guildelder
- [x] drink et dérivées
- [x] switch
- [x] guilddesc
- [x] guildleave
- [x] unlock
- [x] daily
- [x] sell
- [x] guildadd
- [x] guildcreate
- [x] guilddaily
- [x] report
- [x] petfeed (regarder pour éviter les ambiguités)
- [x] class
- [x] pettransfer
- [x] profile
- [x] petnick
- [x] classstats
- [x] shelter
- [x] guildstorage
- [x] invite
- [x] update
- [x] missions
- [x] inv
- [x] badges
- [x] vote
- [x] shop
- [x] guild
- [x] ping
- [x] rarity
- [x] dmnotifications
- [x] help
- [x] unblock
- [x] sendlogs
- [x] senddata
- [x] respawn
- [x] map
- [x] pet
- [x] language
- [x] prefix (faire juste une commande qui explique que c'est plus possible de changer de prefix)
- [x] test
- [x] servers
- [x] sendprivatemessage
- [x] resetbadges
- [x] listitems
- [x] give
- [x] givebadge
- [x] debugblocked
- [x] changepointsweek
- [x] changepoints
- [x] changemoney

**Comment by eagles666** [comment]
bah du coup perso je vois pas trop l'utilité de ce type de commandes, vu que notre système actuel marche bien, et faire des slash commandes, c'est accepter les limites imposées par discord (50 commandes globales disponibles 1 heure après leur création, et 50 commandes spécifiques au serveur), ce que je trouve pas fou non plus ... sinon pour la partie technique, pour l'instant c'est pas supporté par discord.js donc faut soit utiliser un module qui le fait, ou soit faire le système nous même ... honnêtement je comprends même pas l’intérêt de ses dernières, parce que au final on à déjà tout

**Comment by BastLast** [comment]
ok go attendre que ca soit supporté par discord js, la raison, pour laquelle ca vaut le coup c'est que ca facilite l'apprentissage pr les nouveaux utilisateurs

**Comment by BastLast** [comment]
je décale l'issue de milestone, à déplacer quand discord js supporte le truc

**Comment by eagles666** [comment]
oué mais ca risque pas de faire doublon ? parce que ca fait deux endroits différents pour les commandes et je trouve ca moins clair que de juste expliquer quand un bot rejoint un serveur de faire la commande help (bonne idée ca d'ailleurs) ... après a voir l'avis des autres sur la question

**Comment by BastLast** [comment]
je pensais remplacer les commandes par des slash commandes à terme

**Comment by eagles666** [comment]
euh ... bof ... ca veut dire perdre tout ce que on a fait au profit d'un système codé par discord (j'ai rien contre discord hein mais ils en sont quand même à coder des trucs que les bots intègrent déjà depuis longtemps)

**Comment by quenquentin** [comment]
Des news concernant l'issue ? Savoir où on va si on fait ce système déjà

**Comment by BastLast** [comment]
je viens de check la doc de discord js et ca semble pas hyper méga dur, ca sera l'occasion de refacto le fichier command.js en ts !

**Comment by Feiryn** [comment]
D'ailleurs je propose de faire les commandes admin à la fin car pas urgentes si elles sont pas dispo le 1er avril

**Comment by BastLast** [comment]
Je valide

**Comment by romain22222** [comment]
faites : 

- [ ] invite
- [ ] update
- [ ] inv
- [ ] badges
- [ ] vote
- [ ] ping


en cours :

- [ ] report
- [ ] profile

à faire en priorité :

- [ ] drink
- [ ] fight
- [ ] shop et dérivées
- [ ] top et dérivées
- [ ] missions
- [ ] guild
- [ ] guildDaily
- [ ] senddata
- [ ] sendlogs

**Comment by Pietagorh** [comment]
Je fais le profile du coup

**Comment by romain22222** [comment]
faites : 

- [x] invite
- [x] update
- [x] inv
- [x] badges
- [x] vote
- [x] missions
- [x] shop et dérivées
- [x] guild
- [x] ping

en cours :

- [ ] report
- [ ] profile
- [ ] help

à faire en priorité :

- [ ] drink et dérivées
- [ ] fight et dérivées
- [ ] top et dérivées
- [ ] guilddaily
- [ ] senddata
- [ ] sendlogs

liste du reste des commandes :

- [ ] unlock
- [ ] switch
- [ ] sell
- [ ] respawn
- [ ] map
- [ ] dmnotifications
- [ ] daily
- [ ] classstats
- [ ] class
- [ ] pettransfer
- [ ] pettrade
- [ ] petsell
- [ ] petnick
- [ ] petfree (regarder pour éviter les ambiguités)
- [ ] petfeed (regarder pour éviter les ambiguités)
- [ ] pet
- [ ] guildstorage
- [ ] shelter
- [ ] guildleave
- [ ] guildkick
- [ ] guildelderremove
- [ ] guildelder
- [ ] guilddesc
- [ ] guildcreate
- [ ] guildadd

urgent--- :
- [ ] unblock
- [ ] test
- [ ] servers
- [ ] sendprivatemessage
- [ ] resetbadges
- [ ] listitems
- [ ] give
- [ ] givebadge
- [ ] debugblocked
- [ ] changepointsweek
- [ ] changepoints
- [ ] changemoney
- [ ] language

**Comment by romain22222** [comment]
liste des problèmes à régler : 

- commande test :
   - 2 fonctions qui dépendent de la commande report (forcereport / smallEvent)
   - 1 fonction qui dépend de la commande guilddaily (guildreward)
   - une fonction qui plante à cause des constantes transformées (experience)
   - deux fonctions qui plantent à cause d'un problème d'awaiter (fakevote / forcetopweekend)
- EffectErrorMe : faire en sorte qu'il reply et non juste un envoi de message
