### ISSUE TITLE
Notifications par DM

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#341]
Specifications :

- [x] Ajout d'une commande `dmnotification` : 
Cette commande permet d'activer les notifications par messages privés. 
La commande affiche un message privé si la personne a ses messages privés désactivés.
Les notifications sont activées par défaut.
Si la personne a les notification activées, la commande désactive les notifications.

- [x] Modifier le code qui envoi un message privé à la mort. 
Le message sera désormais envoyé dans le chat où le joueur joue si la personne a les notifications désactivées
Le message doit être placé dans un embed qui reprend le même schéma que les autres embeds du bot.
Le footer de l'embed doit mentionner que les joueurs peuvent activer les alertes en messages privés si ils le souhaitent

- [x] Modifier le code qui envoi un message privé quand la personne fait !help et qu'elle n'est pas sur le serveur du bot.
Le message n'est juste pas envoyé si la personne a les notifications désactivées

- [x] Si une personne qui a les notifications dm désactivées envoi un dm au bot, l'émoji :no_bell:  apparait à coté de son id dans la copie de son message privé qui est envoyé dans le channel des messages privés du bot mais il est toujours possible d'utiliser la commande dm pour lui envoyer un message

- [Abandonné] Si une personne bloque ses messages privés et que le bot se tape une erreur en essayant d'envoyer un message privé, le champ "notification" est passé à false automatiquement

- [x] Ajouter la documentation sur les notifications en message privé dans la commande `help`

- [x] Créer le code qui envoi un message en dm quand le `guilddaily` est effectué (sous forme d'embed comme les autres du bot.)
Le message indique qui a récup la récompense et quest-ce que le joueur a obtenu.

- [x] Créer le code qui envoi un message en dm quand un joueur est débloqué par la commande `unblock` (sous forme d'embed comme les autres du bot.)

Doit être fait sous forme d'une fonction globale dans le fichier tools qui prend en paramètre un message et un utilisateur.

**Comment by eagles666** [comment]
relatif à l'issue 333 (https://github.com/DraftBot-A-Discord-Adventure/DraftBot/issues/333).
