### ISSUE TITLE
Backup de la BDD

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#342]
Ajouter un channel privé par exemple où le bot poste chaque jour la base de données

**Comment by BastLast** [comment]
Faire les backups sur discord ? est-ce que c'est vraiment le meilleur système ? si le channel est delete ou perdu pr une raison ou pour une autre rip la bdd

**Comment by BastLast** [comment]
une idée de cloud backup suffisemment sécurisé et de préférence gratuit ?

**Comment by niqore** [comment]
Il y a tous les classiques dropbox, google etc... Pas privacy-friendly mais gratuit. Après il suffit de chiffrer la bdd pour garder tout privé. Pour dropbox il semblerait qu'il y ait des modules par exemple https://www.npmjs.com/package/dropbox. Google je trouve pas.  Après il y a d'autres services de backup gratuis privacy friendly style tresorit ou sync.com mais pour le lier en js au bot je sais pas si ça va être simple.

**Comment by BastLast** [comment]
pourquoi ne pas simplement les envoyer sur le serveur digital océan ?

**Comment by BastLast** [comment]
bon, étant donné le temps que ca prendrait et la flemme je propose de faire ca en 2.2.1

**Comment by Asemerald** [comment]
> 
> 
> Faire les backups sur discord ? est-ce que c'est vraiment le meilleur système ? si le channel est delete ou perdu pr une raison ou pour une autre rip la bdd

T'as souvent perdu un channel ? Et la proba que tu perde le channel et que t'ai besoin de la bdd en meme temps est si faible mdr

**Comment by eagles666** [comment]
Et genre ca nous sert rien de garder des DB qui datent de plus de deux semaines si ? donc même si le salon est supprimé pour une raison ou une autre (vous êtes genre 4 à pouvoir supprimer des salons et il faut appuyer sur deux boutons + message de confirmation qui te dit le nom du canal en question donc pour le supprimer faut vraiment le vouloir) ... après je sais pas si c'est correct de laisser trainer les données de tous les joueurs sur un salon discord ou y'as 0 sécurité et ou les données sont lisibles par tous les gens qui voient le canal ... y'as pas vraiment de données sensibles mais bon :)

**Comment by BastLast** [comment]
> > 
> > 
> > Faire les backups sur discord ? est-ce que c'est vraiment le meilleur système ? si le channel est delete ou perdu pr une raison ou pour une autre rip la bdd
> 
> T'as souvent perdu un channel ? Et la proba que tu perde le channel et que t'ai besoin de la bdd en meme temps est si faible mdr

Oue mais c'est aussi des "bonnes pratiques" et ca permet de faire joujou avec du ftp interserv

**Comment by niqore** [comment]
J'ai mis par défaut un backup toutes les 12h de la base de données avec un backup au démarrage également
Est-ce que je fais un système d'effacement des backups automatique ?

**Comment by BastLast** [comment]
C'est envoyé ou les backups ?

**Comment by niqore** [comment]
Pour l'instant j'ai mis une copie locale et une copie sur dropbox. C'est modulable dans le fichier de config :
```
  "//ENABLED_BACKUPS": "Enabled backups. May contain LOCAL and DROPBOX and must be separated with commas (e.g. LOCAL,DROPBOX)",
  "ENABLED_BACKUPS": "",

  "//BACKUP_ARCHIVE_PASSWORD": "Zip backup archive password",
  "BACKUP_ARCHIVE_PASSWORD": "",

  "//DROPBOX_TOKEN": "Ths dropbox token used to backup the database",
  "DROPBOX_TOKEN": "",
```

**Comment by BastLast** [comment]
Pr la backup locale, on garde que les 10 dernières ca suffit. Pr dropbox on a combien de place ?

**Comment by niqore** [comment]
10 dernières ça fait peu je trouve, peut-être plutôt les 30 dernières (ça fait 15 jours, après faut compter que les redémarrages créent des nouvelles sauvegardes).
Avec l'offre gratuite il y a 2 Go sur Dropbox, sachant que la base de données compressées fait environ 3,5Mo, ça permet d'en stocker grosso modo 500.

**Comment by BastLast** [comment]
Est-ce que ca serait complexe de l'envoyer par mail automatiquement ?

**Comment by niqore** [comment]
Justement non, grâce à la structure modulable que j'ai développé c'est assez simple :)

**Comment by BastLast** [comment]
Quel deus

**Comment by BastLast** [comment]
Bah du coup sincèrement je te fais confiance pr la suppression auto.

**Comment by niqore** [comment]
Je pense que je vais mettre une limite en terme d'espace disque sur la sauvegarde locale et supprimer les plus vieilles au fur et à mesure, pour Dropbox je vais aller au max de ce qui est dispo et aussi supprimer au fur et à mesure. Puis je vais ajouter une option par email.

- [ ] Suppression automatique des anciennes sauvegardes
- [ ] Envoi de la bdd par email

**Comment by BastLast** [comment]
1 mail / semaine a contact@draftbot.com

Pr dropbox faudrait créer un compte avec cette adresse aussi

**Comment by niqore** [comment]
Le mail ça rajoute de la complexité pour rien et en vrai aucun intérêt vu qu'il y a déjà un backup dropbox qui est en ligne
