### ISSUE TITLE
rework des précédents events : généralisation des emojis unicode et fix des émojis manquants

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#346]

**Comment by romain22222** [comment]
le but de cette issue, rajouter les émojis manquants sur certaines intros d'event  (voir next PR) et uniformisation des émojis unicode (plus d'émojis style discord)

**Comment by BastLast** [comment]
@romain22222  c'est fini ca ?

**Comment by BastLast** [comment]
ok je close du coup :) à réouvir si romain est pas doué :kiss:
