### ISSUE TITLE
Ajout de "mini-events"

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#348]
pas encore créé : 

créé, mais manque les textes : 

créé, mais manque la traduction des textes :
- [x] class
- [x] smallBadEvent
- [x] botVote
- [x] bigBadEvent
- [x] findPet
- [x] findItem
- [x] petInteractions
- [x] winHealth
- [x] winPersonalXP
- [x] winGuildXP

créé et prêt pour tous les tests du monde :
- [x] doNothing
- [x] interactOtherPlayers
- [x] shop
- [x] findPotions
- [x] staffMember

Autres tâches plus générales : 

- [x] Faire l'affichage en embed des mini events
- [x] coder l'interfacage des mini events avec la commande rapport

**Comment by BastLast** [comment]
commits lités : 

25ab773d24ebebc7da7577cdbbb1230fe4a28352
3e847b0fc0a3d1a4635b75bd3eb8fe278f2e9c31
7d50d284007bb488db97cbf5bda380e7a1065725

**Comment by BastLast** [comment]
psst @niqore  faut tag l'issue :p 48656306a2a466403e4be4e3c117d5b90872b705

**Comment by BastLast** [comment]
mini shop fini, plus qu'à integrer les phrases ici https://hebdo.framapad.org/p/1vk6fs221u-9mhx?lang=fr  et à traduire

**Comment by BastLast** [comment]
@romain22222  btw l'issue à tag pr les mini event c'est celle là et pas #322

**Comment by romain22222** [comment]
Fichiers à remplir pour next maj :

[ ] /ressources/text/maplocations : tous les desc_fr et desc_en
[ ] /ressources/text/small_events/botVote.json : créer des stories d'intro qui marchent avec les 3 sorties
[ ] /ressources/text/small_events/bigBadEvent.json : toutes les stories
[ ] /ressources/text/small_events/class.json : toutes les stories
[ ] /ressources/text/small_events/findItem.json : partie anglaise
[ ] /ressources/text/small_events/findPet.json : toutes les stories
[ ] /ressources/text/small_events/pet.json : partie anglaise
[ ] /ressources/text/small_events/smallBadEvent.json : toutes les stories
[ ] /ressources/text/small_events/winGuildXP : partie anglaise
[ ] /ressources/text/small_events/winHealth : partie anglaise
[ ] /ressources/text/small_events/winPersonalXP : partie anglaise

**Comment by romain22222** [comment]
update des listes
