### ISSUE TITLE
Amélioration altération prison

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#368]
- [x] Ajout d'une commande permettant à un joueur de payer une caution de 3000 d'argent pour libérer un autre joueur (à voir si on limite cette commande aux joueurs situés au même endroit que le joueur emprisonné ?)

- Certaines commandes ne devraient pas être disponibles quand on est en prison : 
- [x] Commande feedpet
- [x] Commande petname
- [x] Check toutes les autres commandes qui ne devraient pas être possibles depuis la prison

**Comment by rlarbals822V2** [comment]
Il suffit d'ajouter le code de check d'effet avant de faire la commande. Si le membre est enfermer return l'embed comme quoi tu est prisonniers

**Comment by BastLast** [comment]
cette partie là est déjà codé mdr ya juste pas l'effet prison dans la liste des effets interdits de la commande mais c'est littéralement bcp plus simple que ce que tu pense, c'est même pas une ligne de code à rajouter c'est un mot de code :laughing:

**Comment by rlarbals822V2** [comment]
C'est EFFECT.LOCKED a rajouté non?

**Comment by Chevalier2** [comment]
Y a le shop, le profil, help, les commandes de guilde comme guildadd/guildkick, le petfree, les ff...

**Comment by rlarbals822V2** [comment]
Il faudrait qu'on ne puisse rien faire

**Comment by BastLast** [comment]
> Y a le profil, help, language, prefix, les commandes de guilde comme guildadd/guildkick, le petfree, les ff... qu'on peut faire.

Bcp des commandes que tu as cité sont déjà bloquées -_- On cherche seulement celles qui ne le sont pas.

les commandes `help`, `profile`, `ping`, `prefix`, `language` doivent rester accessibles à tout moment. On ne bloque que les commandes de jeu.

**Comment by rlarbals822V2** [comment]
oui c'est ce que je voulais dire

**Comment by BastLast** [comment]
Dans la liste des commandes qui devraient pas être dispos selon moi : 

petfree, petfeed, petnick, drink,

**Comment by rlarbals822V2** [comment]
```js
if (
        (await canPerformCommand(
            message,
            language,
            PERMISSION.ROLE.ALL,
            [EFFECT.BABY, EFFECT.DEAD, EFFECT.LOCKED],
            entity
        )) !== true
    ) {
        return;
    }
    if (await sendBlockedError(message.author, message.channel, language)) {
        return;
    }
 ```
 
 Il sufit de rajouter ça au début de chaque commande qu'il faut bloquer

**Comment by BastLast** [comment]
> ```js
> if (
>         (await canPerformCommand(
>             message,
>             language,
>             PERMISSION.ROLE.ALL,
>             [EFFECT.BABY, EFFECT.DEAD, EFFECT.LOCKED],
>             entity
>         )) !== true
>     ) {
>         return;
>     }
>     if (await sendBlockedError(message.author, message.channel, language)) {
>         return;
>     }
> ```
> 
> Il sufit de rajouter ça au début de chaque commande qu'il faut bloquer

pas tout le code hein juste le "effect locked" 

btw pas besoin de le mettre en commentaire go le faire directement mdr

**Comment by rlarbals822V2** [comment]
Personnellement je bloquerait toute les commandes in games donc toute les commandes dans les catégories ``pets`` et ``player``, dans la catégorie ``guild`` seul GuildKickCommand.js ou GuildLeaveCommand.js serait accesible.

**Comment by BastLast** [comment]
nope, des commandes comme `profile` doivent rester accessibles

**Comment by rlarbals822V2** [comment]
Ouai profile et inv peuvent rester accessible

**Comment by rlarbals822V2** [comment]
```js
if (
		(await canPerformCommand(
			message,
			language,
			PERMISSION.ROLE.ALL,
			[EFFECT.BABY, EFFECT.DEAD],
			entity,
			GUILD.REQUIRED_LEVEL
		)) !== true
	) {
		return;
	}

	if (await sendBlockedError(message.author, message.channel, language)) {
		return;
	}
	```

ici sufit d'ajouter EFFECT.BABY, EFFECT.DEAD, EFFECT.LOCKED

**Comment by Chevalier2** [comment]
Et petfree ? Car même en prison, tu peux leur dire que tu veux plus de ton animal.

**Comment by rlarbals822V2** [comment]
ca peu attendre je pense un petfree

**Comment by rlarbals822V2** [comment]
sachant que profile ok mais en fait inventory on peu pas y acceder vu qu'avant d'aller dans la prison on nous "enleve" ce qu'on a

**Comment by BastLast** [comment]
@Asemerald  on est d'accord que tu n'as fait que la commande tu t'es pas du tout occupé de la partie blocage des commandes ?

**Comment by BastLast** [comment]
OK NE PLUS TOUCHER A CA, JE M'EN OCCUPE A LA FIN DE LA MAJ

**Comment by BastLast** [comment]
Il y a un soucis sur la commande unlock @romain22222  ca enleve pas l'effet correctement
