### ISSUE TITLE
Suggestion pour SECURITY.md

### ISSUE THREAD

**Issue by rlarbals822V2** [DraftBot-A-Discord-Adventure/DraftBot#374]
Je pense qu'il serait important a la fin de rajouter

Use the bot's discord server if you find any security breach.
Join [DraftBot's server english version](https://discord.gg/DxW4DCuE4V)
Rejoindre [Le server de DraftBot version française](https://discord.gg/BG7PcevE)
```
Use the bot's discord server if you find any security breach.
Join [DraftBot's server english version](https://discord.gg/DxW4DCuE4V)
Rejoindre [Le server de DraftBot version française](https://discord.gg/BG7PcevE)
```

**Comment by BastLast** [comment]
(useless)
