### ISSUE TITLE
Ajout d'un mini event api nasa

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#376]
rajouter un mini évent ou tu rencontre un mec qui lit les astres

et genre utiliser l'api de la nasa pour avoir des info réelles sur un astéroides et les afficher

**Comment by BastLast** [comment]
@niqore  je nous assigne comme ca on nous vole pas l'issue :p

**Comment by BastLast** [comment]
@niqore dispo demain pour finir ca ?

**Comment by BastLast** [comment]
repoussé à la prochaine maj par manque de motivation des devs xD

**Comment by niqore** [comment]
2d2d5ecb28fe8bd861a2806de871a74af0e726ee
