### ISSUE TITLE
Bug pettrade

### ISSUE THREAD

**Issue by The5410** [DraftBot-A-Discord-Adventure/DraftBot#380]
Il est impossible d'accepter un pettrade
![image](https://user-images.githubusercontent.com/68448566/114146725-39a03e80-9918-11eb-8439-5b1480eb5061.png)

**Comment by Asemerald** [comment]
T'es sur d'avoir bien lu ça ? ![image](https://user-images.githubusercontent.com/63583036/114147517-7290e100-9921-11eb-9dba-5e01f6554fe3.png)

**Comment by Asemerald** [comment]
A close
