### ISSUE TITLE
Augmentation de la taille de l'inventaire

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#381]
La réserve peut maintenant contenir 3 items au lieu d'un et peut contenir des potions, des armes et des boucliers.

La réserve peut être améliorée dans le shop. Chaque amélioration débloque un slot supplémentaire. Le coût des améliorations est progressif.

(500 , 1000, 2500, 5000, 7500, 10000, 15000)

La commande inventaire n'affiche plus la réserve mais affiche un petit texte expliquant que la réserve peut etre vue à l'aide de la commande correspondante

Une commande `réserve` (ou un truc du genre) est crée pour afficher la liste des items en réserve classés par types et numérotés.

La commande `!switch` affiche la réserve mais le bot ajoute des réactions de 1 au nombre d'item dans la reserve.
Le joueur peut ainsi sélectionner un item. Quand un item est selectionné, son type est detecté par le bot et l'échange est automatique et instantanné.

La commande `drink` test si le joueur a une potion active, si non elle vérifie si le joueur en a une dans sa reserve si oui, ca affiche un texte comme quoi il faut qu'il mette sapotion dans son inventaire pour la boire sinon ca dit qu'il a aucune potion sur lui.

La commande `daily` recoit les meme modifs que la comande `drink`

La commande `sell` affiche la meme interface que la commande `sell` sauf que quand un item est selectionné, son prix est affiché et une confirmation est demandée au joueur avant la vente.

**Comment by niqore** [comment]
Je m'occupe de ça dans les prochains jours

**Comment by niqore** [comment]
- [ ] Tester si le resaleMultiplier marche bien dans le mini event shop

**Comment by niqore** [comment]
Bugs à corriger :
- Le switch ne débloque pas le joueur parfois
- La réaction du shop n'a pas marché une fois

**Comment by niqore** [comment]
Mettre un titre aux embeds slel et switch + explication
