### ISSUE TITLE
Ajouter un mini event qui affiche le dernier tweet du bot

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#385]
Utiliser l'api twitter ?

**Comment by Thero1st** [comment]
J'ai peur que faire sa pub une fois mène à le refaire plus tard, rendant le bot similaire à tous ces jeux mobiles Free-to-Play, et que cela coupe le joueur dans son aventure sans que ça n'y apporte rien.

**Comment by Chevalier2** [comment]
Mettre le lien du Twitter, déjà avec une commande, je suis pour. Mais dans un mini event, je suis largement contre. Ca casse le rp, surtout que le Twitter du bot est pas vraiment dans le rp du bot.

**Comment by Asemerald** [comment]
Perso jsuis pour, c'est pas comme si on faisait une pub pour nord vpn ou raid shadow legend. Si ça casse le 4eme mur de façon humouristique ça peut etre qu'un +

**Comment by Thero1st** [comment]
Oui m'enfin, une pub reste une pub. Et même si c'est super bien fait, ça doit pas être quelque chose qui arrivera à nouveau. Si ça commence à casser le 4ème mur à tous les events, ça n'aura plus rien de spécial.
