### ISSUE TITLE
Remplacer toutes les apostrophes par des apostrophes typographique

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#388]
askip c'est mieux pr les lecteurs d'écran d'utiliser ’ à la place de ' .

+ webstorm me gueule dessus sur tous les mots du coup tant que ce soucis n'est pas fix rendant useless le spellcheck

**Comment by romain22222** [comment]
je peux le faire pour la 220 ca va vite

**Comment by BastLast** [comment]
Jia parlé avec jetbrain sur Twitter en fait on le fait pas
