### ISSUE TITLE
Le role voteur ne semble pas être retiré correctement

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#405]
après 24 h les joueurs ont toujours le role

**Comment by romain22222** [comment]
![image](https://user-images.githubusercontent.com/29299679/120195991-9edd2580-c21f-11eb-9b0d-4d4e4e6326d9.png)

**Comment by BastLast** [comment]
Tu peux le corriger ?

**Comment by romain22222** [comment]
faut voir

**Comment by romain22222** [comment]
est-ce toujours d'actualité ?

**Comment by BastLast** [comment]
Faut test

**Comment by BastLast** [comment]
toujours d'actualité

**Comment by romain22222** [comment]
ok de ce que je vois, le cache de guilde n'est plus complètement accessible par les bots
Il peut y avoir un autofix via l'Intent de discord partner, mais on ne peut pas savoir pour le moment.
Suggestion si pas autofix : recoder verifyDBLRoles : on récupère les personnes ayant votés (pas de dates < 2000) (via requete sql), puis on rajoute un timeout sur son role. dès qu'on enlève le role, on reset aussi le topggATime à la date originelle afin de ne pas surcharger le bot via cette fonction.

**Comment by BastLast** [comment]
je déplace en X.X.X au cas ou autofix

**Comment by quenquentin** [comment]
Pas été fix ? Via l'obtention des intent

**Comment by BastLast** [comment]
au oui bien vu 
go mettre en 2.2.1
