### ISSUE TITLE
Création d'une commande `map`

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#406]
qui affiche un lien vers une photo de la carte du jeu (qui doit être réalisée)

**Comment by Nininanou16** [comment]
pas envie de faire un petit système avec canvas qui place automatiquement la pp du gars sur la route/l'emplacement sur le quel il est ?

C'est pas si compliqué a faire, mais ca peut être très sympa je pense ^^

**Comment by BastLast** [comment]
nan ca sera moche ou trop lourd

**Comment by BastLast** [comment]
- [ ] Ajouter une description pour chaque lieu
- [ ] Ajouter l'affichage de la description du lieu vers lequel le joueur se dirige

**Comment by BastLast** [comment]
f8acdbd011f2e0a53da8e5fcd9a175a58fe5317f tu vois @romain22222  c'était pas 408 le numéro de l'issue :rage:

**Comment by BastLast** [comment]
Il reste quoi à faire sur cette commande ?
