### ISSUE TITLE
Créer item donateur pour ☠︙𝐒 𝐚 𝐧 𝐬 #9138

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#407]

**Comment by quenquentin** [comment]
Je veux bien prendre si jamais.

**Comment by BastLast** [comment]
OK je mettrai les infos sur cette issue quand je les aurai 

Ven 21 mai 2021, à 11:04, QuenQuentin a écrit :

**Comment by BastLast** [comment]
done in ae4b4c847459c615520f30df6be7e0a8be616ef1
