### ISSUE TITLE
fix typos pour la 2.2.0

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#408]

**Comment by romain22222** [comment]
issue à tag si on fait des corrections de typos sur des textes déjà présent dans le bot, et qui ne sont taggables par aucune autre issue

**Comment by BastLast** [comment]
![faute.PNG](https://user-images.githubusercontent.com/38099970/120103572-89e59100-c150-11eb-920d-6d95a2130d7d.PNG)

**Comment by Nininanou16** [comment]
![Capture d’écran de 2021-05-30 14-20-42](https://user-images.githubusercontent.com/71654580/120104233-b64edc80-c153-11eb-906d-6895eaf7de9a.png)

dans le smallevents.json :+1:
-- Vous n'arrivez pas a les retrouver malheuresement
++ Vous n'arrivez malheuresement pas a les retrouver

**Comment by Nininanou16** [comment]
![Capture d’écran de 2021-05-30 14-30-46](https://user-images.githubusercontent.com/71654580/120104255-d67e9b80-c153-11eb-9c8b-5fbf8a56c5de.png)

Manque un espace

**Comment by Nininanou16** [comment]
![Capture d’écran de 2021-05-31 12-01-54](https://user-images.githubusercontent.com/71654580/120176817-038c8600-c208-11eb-83a6-479c42c65d46.png)
small events.json
majuscule au millieu de la phrase

**Comment by romain22222** [comment]
> ![Capture d’écran de 2021-05-30 14-30-46](https://user-images.githubusercontent.com/71654580/120104255-d67e9b80-c153-11eb-9c8b-5fbf8a56c5de.png)
> 
> Manque un espace

où ?

**Comment by Nininanou16** [comment]
> > ![Capture d’écran de 2021-05-30 14-30-46](https://user-images.githubusercontent.com/71654580/120104255-d67e9b80-c153-11eb-9c8b-5fbf8a56c5de.png)
> > Manque un espace
> 
> où ?

> Après l'avoir soigné{feminine}
-> Après l'avoir soigné {feminine} 
Non ?

**Comment by Nininanou16** [comment]
![Capture d’écran de 2021-06-01 18-52-06](https://user-images.githubusercontent.com/71654580/120361759-8990f580-c30a-11eb-9d44-337c06d4950b.png)
-- Racontez
++ Raconter

**Comment by Nininanou16** [comment]
> ![Capture d’écran de 2021-06-01 18-52-06](https://user-images.githubusercontent.com/71654580/120361759-8990f580-c30a-11eb-9d44-337c06d4950b.png)
> -- Racontez
> ++ Raconter

et peut être au passage reformuler un peu la phrase, le "de vous et de votre pet" est un peu répétitif

**Comment by romain22222** [comment]
> > ![Capture d’écran de 2021-06-01 18-52-06](https://user-images.githubusercontent.com/71654580/120361759-8990f580-c30a-11eb-9d44-337c06d4950b.png)
> > -- Racontez
> > ++ Raconter
> 
> et peut être au passage reformuler un peu la phrase, le "de vous et de votre pet" est un peu répétitif

Raconter vos aventures auprès de **{pet}** ...

**Comment by Nininanou16** [comment]
![Capture d’écran de 2021-06-02 00-03-31](https://user-images.githubusercontent.com/71654580/120395856-fc639600-c335-11eb-868b-fd95496e2363.png)
 ' en trop

**Comment by Nininanou16** [comment]
![Capture d’écran de 2021-06-02 00-07-22](https://user-images.githubusercontent.com/71654580/120396244-857acd00-c336-11eb-8020-80dd99d069b9.png)
-- paysan qui as
++ ce paysan qui a

**Comment by Nininanou16** [comment]
![Capture d’écran de 2021-06-02 01-17-43](https://user-images.githubusercontent.com/71654580/120401501-59644980-c340-11eb-9747-666b41f3a6fa.png)
vous decidez de vous adosse**r**

**Comment by Nininanou16** [comment]
![Capture d’écran de 2021-06-02 01-23-41](https://user-images.githubusercontent.com/71654580/120401876-2ec6c080-c341-11eb-98d8-cb9d26a2c62e.png)
vous les mange**z**

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/120468080-21d9b980-c3a1-11eb-8113-835e6085448d.png)
 a fix asap
