### ISSUE TITLE
refonte commande test

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#417]
réécrire la commande test, afin qu'elle soit plus familière à utiliser, et à virer les commandes inutiles (coucou myids et les 3 alias de forcereport et fpl)

**Comment by romain22222** [comment]
#356 lien

**Comment by quenquentin** [comment]
=> !test help qui permet d'afficher toutes les commandes test et leur fonctionnalité
=> Check pour empêcher les gives d'items qui n'existent pas
