### ISSUE TITLE
bug commande daily

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#421]
![image](https://user-images.githubusercontent.com/38099970/120526064-17d3ad00-c3d9-11eb-9280-c29383e121c7.png)

**Comment by quenquentin** [comment]
New bug daily https://ptb.discord.com/channels/429765017332613120/448055928105861120/852492243561873438

**Comment by BastLast** [comment]
c'est fixé ou pas du coup ?

**Comment by BastLast** [comment]
@quenquentin  ?

**Comment by quenquentin** [comment]
Il a été fix il me semble, je ne sais plus par qui, @romain22222 il me semble ? Mais c'était fix dans un de ces commits avant la création de l'issue je crois
