### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#422]
issue pour lister les typos à fix. Merci d'indiquer quand une typo est fix

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/120535168-f4156480-c3e2-11eb-859b-73d4f5833e00.png)

- [ ]

**Comment by athorii** [comment]
![IMG_20210602_203731](https://user-images.githubusercontent.com/72823390/120535415-3ccd1d80-c3e3-11eb-97c7-bc73d18fe334.jpg)
Il manque un "t" à butte.

**Comment by Mekodix** [comment]
![image](https://user-images.githubusercontent.com/42207707/120654784-4a85b000-c482-11eb-85b0-c0cbc4b7d3ac.png)
Erreur à "reconnais" -> "reconnaît"

**Comment by quenquentin** [comment]
https://media.discordapp.net/attachments/448055928105861120/850689591245275157/fb.png
L'une des ressources les plus importantes du jeu*

- [ ] Fix

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/120900003-d76f6b80-c632-11eb-873d-9fe3df056658.png)
Petite erreur de typo: douleureux au lieu de douloureux

- [ ]  Fix

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/120900049-22897e80-c633-11eb-886d-8dcb7ca4950e.png)
si vous voulez voir le profil (pas de "e")

- [ ] Fix

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/120900085-4947b500-c633-11eb-81ff-bca7751dfec3.png)
vous l'empruntez*

- [ ] Fix

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/120900133-785e2680-c633-11eb-99dc-5a914b26e69e.png)
destinations* avec un s

- [ ] Fix

**Comment by quenquentin** [comment]
---------------------------------------------
Les premières typo ont toutes été corrigées

**Comment by quenquentin** [comment]
![Uploading image.png…]()

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/120919315-32e43c80-c6b9-11eb-8807-a9d7fc4ec57c.png)

**Comment by Nininanou16** [comment]
![image0](https://user-images.githubusercontent.com/71654580/120922637-9aef4e80-c6ca-11eb-9663-32cf54c83c3a.jpg)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/120922722-089b7a80-c6cb-11eb-95a9-0a8e5ffdce48.png)
décider -> décidez 
est -> soit

**Comment by Mekodix** [comment]
![image](https://user-images.githubusercontent.com/42207707/120928595-8a000680-c6e5-11eb-8abd-82f537ca7d15.png)
reviens -> revient

**Comment by Chevalier2** [comment]
https://discord.com/channels/429765017332613120/448055928105861120/850250229362327552
![fj](https://user-images.githubusercontent.com/72626953/121001828-f8979f80-c78b-11eb-8385-411dcf0dec12.png)
Vieil homme*

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/121003240-9b045280-c78d-11eb-9521-e67893360abf.png)

vous croiser (avec un R)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/121414461-f178b900-c966-11eb-9ee4-9b2adf4f10fe.png)

 Erreur typo, "vous décider" au lieu de "vous décidez". De plus, il serait plus juste de modifier "il semblerait que seule la salle des armures est encore intacte" par "il semblerait que seule la salle des armures soit encore intacte".

**Comment by Nininanou16** [comment]
![image](https://user-images.githubusercontent.com/71654580/121416310-f50d3f80-c968-11eb-8791-4885aac35e06.png)
Erreur typo, "vous décider" au lieu de "vous décidez". De plus, il serait plus juste de modifier "il semblerait que seule la salle des armures est encore intacte" par "il semblerait que seule la salle des armures soit encore intacte".

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/121432640-39a1d680-c97b-11eb-88e4-42f56c30fa18.png)
à reformuler

**Comment by quenquentin** [comment]
À review https://discord.com/channels/429765017332613120/448055928105861120/852461600714784818
(La fonction d'attachement de photo sur tel est broken)

**Comment by quenquentin** [comment]
-----------------------------------
Typo corrigées
https://discord.com/channels/429765017332613120/448055928105861120/852461600714784818 sauf celle-ci

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/122350616-a7d33400-cf4d-11eb-9e3b-24d74235b924.png)
faute de typo sur cet event derniere ligne le "O" majuscule dans "VOus"

**Comment by quenquentin** [comment]
Je pense que c'est mieux de dire "mélangé" que "mixé", c'est déjà liquide de l'alcool tout comme des extraits de plantes, puis ça fait un peu mixeur alors qu'on est dans un univers médiéval
![image](https://user-images.githubusercontent.com/56274541/122350781-cf2a0100-cf4d-11eb-88e9-8fbe38a623d0.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/122350848-de10b380-cf4d-11eb-89e2-fb2dbdecadb3.png)
"joueur" au lieu de joueuse

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/122351035-0a2c3480-cf4e-11eb-9dfc-86cf3a09c2e1.png)
"sa armure"

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/122351757-c0901980-cf4e-11eb-9aee-098f1e089e6a.png)
trop de répétition au début

**Comment by quenquentin** [comment]
"comme si de rien était"
![image](https://user-images.githubusercontent.com/56274541/122351836-d43b8000-cf4e-11eb-8225-7bfc19695395.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/122351978-f8975c80-cf4e-11eb-9500-d9853ef590ee.png)
Double espace

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/122352226-35fbea00-cf4f-11eb-87f6-e0062e9a74eb.png)
Petit soucis dans les <>

**Comment by Nininanou16** [comment]
![image](https://user-images.githubusercontent.com/71654580/122749172-4f719e80-d28d-11eb-92a1-bd2b85da9904.jpeg)

Dans quel sens vous l'emprunt**ez**

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/122826260-38f63200-d2e3-11eb-837e-014110d06d96.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/122826467-79ee4680-d2e3-11eb-8d29-eb0e57e0806e.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/122826509-85da0880-d2e3-11eb-914a-59721b60a327.png)
![image](https://user-images.githubusercontent.com/56274541/122826531-8ecada00-d2e3-11eb-930e-6221bc8652ad.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/123125500-da4ac880-d448-11eb-8b65-516309212261.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/123135096-b770e200-d451-11eb-816d-41a5617f610d.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/123478697-12e0d280-d600-11eb-9342-3698ff48d5c1.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/123856868-e390d500-d921-11eb-9bc1-f90d92ee514e.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/123857005-0de29280-d922-11eb-9a1d-d7307b2c6059.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/123857039-1b981800-d922-11eb-8f0e-823ea97f0aa7.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/124366763-5cf63380-dc52-11eb-9e40-cb9b60b2c22b.png)
Pas de perte de vie
-
![image](https://user-images.githubusercontent.com/56274541/124366783-83b46a00-dc52-11eb-86b7-ba56000df24f.png)
"Egalement" en trop
-
![image](https://user-images.githubusercontent.com/56274541/124366799-9890fd80-dc52-11eb-980a-36606a1f3eab.png)
"tout" -> "tous"
-
![image](https://user-images.githubusercontent.com/56274541/124366809-acd4fa80-dc52-11eb-96fa-0901a43b4653.png)
Il manque un circonflexe 5 ème ligne à "chateau"
-
![image](https://user-images.githubusercontent.com/56274541/124366817-bcecda00-dc52-11eb-9f37-7e2e36f1ec83.png)
"aucun nouvel familier"
-
![image](https://user-images.githubusercontent.com/56274541/124366834-edcd0f00-dc52-11eb-80d1-eb252337333f.png)
"d'avantage" -> "davantage"
-
![image](https://user-images.githubusercontent.com/56274541/124366846-0b01dd80-dc53-11eb-8175-51aec6538f68.png)
"la buffet"

**Comment by quenquentin** [comment]
@romain22222 / @eagles666  / @BastLast  je vous laisse voir pour les 3 typos plus "compliquées" comment vous voulez gérer ça. Et pour l'advice faux, soit le revoir soit le delete.

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554043-a4c7e826-a61c-487e-8ab9-e69bbf244447.png)
"paladin*"

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554126-84d1c9c3-fc9f-4450-b1cc-58f894f1a8f4.png)
"un église"

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554323-9d142b21-ab3a-4596-9495-fbc29d24aaee.png)
manque de maj + typo

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554413-ee1fbea7-313d-49a6-854c-43a17190b6b1.png)
On met 2h ou 30min dcp ? poke @BastLast

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554538-d83c2c68-fc11-400d-bfc9-377827708827.png)
"récupéréEs"

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554603-d0456d3d-519f-4365-aba2-52b8a1b0c3b1.png)
fouRchettecouteau

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554715-8b8690c7-ab45-4f68-8439-26feaeb0d58e.png)
lui ?

**Comment by BastLast** [comment]
> ![image](https://user-images.githubusercontent.com/56274541/126554413-ee1fbea7-313d-49a6-854c-43a17190b6b1.png)
> On met 2h ou 30min dcp ? poke @BastLast

Je propose "vous reprendrez l'aventure immédiatement"

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554787-c3cc00d3-36b0-4856-b90e-64891b2226bf.png)
Incohérence (on part seul mais finalement il y'a la demoiselle)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554914-cb96f1ee-5d85-4221-8ccd-76dcedab897b.png)
"retrouvez"

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126554970-e9316ba6-7f78-42a2-b47e-90be9ced50bb.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126555125-44e66a38-e2d2-4327-8c44-9a174da22c79.png)
C'est mentionné nul part qu'on le paye.
Et c'est à côté.

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/126555248-7d33ed93-5ea7-4d8d-8955-0688cd72fcd5.png)
Unification des emotes, bonne idée

**Comment by romain22222** [comment]
> ![image](https://user-images.githubusercontent.com/56274541/126555248-7d33ed93-5ea7-4d8d-8955-0688cd72fcd5.png)
> Unification des emotes, bonne idée

En réalité c est juste eagle qui dit nawak sur celui la, le 1er est un gain et l'autre une perte

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/127486815-676cdbeb-0b9a-4eec-9a5f-95e924ee9f5d.png)
(event barman i3)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/127486902-facf7368-51f8-4f83-84dd-3ed02dfcb6e9.png)
(message help badges)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/127486970-4dc1ed7f-0032-4d9a-810b-516ccbe5f690.png)

**Comment by quenquentin** [comment]
help petfeed 10k => 50k

**Comment by BastLast** [comment]
> help petfeed 10k => 50k

Faudra aller édit le code pour aller lire la constante pour ca (facile à faire :)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/128238392-def9edf1-8edd-469d-a709-146193d6ed78.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/128238502-9b5b957c-bde0-4c61-bee6-c3a8fd854e35.png)

**Comment by quenquentin** [comment]
to wax them for you for a few coins. You end up the night in jail and compensate those peoples. 

Fortunately, a young beggar standing right next to you offers you to wax them for a few coins. 

The list of badges is available on the bot guide. à rajouter en trad ENG
