### ISSUE TITLE
Un pet fielleux peut etre bougé

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#423]

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/120538376-b7e40300-c3e6-11eb-8189-101a20fd23d3.png)
![image](https://user-images.githubusercontent.com/56274541/120538413-c29e9800-c3e6-11eb-8063-37b7e16712cc.png)

**Comment by niqore** [comment]
Fixed in 660814d7f417eece84355d2dbf2f0d3fe36e5696

**Comment by BastLast** [comment]
juste par curiosité c'était quoi le soucis @niqore  ?
