### ISSUE TITLE
Améliorer le readme

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#424]
Pourquoi ces badges sont cassés ?

![image](https://user-images.githubusercontent.com/38099970/120558227-74e25980-c3ff-11eb-9726-76907b710f25.png)

**Comment by romain22222** [comment]
![image](https://user-images.githubusercontent.com/29299679/122559522-bd288b00-d03f-11eb-96c6-a056858fde82.png)
fixed now !

**Comment by BastLast** [comment]
wait ca s'est vraiment réparé tout seul ?

**Comment by romain22222** [comment]
> wait ca s'est vraiment réparé tout seul ?

tu vois un commit related ?

**Comment by BastLast** [comment]
bon bah on va juste delete l'issue then aucun interet de garder ca
