### ISSUE TITLE
Emojis commande top

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#425]
- [x] Afficher l'émoji du type de lieu dans lequel le joueur se trouve si il est à destination
- [x] Debug les pastilles ou leur trouver une nouvelle utilité

**Comment by romain22222** [comment]
plutot ne rien mettre quand SE ?

**Comment by BastLast** [comment]
oui juste modifier le journal

**Comment by BastLast** [comment]
je décale en 2.2.2

**Comment by BastLast** [comment]
issue d'origine mise à jour

**Comment by niqore** [comment]
Soit on remet les pastilles noires pour les gens pas sur le serveur, soit on change l'utilité des pastilles

**Comment by quenquentin** [comment]
Personnellement je trouve les pastilles assez useless, à voir si des gens y voient vraiment une utilité mais je serai pour la suppression complète de ce système et ajouter les lieux comme déjà dit dans l'issue

**Comment by niqore** [comment]
Je pensais un peu la même chose
