### ISSUE TITLE
Vente de potion

### ISSUE THREAD

**Issue by quenquentin** [DraftBot-A-Discord-Adventure/DraftBot#431]
- [ ] Il est possible de "vendre" sa potion si on l'a déjà dans son inventaire, le jeu te dis que tu as la même potion et te la sell auto
- [ ] fix mini shop
CF : 
![image](https://user-images.githubusercontent.com/56274541/120899781-b9edd200-c631-11eb-8f20-caabe6b1bc94.png)

**Comment by BastLast** [comment]
la vente d'un objet identique à celui dans l'inventaire n'est également pas concernée par la réduction du prix dans le mini event "mini shop"
