### ISSUE TITLE
Afficher l'interface de voyage quand le joueur est sous altération d'état

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#433]

**Comment by eagles666** [comment]
L'interface de voyage, c'est la map ?

**Comment by BastLast** [comment]
a faire après que #436 soit fait à mon avis ca sera plus simple non ?

**Comment by eagles666** [comment]
Je penses pas. Il suffirait de modifier les lignes 26 à 33 pour remplacer la méthode effectsErrorMe par la méthode sendTravelPath().

**Comment by eagles666** [comment]
> 
> 
> Je penses pas. Il suffirait de modifier les lignes 26 à 33 pour remplacer la méthode effectsErrorMe() par la méthode sendTravelPath().

Voir juste supprimer les lignes 26 à 33.

**Comment by BastLast** [comment]
> Je penses pas. Il suffirait de modifier les lignes 26 à 33 pour remplacer la méthode effectsErrorMe() par la méthode sendTravelPath().

nan fix cette issue n'est clairement pas aussi simple vraiment
