### ISSUE TITLE
Ajout d'évents

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#434]
Ajout de quelques évents dans le bot

**Comment by Hitsukiyo** [comment]
Le #59, le #58 mais je sais pas si tu l'as édit, le #55, la #48, le #52, le #54.

**Comment by Chevalier2** [comment]
" Village du tyran " : event vérifié, traductions terminées normalement, pour terminer le json il ne manque que les textes EN. Event #8 : https://github.com/DraftBot-A-Discord-Adventure/Events/issues/8 et https://github.com/DraftBot-A-Discord-Adventure/Events/blob/main/markdown/fr/8.md 

" La grotte souterraine " : event fini normalement, il faut juste que tu le vérifies, mais les changements que tu avais demandés ont été faits. Après il faudra faire la traduction et le json. Event #15 : https://github.com/DraftBot-A-Discord-Adventure/Events/issues/15 et https://github.com/DraftBot-A-Discord-Adventure/Events/blob/main/markdown/fr/15.md

" La tribu " : event presque fini, il faut seulement faire quelques petits changements et ce sera bon. Lire le message de BastLast sur l'issue pour plus d'informations. Event #16 https://github.com/DraftBot-A-Discord-Adventure/Events/issues/16 et https://github.com/DraftBot-A-Discord-Adventure/Events/blob/main/markdown/fr/16.md

" Le sage " : event en attendre de Drapht ( BastLast ), ne sera probablement pas vérifié tout de suite étant donné que c'est un event lié.

" La course de chiens " : d'après les labels, il est en attente de Drapht. N'ayant rien à voir avec cet event, je n'en connais pas l'avancement. Event #20 : https://github.com/DraftBot-A-Discord-Adventure/Events/issues/20 https://github.com/DraftBot-A-Discord-Adventure/Events/blob/main/markdown/fr/20.md

" Château chasse au trésor " ( #22 ) et " brigand-forêt " ( #23 ) sont apparemment presque finis. Events : https://github.com/DraftBot-A-Discord-Adventure/Events/issues/22 et https://github.com/DraftBot-A-Discord-Adventure/Events/issues/23

" Marchand de vivres " : Nécessite vérification de Drapht. Event #28 : https://github.com/DraftBot-A-Discord-Adventure/Events/issues/28 et https://github.com/DraftBot-A-Discord-Adventure/Events/blob/main/markdown/fr/28.md

" La tour et le gardien " : Vérifié par Drapht et normalement entièrement traduit, je ne sais pas où en est le json, chose sûre il n'y a pas les traductions EN. Event #30 : https://github.com/DraftBot-A-Discord-Adventure/Events/issues/30 et https://github.com/DraftBot-A-Discord-Adventure/Events/blob/main/markdown/fr/30.md

" Face à face " : nécessite vérification de Drapht. Il est je pense correct. Event #31 : https://github.com/DraftBot-A-Discord-Adventure/Events/issues/31 et https://github.com/DraftBot-A-Discord-Adventure/Events/blob/main/markdown/fr/31.md

" Jeux avec des enfants " ( #38 ) est d'après ce que je vois en attente de Drapht. 
https://github.com/DraftBot-A-Discord-Adventure/Events/issues/38 et https://github.com/DraftBot-A-Discord-Adventure/Events/blob/main/markdown/fr/38.md

" Passage en ville bloqué par des gardes " ( #39 ) et " Chasse à prime " ( #40 ) ont pour label presque fini, je présume donc qu'ils le sont. 
https://github.com/DraftBot-A-Discord-Adventure/Events/issues/39 et https://github.com/DraftBot-A-Discord-Adventure/Events/issues/40

" Histoires au feu de camp " ( #44 ) : fini je pense. Pas encore de vérifications de Drapht sur cet event. J'ai remarqué que l'event était en double... ( #43 )
https://github.com/DraftBot-A-Discord-Adventure/Events/issues/44 et https://github.com/DraftBot-A-Discord-Adventure/Events/blob/main/markdown/fr/44.md

Les event #49, #50 et #52 sont en attente de Drapht. 
https://github.com/DraftBot-A-Discord-Adventure/Events/issues/49 https://github.com/DraftBot-A-Discord-Adventure/Events/issues/50 et https://github.com/DraftBot-A-Discord-Adventure/Events/issues/52

" Event au village coco " ( #61 ) est normalement apte à être vérifié par Drapht. 

Classer les events dans l'ordre selon leurs catégories ( de ceux presque terminés à ceux qui le sont ou inversement ) aurait été mieux, je n'ai malheureusement pas le temps de le faire maintenant.
