### ISSUE TITLE
Rendre la durée d'un voyage variable

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#436]
- [x] La durée d'un voyage sera une valeur déterminée entre 1 et 12 h.
- [x] Suppression de l'affichage des mini évent de l'affichage du trajet
- [x] Affichage du temps avant le prochain mini évent
- [x] Réduction du temps avant un mini évent à 10 minutes
- [x] Les récompenses des mini event sont degressives (et décroissent plus vite sur les trajets plus courts)

**Comment by eagles666** [comment]
Je maintient le fait que ta proposition est bancale.

Sur un voyage de 12 heures, on obtient une moyenne de 144 mini événements. Or, si tu maintient le cap des récompenses à 150 points au prochain gros événement (C'est pas très clair tes explications pour le coup ?!), ça donne 141 mini événements qui ne serviront à "rien", si ce n'est que se prendre une altération, perdre de la vie ou de l'argent ... 

Il serait judicieux de revoir cette partie la afin de ne pas juste tomber dans le "avoir des événements pour avoir des événements" et faire le tour des événements en un voyage quoi, parce que même si le contenu des événements est légèrement différent, leur forme est la même, donc proposer un événement tous les 5 minutes, c'est réduire considérablement le temps qu'il faudrait à un nouveau joueur pour découvrir le jeu, le travail de rédaction ne pourra jamais suivre la cadence pour rajouter du contenu nouveau pour toujours maintenir le niveau d’intéressement des joueurs

Le but principal de la refonte des rapports n'était-il pas de contrer le problème de redondance dans le gameplay ? en appliquant tes idées, on semble retourner à la case départ. 

Personnellement, je propose un bonus de 0.25% au nombre de points gagné au prochain rapport par mini évènement réalisé, bonus qui fonctionnerait selon la manière suivante :
si un joueur fait tous les mini événements sur un voyage de 12h (144 événements) et qu'il gagne 1055 points, il cumulera un bonus de 36% (le maximum atteignable avec ma proposition) et en plus de ses points de base, il gagnera 36% de cette somme en plus, ce qu'il lui fera un total de 1434 points 

Ce système à l'avantage de ne pénaliser personne, car il offre un bonus proportionnel à l'investissement du joueur, et il est normal que un joueur qui fasse plus de mini événements gagne plus, de même pour une personne qui aurait un voyage de 12 heures.

Mon autre proposition serait de mettre 15 minutes à la place de de 5 minutes, ce qui pourrait, pour un voyage de 12 heures, donner un maximum de 48 mini événements au lieu de 144, ce qui reste convenable je penses

**Comment by BastLast** [comment]
> Je maintient le fait que ta proposition est bancale.

Merci pour l'attaque ca fait plaisir, au moins c'est clair.

> Sur un voyage de 12 heures, on obtient une moyenne de 144 mini événements. Or, si tu maintient le cap des récompenses à 150 points au prochain gros événement (C'est pas très clair tes explications pour le coup ?!), 

tu as compris correctement


> ça donne 141 mini événements qui ne serviront à "rien", si ce n'est que se prendre une altération, perdre de la vie ou de l'argent ...

non ya aussi des mini event positifs, et il y en a une plus grande proportion que les évents négatifs. Aussi je suis de l'avis qu'un mini event de "texte" ne sert pas à rien

> Il serait judicieux de revoir cette partie la afin de ne pas juste tomber dans le "avoir des événements pour avoir des événements" et faire le tour des événements en un voyage quoi, parce que même si le contenu des événements est légèrement différent, leur forme est la même, donc proposer un événement tous les 5 minutes, c'est réduire considérablement le temps qu'il faudrait à un nouveau joueur pour découvrir le jeu, le travail de rédaction ne pourra jamais suivre la cadence pour rajouter du contenu nouveau pour toujours maintenir le niveau d’intéressement des joueurs

Fair point pour la cadence de rédaction, c'est pourquoi le but n'est pas que les joueurs spamment les mini event, clairement le système que je propose est organisé pour ne pas encourager le joueur à spam les mini events, ce n'est pas le but, personne ne fera cela.

Je m'explique :

- Comme tu as une proportion de mini events négatifs tu as un "risque potentiel" (la présence de petites altérations de 10 / 15 /30 min pourra être augmentée pour forcer une pause aux spammeurs éventuels)
- il y a 5 minutes à attendre entre chaque mini event (ca peut paraitre peu mais c'est quand meme long d'attendre 5 minutes juste comme ca)
- une grande majorité des mini events seront "textuels" (aka une fois passé la période ou un mini event donne 50 points, deviennent useless) donc tu as perdu 5 min de ta vie pr rien

Bref la somme de tout ca fait que une fois la période des 3 mini events qui te rapporte quelque chose, tu vas faire très peu de mini event ou du moins tu ne va pas les spam à la chaine juste tu vas en faire 4 /  5 quand tu passe dans le channel de manière random pendant toin voyage de 12 h

Je pense que c'est mieux de tomber sur un mini event avec une petite phrase sympa plutot que juste un truc qui te dis que tu arrive dans 12 h

Enfin un mini event peut paraitre comme ayant la meme forme mais les mini events sont ultra libre vu qu'on peut mettre du code dedans on peut imaginer des trucs assez innovants et perso j'ai pleins d'idées qui permettront de diversifier le paysage et j'ai peur que si on ne met pas en avant ces mini event bcp de gens vont juste passer à coté


> Le but principal de la refonte des rapports n'était-il pas de contrer le problème de redondance dans le gameplay ? en appliquant tes idées, on semble retourner à la case départ.

L'un des soucis de cette maj est que la plupart des gens viens de temps en temps sur discord mais laisse plus de 2 h entre 2 commande rapport et du coup ne tompbe pas sur les mini event actuellement et font juste des gros event en boucle. 

la solution à ce probleme est d'allonger le temps de trajet pour que plus de gens tombe sur les mini event

Mais du coup il faut que les gens qui viennet souvent aient un truc à faire.

le but c'est que draftbot s'adapte plus à la facon de jouer de chacun en bref

 
> Personnellement, je propose un bonus de 0.25% au nombre de points gagné au prochain rapport par mini évènement réalisé, bonus qui fonctionnerait selon la manière suivante :

> si un joueur fait tous les mini événements sur un voyage de 12h (144 événements) et qu'il gagne 1055 points, il cumulera un bonus de 36% (le maximum atteignable avec ma proposition) et en plus de ses points de base, il gagnera 36% de cette somme en plus, ce qu'il lui fera un total de 1434 points
> 
> Ce système à l'avantage de ne pénaliser personne, car il offre un bonus proportionnel à l'investissement du joueur, et il est normal que un joueur qui fasse plus de mini événements gagne plus, de même pour une personne qui aurait un voyage de 12 heures.
> 
> Mon autre proposition serait de mettre 15 minutes à la place de de 5 minutes, ce qui pourrait, pour un voyage de 12 heures, donner un maximum de 48 mini événements au lieu de 144, ce qui reste convenable je penses

J'étudierai ta proposition avec plus d'attention mais pour le moment, les retours que j'ai à faire sont les suivants :
- un voyage de 12h sera super rare (plus souvent 4 à 8 h me semble un bon délais avec quelques trajets plus courts et quelques plus longs

**Comment by niqore** [comment]
Le problème avec ceci selon moi est le deséquilibre entre les joueurs : les trajets longs sont plus un malus qu'autre chose. Si le nombre de points est limité à 150, un trajet de 12h sera bien moins rentable que 12 trajets de 1h, ça donne une différence de points de 1650, sans parler que c'est très rare des mini events avec des gains d'argent, d'xp etc... Vu que c'est adapté à la façon de jouer de chacun, perso je ne joue que pour l'xp. Or imaginons que je me tape des trajets de 12h avec un gros évent que je réussis pas très bien, j'aurais par exemple 25 xp / 12h j'aurais plus envie de jouer. On peut appliquer la même chose à l'argent, la vie etc...

**Comment by BastLast** [comment]
Sauf que c'est pas possible de faire que des trajets de 12 h ou que des trajets de 1h

**Comment by BastLast** [comment]
aussi le commentaire en haut n'est pas à jour :sweat:

**Comment by BastLast** [comment]
j'ai mis à jour
