### ISSUE TITLE
Ajout d'un mini event donnant des infos sur l'aventure

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#437]
Genre le joueur recoit une lettre du roi ou encore il voit une affiche officielle du roi à propos de la competition.
Les infos pourraient être :
- le nombre de joueurs en lice,
- le nombre depoints moyen des joueurs
- la quantité moyenne que les joueurs ont en poche
- la quantité d'argent que le joueur le plus riche a en poche
- le nombre de familiers dressés...

Exemple :

:scroll: Alors que vous voyagez tranquillement, vous recevez une missive du roi. Ce dernier vous écrit à propos de la compétition pour la main de la princesse à laquelle vous participez. Vous découvrez à la lecture de la lettre que d'après un comptage des points effectué récemment par les organisateur, les candidats ont en moyenne un score de 12 785 points actuellement. Grandement motivé par cette nouvelle, vous reprenez votre route.

**Comment by romain22222** [comment]
Quelqu'un va devoir prendre le relais pour placer les traductions dans le json, et faire les tests, je n'aurai pas accès à mon PC pendant 15 jours
