### ISSUE TITLE
Change direction without event

### ISSUE THREAD

**Issue by quenquentin** [DraftBot-A-Discord-Adventure/DraftBot#451]
https://media.discordapp.net/attachments/771370060848824350/851570993344675860/Capture_decran_de_2021-06-07_23-18-44.png?width=300&height=676
Possibilité de changer de direction sans avoir d'évent

**Comment by BastLast** [comment]
toujours plus flou les images

**Comment by quenquentin** [comment]
Pas de ma faute si tu peux pas zoom ¯\_(ツ)_/¯

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/121090493-f7e12680-c7e8-11eb-9002-1a97ea6c16d6.png)

**Comment by BastLast** [comment]
T'ES PAS NET

**Comment by BastLast** [comment]
est-ce que quelqu'un a des infos au sujet de ce bug ?

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/123387092-af22bf00-d597-11eb-9506-38c24d79979e.png)
![image](https://user-images.githubusercontent.com/56274541/123387125-ba75ea80-d597-11eb-9948-95cae3deae86.png)
Pas la première fois, c'est sûrement le même problème dans tout les cas

**Comment by quenquentin** [comment]
https://discord.com/channels/429765017332613120/826176541620830298/859505641851977830
https://discord.com/channels/429765017332613120/826176541620830298/859511603900317726

Le joueur à un rapport normal, choisi sa destination ... au rapport suivant il est transporté directement sur une nouvelle destination

**Comment by quenquentin** [comment]
+ TP à la destination sans les 2h d'attente avant le problème

**Comment by BastLast** [comment]
![image](https://user-images.githubusercontent.com/38099970/124100338-b0079500-da5e-11eb-8620-00ff8eba91a9.png)
@romain22222  a trouvé le soucis !

**Comment by romain22222** [comment]
fixed
