### ISSUE TITLE
refact command petfeed

### ISSUE THREAD

**Issue by eagles666** [DraftBot-A-Discord-Adventure/DraftBot#473]
je suis un boulet :/

**Comment by eagles666** [comment]
ce qui se passe c'est que tout le code correspond à ma version que j'avait coder avant que draft demande de rajouter une partie pour les gens qui ont pas de guilde... j'ai rajouter cette partie par dessus, mais du coup y'as rien qui vas

**Comment by BastLast** [comment]
@eagles666  possible d'avoir des indications sur quoi faire ici parce que j'avoue que j'ai pas compris mdr

**Comment by eagles666** [comment]
* ligne 1 : retirer cette ligne
* certains commentaires sont en français
* ajouter 
```js
pet.lovePoints += JsonReader.food.commonFood.effect;
```
à la ligne 157
* la partie qui concerne les gens qui n'ont pas de guilde est directement dans la commande
* certaines parties pourraient être simplifiées
