### ISSUE TITLE
tp au premier rapport après un event

### ISSUE THREAD

**Issue by eagles666** [DraftBot-A-Discord-Adventure/DraftBot#476]
https://discord.com/channels/429765017332613120/826176541620830298/859505641851977830
https://discord.com/channels/429765017332613120/826176541620830298/859511603900317726

Le joueur à un rapport normal, choisi sa destination ... au rapport suivant il est transporté directement sur une nouvelle destination

**Comment by Chevalier2** [comment]
J'ai été tp à ma destination et en ai obtenu une nouvelle en fait ( j'ai été tp à Boug-Coton qui était ma destination, et je me suis dirigé vers la Vallée des Rois ).
