### ISSUE TITLE
commandes non bloquées

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#507]
- [x] daily
- [x] petfree
- [x] guilddaily
- [x] petfeed

https://cdn.discordapp.com/attachments/448055928105861120/867369686310846464/unknown.png

**Comment by eagles666** [comment]
la commande guilddaily non plus

**Comment by eagles666** [comment]
```js
if (await sendBlockedError(message.author, message.channel, language)) {
		return;
	}
```
il me semble qu'il manque ses lignes

**Comment by BastLast** [comment]
@romain22222  tu le fais ca ?
