### ISSUE TITLE
Review meta d'xp

### ISSUE THREAD

**Issue by QQtin3** [DraftBot-A-Discord-Adventure/DraftBot#510]
Issue ultra importante de la mort qui tue si c'est close on ban instant.

**Comment by quenquentin** [comment]
+ xp guilde

**Comment by BastLast** [comment]
ya des chances que ça soit repoussé pour la maj ou on fait les missions (càd la prochaine)

**Comment by BastLast** [comment]
@quenquentin dispo pour vocal ?

**Comment by BastLast** [comment]
bon c'est clairement pas une priorité maintenant et personne n'est motivé pour le faire donc je close ceci en wontfix
