### ISSUE TITLE
Ajout de nouveaux évents

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#530]

**Comment by Chevalier2** [comment]
Les events en attente de validation finale sont : 
Events avec le label " urgent " : 96, 100, 101 et 102.
L'event 120.

Les events 65, 97 et 99 ont déjà été validé.

**Comment by Chevalier2** [comment]
_Les events 97 et 99 n'étaient pas sur Crowdin, je viens de les ajouter._
