### ISSUE TITLE
Mettre à jour / Ajouter des conseils

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#532]

**Comment by Thesmokingllama** [comment]
C'est plus d'actualité, maintenant c'est à chaque altération d'état
![image](https://user-images.githubusercontent.com/80409766/132128903-771d6c32-4777-4ae0-b268-c53159c79d9f.png)

**Comment by Thesmokingllama** [comment]
C'est faux. Cette commande nous permet de vendre un familier, pas d'en acheter un
![image](https://user-images.githubusercontent.com/80409766/132128919-34729e3e-e7c6-471f-bb81-8a70c220d2b0.png)

**Comment by Thesmokingllama** [comment]
Plus forcément vrai
![image](https://user-images.githubusercontent.com/80409766/132128929-3b7f01b5-e40e-4622-b4a7-49bb219b4db7.png)

**Comment by Thesmokingllama** [comment]
*s'ils
![image](https://user-images.githubusercontent.com/80409766/132128943-9e8d91f6-b2a5-4019-8179-ec5ba1859601.png)

**Comment by Thesmokingllama** [comment]
Faux
![image](https://user-images.githubusercontent.com/80409766/132128958-27cb88ac-9f7b-4962-82a1-c55e8ac71a9e.png)

**Comment by Thesmokingllama** [comment]
Faux et preuve : 
![image](https://user-images.githubusercontent.com/80409766/132128994-76152dcb-af8e-4194-9ea7-fedca1d6682b.png)
![image](https://user-images.githubusercontent.com/80409766/132129002-6936afb8-5276-48c3-89cc-895fdb55de17.png)

**Comment by Thesmokingllama** [comment]
Remplacer $ par 💰
![image](https://user-images.githubusercontent.com/80409766/132129180-5fd6c383-94dd-4667-83f5-780e22482493.png)

**Comment by Thesmokingllama** [comment]
Conseil faux
![image](https://user-images.githubusercontent.com/80409766/132129191-f2f2b4c2-132f-4836-8634-a474a40e8bf4.png)
![image](https://user-images.githubusercontent.com/80409766/132129196-baaaff31-5ac1-482e-92e5-8150a79266bd.png)

**Comment by Chevalier2** [comment]
Objets pas items.
![objets](https://user-images.githubusercontent.com/72626953/132681772-ff16f17d-c6d3-4c63-aad2-810e3fac860f.png)

**Comment by Chevalier2** [comment]
![g top faux](https://user-images.githubusercontent.com/72626953/132682487-e5a07bd4-0338-437d-8912-4b47e3082ea2.png)

**Comment by Chevalier2** [comment]
Retirer le s de potions.
![potion](https://user-images.githubusercontent.com/72626953/132686510-1c0106ab-f3a3-4eac-bda9-b11ec74cd915.png)

**Comment by Chevalier2** [comment]
Manque " vous ".
![vous](https://user-images.githubusercontent.com/72626953/132687445-ca2046ba-fb80-4c80-ad95-8492d26aa5e2.jpg)

**Comment by niqore** [comment]
> 
> 
> Manque " vous ". ![vous](https://user-images.githubusercontent.com/72626953/132687445-ca2046ba-fb80-4c80-ad95-8492d26aa5e2.jpg)

Mauvaise issue du coup

**Comment by niqore** [comment]
Le commit 7e925d9097977fa9606de5ea7e695b246b522c56 prend en compte tous les commentaires ci-dessus
