### ISSUE TITLE
remettre le remplacement des émotes customs par un emote par défaut si ils sont pas dispo

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#533]

**Comment by niqore** [comment]
Il faut modifier DraftBotReaction en ajoutant un paramètre optionnel (fallbackEmote par exemple) contenant un emote à utiliser si jamais celui demandé n'existe pas. Ensuite il faut modifier le DraftBotReactionEmbed pour check et utiliser l'emote principal ou le remplacement

**Comment by niqore** [comment]
+ possibilité de mettre une réaction cachée

**Comment by niqore** [comment]
Je déplace en X.X.X, ça presse pas

**Comment by Pietagorh** [comment]
@niqore j'peux m'en occuper ? J'pense que cette fois-ci j'réussirai x)
