### ISSUE TITLE
Mini event loterie 

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#536]
Le joueur rencontre un mec qui propose une sorte de loterie.

Le joueur peut choisir entre 3 choix randoms

Le premier choix est une "petite récompense"

Le second, une "récompense moyenne"

Le dernier une "grosse récompense"

Pr chaque récompense le theme est random
(gain xp, gain money...) et le montant aussi

Plus le joueur choisi une grosse récompense pmus la chance random que la loterie ne marche pad et que le joueur nobtienne rien du tout augmente.

Pr la grosse récompense seulement ya aussi une petite chance de malus

**Comment by quenquentin** [comment]
@BastLast si tu penses que je peux le faire je suis chaud, par contre j'aimerai en discuter avec toi quand même

**Comment by BastLast** [comment]
c'est pas hors de ta portée sincèrement. ya pas mal de taf en vrai x) mais normalement pas grand chose d'ultra complexe @quenquentin
