### ISSUE TITLE
Bug possibilité de transfer un pet fielleux en utilisant la commande ptr <num>

### ISSUE THREAD

**Issue by Izukulele** [DraftBot-A-Discord-Adventure/DraftBot#537]
De base on peut pas transférer un pet fielleux de chez nous au shelter et donc on aura un message du bot disant qu'on peut pas le faire avec un !ptr normal. Mais en faisant !ptr <num> on aura toujours le message d'erreur mais le transfert aura quand même lieu
![image](https://user-images.githubusercontent.com/70220545/129547326-1bf665a3-6eaf-4222-a3c2-3dbe8bf953ec.png)

**Comment by Pietagorh** [comment]
Le bug est réapparu https://discord.com/channels/429765017332613120/879847273104814092/879872856060747796

**Comment by niqore** [comment]
Oui normal y a pas encore eu la mise à jour

**Comment by Pietagorh** [comment]
Ah bah oui j'suis con
