### ISSUE TITLE
Indiquer les issues qui peuvent mener à un os de quelque chose

### ISSUE THREAD

**Issue by Izukulele** [DraftBot-A-Discord-Adventure/DraftBot#539]
Indiquer les issues dans les reports qui peuvent mener à un one shot de quelque chose comme ça les gens ont pas besoin d'aller sur GitHub
![image](https://user-images.githubusercontent.com/70220545/129763985-3daf0cec-8505-48fb-9c23-e44a76c0ce07.png)
et un screen bonus merci thero 
![image](https://user-images.githubusercontent.com/70220545/129764042-5122d84e-ee92-412e-9d31-51d6308af99b.png)

**Comment by niqore** [comment]
Tu t'es assigné @BastLast . T'auras le temps de t'en occuper ? Sinon je le fais

**Comment by BastLast** [comment]
> Tu t'es assigné @BastLast . T'auras le temps de t'en occuper ? Sinon je le fais

j'aurai le temps

**Comment by niqore** [comment]
T'es sûr ? 👀

**Comment by BastLast** [comment]
Oui

**Comment by BastLast** [comment]
au final on a décidé de supprimer les oneshot pas clairs et d'ajouter des nouveaux qui soient plus prévisibles
