### ISSUE TITLE
Refaire le système de logs

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#546]
On pourrait soit prendre un truc tout faire, soit faire un truc perso qui sort des stats et tout si y a rien

Logs à faire :
- [x] Big events
- [x] Small events
- [x] Changement d'experience
- [x] Changement de gemmes
- [x] Changement de vie
- [x] Changement de niveau
- [x] Changement d'argent
- [x] Changement de score
- [x] Unlock
- [x] Commandes
------------
- [x] Altérations
- [x] Changement de classe
- [x] Votes
- [x] Server join
- [x] Server leave
- [x] Trajets joueur (start travel)
- [x] Mission find
- [x] Mission complete
- [x] Mission fail
- [x] Mission daily
----------
- [x] Mission daily finished
- [x] Campaign progression
- [x] 15 joueurs top week chaque jour
- [x] Gain d'item
- [x] Vente d'item
- [x] Avance de temps joueur
- [x] Pet nickname change
- [x] Guild kick
- [x] Potion du jour
- [x] Achat shop classique
---------
- [x] Achat shop guilde
- [x] Achat shop missions
- [x] Timeouts (daily,, week...)
- [x] Guild daily
- [x] Pet transfer
- [x] Guild leave
- [x] Guild destroy
- [x] Guild elder remove
- [x] Guild chief changes
- [x] Pet free
---------
- [x] Actions combats
- [x] Resultats combats
- [x] Guild join
- [x] Guild create
- [x] Guild experience changes
- [x] Guild level up
- [x] Pet trade
- [x] Guild elder add
- [x] Guild description changes
- [x] Pet love change
---------
- [x] Guild food change
- [x] Pet sell
- [x] Guild new pets
- [x] Player new pet

**Comment by niqore** [comment]
Ah oui et aussi tracer hyper bien les erreurs pour trouver d'où ça vient

**Comment by quenquentin** [comment]
Peut-être utiliser le fuseau horaire français aussi ? Un peu embêtant de chercher si +2h/-2h etc...

**Comment by BastLast** [comment]
j'aimerai vraiment utiliser un agrégateur de logs https://grafana.com/grafana/

**Comment by Feiryn** [comment]
Logs à faire :
- [ ] Big events
- [ ] Small events
- [ ] Changement d'experience
- [ ] Changement de gemmes
- [ ] Changement de vie
- [ ] Changement de niveau
- [ ] Changement d'argent
- [ ] Changement de score
- [ ] Unlock
- [ ] Commandes
- [ ] Altérations
- [ ] Changement de classe
- [ ] Pet trade
- [ ] Pet feed
- [ ] Pet transfer
- [ ] Pet free
- [ ] Actions combats
- [ ] Resultats combats
- [ ] Guild join
- [ ] Guild leave
- [ ] Guild kick
- [ ] Guild create
- [ ] Guild elder add
- [ ] Guild elder remove
- [ ] Guild daily
- [ ] Guild experience changes
- [ ] Guild level up
- [ ] Guild description changes
- [ ] Guild chief changes
- [ ] Guild food changes
- [ ] Guild new pets
- [ ] Guild destroy
- [ ] Player new pet
- [ ] Pet nickname change
- [ ] Pet love change
- [ ] Mission find
- [ ] Mission complete
- [ ] Mission fail
- [ ] Achat shop classique
- [ ] Achat shop guilde
- [ ] Achat shop missions
- [ ] Gain d'item
- [ ] Vente d'item
- [ ] Avance de temps joueur
- [ ] Votes
- [ ] Trajets joueur (start travel)
- [ ] Campaign progression
- [ ] Timeouts (daily,, week...)
- [ ] Joueur top week
- [ ] 15 joueurs top week chaque jour
- [ ] Potion du jour
- [ ] Server join
- [ ] Server leave
