### ISSUE TITLE
TYPO ajout du féminin de chameau (chamelle) 

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#547]
![image](https://user-images.githubusercontent.com/80409766/130362749-91a7fbfc-bdf5-4f08-ac6c-984f25a0b283.png)

**Comment by BastLast** [comment]
pourquoi ca a été close ? fixé ?

**Comment by Pietagorh** [comment]
> pourquoi ca a été close ? fixé ?

Oui
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/1e8c7bc93a43ff5e0d8ed0c45c8b21c39ba81122/resources/text/pets/50.json#L5

**Comment by BastLast** [comment]
Bien vu merci :)
