### ISSUE TITLE
[BUG] la commande !feedpet ne fonctionne plus correctement

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#550]
![image](https://user-images.githubusercontent.com/80409766/130368632-7247aa40-87ff-462c-ac7a-d94efb98df1e.png)

![image](https://user-images.githubusercontent.com/80409766/130411668-234ec8ab-e0f9-4318-ad8e-12057d4cd83b.png)

**Comment by niqore** [comment]
Problème temporaire corrigé
