### ISSUE TITLE
possibilité d'aller en négatif pour l'argent

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#552]
surement achat de nourriture via la guilde

**Comment by BastLast** [comment]
@romain22222  tu as fini ?

**Comment by BastLast** [comment]
@niqore  faut qu'on discute de ça j'ai rien compris de ce que m'a expliqué @romain22222  à propos de https://canary.discord.com/channels/429765017332613120/440879632837902346/879468651772805240

**Comment by niqore** [comment]
C'est pas un bug qu'on aura on s'en fout de ça. J'ai changé le code du shop pour le provoquer

**Comment by niqore** [comment]
Il me semble que c'est fini, tu peux PR ça stp @romain22222 que je valide ?
