### ISSUE TITLE
Issues conditionnelles pour les évents

### ISSUE THREAD

**Issue by niqore** [DraftBot-A-Discord-Adventure/DraftBot#627]
### Discussed in https://github.com/DraftBot-A-Discord-Adventure/DraftBot/discussions/586

<div type='discussions-op-text'>

<sup>Originally posted by **Pietagorh** October  1, 2021</sup>
Ajouter la possibilité de faire des events changeant en fonction de la classe de la personne. Par exemple un event ou il y a un combat, et a un moment le joueur décoche une flèche sur la personne, et cet event serait uniquement accessible aux archers, ou genre il serait accessible aussi aux autres mais changerait (ex piquier : vous lui lancez une lance dans le buste, maillé : vous arrivez a ne pas être infligé par son attaque grâce a votre armure etc...)

Que certain report, le stuff que l'on possède joue sur l'event.

Exemple:

On a la dame qui a entendu un truc dans la grotte et tu décide d'aller voir. Dans la grote y'a l'Ours que tu doit battre, faire que si par exemple ton boulier et attaque est supérieur a 120 alors tu as 100% de chance de battre l'ours.
Ou si tu te fait agresser tu te défend si tu as une arme a distance ou au corps a corps. Ou si tu as une bonne armure trébucher ou tomber dans un trou t'enlève moins de vie.</div>

autre issue liée : #633

**Comment by Pietagorh** [comment]
Pousser le truc au max avec d'autres conditions
Voilà les quelques idées qu'on a eu avec Eagle : 
- être dans une guilde
- posséder un animal
- avoir un item d'une certaine rareté ou mieux
- avoir tel badge
- être Xème dans le top
- être Xème dans le tw

**Comment by Feiryn** [comment]
C'est déjà codé
