### ISSUE TITLE
pv supérieurs à leur limite

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#634]
![image](https://user-images.githubusercontent.com/60353007/136919969-489fa27d-b3d2-4a3d-943d-ca3f9f0f3969.png)
(Elle n'a pas joué depuis longtemps de ce que j'ai pu voir)

**Comment by niqore** [comment]
Je pense que ce n'est pas un bug très grave, c'est très rare et ça se corrige tout seul au prochain moment où la personne perd ou gagne de la vie. Si elle n'a pas joué depuis longtemps, c'est sûrement dû à une modification de la barre de vie maximale je ne sais pas quand

**Comment by BastLast** [comment]
Je pense aussi que ça viens de la mise à jour ajoutant les classes.
