### ISSUE TITLE
check si ya pas des coms useless

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#653]
![image](https://user-images.githubusercontent.com/38099970/137645799-0dd3c3bf-c9f6-41c5-a4b0-d637eb1f1b88.png)

**Comment by Surdidi** [comment]
mzj ce com : https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/ab2662bc04e5c39fce6ec879bffaeab4203594ff/src/commands/player/FriendlyFightCommand.js#L9

**Comment by BastLast** [comment]
Bon vu qu'on repart de 0 pr la 5.0 ya des chances que ça soit fix par ça
