### ISSUE TITLE
équilibrage divers

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#659]
![image](https://user-images.githubusercontent.com/38099970/137808593-40289697-c2e2-4a4a-a098-999e96d37a32.png)
cette issue devrait rendre malade

**Comment by Thesmokingllama** [comment]
le joueur aurait dû recevoir 150xp

![2B39353D-7539-417E-935D-6469DD304ED0](https://user-images.githubusercontent.com/80409766/141116065-8cca7b4a-dd96-4506-b70d-8bda4d9f96ae.jpeg)

**Comment by quenquentin** [comment]
Cette issue n'avait pas lieu d'être cf : #682
Cependant c'est fait, je close donc l'issue et j'informe pour ne pas oublier la meta report par Angel
