### ISSUE TITLE
afficher "non classé" plutot qu'un chiffre supérieur au nombre de joueur

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#660]
- [ ] sur le profil d'un joueur
- [ ] dans les mini-events

**Comment by quenquentin** [comment]
Uniquement quand le joueur n'a pas fait de report non ?

**Comment by BastLast** [comment]
????

**Comment by BastLast** [comment]
Ca serait top que l'affichage en bas du top et du topweek ne soit pas tout moche quand on les affiche sans être classé. #793 

Je remet ca en 2.3.0 du coup

**Comment by Pietagorh** [comment]
Tu voudrais mettre quoi comme affichage ? x)

**Comment by BastLast** [comment]
jsp mais pas un truc avec des chiffres qui n'ont aucun sens
