### ISSUE TITLE
Nouveau mini évent qui dépend du level

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#663]
Ajout de deux nouveaux mini events de rareté 1 tous les deux.

Le joueur rencontre un pnj (l'un est le frère de l'autre) (un frère / mini event) qui offre des récompenses ou pénalités en fonction du level du joueur.

Un des frères donne des pénalités de plus en plus grosse quand le level du joueur augmente
l'autre donne des récompenses de plus en plus grosses quand le level du joueur augmente 

(les mini event ne se cancellent pas le type de récompense / pénalité n'est pas la meme , à discuter ci-dessous)

**Comment by quenquentin** [comment]
Je veux bien prendre l'issue mais faudrait un petit voc @BastLast si tu veux me dire quand t'es dispo

**Comment by BastLast** [comment]
yes ca peut etre cool de la faire en typescript 
je pense que ca peut etre un bon exercice

**Comment by Pietagorh** [comment]
Du coup QQ tu la prends ou j'peux te la piquer ?

**Comment by quenquentin** [comment]
> Du coup QQ tu la prends ou j'peux te la piquer ?

Tu piques rien @Pietagorh, pas deux fois 👍 
Je m'en occupe dès que j'ai du temps pour regarder les models faits en TS

**Comment by BastLast** [comment]
du coup @quenquentin  tu as le temps de faire ca qd ?

**Comment by quenquentin** [comment]
Pendant mes vacances donc à partir d'aujourd'hui

**Comment by Pietagorh** [comment]
Bonus : 
Avec guilde et plus de level 30 : 1 à 5 soupes ultimes ou item avec rareté différée
Sinon : 20 + level 💰

Malus :
Petit jeu avec 1 chance sur 3 pour chaque : 
- Perte de vie
- Perte de temps
- Rien
End : vous roue de coups

**Comment by Pokegali** [comment]
Rareté min : `floor(5*tanh(x/125)+1)`
Rareté max : `floor(7*tanh(x/62))`

**Comment by BastLast** [comment]
@Pietagorh est-ce que tu peux finir ça avant le 20 ? Ou c'est chaud ?

**Comment by Pietagorh** [comment]
J'ai eu quelques problèmes cette semaine mais du coup j'finis dans les prochains jours

**Comment by Pietagorh** [comment]
(j'ai fini le premier et la moitié du deuxième, qui devrait pas être trop long)

**Comment by DoctorT1807** [comment]
Petit bug
![image](https://user-images.githubusercontent.com/89483734/158026231-02bf1fce-babd-4409-a075-afdd3e4bbef3.png)
