### ISSUE TITLE
Bug xp de guilde

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#671]
![image](https://user-images.githubusercontent.com/38099970/138565389-bcb94b80-7e44-43fa-b211-1db474b7e365.png)

**Comment by Pietagorh** [comment]
Le bug est aussi présent pour l'exp perso
![image](https://user-images.githubusercontent.com/60353007/141634834-41cbfeb0-ade3-477e-b512-5dabe87c9668.png)
![image](https://user-images.githubusercontent.com/60353007/141634917-5cd0d426-7b04-4071-9cb9-0fc84f44e590.png)
