### ISSUE TITLE
Temps entre mini-évent

### ISSUE THREAD

**Issue by quenquentin** [DraftBot-A-Discord-Adventure/DraftBot#673]
![image](https://user-images.githubusercontent.com/56274541/138586647-e9d130c2-231e-4dc0-814a-3e26347958e2.png)
Ici on voit que le joueur a une alté de 5 min qui se fini à 18h45, or il a pu lancer son mini évent à 50 avant les 10 minutes.

**Comment by Pietagorh** [comment]
D'après mon expérience, le bug ne se produit que pendant le tout début de la fin d'une altération/juste après d'un advance time, à partir d'un certain temps on peut pas !r une deuxième fois
