### ISSUE TITLE
Ajout du questshop

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#675]
- [x] 1000 points  (cooldown de 1 semaine)
- [x] Item ++ (item avec une rareté minimale de spéciale)
- [x] voir l'amour exact de ton pet (en pourcentages)
- [x] Badge quest master
- [x] money (ratio nul)
- [x] passage des quetes randoms (cher)
- [x] le vétérinaire doit donner le régime alimentaire du pet
- [x] rajouter les conseils du veterinaire

**Comment by romain22222** [comment]
#153

**Comment by DoctorT1807** [comment]
Quand on prend l'argent du roi celui-ci n'est pas give
