### ISSUE TITLE
Typos pour la 2.3.0 & changements concernant les évents

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#682]
Toutes les typos déjà report sont implémentées dans le repo chaque mois

**Comment by Pietagorh** [comment]
Peut-être **qu'**une meilleure récompense
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/advices.json#L173

**Comment by Pietagorh** [comment]
Il manque un point
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/advices.json#L170

**Comment by Pietagorh** [comment]
Ce serait mieux de mettre le lien du discord du bot à la fin
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/advices.json#L169

**Comment by Pietagorh** [comment]
Mauvais lien
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/commands/idea.json#L5
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/commands/idea.json#L9

**Comment by Pietagorh** [comment]
Heureusement que Pourfi a changé, sinon il aurait fait une crise (il manque un point)
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/advices.json#L162

**Comment by Pietagorh** [comment]
> Ce serait mieux de mettre le lien du discord du bot à la fin
> 
> https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/advices.json#L169

Idem
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/advices.json#L156

**Comment by Pietagorh** [comment]
Plus "un temps variable **compris** entre" ou juste "un temps **compris** entre"
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/advices.json#L153

**Comment by Pietagorh** [comment]
J'vais mettre tous ceux qui ont pas de point ici
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/advices.json#L138

**Comment by Pietagorh** [comment]
y'a ! et : à côté
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/advices.json#L63

**Comment by Pietagorh** [comment]
rencontrés 
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/smallEvents/interactOtherPlayers.json#L99

**Comment by Pietagorh** [comment]
paid
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/commands/petFree.json#L24

**Comment by Pietagorh** [comment]
> paid
> 
> https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/commands/petFree.json#L24

btw plutôt "You paid 1000 coins to free a fiesty pet" apparemment

**Comment by Pietagorh** [comment]
gagné*
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/smallEvents/pet.json#L39
![image](https://user-images.githubusercontent.com/60353007/140655357-6449b2ae-45e5-4142-b2ee-20f799b9fc9c.png)

**Comment by Thesmokingllama** [comment]
*Vois réussissez à vous accrocher à une planche plus solide
![](https://media.discordapp.net/attachments/870363331922382868/903134553156251708/IMG_1141.png)

**Comment by Pietagorh** [comment]
> *Vous réussissez à vous accrocher à une planche plus solide https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/resources/text/events/21.json#L54 ![](https://media.discordapp.net/attachments/870363331922382868/903134553156251708/IMG_1141.png?width=578&height=662)

https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/events/21.json#L54

**Comment by Thesmokingllama** [comment]
Remplacer "la jambe" par "les jambes" par souci de cohérence avec la seconde phrase 

![](https://media.discordapp.net/attachments/870363331922382868/900389887767900170/unknown.png)

**Comment by Thesmokingllama** [comment]
Retirer "scruter le ciel" et remplacer par "le scruter" pour éviter la répétition 

![](https://media.discordapp.net/attachments/870363331922382868/894606390822338632/ciel.png)

**Comment by Pietagorh** [comment]
de rose**s**
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/weapons/44.json#L3

**Comment by Pietagorh** [comment]
Double dague
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/weapons/15.json#L3

**Comment by Pietagorh** [comment]
Pas de majuscule à celui
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/smallEvents/winPersonalXP.json#L6

**Comment by Pietagorh** [comment]
à remplacer par **parti{feminine}**
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/fd5ef811423a512a35d0cdae13b8fc881bd3dce3/resources/text/smallEvents/pet.json#L21

**Comment by Pietagorh** [comment]
Remplacer par "sans quoi la foule l'aurait déjà touché" et enlever les *
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/0b638133a521a5fe5ce6ea5c5ab0c81e6e6e20d6/resources/text/smallEvents/class.json#L43

**Comment by Pietagorh** [comment]
"**à** cette dernière un grand coup" (sans le d')
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/0b638133a521a5fe5ce6ea5c5ab0c81e6e6e20d6/resources/text/smallEvents/findItem.json#L11

**Comment by Thesmokingllama** [comment]
*comptez=>contez ; le lui remettre=>qui ? ; le lui remettre=>idem ; au traître=>pas nommé dans les phrases précédentes

![image](https://user-images.githubusercontent.com/80409766/141687650-2ad8dbdd-f181-4b31-afc3-037abd8c6349.png)

**Comment by Pietagorh** [comment]
J'ai delete toutes les typos fix dans ma pr #715

**Comment by Pietagorh** [comment]
Il manque un espace avant le : 
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/f1c3a00c2ae07a4c2dd320fb275f023b01566e2d/resources/text/commands/fight.json#L10

**Comment by Pietagorh** [comment]
Majuscule à "ces"
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/1e8c7bc93a43ff5e0d8ed0c45c8b21c39ba81122/resources/text/events/5.json#L18

**Comment by Pietagorh** [comment]
Changer versée pour un truc modulable, comme pour les pets OU changer pour "Vous avez versé {item} dans un évier"

**Comment by Thesmokingllama** [comment]
correction globale du mini-event : 
"Après un virage, un jeune garçon vous bouscule en vous doublant. Envahi d'un mauvais pressentiment, vous vérifiez le contenu vos poches : votre bourse a disparu ! Parvenant à le rattraper après une course effrénée, vous récupérez ce qui vous revient de droit et laissez le mécréant dans un fossé non sans l'avoir puni comme il le méritait. Vous vous rendez compte que cet événement vous aura permis de gagner **{time} minutes}** sur votre itinéraire."

![](https://media.discordapp.net/attachments/870363331922382868/911603581357010995/unknown.png)

**Comment by Pietagorh** [comment]
Truc modulable aussi pour les items de temps ("heure(s)")

> Changer versée pour un truc modulable, comme pour les pets OU changer pour "Vous avez versé {item} dans un évier"![IMG_20211119_002057.jpg](https://user-images.githubusercontent.com/60353007/142512328-c1a8c728-e6f1-4c6d-a484-20d1242e155a.jpg)

**Comment by Pietagorh** [comment]
bas-côté
![image](https://user-images.githubusercontent.com/60353007/142768623-5fb3a887-e012-4d45-862c-0a7410187078.png)
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/c0c2ea2f326278816b62003706c29ee64ffee913/resources/text/smallEvents/findItem.json#L6
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/c0c2ea2f326278816b62003706c29ee64ffee913/resources/text/smallEvents/findPotions.json#L6

**Comment by Thesmokingllama** [comment]
=> pas "fatal"
=> pléonasme "fatal" "de la mort"
=> reformuler "tourbillon glacé de la mort" car trop enfantin ?

![](https://media.discordapp.net/attachments/870363331922382868/912073684498415626/unknown.png)

>

**Comment by symsym-1629** [comment]
![Screenshot_20211122-131154_Discord](https://user-images.githubusercontent.com/83075391/142910794-1d23ff8f-6a61-43b4-81dd-d5a56d7907c5.jpg)
enlever les points et l'elo car c pas logique puisqu'il n'y a pas de gagnant

**Comment by Pietagorh** [comment]
jours(s) -> jour(s) (potentiellement un truc modulable, comme pour les items de temps et le delete des potions
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/1e8c7bc93a43ff5e0d8ed0c45c8b21c39ba81122/resources/text/smallEvents/space.json#L82

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/143489969-c1caa17b-cd64-4df8-9147-60295df33644.png)
revoir la meta

**Comment by Chevalier2** [comment]
![Sa](https://user-images.githubusercontent.com/72626953/143499911-ede54f8d-7b84-4b64-bff8-2897f3a2e73c.png)
Mettre du texte modulable.

**Comment by Pietagorh** [comment]
> ![image](https://user-images.githubusercontent.com/56274541/143489969-c1caa17b-cd64-4df8-9147-60295df33644.png)
> revoir la meta

-> #659

**Comment by quenquentin** [comment]
Voir la méta report par angel sur l'issue #659

**Comment by Pietagorh** [comment]
Manque le gras sur la récompense
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/1e8c7bc93a43ff5e0d8ed0c45c8b21c39ba81122/resources/text/smallEvents/lottery.json#L21
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/1e8c7bc93a43ff5e0d8ed0c45c8b21c39ba81122/resources/text/smallEvents/lottery.json#L22
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/1e8c7bc93a43ff5e0d8ed0c45c8b21c39ba81122/resources/text/smallEvents/lottery.json#L23
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/1e8c7bc93a43ff5e0d8ed0c45c8b21c39ba81122/resources/text/smallEvents/lottery.json#L24

**Comment by Thesmokingllama** [comment]
Pas possible de s'accrocher à la rive sans être mouillé, à remanier
![](https://media.discordapp.net/attachments/870363331922382868/915333111020134470/unknown.png)

**Comment by Pietagorh** [comment]
{moneyWon} -> {money}
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/0b638133a521a5fe5ce6ea5c5ab0c81e6e6e20d6/resources/text/smallEvents/lottery.json#L46

**Comment by Pietagorh** [comment]
Uniformiser les descriptions d'items et potions de temps ![Capture_decrans_20211205-224333.jpg](https://user-images.githubusercontent.com/60353007/144765310-6d418b4b-d7e1-4074-b8f8-b60ed5fe867e.jpg)![Capture_decrans_20211205-224231.jpg](https://user-images.githubusercontent.com/60353007/144765312-5cfdb4c7-6215-4c03-af10-9e538791cb69.jpg)

**Comment by Thesmokingllama** [comment]
Changer la répétition "de cet apport de sucre" par "de cet apport en sucre" 


![](https://media.discordapp.net/attachments/870363331922382868/917753455551062016/IMG_20211207_132346.jpg)

**Comment by Pietagorh** [comment]
Utiliser #763 pour régler les problèmes avec voyelles en début de mot![unknown-16.png](https://user-images.githubusercontent.com/60353007/145600427-3ca7b384-1675-4d53-a98a-87053733005a.png)

**Comment by Pietagorh** [comment]
> ![Sa](https://user-images.githubusercontent.com/72626953/143499911-ede54f8d-7b84-4b64-bff8-2897f3a2e73c.png) Mettre du texte modulable.

Le problème était en fait au niveau de l'item, ça a été fix dans #764

**Comment by Thesmokingllama** [comment]
Le "ne" est de trop
![](https://media.discordapp.net/attachments/870363331922382868/921098415654461470/Screenshot_20211216-185503_Discord.jpg)

**Comment by Thesmokingllama** [comment]
**[TYPO]** À refaire, virgules en trop (notamment la dernière) et tout en avançant [...] vous tombez" pas top

![](https://media.discordapp.net/attachments/870363331922382868/920726329274556436/IMG_3857.png)

**Comment by Pietagorh** [comment]
On élit pas, à reformuler
![SmartSelect_20211222-003338_Discord.jpg](https://user-images.githubusercontent.com/60353007/147011995-7321f146-d0e8-41e6-9045-c8787f5ea170.jpg)

**Comment by Thesmokingllama** [comment]
Retirer le gain d'xp, ça avait pas été fait 

![](https://media.discordapp.net/attachments/870363331922382868/925088874458407002/IMG_4039.png)

**Comment by Thesmokingllama** [comment]
Majuscule à Zeus 

![](https://media.discordapp.net/attachments/870363331922382868/925901643558559744/SmartSelect_20211230-010150_Discord.jpg)

**Comment by Thesmokingllama** [comment]
Ajouter l'emote 💎 au conseil


![](https://media.discordapp.net/attachments/870363331922382868/927200241529290762/unknown.png)

**Comment by Thesmokingllama** [comment]
Reformuler end event champs de bataille 


![](https://media.discordapp.net/attachments/870363331922382868/927618185463738408/inconnu.png)

**Comment by Thesmokingllama** [comment]
Pluriel à pièce 

![](https://media.discordapp.net/attachments/870363331922382868/927551583191986196/Screenshot_2022-01-03-14-10-55-65_572064f74bd5f9fa804b05334aa4f9123.jpg)

**Comment by Thesmokingllama** [comment]
Reformuler end marchand ambulant 

![](https://media.discordapp.net/attachments/870363331922382868/927523834888847370/inconnu.png)

**Comment by Pietagorh** [comment]
Manque un point
![image](https://user-images.githubusercontent.com/60353007/148066265-d8b91ddf-32dc-4229-b3bb-755f0a5a2e99.png)

**Comment by Pietagorh** [comment]
Changer pour "Armure/bouclier" ![IMG_20220106_131954.jpg](https://user-images.githubusercontent.com/60353007/148382099-2f521826-b134-4952-bfc9-0ba0d947ee70.jpg)

**Comment by Thesmokingllama** [comment]
Un seul l à palier 
![](https://media.discordapp.net/attachments/870363331922382868/928283294888521828/Screenshot_2022-01-05-14-42-44-55_572064f74bd5f9fa804b05334aa4f9122.jpg)

**Comment by Pietagorh** [comment]
Mauvaise valeur max
![image](https://user-images.githubusercontent.com/60353007/148571978-cd1b25f3-0815-4b1d-a3f8-4e1aca0f36af.png)

**Comment by Thesmokingllama** [comment]
il faut écrire "après que votre quête vous a mené". Le subjonctif passé ne doit pas être utilisé après la formule "après que", en plus il aurait fallu mettre un "t" (qu'il ait).

![image](https://user-images.githubusercontent.com/80409766/148647042-8169b0fb-718b-4d61-91ed-52fb9b052cc2.png)

**Comment by Thesmokingllama** [comment]
Assommé ; étiez 


![](https://media.discordapp.net/attachments/870363331922382868/930893387312279703/unknown.png)

**Comment by Thesmokingllama** [comment]
Mettre à jour 
![](https://media.discordapp.net/attachments/870363331922382868/930701938503344138/SmartSelect_20220112-065701_Discord.jpg)

**Comment by Thesmokingllama** [comment]
Seul le chef peut remove l'elder
![](https://media.discordapp.net/attachments/870363331922382868/930215919811182642/unknown.png)

**Comment by quenquentin** [comment]
@Pietagorh tu as les perms sur le repo pour pouvoir hide les messages ? Si oui il faudrait à chaque correction pouvoir hide les messages qui ont été corrigé please. Ty

**Comment by Pietagorh** [comment]
Pas la perm

**Comment by symsym-1629** [comment]
Créer une carte avec les noms en anglais (pour le bot en anglais
![unknown](https://user-images.githubusercontent.com/83075391/150137098-df56bc7a-3612-4f20-8108-92fae4f894bb.png)
)

**Comment by Thesmokingllama** [comment]
Réécrire de façon à introduire la perte d'argent, rendre = 0 != perte
![](https://media.discordapp.net/attachments/870363331922382868/931267019880411236/unknown.png)

**Comment by Thesmokingllama** [comment]
Points à l'intro et au dernier choix
![](https://media.discordapp.net/attachments/870363331922382868/933445709108224080/j.png)

**Comment by Thesmokingllama** [comment]
Supprimer "ou ainé", l'elder ne peut pas kick (sinon bug)
![](https://media.discordapp.net/attachments/870363331922382868/932694330475442216/unknown.png)

**Comment by Chevalier2** [comment]
C'est êtes**-**vous s**û**r.
![j](https://user-images.githubusercontent.com/72626953/151255430-b20768eb-312d-48e3-b641-b948ac8ea0e7.png)

**Comment by Thesmokingllama** [comment]
"faites" et non faîte de toit (et peut-être "vous drogué" aussi plutôt)
![](https://media.discordapp.net/attachments/870363331922382868/934802389163196416/unknown.png)

**Comment by Chevalier2** [comment]
> "faites" et non faîte de toit (et peut-être "vous drogué" aussi plutôt)
Vous à la place de "toi" et menez à la place de "mènent" aussi

**Comment by Pietagorh** [comment]
Y'a moins de 15 joueurs
![image](https://user-images.githubusercontent.com/60353007/151435229-03e048e4-dcf8-4d76-9d5b-609dc52a5b59.png)

**Comment by Thesmokingllama** [comment]
Biens
![image](https://user-images.githubusercontent.com/80409766/152687550-0ac1ed0f-addb-4cba-8311-fcc2354d9e03.png)

**Comment by Thesmokingllama** [comment]
Ajouter "Plage" et supprimer les déterminants avant les noms de lieux car aléatoires "la rivière aux crabes"/"rivière vacarme"
![image](https://user-images.githubusercontent.com/80409766/152687622-2ffff06b-9f2e-4a31-93a3-3922e69c048b.jpeg)

**Comment by Thesmokingllama** [comment]
Supprimer la répétition par "Il à l'air cependant"

![image](https://user-images.githubusercontent.com/80409766/152687660-d8851577-537d-4185-9588-de7c12db4264.png)

**Comment by Thesmokingllama** [comment]
Remplacer la fin par "Participez a la loterie vous aura fait perdre 10min."
![image](https://user-images.githubusercontent.com/80409766/152687711-45ed14e8-707b-4100-908b-f18eb1140f61.jpeg)

**Comment by Thesmokingllama** [comment]
a été
![image](https://user-images.githubusercontent.com/80409766/152687729-dc9a71f3-050c-4ef4-a123-b3bb35d724a2.png)

**Comment by Thesmokingllama** [comment]
Vous manquants 
![](https://media.discordapp.net/attachments/870363331922382868/939848471920390154/unknown.png)

**Comment by Thesmokingllama** [comment]
Rajoutée 

![](https://media.discordapp.net/attachments/870363331922382868/943165479151865936/IMG_20220215_162217.jpg)

**Comment by Thesmokingllama** [comment]
Point d'exclamation en gras

![](https://media.discordapp.net/attachments/870363331922382868/942849770605654056/IMG_4783.png)

**Comment by Thesmokingllama** [comment]
Créées

![](https://media.discordapp.net/attachments/870363331922382868/941688221950152765/IMG_4718.png)

**Comment by Thesmokingllama** [comment]
Point en trop
![](https://media.discordapp.net/attachments/870363331922382868/941007888367910952/Sans_titre_14.jpg)

**Comment by Thesmokingllama** [comment]
Reformuler de façon à justifier la perte de temps

![](https://media.discordapp.net/attachments/870363331922382868/940539812774047774/IMG_4683.png)

**Comment by Thesmokingllama** [comment]
ici surgit doit être utilisé comme un adjectif ou la phrase est une suite de verbes, auquel cas il manque une virgule

![image](https://user-images.githubusercontent.com/80409766/154360540-109d0090-9417-4f31-95fe-3f9802173336.png)

**Comment by Thesmokingllama** [comment]
assène à son adversaire une attaque puissante
![image](https://user-images.githubusercontent.com/80409766/154361352-e671f32b-0d86-4574-af16-e21831a2256c.png)

**Comment by Thesmokingllama** [comment]
mettre l'argent en gras 
![image](https://user-images.githubusercontent.com/80409766/154856072-009e61e3-ba7c-42a8-8544-8044d7787148.png)

**Comment by Thesmokingllama** [comment]
de vos poches 
![image](https://user-images.githubusercontent.com/80409766/154856425-7517e83d-4583-4310-94c1-f07695956cf2.png)

**Comment by Thesmokingllama** [comment]
Event du sanctuaire, choix 1
C'est "Il se révèle" car c'est un sanctuaire, pas plusieurs
![image](https://user-images.githubusercontent.com/80409766/154856442-e529e391-b7e8-4b19-b690-63e8a5c37a71.png)

**Comment by Thesmokingllama** [comment]
pas de négation 
![image](https://user-images.githubusercontent.com/80409766/154856467-e5691e28-2ce6-45fe-852b-c437e5066e44.png)

**Comment by Thesmokingllama** [comment]
pas de majuscule à vous
![image](https://user-images.githubusercontent.com/80409766/154856485-8f47e9f0-7a7d-4380-9efa-0c79ec5324ce.png)

**Comment by Thesmokingllama** [comment]
côté
![image](https://user-images.githubusercontent.com/80409766/154856502-cd0eff6f-1501-4248-9c5d-69bf55d79c66.png)

**Comment by Thesmokingllama** [comment]
exécutez 
![image](https://user-images.githubusercontent.com/80409766/154856518-54bd9636-aa17-4b75-a85d-a279db508c80.png)

**Comment by Thesmokingllama** [comment]
ajouter l'ainé
![image](https://user-images.githubusercontent.com/80409766/154857536-d4e1b48b-b8d4-412d-8a94-6698d7cae304.png)
![image](https://user-images.githubusercontent.com/80409766/154857543-b521566e-5a47-4986-acbc-4aba3e2f1d0b.png)
![Capture d’écran 2022-02-20 à 19 16 16](https://user-images.githubusercontent.com/80409766/154857585-b65178d7-caf7-4d17-8871-9980aec5a6c2.png)

**Comment by BastLast** [comment]
je close cette issue et je vous invite à reporter toutes les typos qui n'ont pas été corrigées sur une nouvelle issue x)
