### ISSUE TITLE
end lottery + no money

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#685]
quand on répond pas à la lotterie, le message se renvoit
![image](https://user-images.githubusercontent.com/60353007/140314555-86b0a48d-e460-4fef-8bea-0e0a8f94d485.png)
(premier message à 49 et deuxième à 51)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/141651294-d9fffdcd-b318-4b1a-a8e1-d322730689d2.png)
Petit soucis, le joueur avec 101 pièces apparemment

**Comment by quenquentin** [comment]
> ![image](https://user-images.githubusercontent.com/56274541/141651294-d9fffdcd-b318-4b1a-a8e1-d322730689d2.png) Petit soucis, le joueur avec 101 pièces apparemment

La limite a été changée à 175 avant le push master, donc tout est normal de ce côté là.
