### ISSUE TITLE
utilisation plusieurs commandes pet

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#688]
Peut créer un pet fantôme et bloquer le shelter de la guilde
![image](https://user-images.githubusercontent.com/60353007/140516875-ec7ca8c2-4030-403d-bef5-d492b45ee49a.png)
https://discord.com/channels/429765017332613120/429765574923649025/906170595274805248

**Comment by niqore** [comment]
![Uploading Screenshot_20211105-142551697.jpg…]()

**Comment by niqore** [comment]
![Screenshot_20211105-142551697](https://user-images.githubusercontent.com/18489162/140517555-221c66c1-c79c-4cfe-a5e0-0817ee69c8b3.jpg)

**Comment by Pietagorh** [comment]
![image](https://user-images.githubusercontent.com/60353007/140517544-517892a7-cdfc-4e66-b935-176283df7794.png)
![image](https://user-images.githubusercontent.com/60353007/140517554-e66cb1ee-e35d-419a-b609-ec0e25fb64f6.png)

**Comment by niqore** [comment]
Il faut bloquer TOUTES les commandes de pets

**Comment by Pietagorh** [comment]
> Il faut bloquer TOUTES les commandes de pets

(parce que dupli de pet avec petsell + pettrade)
