### ISSUE TITLE
ne pas accepter un item random du shop enlève la perte d'argent

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#695]
Si vous achetez un item random, que vous obtenez un objet et que vous ne l'acceptez pas (donc emplacements pleins) ça ne débite pas des 350 :moneybag: de l'achat de l'item
Ça marche pas avec les potions, faudrait tester pour armes et armures ![image](https://cdn.discordapp.com/attachments/870363331922382868/908003262165286962/unknown.png) ![image](https://cdn.discordapp.com/attachments/870363331922382868/908003301038100490/unknown.png)
![Screenshot_2021-11-10-15-49-02-888_com.discord.jpg](https://user-images.githubusercontent.com/60353007/141135045-88e82242-575c-4e47-a550-1a86e78cf4b6.jpg)
![Screenshot_2021-11-10-15-49-14-259_com.discord.jpg](https://user-images.githubusercontent.com/60353007/141135071-815e6779-dc9c-4b11-b8bf-b227dc0a2f85.jpg)

**Comment by Pietagorh** [comment]
![Screenshot_2021-11-10-15-51-40-768_com.discord.jpg](https://user-images.githubusercontent.com/60353007/141135628-70247b9b-b029-4ad5-8b99-c48cde5c3bdc.jpg)
![Screenshot_2021-11-10-15-51-34-850_com.discord.jpg](https://user-images.githubusercontent.com/60353007/141135627-c04e9b6e-0d76-46b9-8680-62d1bc868a5e.jpg)

**Comment by quenquentin** [comment]
Well, @niqore ça a pas été fix par tes commits ça ? J'ai testé avec les potions et c'est plus le cas

**Comment by niqore** [comment]
J'avais tenté de hotfix mais ça n'avait pas marché

**Comment by niqore** [comment]
Finalement le fix a marché
