### ISSUE TITLE
certains pets ont du love plus petit que 0 ou plus grand que 100

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#701]

**Comment by quenquentin** [comment]
Comment ? Mini events ? C'est plutôt ce qu'il faudrait  savoir pour la résolution du problème

**Comment by BastLast** [comment]
jsp ya moyen que ca soit déà fix et que ca soit juste un problème en bdd

**Comment by Thesmokingllama** [comment]
Nouvelle déclinaison de ce bug : le pet peut avoir une mentalité supérieure à 100
![](https://media.discordapp.net/attachments/447885296126656512/918582776184324166/unknown.png)

**Comment by niqore** [comment]
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/src/commands/pets/PetFeedCommand.js#L183
Quand le joueur n'a pas de guilde ce n'est check nul part que ça ne dépasse pas 100
