### ISSUE TITLE
premier report argent

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#703]
Le tout premier rapport que l'on fait quand on est nouveau joueur ne prend pas en compte l'argent gagné dans l'événement 0
![image](https://user-images.githubusercontent.com/60353007/141683555-30ba6c7b-8701-4723-b4d7-d58c8d594506.png)

**Comment by niqore** [comment]
Sera fix grâce à #732
