### ISSUE TITLE
Integration api top.gg

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#71]
Donner un badge de manière temporaire (12 heures) aux personnes qui votent pour le bot sur top.gg

**Comment by BastLast** [comment]
A déplacer en milestone 2.0.2 car plus urgent à faire avant

**Comment by Nashoba24** [comment]
J'ai fait en grande partie l'intégration via les webhooks. Il faudra donc configurer quand ce sera sur la vraie machine le webhook sur top.gg. Je n'ai pas mis de vérification de token car normalement avec un champ DBL_WEBHOOK_URL compliqué, sachant que peu de personnes ont l'ip de la machine ça devrait être une sécurité suffisante.

Attention, sur la vraie machine, il faudra choisir un **port ouvert**.

Pour l'intégration ça ajoute le rôle Mini-Vip, j'ai mis des vérifications si une personne vote avant la fin de son rôle (24h par défaut) et si le bot redémarre, ça remet comme il faut le timeout du rôle.
Ils gagnent aussi avec un vote le badge 🗳️ pendant 12h. Comme le temps du rôle c'est configurable dans Constant.js.

Enfin, pour l'instant le message pour avoir voté est en anglais, à voir si on le passe en français, on fait 2 channels séparés par langue ou on laisse comme ça.

**Comment by Nashoba24** [comment]
Ah et il faudra aussi penser à faire `yarn install` pour la nouvelle dépendance et backup la base de données car il y a une migration

**Comment by Nashoba24** [comment]
Il faudrait voir pour l'intégration du nombre de serveurs sur top.gg

**Comment by Nashoba24** [comment]
Apparemment, le rôle s'enlève parfois alors qu'on vote. C'est peut-être dû à 2 votes en moins de 24h

**Comment by Nashoba24** [comment]
- [ ] Intégration du nombre de serveur
- [ ] Correction du bug du rôle qui s'enlève

**Comment by BastLast** [comment]
correction à faire pour la 2.0.3, le reste peut attendre

**Comment by BastLast** [comment]
issue close avec tag wontfix principalement car personne est motivé pr le faire + pas urgent x)

**Comment by BastLast** [comment]
A réouvrir évidemment si qqun se motive
