### ISSUE TITLE
Bug event advance time

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#712]
On ne devrait pas avoir un second mini-event à la suite du gain de temps.

![image](https://user-images.githubusercontent.com/80409766/141690278-9626c87a-447c-4447-be76-20c8e41b4639.png)

**Comment by Pietagorh** [comment]
Même problème que #673 d'après mes heures de jeu

**Comment by Pietagorh** [comment]
C'est fix ça nan ?

**Comment by BastLast** [comment]
pas sur de comprendre ce qu'il s'est passé, possible de check que c'est dans la bonne milestone ?
