### ISSUE TITLE
Ajout items donateurs

### ISSUE THREAD

**Issue by quenquentin** [DraftBot-A-Discord-Adventure/DraftBot#720]
Pour l'instant on a Nininanou16 : Manchot -> pet 4 étoiles

**Comment by quenquentin** [comment]
Et la multinationale de Pietagorh +700$ daily Mythique

**Comment by BastLast** [comment]
euh pas sur pr la multinationale, c'est un peu op

**Comment by Pietagorh** [comment]
> euh pas sur pr la multinationale, c'est un peu op

Y'a pas d'item d'argent mythique donc en vrai...
Fin après ouais 700 c'est p't'êt' trop, on peut baisser

**Comment by BastLast** [comment]
on en rediscute juste avant la maj

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/147278894-bf121a9b-5faf-4f18-be05-f9db816f9792.png)

**Comment by quenquentin** [comment]
![image](https://user-images.githubusercontent.com/56274541/148652148-471df900-1be3-4525-b650-aff33349ebeb.png)

**Comment by Pietagorh** [comment]
Bouclier/Armure :
🤡 Autodérision | ☄️ Rare | 🛡️65 🗡️-30

**Comment by BastLast** [comment]
possiible de faire ca ce week end ? sinon on repousse à prochaine maj

**Comment by Pietagorh** [comment]
Yep, c'est fait, faut juste que je pr x)
J'aurai mon ordi demain pendant 6/7h donc y'aura pas de problème

**Comment by DoctorT1807** [comment]
Tu peux ajouter mon arme aussi stp : Tournevis sonique :screwdriver: Épique +5 de d'attaque et + 80 de vitesse

**Comment by Pietagorh** [comment]
Yup

**Comment by Pietagorh** [comment]
Augmenter un peu l'attaque de la forteresse

**Comment by BastLast** [comment]
On fera les derniers items donateur juste avant la mise à jour préparer le volonté détonateur pour samedi soir et on en discutera ensemble en vocal

**Comment by Pietagorh** [comment]
Oki
