### ISSUE TITLE
Affichage top `

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#721]
On peut faire bug tout l'affichage d'une page top avec un simple caractère ` dans son pseudo ![Screenshot_2021-11-16-00-42-55-947_com.discord.jpg](https://user-images.githubusercontent.com/60353007/141870689-e21b97e9-0640-41d9-bec7-318f55400d9b.jpg)![Screenshot_2021-11-16-00-43-03-237_com.discord.jpg](https://user-images.githubusercontent.com/60353007/141870717-06c4c23c-f26f-400b-93a1-ee2bd6293e15.jpg)

**Comment by romain22222** [comment]
plus généralement, faut qu'on refact comment sont gérés les pseudos dans le code, ils sont pas du tout échappés et mènent à des situations de ce genre

**Comment by BastLast** [comment]
https://stackoverflow.com/questions/39542872/escaping-discord-subset-of-markdown
