### ISSUE TITLE
Mauvaises variables pour calculer l'exp de guilde

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#725]
L'exp pour les niveaux de guilde est basée sur l'exp de ceux de joueurs
![IMG_20211117_232110.jpg](https://user-images.githubusercontent.com/60353007/142299248-ba6d6ee8-127d-4fbc-beb8-83dea5602ac1.jpg)
[Google doc avec plein de stats sur ça](https://docs.google.com/spreadsheets/d/1hAoLmp3-Ig8oGaZXsETC04YwsK3eW85pMoT24rEvTkU/edit?usp=drivesdk) (vous risquez d'arriver sur la mauvaise feuille, choisissez "Exp de guilde")

**Comment by Pietagorh** [comment]
À faire :
Augmenter la difficulté des variables prévues initialement (mais que ce soit toujours inférieur au joueur)
Remplacer la faute dans le code

**Comment by Pietagorh** [comment]
@BastLast mais du coup les levels "perdus" seront restitués ou pas ?

**Comment by BastLast** [comment]
Non, je réfléchir à une petite compensation en fonction de la réduction de lxp nécessaire

**Comment by BastLast** [comment]
du coup on change pas le comportement du bot mais faut clean le code quand meme :)

**Comment by BastLast** [comment]
(du coup c'est facile à dev :) poke @Pietagorh  @quenquentin @Asemerald

**Comment by Pietagorh** [comment]
Fait ✔️

**Comment by BastLast** [comment]
go pr avant de main car je maj demain donc tout ce qui n'est pas pr ne sera pas dans le bot avant février

**Comment by BastLast** [comment]
et déplacer tout ce qui est fix d'ici demain dans la milestone 2.2.3

**Comment by Pietagorh** [comment]
> go pr avant de main car je maj demain donc tout ce qui n'est pas pr ne sera pas dans le bot avant février


ok

**Comment by Pietagorh** [comment]
Btw la 2.2.3 est close

**Comment by BastLast** [comment]
pas grave
