### ISSUE TITLE
points lottery & pet

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#726]
Les points gagnés dans la lotterie ne sont pas comptabilisés dans le tw
![Screenshot_20211120-213357__01.jpg](https://user-images.githubusercontent.com/60353007/142741203-a7aeb4ad-55e5-4b33-9657-8da18af4d36c.jpg)
![Screenshot_20211120-213427__01.jpg](https://user-images.githubusercontent.com/60353007/142741205-a41a9cdb-9bf1-4069-a654-3f9068cf5905.jpg)
(J'ai testé, c'est pas comptabilisé à la fin du voyage)

**Comment by Pietagorh** [comment]
Présent aussi chez les pets 
![unknown-10.png](https://user-images.githubusercontent.com/60353007/142741350-dc0d9af3-4197-4d8e-95de-bc65c939fa9c.png)
![unknown-15.png](https://user-images.githubusercontent.com/60353007/142741356-9952cff7-ee7f-433c-a0c9-f7148663d3b0.png)

**Comment by BastLast** [comment]
ca mérite un badge ca

**Comment by BastLast** [comment]
ca a pas été fix 2 fois ca du coup ?

**Comment by BastLast** [comment]
(je suis peut etre perdu )
