### ISSUE TITLE
Égalité fights

### ISSUE THREAD

**Issue by symsym-1629** [DraftBot-A-Discord-Adventure/DraftBot#731]
Il faudrait enlever l'elo et les points gagnés/perdus en cas d'égalité ds un fight
![Capture-1_23-11-2021](https://user-images.githubusercontent.com/83075391/143070772-a8da5a16-1b33-4c26-bb3c-5250b6c2f381.png)

**Comment by BastLast** [comment]
l'élo on peut le garder mais les pointds perdus oui faudrait les enlever

**Comment by symsym-1629** [comment]
La modif a été faite ou non ? Je peux close l'issue ?

**Comment by niqore** [comment]
?? Où est-ce sue tu vois une modif ?

**Comment by BastLast** [comment]
De manière générale, laissez nous close les issues x)
