### ISSUE TITLE
le switch ne devrait pas afficher le menu si il n'y a qu'une option possible

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#733]
![image](https://user-images.githubusercontent.com/38099970/143322564-71ff2512-b0a6-4e2e-801d-4a86d111945c.png)

(probablement idem pour le `!sell`)

**Comment by dannyhpy** [comment]
je suis d'accord

**Comment by BastLast** [comment]
je décale ça à la prochaine mise à jour du coup histoire qu'on se stress pas là dessus
