### ISSUE TITLE
Reformuler la description des potions skiptime 

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#734]
par exemple remplacer par "fait avancer de {time} heure(s) sur le voyage" pour clarifier que le temps ne s'écoule pas plus vite sur la durée citée mais fait bien faire un bond dans le temps

![](https://media.discordapp.net/attachments/870363331922382868/911674572640747520/unknown.png)

**Comment by Pietagorh** [comment]
-> #682

**Comment by BastLast** [comment]
c'est une typo/reformulation donc duplicata de l'issue dédiée aux typos

**Comment by BastLast** [comment]
pas de milestone sur les duplicata
