### ISSUE TITLE
Corriger les descriptions de lieux affichés par la commande map

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#735]
Typo signalée par Coronana concernant le Mont Célestrum (comme il s'agit d'un nom ressemblant à du latin peut-être simplement supprimer l'accent ?) 
![](https://media.discordapp.net/attachments/870363331922382868/913467436664246342/unknown.png)

**Comment by Pietagorh** [comment]
-> #682

**Comment by BastLast** [comment]
je ferme vu que c'est un duplicata
