### ISSUE TITLE
faire la distinction entre acheté et trouvé

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#738]
Quand on obtient un item, il faudrait que le titre de l'embed dépende de si on l'a trouvé ou acheté

![image](https://user-images.githubusercontent.com/60353007/143765321-73271525-a284-4b77-a5e1-4edfbed8348e.png)

**Comment by BastLast** [comment]
pourquoi ?

**Comment by BastLast** [comment]
c'est chiant à dev je vois pas ce que ca apporte

**Comment by BastLast** [comment]
+ ca devrait etre une suggestion, c'est pas un bug.

**Comment by BastLast** [comment]
je converti en discussion
