### ISSUE TITLE
double fight

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#744]
Si 2 personnes réagissent même temps à une demande de fight, c'est possible d'en avoir 2 en même temps
![image](https://user-images.githubusercontent.com/60353007/144134812-3cf62c78-2511-4773-9202-375c2ea8b139.png)

**Comment by quenquentin** [comment]
Le bug était déjà connu mais pas répertorié, une idée de comment résoudre cette possibilité ?

**Comment by Pietagorh** [comment]
De la même manière, si tu annules un combat pendant que quelqu'un l'accepte, un combat se lance sans que tu sois bloqué
Ça marche aussi sûrement sur un petsell, donc c'est dangereux

**Comment by BastLast** [comment]
@Feiryn  est-ce que ca serait facile d'implémenter le check de spam à chaque réaction de commandes comme ca ? ca devrait résoudre le problème non ?
