### ISSUE TITLE
Améliorer le string formatter

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#763]
Pour pouvoir :
- [ ] Faire des opérations
- [ ] Mettre plusieurs conditions (&&, ||, etc)
- [ ] Pouvoir mettre des variables à l'intérieur de conditions (ex: {truc>1?{truc}:{machin}})

**Comment by Pietagorh** [comment]
On peut add "Rajouter des connecteurs logiques" ?

**Comment by niqore** [comment]
C'est-à-dire ?

**Comment by Pietagorh** [comment]
Genre {item1FrenchMasculine=1&&item2FrenchMasculine=1?e:}
