### ISSUE TITLE
Certaines commandes ne marchent pas sur la shard 1

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#783]
Possiblement lié aux shards vu que fonctionne sur certains servs et pas d'autres
![image](https://user-images.githubusercontent.com/60353007/146027540-50bed00b-5b27-410d-bef7-fdc54e65f3fe.png)
![image](https://user-images.githubusercontent.com/60353007/146027652-d995c2e9-cbf3-4cc7-ad5a-3b71ddadd359.png)

**Comment by niqore** [comment]
Oui c'est lié, ça crash au niveau du client.guilds.cache

**Comment by BastLast** [comment]
je confirme, tous les serveurs sur le thread 1 n'ont plus accès à la commande help

**Comment by BastLast** [comment]
shard*
