### ISSUE TITLE
Rajouter une commande !rules

### ISSUE THREAD

**Issue by quenquentin** [DraftBot-A-Discord-Adventure/DraftBot#787]
### Discussed in https://github.com/DraftBot-A-Discord-Adventure/DraftBot/discussions/782

<div type='discussions-op-text'>

<sup>Originally posted by **romain22222** December 13, 2021</sup>
Permettrait de connaitre les règles de base du bot, permettant ainsi de les diffuser à travers le royaume de draftland</div>

**Comment by Pietagorh** [comment]
J'ai commencé vu que j'ai pas le niveau pour régler les bugs et que j'ai pas envie d'être désœuvré

**Comment by Pietagorh** [comment]
Possible d'avoir les règles que tu veux donner @BastLast ?

**Comment by niqore** [comment]
^
 |
 |   Fausse alerte c'est une erreur de tag

**Comment by BastLast** [comment]
cette issue ne sera finalement pas réalisée
