### ISSUE TITLE
Rajouter des pets

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#788]
"canard écarlate"

**Comment by BastLast** [comment]
l'emote canard

**Comment by niqore** [comment]
C'est déjà utilisé par le pet canard justement https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/784b4bc09c06362964a0f36f1069537e7a474e54/resources/text/pets/12.json

**Comment by BastLast** [comment]
Ya une limitation technique à faire un doublon ?

**Comment by niqore** [comment]
Non mais bon

**Comment by niqore** [comment]
- Canard écarlate 🦆 (5*)
- Bonhomme de neige ⛄ (1*)
- Bonhomme de neige ☃️ (4*)
- Alien 👽 (5*)
- Poulpe 🐙 (3*)

**Comment by Pietagorh** [comment]
Oubliez pas le manchot de #720
