### ISSUE TITLE
Emplacement Vide

### ISSUE THREAD

**Issue by symsym-1629** [DraftBot-A-Discord-Adventure/DraftBot#791]
![unknown](https://user-images.githubusercontent.com/83075391/146678825-6ff84093-16e5-457f-ba7e-4b6f72bfdefa.png)

**Comment by Nargacaura** [comment]
C'est toujours là sur la 3.0.1b.
![IMG_20220830_193242.jpg](https://user-images.githubusercontent.com/94372084/187504969-6d196f35-c87a-49ee-8075-7e506f11aedd.jpg)

Si ça avait été fix avant, est-ce que ça a été revert ou ça n'a jamais pu être fix? (Oui, je me permets de commenter sur cette issue au lieu de créer une nouvelle qui serait un duplicata de celui-ci.)

**Comment by BastLast** [comment]
Mais c'est fou ces bugs qui disparaissent jamais
