### ISSUE TITLE
pouvoir voir le top sans être classé

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#793]

**Comment by BastLast** [comment]
Et afficher non classé pour les joueurs non classés au lieu dun truc bug

**Comment by Pietagorh** [comment]
J'ai fait ça, vous en pensez quoi ? 

![image](https://user-images.githubusercontent.com/60353007/146951235-e686e316-8506-4ef5-b916-b93adc46e8b0.png)
