### ISSUE TITLE
Lottery player not in guild

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#811]
![Screenshot_20211225_041220.jpg](https://user-images.githubusercontent.com/60353007/147383087-0d18eb5d-3672-4813-85bf-c241625e93ec.jpg)

**Comment by BastLast** [comment]
je copy past le résumé de @AmauryCarrade fait sur la #870 ici au cas où il y ai besoin de doc même si je pense que l'origine du bug est déjà connue J'ai constaté avec des amis sur un serveur que l'événement où un homme vient et propose un jeu de hasard ne fonctionne pas. En effet, en réagissant, il n'y a jamais de réponse. Je parle de cet événement, et toute réaction (quelle qu'elle soit, on a déjà eu le cas plusieurs fois) est ignorée.

![Événement « :slot_machine: Vous croisez le chemin d'un homme qui vous interpelle, curieux, vous vous arrêtez. Celui-ci vous propose de participer à un jeu de hasard de sa concoction. Vous pouvez choisir entre plusieurs niveaux de récompenses. »](https://user-images.githubusercontent.com/1417570/149637201-77940f05-6764-487a-ba82-afb3dd4ce7fb.png)

L'événement a fonctionné une fois au début de ma partie, pour moi, puis plus jamais.
