### ISSUE TITLE
Le skip time de 10min lors de la consommation d'une potion de temps n'est pas garanti 

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#820]
C'est pas facile d'expliquer mieux mais en gros on devrait avoir un mini event après avoir consommé la potion (du moins dans certains cas ça arrive, à voir dans quel sens est le bug). Voilà une image pour se faire une idée plus claire : 

![](https://media.discordapp.net/attachments/870363331922382868/924948592827977728/IMG_4007.png)

![](https://media.discordapp.net/attachments/870363331922382868/924948593092202516/IMG_4008.png)

**Comment by Thesmokingllama** [comment]
Truc que j'ai remarqué c'est qu'au début d'un nouveau trajet, si on prend une potion de skip time, disons 1h, 10min ce seront écoulée et le mini event sera disponible, mais à chaque nouveau time skip rien

**Comment by romain22222** [comment]
je pense avoir compris le bug :

- le temps réel et le temps du mini event sont pour une raison inexpliqué pas calculés de la même manière
- donc arrivé à la fonction de check, le dernier mini event peut dans certains cas être positionné après le moment m

**Comment by Feiryn** [comment]
Ca aussi c'est fix ?

**Comment by romain22222** [comment]
ca c'est fix pr logs

**Comment by Pietagorh** [comment]
À close aussi nan ?

**Comment by BastLast** [comment]
Jso @romain22222 a pas close l'issue

**Comment by BastLast** [comment]
Ya peut etre une raison

**Comment by romain22222** [comment]
j'avais pas close celle ci car j'aimerais qu'il y ait des tests sur l'alpha avant

**Comment by BastLast** [comment]
je parle de ce bug là

**Comment by BastLast** [comment]
du coup j'ai missionné 2 testeurs sur les tests de ce bug, ils feront leur rapport en fin d'aprem

**Comment by Feiryn** [comment]
Bug toujours présent : s'il y a un mini-évent qui a été fait avant la potion d'avance de temps, il n'y aura pas de mini-évent, si c'est juste après un report (aucun mini-évent réalisé avant), après la potion il y a un mini-évent
