### ISSUE TITLE
Soin complet de la vie en gd

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#822]
la récompense de guilde a un souci de calcul de la vie max pour un soint complet

**Comment by Pietagorh** [comment]
En fait j'ai l'impression que c'est un problème avec le maxhealth de entities dans la db, parce même en changeant de classe ou level up je reste toujours au même montant et que le seul autre endroit qui utilise cette colonne est le regen du shop et que y'a le même problème x)

Est-ce que vous pourriez check les maxhealth de tous les gens qui ont commencé y'a pas longtemps ?

**Comment by niqore** [comment]
Dans le code du gd c'est .maxHealth qui est utilisé, or cette colonne est obsolète et inutilisée, il faut passer par Player.getMaxHealth() ou Entity.getMaxHealth() (je sais plus où elle est cette fonction)

**Comment by Pietagorh** [comment]
Yep j'avais trouvé

**Comment by Pietagorh** [comment]
J'en profite pour fix le shop du coup

**Comment by Pietagorh** [comment]
Attendez mais j'dis full merde par rapport au shop, lui il marche x)

**Comment by Pietagorh** [comment]
J'me suis embrouillé :x
