### ISSUE TITLE
Affiché inactif quand un évent attends une réaction

### ISSUE THREAD

**Issue by DoctorT1807** [DraftBot-A-Discord-Adventure/DraftBot#824]
Quand un joueur arrive sur un évent, le temps qu'il choisisse une réaction il est affiché comme inactif :ghost: dans le top week.
![image](https://user-images.githubusercontent.com/89483734/147835144-80c53012-6326-4d59-8eba-c7a72971ce20.png)
![image](https://user-images.githubusercontent.com/89483734/147835154-8e6f2994-cbe2-4ded-8e68-039db37e292d.png)
A vérifié si cela se produit dans tout le top et top serveur.

**Comment by symsym-1629** [comment]
Je vérifie ça peut être avec la #1002 ou sur le bot tout cours

**Comment by BastLast** [comment]
Il y a une possibilité non négligeable que romain ai déjà résolu ce problème en te faisant la commande top

**Comment by symsym-1629** [comment]
Ok bah j'attendrais la maj pour vérifier si c'est tjrs la ou nan en attendant je laisse l'issue open

**Comment by leuhvraiminoryo** [comment]
très possiblement un cas de ceci : 

![image](https://user-images.githubusercontent.com/50586611/181091890-32684515-d985-46fb-b0f4-01a5f65f9ba0.png)
