### ISSUE TITLE
Le premier report effectué indique une somme d'argent différente de celle sur le profil du joueur 

### ISSUE THREAD

**Issue by Thesmokingllama** [DraftBot-A-Discord-Adventure/DraftBot#829]
![](https://media.discordapp.net/attachments/870363331922382868/927303630892175360/unknown.png)

![](https://media.discordapp.net/attachments/870363331922382868/927303631273852968/unknown.png)

**Comment by BastLast** [comment]
je confirme, j'avais observé ce bug j'avais oublié de le noter !

**Comment by Pietagorh** [comment]
Duplicata #703
