### ISSUE TITLE
Ajout d'un message de validation pour la commande drink/glouglou/dr

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#838]
### Discussed in https://github.com/DraftBot-A-Discord-Adventure/DraftBot/discussions/837

<div type='discussions-op-text'>

<sup>Originally posted by **Thesmokingllama** January  6, 2022</sup>
Avec la possibilité de stocker plusieurs potions il est devenu plus difficile de savoir où a été placée la potion de son choix, par conséquent, les erreurs sont fréquentes. C'est pourquoi je propose d'ajouter un message rappelant aux joueurs quelle potion ils s'apprêtent à boire et leur demandant confirmation 

![5E28AEAB-E9EB-49DB-B2C5-2464D22E9FC3](https://user-images.githubusercontent.com/80409766/148390840-64a05a00-9d86-4850-9eec-98710666bed7.jpeg)
*voici l'erreur type de la consommation de potion de soin en pensant boire une potion de temps*
</div>

**Comment by BastLast** [comment]
ajouter la possibilité de forcer le drink sans confirmation avec des alias genre !glouglouvite et !forcedrink

**Comment by Pietagorh** [comment]
Le visuel te va ? 
![image](https://user-images.githubusercontent.com/60353007/148643894-1601d65e-5229-4c85-99b0-df417efe1a54.png)

**Comment by BastLast** [comment]
Rajouter un footer pr dire qu'on peut passee cette confirmation avec des alias
