### ISSUE TITLE
langue de draftbot 

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#853]
![image](https://user-images.githubusercontent.com/38099970/149036301-b76c0acc-9b81-4c8d-9644-0d6275620b08.png)

a faire dès que l'api le permet,

- [ ] Renommer la commande `!language` `!serverlanguage`
- [ ] la commande `!serverlanguage` permet aux admins de forcer une langue (désactivé par défaut) (à discuter, je suis pas sûr de ce point)
- [ ] créer une nouvelle commande accessible à tous qui permet à un utilisateur d'avoir DraftBot qui lui parle avec la langue choisie par l'admin du serveur sur lequel il joue au lieu de la langue de son client (choix par défaut) cette commande s'appellera `!language`

**Comment by BastLast** [comment]
Faudra faire les /commandes avant

**Comment by Feiryn** [comment]
Plus d'actualité
