### ISSUE TITLE
minievent dressage

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#856]
Créer un minievent qui explique au joueur comment dresser un pet et fait dresser son affection
Si le pet est déjà dressé, le joueur obtient des récompenses

**Comment by BastLast** [comment]
et c'est @eagles666  qui explique ca en tant que dresseur pro

**Comment by romain22222** [comment]
alors vous allez rire, mais dans le mission shop prévu pour la prochaine maj, il y aura aussi des conseils du vétérinaire de la cour

**Comment by BastLast** [comment]
uh ? on a décidé ca quand ? je me souviens pas de ca...

**Comment by romain22222** [comment]
> uh ? on a décidé ca quand ? je me souviens pas de ca...

je te laisse check l'issue en question, et le channel discord private bot, on en avait discuté, et c'est codé (manque que les dits conseils à rajouter aux endroits prévus)

**Comment by BastLast** [comment]
ok on en reparle un autre jour pour voir comment on intègre ca et l'autre truc

**Comment by BastLast** [comment]
> > uh ? on a décidé ca quand ? je me souviens pas de ca...
> 
> je te laisse check l'issue en question, et le channel discord private bot, on en avait discuté, et c'est codé (manque que les dits conseils à rajouter aux endroits prévus)

tu as le numéro de l'issue ? j'ai pas réussi à la retrouver ?

**Comment by BastLast** [comment]
après discussion cet aprem, je close cette issue car je pense qu'il sera plus interessant de rendre le vétérinaire plus attractif
