### ISSUE TITLE
ajout d'un mini event cedille.ai

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#857]
mini évènement utilisant l'api de @coteries https://github.com/coteries/cedille-ai

Documentation de l'api dispo dans le salon private bot.

Format du mini event à discuter en voc à l'occaz

**Comment by Feiryn** [comment]
Finalement ce ne sera pas fait, et il commence à y avoir des alternatives open source et locales si on a besoin de cette feature
