### ISSUE TITLE
le blocage ne marche que sur la shard où le joueur a été bloqué 

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#864]
Début d'un combat sur la shard 0
![image](https://user-images.githubusercontent.com/60353007/149501159-56184cba-8d66-4c1a-a5ab-b254ed97bb9b.png)
Pendant ce temps sur la shard 1
![image](https://user-images.githubusercontent.com/60353007/149501282-0633dfe3-405f-45d8-a1fe-fb0d0be7e3b1.png)

**Comment by BastLast** [comment]
pas bon ça
pas bon
