### ISSUE TITLE
L'homme du jeu de hasard ne répond jamais

### ISSUE THREAD

**Issue by AmauryCarrade** [DraftBot-A-Discord-Adventure/DraftBot#870]
Bonjour,

J'ai constaté avec des amis sur un serveur que l'événement où un homme vient et propose un jeu de hasard ne fonctionne pas. En effet, en réagissant, il n'y a jamais de réponse. Je parle de cet événement, et toute réaction (quelle qu'elle soit, on a déjà eu le cas plusieurs fois) est ignorée.

![Événement « :slot_machine: Vous croisez le chemin d'un homme qui vous interpelle, curieux, vous vous arrêtez. Celui-ci vous propose de participer à un jeu de hasard de sa concoction. Vous pouvez choisir entre plusieurs niveaux de récompenses. »](https://user-images.githubusercontent.com/1417570/149637201-77940f05-6764-487a-ba82-afb3dd4ce7fb.png)

L'événement a fonctionné une fois au début de ma partie, pour moi, puis plus jamais.

Si ça peut vous être utile, voici quelques identifiants : 
- du dernier message concerné par ce problème : 932012243116245052
- de mon compte : 626635951531360256
- du serveur : 650237632533757965

Merci !

P.-S. J'ai essayé de trouver un autre ticket mentionnant ce problème, sans succès. Désolé si j'en ai raté un.
P.-P.-S. J'ai été mauvais de toute évidence : c'est le même problème que #811 (je n'avais cherché qu'en français…).

**Comment by DoctorT1807** [comment]
Le bug de déjà été report #811

**Comment by DoctorT1807** [comment]
Pour les report passe par le serveur discord directement c plus simple pour nous 😉

**Comment by BastLast** [comment]
Merci quand même pour le ticket super détaillé x) 
Si jamais tu souhaite nous aider à améliorer le bot hésite pas à te renseigner sur le serveur officiel x) on cherche toujours des gens pour tester les nouvelles fonctionnalités / rédiger des évènements etc etc !
