### ISSUE TITLE
player too poor all choices

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#884]
Peut importe la réaction, si le joueur a moins de 175 💰, il se prendra le message disant qu'il est trop pauvre

**Comment by BastLast** [comment]
Rien compris

**Comment by Pietagorh** [comment]
Normalement il te faut un minimum d'argent seulement si tu choisis la 3è option
Bah ça le faisait peut importe l'option que tu choisissais

**Comment by BastLast** [comment]
c fixé ou pas ?

**Comment by BastLast** [comment]
ca a été merge ?

**Comment by Pietagorh** [comment]
nope

**Comment by BastLast** [comment]
pk ?

**Comment by Pietagorh** [comment]
Parce que j'ai pas encore pr x)

**Comment by BastLast** [comment]
Pk ?

**Comment by Pietagorh** [comment]
Je sais pas

**Comment by BastLast** [comment]
Go pr asap

**Comment by Pietagorh** [comment]
J'fais ça cette aprèm
Du coup ça ajoutera aussi les items dona sauf 1 (faut qu'on voie pour l'équilibrage)

**Comment by quenquentin** [comment]
tousse tousse @Pietagorh

**Comment by BastLast** [comment]
ptdr j'allais le faire

**Comment by Pietagorh** [comment]
Rooooh ça vaaaaa

**Comment by BastLast** [comment]
du coup ?
