### ISSUE TITLE
nouveau mini event achat de charette

### ISSUE THREAD

**Issue by BastLast** [DraftBot-A-Discord-Adventure/DraftBot#902]
![image](https://user-images.githubusercontent.com/38099970/154360782-4255a50d-643b-4d05-aa0a-a0f9a0bdb13b.png)

**Comment by BastLast** [comment]
je m'en occuperai

**Comment by Feiryn** [comment]
Est-ce qu'on ferait pas plutôt un mini-évent où le joueur croise une charette et le pnj lui propose de venir avec lui pour un peu d'argent, mais ça le tp sur un autre trajet ?

**Comment by BastLast** [comment]
> Est-ce qu'on ferait pas plutôt un mini-évent où le joueur croise une charette et le pnj lui propose de venir avec lui pour un peu d'argent, mais ça le tp sur un autre trajet ?

Je suis chaud, je propose que le mini event reste vraiment rare pour pas qu'on ai des TP dans tous les sens. (rareté 1)

Je propose que ce mini event ai 40% de chance que le joueurs sache où il va atterrire avec le tp et 50% qu'il sache pas et 5% que le mec ai menti sur la destination mais propose le trajet pour pas cher et 5% que le trajet soit juste pas cher.

pour le prix je propose:

250 pièces pour un TP full random
1200 pièces pour un TP où le mec sait ou il va
500 pièces pour un tp ou le mec sait ou il va mais ya 50% de chance que ça soit en fait un TP random


ça me parait être fun et pas trop complexe à dev
