### ISSUE TITLE
level up heal lottery

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#931]
Les level up tous les 10 niveaux ne regen pas quand c'est sur le minievent lottery

**Comment by BastLast** [comment]
est-ce que c'est sur que c'est pas partout que ca heal pas ?

**Comment by Pietagorh** [comment]
De souvenir quand j'suis passé level 80 ça m'a heal

**Comment by Pietagorh** [comment]
Confirmed ![IMG_20220224_123027.jpg](https://user-images.githubusercontent.com/60353007/155516153-34503549-8b60-4bbe-b2b6-f2ef3c79b82f.jpg)
![IMG_20220224_123036.jpg](https://user-images.githubusercontent.com/60353007/155516160-822067b6-55ce-4d74-92a5-0769af7956a7.jpg)

**Comment by quenquentin** [comment]
Il me semble avoir vu un player.save passer récemment ou autre, ça peut pas être lié à ça ? Voir chaque cas de toute façon

**Comment by quenquentin** [comment]
Ah nevermind, juste que ce que tu dis @Pietagorh n'a aucun sens, ce joueur est monté de niveau grâce à un évent et pas grâce à la lottery, donc normal qu'il soit heal

**Comment by Pietagorh** [comment]
> Ah nevermind, juste que ce que tu dis @Pietagorh n'a aucun sens, ce joueur est monté de niveau grâce à un évent et pas grâce à la lottery, donc normal qu'il soit heal

Non mais justement là je montre que c'est pas un phénomène global vu qu'il apparaît pas avec les events

**Comment by Pietagorh** [comment]
C'est ça le screen qu'on a eu dans le report, j'l'ai juste oublié x) ![unknown-23.png](https://user-images.githubusercontent.com/60353007/155517934-1743cac2-2c9b-4f43-8af1-b2414321af24.png)

**Comment by Pietagorh** [comment]
> Il me semble avoir vu un player.save passer récemment ou autre, ça peut pas être lié à ça ? Voir chaque cas de toute façon

J'pense que ouais c'est parce qu'il y a un player.save mais pas d'entity.save mais à voir
