### ISSUE TITLE
Typos pour la 3.0.0

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#952]

**Comment by BastLast** [comment]
wtf on peut faire ca ?

**Comment by quenquentin** [comment]
> wtf on peut faire ca ?

Fonctionnalité pas pensée mais qui est viable :joy:
Sinon plus sérieusement oui on peut

**Comment by DoctorT1807** [comment]
Assommoir*
![image](https://user-images.githubusercontent.com/89483734/157330468-855a17be-e647-4359-ab59-78e470017894.png)
satisfaites* 
![image](https://user-images.githubusercontent.com/89483734/157330546-9f712ddd-ccfe-4d40-b875-77991bec684f.png)
ébahi*
![image](https://user-images.githubusercontent.com/89483734/157330650-888b3d4b-448d-44c3-b78f-37fa5d0612d0.png)

**Comment by Pietagorh** [comment]
L'assomoire c'est fait exprès apparemment

**Comment by DoctorT1807** [comment]
ok

**Comment by DoctorT1807** [comment]
bons*
![image](https://user-images.githubusercontent.com/89483734/157331154-0a082cc3-e8ad-42ae-b0cf-a23d92b5898c.png)

**Comment by DoctorT1807** [comment]
Précision : le nid de guêpes tombe d'où ?
![image](https://user-images.githubusercontent.com/89483734/158025123-ad76d9fa-31e8-42ab-bf15-98c9018b58a1.png)

**Comment by DoctorT1807** [comment]
Enlever le drop de l'item
![image](https://user-images.githubusercontent.com/89483734/158025172-d640ec44-5ebd-4066-9962-c60c8718a4fc.png)

**Comment by DoctorT1807** [comment]
"Non sans peine"
L'expression est toujours au singulier.
![image](https://user-images.githubusercontent.com/89483734/158025248-cb6c35b7-541a-4035-8c44-7fba985fc163.png)

"C'est au moment où vous décidez de rebrousser chemin"
"Une quantité de pièces"
![image](https://user-images.githubusercontent.com/89483734/158025268-ff57447e-e0c8-4b86-9182-4ac5eb066827.png)

"Vous chantez pour vous-même"
Il manque le trait d'union.
![image](https://user-images.githubusercontent.com/89483734/158025286-4fbd2315-87ad-40d3-838a-de84fb11ea5d.png)

"Vous leur accordez"
![image](https://user-images.githubusercontent.com/89483734/158025294-af6941c9-c318-4180-8faf-4c1dde1eda17.png)

On parle de l'astre donc c'est la "Lune".
![image](https://user-images.githubusercontent.com/89483734/158025300-39517986-f7c9-48a7-be31-85178d1e6301.png)

**Comment by DoctorT1807** [comment]
"vootre"
![image](https://user-images.githubusercontent.com/89483734/158025444-98003f84-236d-4634-af00-5f076883a11c.png)

**Comment by DoctorT1807** [comment]
À la dernière phrase "chef-lieux" ya pas de "x" vu que c'est un seul chef-lieu
![image](https://user-images.githubusercontent.com/89483734/158025490-7a4f2dc0-4852-461f-ac52-41858efd6e95.png)

**Comment by DoctorT1807** [comment]
Serai*
![image](https://user-images.githubusercontent.com/89483734/158025531-0471181c-d498-45d9-91ff-44a029bcd932.png)

**Comment by DoctorT1807** [comment]
Le message en bas est faux, le pet ne perds que 5 points par ⭐ 
![image](https://user-images.githubusercontent.com/89483734/158025661-22ddafb0-0a16-4832-bf90-fb9750de5812.png)

**Comment by DoctorT1807** [comment]
son*
![unknown-3](https://user-images.githubusercontent.com/89483734/158553227-b031cde5-bdaf-487f-997d-84ff904eb9e1.png)

**Comment by DoctorT1807** [comment]
vous continuez sans faire --> vous continuez votre route sans faire
![image](https://user-images.githubusercontent.com/89483734/159089528-57856027-d903-464e-81d2-31620bfd0b1a.png)

**Comment by DoctorT1807** [comment]
nous --> non
![image](https://user-images.githubusercontent.com/89483734/159090918-649afed1-fc8e-40af-a198-e137dbed4e9c.png)

**Comment by DoctorT1807** [comment]
Qui ne cesse d'accroître --> Qui ne cesse DE s'accroître
![image](https://user-images.githubusercontent.com/89483734/159124773-faf98e74-7daf-4ee6-8448-da177889af11.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/161064686-be3e802f-c5d4-4238-89de-647ef5e453e4.png)
Typo event 26 choix 3. Remplacer "durant votre course, vous voyez au loin, un coffret ouvert" par "En vous éloignant, vous apercevez au loin un coffret" (ouvert est supprimé car il est dit après que le joueur l'ouvre)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/161070678-3a687bfe-7215-467f-8dd6-c8749fbf6e65.png)
Il faudrait enlever le "e" à la fin de "utilisée" puisque c'est le Grand Axe qui est utilisé, mettre les majuscules à Grand Axe aussi.

**Comment by Chevalier2** [comment]
Accent manquant au e de comp**é**tition : 
![image](https://user-images.githubusercontent.com/72626953/161344029-c62cc7a5-619c-4b6c-a001-dbab5b925e70.png)

**Comment by Chevalier2** [comment]
R**é**ception _et il y a un problème pour le temps mais c'est pas une typo_
![image](https://user-images.githubusercontent.com/72626953/161384037-ab93e45a-a77e-45ef-9519-45ed5805789b.png)

**Comment by Thero1st** [comment]
![image](https://user-images.githubusercontent.com/82404321/163677383-8036cbc0-22b6-4dda-b90e-a784fdaec894.png)
Lors du mini-event où on peut donner une pièce à un autre joueur, la réponse est un peu abusée 
(C'est Draft qui m'a demandé de signaler ça au fait)

**Comment by leuhvraiminoryo** [comment]
![image](https://user-images.githubusercontent.com/50586611/163962715-68efbab3-4b43-428b-bd8d-f19b992bdea3.png)
le message d'erreur dit qu'il faut être aîné ou chef mais seul le chef peut kick.

**Comment by Chevalier2** [comment]
2 fautes dans la description du Bois Hurlant _corrigées sur le wiki_ : dû**e** et rep**ai**res.
La description : "Forêt mal famée au bord de Claire De Ville. Ce bois a une très mauvaise réputation dûe aux repaires de bandits et hors la loi en tout genre. La forêt tient surtout son nom de ces pratiques douteuses il y a de ça des centaines d’années."

**Comment by Chevalier2** [comment]
Espace en trop https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/master/resources/text/bot.json ligne 58
![image](https://user-images.githubusercontent.com/72626953/166260512-8128a775-51bf-4d93-864d-71720b443e70.png)

**Comment by Chevalier2** [comment]
Les problèmes : "item" et "à" à la place de "a" pour "L'arnaqueur à profité [...]".
Correction : "💸 Vous achetez l'un de ses objets à faible valeur, mais au moment où vous recevez votre achat et commencez à l'inspecter, vous vous rendez compte qu'il vous a vendu un objet en piteux état. L'arnaqueur a profité de votre naïveté et du moment où vous observiez l'objet pour prendre ses jambes à son cou. Vous jurez de ne plus vous faire berner par ce type."
![image](https://user-images.githubusercontent.com/72626953/166261010-edfff730-bbe9-41a4-8128-33b75b591b2b.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/166261436-03d122d2-0d6d-41ed-9258-e87c82af52ca.png)
S'il*

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/166264061-e7cc1235-9841-4c0b-8904-92d5a1839378.png)
"Ce bon repas vous **a** redonn**é** des forces"

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/166704070-08c3fec7-3a36-44d0-b8c9-a773d5aa3766.png)
Rajouter une phrase d'introduction avant "Soudain" ?

**Comment by Chevalier2** [comment]
Plusieurs problèmes : un t en trop à "n'arrêtez", et la phrase est selon vraiment mal construite. Aussi, c'est réguli**é** pas réguli**er**. Je propose de changer la phrase en : "N'oubliez pas de nourrir régulièrement votre familier".
![image](https://user-images.githubusercontent.com/72626953/166705158-06ee6d84-62b0-42e5-a09b-cb7613beb5d2.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/167875804-f5b7410b-0c5d-48f7-a47d-6b885f2e13bf.png)
"sa jus de banane" alors que cela devrait être "son jus de banane".

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/169662489-59e94cd3-299a-4e08-a974-4c2778ea6c2e.png)
Majuscule manquante au début et  "à" à la place du verbe avoir à la 3e personne du singulier.

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/169713431-a14c092b-6b39-4ee5-8653-c24c799c4c5c.png)
Accent en trop sur le **a**.

**Comment by Thesmokingllama** [comment]
Event Gruffo l'alchimiste "Vous entrez"
![](https://media.discordapp.net/attachments/870363331922382868/979389858135027732/Screenshot_20220526-162033.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/172696570-4f2685ca-56a0-4460-96c0-413b51ac8db5.png)
Après un trade. C'est "Occupez**-**vous en bien !", il manque le tiret.

**Comment by Pietagorh** [comment]
![image](https://user-images.githubusercontent.com/60353007/175658196-5a50f557-4662-48e9-8cfa-6128bf97f927.png)

**Comment by Pietagorh** [comment]
Hmmm...
![image](https://user-images.githubusercontent.com/60353007/175956027-818a66f2-d182-4ac6-95c0-1f990be1d419.png)

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/177010748-916c3d86-73c0-4ab5-ade2-6ab730d39f99.png)
"Pris d'un élan de pitié, vous satisfaisez sa demande et lui donnez [...]".
"satisfaisez" n'existe pas, c'est "satisfai**tes**" comme avec le verbe faire.

**Comment by Chevalier2** [comment]
![image](https://user-images.githubusercontent.com/72626953/177012896-ae19fb0a-fc5c-4d39-bc09-cc31ed194113.png)
C'est la commande **unlock**, pas unblock.

**Comment by BastLast** [comment]
Toutes les typos ont été faites pour cette mise à jour. Si de nouvelles sont découvertes (même si la maj est pas encore sortie, merci d'utiliser une nouvelle issue)

**Comment by BastLast** [comment]
et poke à l'issur #1183 pour les prochaines typos
