### ISSUE TITLE
!m ne marche plus mission secondaire de points

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#953]
![image](https://user-images.githubusercontent.com/60353007/155888674-74c8648c-67c1-47fb-876c-6de82a0c8e62.png)
Sûrement la progress bar qui sait pas quoi afficher à cause d'un nombre négatif

**Comment by quenquentin** [comment]
screen de la bar ?

**Comment by Pietagorh** [comment]
Ah oui j'ai pas précisé
Du coup le message s'envoie juste pas
