### ISSUE TITLE
Mission getting heal

### ISSUE THREAD

**Issue by quenquentin** [DraftBot-A-Discord-Adventure/DraftBot#966]
Au lieu que ce soit uniquement le nombre de points de vie régénérés qui comptent pour la mission, faire en sorte que ce soit l'entièreté des HP qui sont affichés. Si une potion donne 40 hp alors la mission avancera à 40/50 même si le joueur est à 132/132 hp.

**Comment by Pietagorh** [comment]
C'est pas fait ça ?
