### ISSUE TITLE
Affichage nerf

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#975]
Hito et moi avons beaucoup plus de speed que ça, et c'est pourtant nerf ![IMG_20220228_165826.jpg](https://user-images.githubusercontent.com/60353007/156360827-5b07b416-bfeb-483f-9512-37ca1faaf849.jpg)![IMG_5140.png](https://user-images.githubusercontent.com/60353007/156360838-181545c4-bf73-4b03-993c-c34c2b95b754.png)

**Comment by Pietagorh** [comment]
En fait tous les nerfs ont des problèmes niveau affichage actuellement, cf https://discord.com/channels/429765017332613120/870363331922382868/953155081551900772

**Comment by Pietagorh** [comment]
(Il était ganté)
![image](https://user-images.githubusercontent.com/60353007/175655403-717fad0d-7778-4d01-a092-9d257ceb08f7.png)

**Comment by BastLast** [comment]
Du coup ct quoi le soucis ? Je suis curieux
