### ISSUE TITLE
Mission gd

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#976]
2 options :
Soit vu que les mp du bot marchent plus il a pas eu le message et la mission marche que si tu fais le gd
Soit son gd a été reset à cause d'un problème de temps![Screenshot_2022-03-02-08-16-21-639_com.discord.jpg](https://user-images.githubusercontent.com/60353007/156361824-c656cadb-36b7-4a5b-92a0-05c359a3f82a.jpg)![Screenshot_2022-03-02-08-16-27-860_com.discord.jpg](https://user-images.githubusercontent.com/60353007/156361829-b5550302-97be-40ec-b527-9faef661387b.jpg)

**Comment by romain22222** [comment]
problème durant le 1er gd, surement lié à #970
