### ISSUE TITLE
Drink refusé

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#978]
Pas de message de confirmation de l'annulation ![Screenshot_2022-02-27-21-21-04.png](https://user-images.githubusercontent.com/60353007/156362908-a1cdf30c-4b60-4e0b-a700-40718c97b18d.png)

**Comment by romain22222** [comment]
bug non lié aux problèmes de temps

**Comment by BastLast** [comment]
faut pas close l'issue tant que c'est pas merge btw

**Comment by BastLast** [comment]
sauf si c'est corrigé dans un autre commit
