### ISSUE TITLE
Mission boire une potion

### ISSUE THREAD

**Issue by Pietagorh** [DraftBot-A-Discord-Adventure/DraftBot#979]
Les potions sans effet ne sont pas comptabilisées ![Screenshot_2022-02-27-21-11-23-848_com.discord.jpg](https://user-images.githubusercontent.com/60353007/156363097-1fd49612-c26d-4eb7-b2ca-4b2a8dba0322.jpg)

**Comment by romain22222** [comment]
already fixed
