### ISSUE TITLE
les missions d'obtention d'un objet de rareté ne se valident pas automatiquement pour un objet de la rareté exacte

### ISSUE THREAD

**Issue by romain22222** [DraftBot-A-Discord-Adventure/DraftBot#980]

**Comment by romain22222** [comment]
apparament, le bug est tjrs présent, cf mura

**Comment by DoctorT1807** [comment]
![Screenshot_20220304-223649_Discord](https://user-images.githubusercontent.com/89483734/156845062-3f597df3-cca4-4648-8060-979ca3dcffa5.jpg)
Yep

**Comment by BastLast** [comment]
du coup c'est vraiment fixé ou pas mtn ?
